name = "KuuOS"
version = "0.20.0"
defaultTargets = ["KuuOSFormal"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "KuuOSFormal"
srcDir = "formal"
roots = [
  "KuuOSFormal",
  "KUOS",
  "KuuOSModularEvolutionMeshV0_1",
  "KuuOSFormalV0_41",
  "KuuOSFormalV0_42",
  "KuuOSFormalV0_43",
  "KuuOSFormalV0_44",
  "KuuOSFormalV0_45",
  "KuuOSFormalV0_46",
  "KuuOSFormalV0_47",
  "KuuOSFormalV0_48",
  "KuuOSFormalV0_49",
  "KuuOSFormalV0_50",
  "KuuOSFormalV0_51",
  "KuuOSFormalV0_52",
  "KuuOSFormalV0_53",
  "KuuOSFormalV0_54",
  "KuuOSFormalV0_55",
  "KuuOSFormalV0_56",
  "KuuOSArakiCalculusV0_56",
  "KuuOSFormalV0_57",
  "KuuOSFormalV0_58",
  "KuuOSFourGreatCoreV0_59",
  "KuuOSFormalV0_59",
  "KuuOSFormalV0_60",
  "KuuOSFormalV0_61",
  "KuuOSFormalV0_62",
  "KuuOSFormalV0_69",
  "KuuOSFormalV0_70",
  "KuuOSFormalV0_71",
  "KuuOSFormalV0_72",
  "KuuOSMemoryEvaluationV0_73"
]
