name = "KuuOS"
version = "0.20.0"
defaultTargets = ["KuuOSFormal"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "KuuOSFormal"
srcDir = "formal"
roots = [
  "KuuOSFormal",
  "KUOS",
  "KuuOSFormalV0_41",
  "KuuOSFormalV0_42",
  "KuuOSFormalV0_43",
  "KuuOSFormalV0_44",
  "KuuOSFormalV0_45",
  "KuuOSFormalV0_46",
  "KuuOSFormalV0_47",
  "KuuOSFormalV0_48",
  "KuuOSFormalV0_49",
  "KuuOSFormalV0_50"
]
