.PHONY: ai-provider-boundary-checks ai-yogacara-checks ai-yogacara-build-bundle ai-yogacara-validate-bundle mandala-checks bodhisattva-checks paramita-router-checks dukkha-checks dukkha-qi-checks qi-motion-chain-checks samvrti-qi-runtime-checks samvrti-qi-to-physical-motion-checks physical-quantum-qi-runtime-checks physical-quantum-qi-dynamics-checks physical-quantum-qi-motion-pipeline-checks physical-quantum-qi-deepening-checks physical-quantum-qi-runtime-evolution-checks physical-quantum-qi-runtime-evolution-ci-receipt-checks physical-quantum-qi-runtime-evolution-bundle-checks physical-quantum-qi-runtime-evolution-finality-checks physical-quantum-qi-runtime-evolution-finality-post-merge-receipt-checks physical-quantum-qi-runtime-evolution-baseline-lock-checks formal-invariant-checks super-relativity-checks invariant-matrix-checks invariant-gate-checks invariant-pipeline-checks invariant-pipeline-build-bundle invariant-pipeline-validate-bundle invariant-pipeline-attest invariant-pipeline-release-closure invariant-pipeline-finality gpt-github-integration-checks memoryos-github-external-memory-checks emptiness-two-truths-runtime-audit-checks emptiness-superposition-noncollapse-checks superstring-emptiness-sbm-checks core-governance-checks all-governance-checks

ai-provider-boundary-checks:
	python3 scripts/validate_ai_provider_boundary_runtime_v0_1.py
	python3 scripts/validate_ai_provider_boundary_audit_event_v0_1.py

ai-yogacara-checks:
	python3 scripts/run_ai_yogacara_full_checks_v0_1.py

ai-yogacara-build-bundle:
	python3 scripts/build_ai_yogacara_release_bundle_manifest_v0_1.py

ai-yogacara-validate-bundle:
	python3 scripts/validate_ai_yogacara_release_bundle_manifest_v0_1.py

mandala-checks:
	python3 scripts/validate_mandala_multi_world_v0_1.py

bodhisattva-checks:
	python3 scripts/validate_bodhisattva_ten_paramita_v0_1.py

paramita-router-checks:
	python3 scripts/validate_paramita_repair_router_v0_1.py
	python3 scripts/validate_paramita_repair_router_fixtures_v0_1.py

dukkha-checks:
	python3 scripts/validate_dukkha_mathematical_model_v0_1.py
	python3 scripts/validate_dukkha_model_fixtures_v0_1.py

dukkha-qi-checks:
	python3 scripts/validate_dukkha_as_qi_mode_v0_1.py

qi-motion-chain-checks:
	python3 scripts/run_qi_motion_chain_checks_v0_1.py

samvrti-qi-runtime-checks:
	python3 examples/samvrti_qi_runtime_adapter_minimal.py
	python3 scripts/validate_samvrti_qi_runtime_v0_1.py

samvrti-qi-to-physical-motion-checks:
	python3 examples/samvrti_qi_to_physical_motion_evidence_builder_minimal.py
	python3 scripts/validate_samvrti_qi_to_physical_motion_evidence_builder_v0_1.py

physical-quantum-qi-runtime-checks:
	python3 scripts/validate_physical_quantum_qi_runtime_contract_v0_1.py
	python3 scripts/validate_physical_quantum_qi_runtime_release_packet_v0_1.py

physical-quantum-qi-dynamics-checks:
	python3 examples/physical_quantum_qi_dynamics_kernel_minimal.py
	python3 scripts/validate_physical_quantum_qi_dynamics_kernel_v0_1.py

physical-quantum-qi-motion-pipeline-checks:
	python3 examples/physical_quantum_qi_motion_pipeline_minimal.py
	python3 scripts/validate_physical_quantum_qi_motion_pipeline_v0_1.py

physical-quantum-qi-deepening-checks:
	python3 scripts/validate_physical_quantum_qi_equations_v0_2.py
	python3 scripts/validate_physical_quantum_qi_equation_packet_v0_2.py
	python3 scripts/validate_physical_quantum_qi_non_markov_memory_v0_2E.py
	python3 tests/test_physical_quantum_qi_non_markov_memory_v0_2E.py
	python3 scripts/validate_physical_quantum_qi_process_tensor_v0_2F.py
	python3 tests/test_physical_quantum_qi_process_tensor_v0_2F.py
	python3 scripts/validate_kuuos_qi_process_tensor_conventional_autonomy_v0_2G.py
	python3 tests/test_kuuos_qi_process_tensor_conventional_autonomy_v0_2G.py
	python3 scripts/validate_qi_process_tensor_release_chain_docs_v0_2FG.py
	python3 scripts/validate_qi_process_tensor_v0_2FG_docs_closure_addendum_packet.py
	python3 scripts/validate_physical_quantum_qi_dpi_recoverability_v0_2C.py
	python3 scripts/validate_physical_quantum_qi_indranet_gauge_transport_v0_2D.py
	python3 tests/test_physical_quantum_qi_indranet_gauge_transport_v0_2D.py
	python3 tests/test_physical_quantum_qi_indranet_transport_runtime_v0_2D.py
	python3 tests/test_physical_quantum_qi_indranet_planos_handoff_v0_2D.py
	python3 tests/test_physical_quantum_qi_phase_runtime_v0_2.py
	python3 tests/test_physical_quantum_qi_os_bridge_v0_2.py
	python3 tests/test_physical_quantum_qi_memory_record_v0_2.py
	python3 tests/test_physical_quantum_qi_ward_leak_v0_2B_deepening.py
	python3 examples/run_physical_quantum_qi_phase_demo_v0_2.py
	python3 examples/run_physical_quantum_qi_indranet_planos_handoff_demo_v0_2D.py
	python3 scripts/validate_physical_quantum_qi_deepening_v0_2.py
	python3 scripts/validate_physical_quantum_qi_deepening_release_packet_v0_2.py
	python3 scripts/validate_qi_process_tensor_release_chain_v0_2FG.py

physical-quantum-qi-runtime-evolution-checks:
	python3 scripts/validate_qi_bensho_treatment_route_candidate_v0_2J.py
	python3 scripts/validate_qi_bensho_decisionos_clinician_handoff_v0_2K.py
	python3 scripts/validate_qi_clinical_red_flag_handover_governor_v0_2L.py
	python3 scripts/check_qi_clinical_red_flag_consultation_governor_finality_v0_2L.py
	python3 scripts/validate_physical_quantum_qi_observation_kernel_v0_2M.py
	python3 tests/test_physical_quantum_qi_observation_kernel_v0_2M.py
	python3 scripts/validate_physical_quantum_qi_state_transition_kernel_v0_2N.py
	python3 tests/test_physical_quantum_qi_state_transition_kernel_v0_2N.py
	python3 scripts/validate_physical_quantum_qi_transition_trajectory_ledger_v0_2O.py
	python3 tests/test_physical_quantum_qi_transition_trajectory_ledger_v0_2O.py
	python3 scripts/validate_physical_quantum_qi_trajectory_phase_transition_detector_v0_2P.py
	python3 tests/test_physical_quantum_qi_trajectory_phase_transition_detector_v0_2P.py
	python3 scripts/validate_physical_quantum_qi_phase_transition_response_governor_v0_2Q.py
	python3 tests/test_physical_quantum_qi_phase_transition_response_governor_v0_2Q.py
	python3 scripts/validate_physical_quantum_qi_response_feedback_loop_v0_2R.py
	python3 tests/test_physical_quantum_qi_response_feedback_loop_v0_2R.py
	python3 scripts/check_physical_quantum_qi_runtime_evolution_ci_receipt_v0_2JR.py
	python3 scripts/validate_physical_quantum_qi_runtime_evolution_bundle_manifest_v0_2JR.py
	python3 scripts/check_physical_quantum_qi_runtime_evolution_finality_packet_v0_2JR.py
	python3 scripts/check_physical_quantum_qi_runtime_evolution_finality_post_merge_receipt_v0_2JR.py
	python3 scripts/check_physical_quantum_qi_runtime_evolution_baseline_lock_v0_2S.py

physical-quantum-qi-runtime-evolution-ci-receipt-checks:
	python3 scripts/check_physical_quantum_qi_runtime_evolution_ci_receipt_v0_2JR.py

physical-quantum-qi-runtime-evolution-bundle-checks:
	python3 scripts/validate_physical_quantum_qi_runtime_evolution_bundle_manifest_v0_2JR.py

physical-quantum-qi-runtime-evolution-finality-checks:
	python3 scripts/check_physical_quantum_qi_runtime_evolution_finality_packet_v0_2JR.py

physical-quantum-qi-runtime-evolution-finality-post-merge-receipt-checks:
	python3 scripts/check_physical_quantum_qi_runtime_evolution_finality_post_merge_receipt_v0_2JR.py

physical-quantum-qi-runtime-evolution-baseline-lock-checks:
	python3 scripts/check_physical_quantum_qi_runtime_evolution_baseline_lock_v0_2S.py

formal-invariant-checks:
	python3 scripts/validate_formal_invariant_spine_v0_1.py

super-relativity-checks:
	python3 scripts/validate_super_relativity_invariant_bridge_v0_1.py

invariant-matrix-checks:
	python3 scripts/validate_invariant_preservation_matrix_v0_1.py
	python3 scripts/validate_invariant_preservation_matrix_fixtures_v0_1.py

invariant-gate-checks:
	python3 scripts/validate_invariant_gate_fixtures_v0_1.py

invariant-pipeline-build-bundle:
	python3 scripts/build_invariant_pipeline_release_bundle_manifest_v0_1.py

invariant-pipeline-validate-bundle:
	python3 scripts/validate_invariant_pipeline_release_bundle_manifest_v0_1.py
	python3 scripts/validate_invariant_pipeline_bundle_closure_inclusion_v0_1.py

invariant-pipeline-attest:
	python3 scripts/validate_invariant_pipeline_release_attestation_v0_1.py

invariant-pipeline-release-closure:
	python3 scripts/validate_invariant_pipeline_release_closure_packet_v0_1.py
	python3 scripts/validate_invariant_pipeline_bundle_closure_inclusion_v0_1.py

invariant-pipeline-finality:
	python3 scripts/check_invariant_pipeline_finality_packet_v0_1.py

invariant-pipeline-checks:
	python3 scripts/validate_invariant_governance_pipeline_v0_1.py
	python3 scripts/validate_invariant_governance_pipeline_fixtures_v0_1.py
	python3 scripts/validate_invariant_pipeline_audit_event_v0_1.py
	python3 scripts/validate_invariant_pipeline_audit_hash_chain_v0_1.py
	python3 scripts/validate_invariant_pipeline_audit_worm_export_receipt_v0_1.py
	python3 scripts/validate_invariant_pipeline_release_bundle_manifest_v0_1.py
	python3 scripts/validate_invariant_pipeline_bundle_closure_inclusion_v0_1.py
	python3 scripts/validate_invariant_pipeline_release_attestation_v0_1.py
	python3 scripts/validate_invariant_pipeline_release_closure_packet_v0_1.py
	python3 scripts/check_invariant_pipeline_finality_packet_v0_1.py

gpt-github-integration-checks:
	python3 scripts/validate_gpt_github_integration_v0_1.py

memoryos-github-external-memory-checks:
	python3 scripts/validate_memoryos_github_external_memory_v0_1.py

emptiness-two-truths-runtime-audit-checks:
	python3 scripts/export_emptiness_do_two_truths_runtime_audit_v0_1.py
	python3 scripts/build_emptiness_do_two_truths_runtime_audit_chain_v0_1.py
	python3 scripts/check_emptiness_do_two_truths_runtime_audit_chain_v0_1.py
	python3 scripts/run_emptiness_do_two_truths_runtime_checks_v0_1.py
	python3 scripts/validate_emptiness_do_two_truths_runtime_release_packet_v0_1.py
	python3 scripts/validate_emptiness_do_two_truths_runtime_release_bundle_manifest_v0_1.py

emptiness-superposition-noncollapse-checks:
	python3 scripts/validate_kuos_emptiness_superposition_non_collapse_v0_2.py
	python3 scripts/validate_kuos_emptiness_superposition_non_collapse_release_packet_v0_2.py

superstring-emptiness-sbm-checks:
	python3 validators/validate_superstring_emptiness_string_brane_membrane_v0_1.py examples/superstring_emptiness_string_brane_membrane_packet_v0_1.json
	python3 validators/run_superstring_emptiness_string_brane_membrane_cases_v0_1.py validation_cases/superstring_emptiness_string_brane_membrane_validation_cases_v0_1.json
	python3 validators/run_superstring_emptiness_string_brane_membrane_cases_v0_2.py validation_cases/superstring_emptiness_string_brane_membrane_validation_cases_v0_2.json
	python3 validators/validate_superstring_emptiness_sbm_manifest_v0_2.py manifests/superstring_emptiness_string_brane_membrane_manifest_v0_1.json
	python3 validators/validate_superstring_emptiness_sbm_packet_chain_v0_2.py packets/superstring_emptiness_string_brane_membrane_release_packet_v0_1.json packets/superstring_emptiness_string_brane_membrane_finality_packet_v0_1.json
	python3 validators/validate_superstring_emptiness_indranet_gauge_interface_v0_4.py examples/superstring_emptiness_indranet_gauge_interface_packet_v0_4.json
	python3 validators/run_superstring_emptiness_indranet_gauge_interface_cases_v0_4.py validation_cases/superstring_emptiness_indranet_gauge_interface_validation_cases_v0_4.json
	python3 validators/validate_superstring_emptiness_observer_record_scale_bridge_v0_6.py examples/superstring_emptiness_observer_record_scale_bridge_packet_v0_6.json
	python3 validators/run_superstring_emptiness_observer_record_scale_bridge_cases_v0_6.py validation_cases/superstring_emptiness_observer_record_scale_bridge_validation_cases_v0_6.json

core-governance-checks:
	python3 scripts/run_core_governance_full_checks_v0_1.py

all-governance-checks:
	python3 scripts/run_all_governance_full_checks_v0_1.py

.PHONY: two-truths-gap-holography-spine-checks

two-truths-gap-holography-spine-checks:
	python3 scripts/run_kuos_two_truths_gap_holography_spine_checks_v0_1.py
