import KUOS.DependentOriginationScaledColimitsPresentabilityV1_45

namespace KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46

open CategoryTheory
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationScaledAnodyneGeneratorClosureV1_42
open KUOS.DependentOriginationScaledAnodyneWFSUniversalityV1_43
open KUOS.DependentOriginationScaledColimitsPresentabilityV1_45

universe u

/-!
# External scaled-anodyne generator comparison v1.46

Version 1.45 closes the internal KuuOS small-object argument for the canonical
horn-cylinder generator family `T`.  The remaining comparison problem is now
external: how can another proposed standard generator family `E` be shown to
present the same scaled-anodyne/fibration theory?

For any morphism property `E` in `ScaledSSet`, write

```text
A_E := E.rlp.llp
F_E := E.rlp.
```

It is enough to prove the two mutual generation inclusions

```text
T ≤ A_E
E ≤ A_T.
```

The first says every canonical KuuOS horn-cylinder generator is generated by
the external family.  The second says every external generator is already
canonical generated-anodyne.  No equality of literal generator lists is
required.

From these two inclusions, orthogonal saturation gives

```text
A_E = A_T
F_E = F_T.
```

Consequently the unconditional weak factorization system constructed in v1.45
transports to `E` without a second small-object argument, and fibrancy for the
external generators is exactly canonical attachment fibrancy.

This file deliberately does not claim that pinned Mathlib already contains a
Lurie scaled-anodyne generator family.  A future external implementation only
has to instantiate the comparison structure below.
-/

/-- The left orthogonal closure generated by an arbitrary external family. -/
def externalGeneratedScaledAnodyne
    (E : MorphismProperty (ScaledSSet.{u})) :
    MorphismProperty (ScaledSSet.{u}) :=
  E.rlp.llp

/-- The right lifting class determined by an arbitrary external family. -/
def externalGeneratedScaledFibration
    (E : MorphismProperty (ScaledSSet.{u})) :
    MorphismProperty (ScaledSSet.{u}) :=
  E.rlp

/-- Every generated left class `E.rlp.llp` is orthogonally saturated. -/
theorem externalGeneratedScaledAnodyne_isOrthogonallySaturated
    (E : MorphismProperty (ScaledSSet.{u})) :
    IsOrthogonallySaturated (externalGeneratedScaledAnodyne E) := by
  unfold IsOrthogonallySaturated externalGeneratedScaledAnodyne
  rw [MorphismProperty.rlp_llp_rlp]

/-- Generic universal property: the orthogonal closure of `E` lies in every
orthogonally saturated class containing `E`. -/
theorem externalGeneratedScaledAnodyne_le_of_le_saturated
    {E A : MorphismProperty (ScaledSSet.{u})}
    (h : E ≤ A)
    (hsat : IsOrthogonallySaturated A) :
    externalGeneratedScaledAnodyne E ≤ A := by
  have hrlp : A.rlp ≤ E.rlp :=
    MorphismProperty.antitone_rlp h
  have hllp : E.rlp.llp ≤ A.rlp.llp :=
    MorphismProperty.antitone_llp hrlp
  rw [hsat] at hllp
  exact hllp

/-- Generator-level comparison data between an external family `E` and the
canonical KuuOS horn-cylinder family `T`.

The conditions are closure-level mutual generation, not equality of literal
generator lists. -/
structure ScaledAnodyneGeneratorComparison
    (E : MorphismProperty (ScaledSSet.{u})) : Prop where
  canonicalGenerators_le_externalGenerated :
    (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E
  externalGenerators_le_canonicalGenerated :
    E ≤ (canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u}))

namespace ScaledAnodyneGeneratorComparison

variable
    {E : MorphismProperty (ScaledSSet.{u})}
    (K : ScaledAnodyneGeneratorComparison E)

/-- The canonical generated class is contained in the external generated
class. -/
theorem canonicalGenerated_le_externalGenerated :
    (canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E :=
  canonicalGeneratedScaledAnodyne_le_of_saturated
    K.canonicalGenerators_le_externalGenerated
    (externalGeneratedScaledAnodyne_isOrthogonallySaturated E)

/-- Conversely the external generated closure is contained in the canonical
closure because every external generator is canonical generated-anodyne. -/
theorem externalGenerated_le_canonicalGenerated :
    externalGeneratedScaledAnodyne E ≤
      (canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u})) :=
  externalGeneratedScaledAnodyne_le_of_le_saturated
    K.externalGenerators_le_canonicalGenerated
    canonicalGeneratedScaledAnodyne_isOrthogonallySaturated

/-- Mutual closure-generation identifies the generated left classes literally. -/
theorem externalGeneratedScaledAnodyne_eq_canonical :
    externalGeneratedScaledAnodyne E =
      (canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u})) := by
  apply le_antisymm
  · exact K.externalGenerated_le_canonicalGenerated
  · exact K.canonicalGenerated_le_externalGenerated

/-- The external and canonical right lifting classes are also literally equal. -/
theorem externalGeneratedScaledFibration_eq_canonical :
    externalGeneratedScaledFibration E =
      (canonicalGeneratedScaledFibration : MorphismProperty (ScaledSSet.{u})) := by
  unfold externalGeneratedScaledFibration
  rw [← MorphismProperty.rlp_llp_rlp E]
  rw [K.externalGeneratedScaledAnodyne_eq_canonical]
  exact canonicalGeneratedScaledAnodyne_rlp_eq_fibration

/-- In particular the external family has exactly the same RLP as the original
canonical generator family. -/
theorem external_rlp_eq_canonical_generators_rlp :
    E.rlp =
      (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})).rlp := by
  rw [← K.externalGeneratedScaledFibration_eq_canonical]
  rfl

/-- The external generated closure is itself a compatible v1.42 presentation. -/
def toScaledAnodynePresentation : ScaledAnodynePresentation.{u} where
  anodyne := externalGeneratedScaledAnodyne E
  generators_le := K.canonicalGenerators_le_externalGenerated
  le_generatedClosure := K.externalGenerated_le_canonicalGenerated

/-- Because the canonical small-object argument is already theorem-level, the
external generated pair inherits a native Mathlib weak factorization system
without requiring any smallness or presentability theorem for the external
generator list. -/
noncomputable def externalGeneratedScaledWeakFactorizationSystem :
    MorphismProperty.IsWeakFactorizationSystem
      (externalGeneratedScaledAnodyne E)
      (externalGeneratedScaledFibration E) := by
  rw [K.externalGeneratedScaledAnodyne_eq_canonical]
  rw [K.externalGeneratedScaledFibration_eq_canonical]
  exact canonicalGeneratedScaledWeakFactorizationSystem_unconditional

/-- The external generated left class therefore has the same canonical
cellular description as the KuuOS closure. -/
theorem externalGeneratedScaledAnodyne_eq_canonicalCellularClosure :
    externalGeneratedScaledAnodyne E =
      (MorphismProperty.transfiniteCompositions.{u}
        (MorphismProperty.coproducts.{u}
          (scaledHornAttachmentGenerators : MorphismProperty
            (ScaledSSet.{u}))).pushouts).retracts := by
  rw [K.externalGeneratedScaledAnodyne_eq_canonical]
  exact canonicalGeneratedScaledAnodyne_eq_cellularClosure_unconditional

end ScaledAnodyneGeneratorComparison

/-! ## External fibrancy and canonical attachment fibrancy -/

/-- Fibrancy measured directly by an external generator family. -/
def IsFibrantForExternalGenerators
    (E : MorphismProperty (ScaledSSet.{u}))
    (X : ScaledSSet.{u}) : Prop :=
  E.rlp (ScaledSSet.toPoint X)

/-- Under generator comparison, external fibrancy is exactly canonical
attachment fibrancy. -/
theorem isFibrantForExternalGenerators_iff_attachmentFibrant
    {E : MorphismProperty (ScaledSSet.{u})}
    (K : ScaledAnodyneGeneratorComparison E)
    (X : ScaledSSet.{u}) :
    IsFibrantForExternalGenerators E X ↔ IsAttachmentFibrant X := by
  unfold IsFibrantForExternalGenerators IsAttachmentFibrant
  rw [K.external_rlp_eq_canonical_generators_rlp]

/-- External fibrancy therefore supplies the exact terminal RLP for every
chosen scaled horn family. -/
noncomputable def familyTerminalRLPOfExternalFibrant
    {E : MorphismProperty (ScaledSSet.{u})}
    (K : ScaledAnodyneGeneratorComparison E)
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    (hX : IsFibrantForExternalGenerators E (ScaledSSet.of X sX))
    (F : ScaledHornFamily X sX) :
    ScaledHornFamilyTerminalRLP sX F :=
  familyTerminalRLPOfAttachmentFibrant
    ((isFibrantForExternalGenerators_iff_attachmentFibrant K _).mp hX) F

/-!
The comparison spine is now:

```text
external generator family E
  + T ≤ E.rlp.llp
  + E ≤ T.rlp.llp
  -> E.rlp.llp = T.rlp.llp
  -> E.rlp = T.rlp
  -> external WFS = canonical WFS
  -> external fibrancy = attachment fibrancy
  -> terminal RLP for every horn family.
```

The existing v1.42 model-equivalence carrier accepts attachment fibrancy, so
external fibrancy can be converted through the proved equivalence above before
applying the established presentation-independent strict global Duskin theorem.

Thus an eventual standard/Lurie scaled-anodyne implementation does not need a
second KuuOS strictification or small-object proof.  Its only comparison burden
is the two generator-level closure inclusions above.
-/

end KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
