import KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseABCellularityV1_72

namespace KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseScaledPushoutV1_73

open CategoryTheory
open CategoryTheory.Category
open CategoryTheory.Limits
open Opposite
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationGlobalDuskinScaledHornCoherenceV1_22
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationScaledAnodyneAttachmentFactorizationV1_48
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
open KUOS.DependentOriginationStandardTypeABoundaryPrismRelativeCellV1_61
open KUOS.DependentOriginationStandardTypeABoundaryPrismScaledRankFiltrationV1_71
open KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseABCellularityV1_72

universe u

noncomputable section

/-!
# Exact scaled rank pushouts for the standard type-(A) boundary prism v1.73

Version v1.72 consumed all local scaling geometry into the standard A/B
cellular calculus.  Every exact rank cell is now known to be either pure A or
A followed by exactly one q12/q23 B completion, and every such exact cell lies
in the standard cellular closure.

The remaining problem is global: Mathlib v1.61 supplies a simultaneous ordinary
pushout square at every natural-number rank, while v1.71 equips every rank stage
with the exact scaling pulled back from the ambient scaled cylinder.  This file
proves that these two structures are compatible *categorically*.

The proof is organized around one reusable construction.  Given an ordinary
simplicial pushout

```text
Z --f--> X
|         |
g         inl
v         v
Y --inr-> P,
```

and chosen scalings on `X` and `Y`, put on `P` the least scaling containing

* the two mandatory degenerate families;
* all images of thin 2-simplices from `X` along `inl`;
* all images of thin 2-simplices from `Y` along `inr`.

The ordinary pushout universal property then upgrades to a genuine pushout in
`ScaledSSet`: a descended map is scaled because it is scaled on exactly those
generators.  This is the rankwise analogue of the v1.55 generated Leibniz
pushout argument, now stated independently of the special union-product
geometry.

For the boundary-prism rank square we equip the two coproduct carriers
`sigmaHorn j` and `sigmaStdSimplex j` by pullback from the current and successor
rank stages.  The Mathlib square commutativity makes the coproduct horn map
scaled.  Finally, Mathlib's degreewise joint-surjectivity theorem for the rank
pushout proves that the least generated pushout scaling is *equal* to the
ambient-pullback scaling already present on rank `j+1`.

Thus every ordinary rank successor square of v1.61 is literally a scaled
pushout square between the v1.71 stages.  No q12/q23 case split reappears here.
The next unit can therefore split this simultaneous exact-cell pushout into the
simultaneous A phase and simultaneous exceptional B phase and read each rank
successor as a finite composite of raw standard A/B cellular steps.
-/

/-! ## A generic generated scaling on an ordinary pushout target -/

/-- The least explicit scaling on an ordinary pushout target generated by the
two incoming scaled objects. -/
def generatedPushoutScaling
    {X Y P : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    (sY : ScaledSimplicialSet Y)
    (inl : X ⟶ P)
    (inr : Y ⟶ P) :
    ScaledSimplicialSet P where
  thin := fun t =>
    (minimalScaling P).thin t ∨
      (∃ x : X.obj (op ⦋2⦌),
        sX.thin x ∧ inl.app (op ⦋2⦌) x = t) ∨
      (∃ y : Y.obj (op ⦋2⦌),
        sY.thin y ∧ inr.app (op ⦋2⦌) y = t)
  thin_sigma_zero := by
    intro x
    exact Or.inl ((minimalScaling P).thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl ((minimalScaling P).thin_sigma_one x)

/-- The generated scaled pushout target object. -/
def generatedPushoutTarget
    {X Y P : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    (sY : ScaledSimplicialSet Y)
    (inl : X ⟶ P)
    (inr : Y ⟶ P) : ScaledSSet.{u} :=
  ScaledSSet.of P (generatedPushoutScaling sX sY inl inr)

/-- The first ordinary pushout leg is scaled for the generated target scaling. -/
def generatedPushoutInl
    {X Y P : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    (sY : ScaledSimplicialSet Y)
    (inl : X ⟶ P)
    (inr : Y ⟶ P) :
    ScaledSSet.of X sX ⟶ generatedPushoutTarget sX sY inl inr where
  map := inl
  scaled := by
    intro t ht
    exact Or.inr (Or.inl ⟨t, ht, rfl⟩)

/-- The second ordinary pushout leg is scaled for the generated target scaling. -/
def generatedPushoutInr
    {X Y P : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    (sY : ScaledSimplicialSet Y)
    (inl : X ⟶ P)
    (inr : Y ⟶ P) :
    ScaledSSet.of Y sY ⟶ generatedPushoutTarget sX sY inl inr where
  map := inr
  scaled := by
    intro t ht
    exact Or.inr (Or.inr ⟨t, ht, rfl⟩)

/-! ## Lift an ordinary pushout universal property to `ScaledSSet` -/

/-- A compatible square of scaled maps gives the underlying ordinary
compatibility equation. -/
theorem generatedPushout_compatibility_map
    {Z X Y : SSet.{u}}
    {sZ : ScaledSimplicialSet Z}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : ScaledSSet.of Z sZ ⟶ ScaledSSet.of X sX)
    (g : ScaledSSet.of Z sZ ⟶ ScaledSSet.of Y sY)
    {W : ScaledSSet.{u}}
    (a : ScaledSSet.of X sX ⟶ W)
    (b : ScaledSSet.of Y sY ⟶ W)
    (w : f ≫ a = g ≫ b) :
    f.map ≫ a.map = g.map ≫ b.map := by
  have hw := congrArg ScaledSSet.ScaledMap.map w
  simpa using hw

/-- The ordinary desc map supplied by the underlying simplicial pushout. -/
noncomputable def generatedPushoutDescMap
    {Z X Y P : SSet.{u}}
    {sZ : ScaledSimplicialSet Z}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : ScaledSSet.of Z sZ ⟶ ScaledSSet.of X sX)
    (g : ScaledSSet.of Z sZ ⟶ ScaledSSet.of Y sY)
    (inl : X ⟶ P)
    (inr : Y ⟶ P)
    (h : IsPushout f.map g.map inl inr)
    {W : ScaledSSet.{u}}
    (a : ScaledSSet.of X sX ⟶ W)
    (b : ScaledSSet.of Y sY ⟶ W)
    (w : f ≫ a = g ≫ b) :
    P ⟶ W.carrier :=
  h.desc a.map b.map
    (generatedPushout_compatibility_map f g a b w)

/-- The ordinary descended map preserves the generated pushout scaling. -/
theorem generatedPushoutDescMap_scaled
    {Z X Y P : SSet.{u}}
    {sZ : ScaledSimplicialSet Z}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : ScaledSSet.of Z sZ ⟶ ScaledSSet.of X sX)
    (g : ScaledSSet.of Z sZ ⟶ ScaledSSet.of Y sY)
    (inl : X ⟶ P)
    (inr : Y ⟶ P)
    (h : IsPushout f.map g.map inl inr)
    {W : ScaledSSet.{u}}
    (a : ScaledSSet.of X sX ⟶ W)
    (b : ScaledSSet.of Y sY ⟶ W)
    (w : f ≫ a = g ≫ b) :
    IsScaledMap
      (generatedPushoutScaling sX sY inl inr)
      W.scaling
      (generatedPushoutDescMap f g inl inr h a b w) := by
  intro t ht
  rcases ht with hmin | ⟨x, hx, rfl⟩ | ⟨y, hy, rfl⟩
  · exact
      (minimalScaling_map W.scaling
        (generatedPushoutDescMap f g inl inr h a b w)) t hmin
  · have hfac := ConcreteCategory.congr_hom
      (congr_app
        (h.inl_desc a.map b.map
          (generatedPushout_compatibility_map f g a b w))
        (op ⦋2⦌)) x
    change W.scaling.thin
      ((ConcreteCategory.hom
        ((inl ≫ h.desc a.map b.map
          (generatedPushout_compatibility_map f g a b w)).app
          (op ⦋2⦌))) x)
    rw [hfac]
    exact a.scaled x hx
  · have hfac := ConcreteCategory.congr_hom
      (congr_app
        (h.inr_desc a.map b.map
          (generatedPushout_compatibility_map f g a b w))
        (op ⦋2⦌)) y
    change W.scaling.thin
      ((ConcreteCategory.hom
        ((inr ≫ h.desc a.map b.map
          (generatedPushout_compatibility_map f g a b w)).app
          (op ⦋2⦌))) y)
    rw [hfac]
    exact b.scaled y hy

/-- The native ordinary pushout desc map upgraded to a scaled map. -/
noncomputable def generatedPushoutDesc
    {Z X Y P : SSet.{u}}
    {sZ : ScaledSimplicialSet Z}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : ScaledSSet.of Z sZ ⟶ ScaledSSet.of X sX)
    (g : ScaledSSet.of Z sZ ⟶ ScaledSSet.of Y sY)
    (inl : X ⟶ P)
    (inr : Y ⟶ P)
    (h : IsPushout f.map g.map inl inr)
    {W : ScaledSSet.{u}}
    (a : ScaledSSet.of X sX ⟶ W)
    (b : ScaledSSet.of Y sY ⟶ W)
    (w : f ≫ a = g ≫ b) :
    generatedPushoutTarget sX sY inl inr ⟶ W where
  map := generatedPushoutDescMap f g inl inr h a b w
  scaled := generatedPushoutDescMap_scaled f g inl inr h a b w

@[simp, reassoc]
theorem generatedPushout_inl_desc
    {Z X Y P : SSet.{u}}
    {sZ : ScaledSimplicialSet Z}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : ScaledSSet.of Z sZ ⟶ ScaledSSet.of X sX)
    (g : ScaledSSet.of Z sZ ⟶ ScaledSSet.of Y sY)
    (inl : X ⟶ P)
    (inr : Y ⟶ P)
    (h : IsPushout f.map g.map inl inr)
    {W : ScaledSSet.{u}}
    (a : ScaledSSet.of X sX ⟶ W)
    (b : ScaledSSet.of Y sY ⟶ W)
    (w : f ≫ a = g ≫ b) :
    generatedPushoutInl sX sY inl inr ≫
        generatedPushoutDesc f g inl inr h a b w = a := by
  apply ScaledSSet.ScaledMap.ext
  exact h.inl_desc a.map b.map
    (generatedPushout_compatibility_map f g a b w)

@[simp, reassoc]
theorem generatedPushout_inr_desc
    {Z X Y P : SSet.{u}}
    {sZ : ScaledSimplicialSet Z}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : ScaledSSet.of Z sZ ⟶ ScaledSSet.of X sX)
    (g : ScaledSSet.of Z sZ ⟶ ScaledSSet.of Y sY)
    (inl : X ⟶ P)
    (inr : Y ⟶ P)
    (h : IsPushout f.map g.map inl inr)
    {W : ScaledSSet.{u}}
    (a : ScaledSSet.of X sX ⟶ W)
    (b : ScaledSSet.of Y sY ⟶ W)
    (w : f ≫ a = g ≫ b) :
    generatedPushoutInr sX sY inl inr ≫
        generatedPushoutDesc f g inl inr h a b w = b := by
  apply ScaledSSet.ScaledMap.ext
  exact h.inr_desc a.map b.map
    (generatedPushout_compatibility_map f g a b w)

/-- Uniqueness of the generated scaled desc map is inherited from the ordinary
pushout. -/
theorem generatedPushout_hom_ext
    {Z X Y P : SSet.{u}}
    {sZ : ScaledSimplicialSet Z}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : ScaledSSet.of Z sZ ⟶ ScaledSSet.of X sX)
    (g : ScaledSSet.of Z sZ ⟶ ScaledSSet.of Y sY)
    (inl : X ⟶ P)
    (inr : Y ⟶ P)
    (h : IsPushout f.map g.map inl inr)
    {W : ScaledSSet.{u}}
    {a b : generatedPushoutTarget sX sY inl inr ⟶ W}
    (h₁ : generatedPushoutInl sX sY inl inr ≫ a =
      generatedPushoutInl sX sY inl inr ≫ b)
    (h₂ : generatedPushoutInr sX sY inl inr ≫ a =
      generatedPushoutInr sX sY inl inr ≫ b) :
    a = b := by
  apply ScaledSSet.ScaledMap.ext
  apply h.hom_ext
  · have hm := congrArg ScaledSSet.ScaledMap.map h₁
    change inl ≫ a.map = inl ≫ b.map at hm
    exact hm
  · have hm := congrArg ScaledSSet.ScaledMap.map h₂
    change inr ≫ a.map = inr ≫ b.map at hm
    exact hm

/-- Every ordinary simplicial pushout with scaled incoming objects becomes a
genuine `ScaledSSet` pushout after equipping the target with the generated
scaling. -/
noncomputable def generatedPushout_isPushout
    {Z X Y P : SSet.{u}}
    {sZ : ScaledSimplicialSet Z}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : ScaledSSet.of Z sZ ⟶ ScaledSSet.of X sX)
    (g : ScaledSSet.of Z sZ ⟶ ScaledSSet.of Y sY)
    (inl : X ⟶ P)
    (inr : Y ⟶ P)
    (h : IsPushout f.map g.map inl inr) :
    IsPushout
      f g
      (generatedPushoutInl sX sY inl inr)
      (generatedPushoutInr sX sY inl inr) := by
  have hw :
      f ≫ generatedPushoutInl sX sY inl inr =
        g ≫ generatedPushoutInr sX sY inl inr := by
    apply ScaledSSet.ScaledMap.ext
    exact h.w
  refine {
    w := hw
    isColimit' := ⟨?_⟩
  }
  exact PushoutCocone.IsColimit.mk
    hw
    (fun s => generatedPushoutDesc f g inl inr h s.inl s.inr s.condition)
    (fun s => generatedPushout_inl_desc
      f g inl inr h s.inl s.inr s.condition)
    (fun s => generatedPushout_inr_desc
      f g inl inr h s.inl s.inr s.condition)
    (by
      intro s m hm₁ hm₂
      apply generatedPushout_hom_ext f g inl inr h
      · rw [hm₁, generatedPushout_inl_desc]
      · rw [hm₂, generatedPushout_inr_desc])

/-! ## Pullback scalings on the two Mathlib coproduct carriers -/

/-- The scaling on the coproduct of rank-`j` horns is pulled back from the
current scaled rank stage along Mathlib's map `t j`. -/
def standardTypeABoundaryPrismRankSigmaHornScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    ScaledSimplicialSet
      ((standardTypeABoundaryPrismRankFunction g).sigmaHorn j) :=
  pullbackScaling
    (standardTypeABoundaryPrismRankStageScaling g j)
    ((standardTypeABoundaryPrismRankFunction g).t j)

/-- The exact scaling on the coproduct of attached simplices is pulled back
from the successor rank stage along Mathlib's map `b j`. -/
def standardTypeABoundaryPrismRankSigmaStdSimplexScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    ScaledSimplicialSet
      ((standardTypeABoundaryPrismRankFunction g).sigmaStdSimplex j) :=
  pullbackScaling
    (standardTypeABoundaryPrismRankStageScaling g (j + 1))
    ((standardTypeABoundaryPrismRankFunction g).b j)

/-- The scaled coproduct horn object at rank `j`. -/
def standardTypeABoundaryPrismRankSigmaHorn
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : ScaledSSet.{u} :=
  ScaledSSet.of
    ((standardTypeABoundaryPrismRankFunction g).sigmaHorn j)
    (standardTypeABoundaryPrismRankSigmaHornScaling g j)

/-- The scaled coproduct simplex object at rank `j`. -/
def standardTypeABoundaryPrismRankSigmaStdSimplex
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : ScaledSSet.{u} :=
  ScaledSSet.of
    ((standardTypeABoundaryPrismRankFunction g).sigmaStdSimplex j)
    (standardTypeABoundaryPrismRankSigmaStdSimplexScaling g j)

/-- The coproduct horn maps to the current rank stage by construction. -/
def standardTypeABoundaryPrismRankSigmaHornToStage
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankSigmaHorn g j ⟶
      standardTypeABoundaryPrismRankStage g j where
  map := (standardTypeABoundaryPrismRankFunction g).t j
  scaled := pullbackScaling_map _ _

/-- The coproduct of attached simplices maps to the successor rank stage by
construction. -/
def standardTypeABoundaryPrismRankSigmaStdSimplexToSucc
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankSigmaStdSimplex g j ⟶
      standardTypeABoundaryPrismRankStage g (j + 1) where
  map := (standardTypeABoundaryPrismRankFunction g).b j
  scaled := pullbackScaling_map _ _

/-- Mathlib's coproduct horn map is scaled for these two pullback scalings.
This uses only the commutativity of the ordinary rank square and the scaled
monotonicity map between consecutive ambient-pullback stages. -/
def standardTypeABoundaryPrismRankSigmaCellHom
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankSigmaHorn g j ⟶
      standardTypeABoundaryPrismRankSigmaStdSimplex g j where
  map := (standardTypeABoundaryPrismRankFunction g).m j
  scaled := by
    intro t ht
    change
      (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin
        ((((standardTypeABoundaryPrismRankFunction g).m j ≫
          (standardTypeABoundaryPrismRankFunction g).b j).app
            (op ⦋2⦌)) t)
    have hstage :=
      (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).scaled
        (((standardTypeABoundaryPrismRankFunction g).t j).app
          (op ⦋2⦌) t) ht
    have hw := ConcreteCategory.congr_hom
      (congr_app
        ((standardTypeABoundaryPrismRankFunction g).w j)
        (op ⦋2⦌)) t
    rw [← hw]
    exact hstage

/-! ## The generated rank target scaling equals the exact ambient scaling -/

/-- The least scaling generated by the current stage and the exact coproduct of
attached simplices is exactly the ambient-pullback scaling on rank `j+1`.
The reverse inclusion is where the ordinary Mathlib pushout is used
substantively: its two legs are jointly surjective in degree two. -/
theorem standardTypeABoundaryPrismRankGeneratedPushoutScaling_eq_succ
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    generatedPushoutScaling
        (standardTypeABoundaryPrismRankStageScaling g j)
        (standardTypeABoundaryPrismRankSigmaStdSimplexScaling g j)
        (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map
        ((standardTypeABoundaryPrismRankFunction g).b j) =
      standardTypeABoundaryPrismRankStageScaling g (j + 1) := by
  apply scaling_eq_of_le_antisymm
  · intro t ht
    rcases ht with hmin | ⟨x, hx, rfl⟩ | ⟨y, hy, rfl⟩
    · rcases hmin with ⟨x, rfl⟩ | ⟨x, rfl⟩
      · exact
          (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin_sigma_zero x
      · exact
          (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin_sigma_one x
    · exact
        (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).scaled x hx
    · exact hy
  · intro t ht
    have hmem :
        t ∈
          Set.range
              ((SSet.Subcomplex.homOfLE
                ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                  (Order.le_succ j))).app (op ⦋2⦌)) ⊔
            Set.range
              (((standardTypeABoundaryPrismRankFunction g).b j).app
                (op ⦋2⦌)) := by
      rw [(standardTypeABoundaryPrismRankFunction g).range_homOfLE_app_union_range_b_app
        j (op ⦋2⦌)]
      exact Set.mem_univ t
    change
      t ∈
        Set.range
            ((SSet.Subcomplex.homOfLE
              ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                (Order.le_succ j))).app (op ⦋2⦌)) ∪
          Set.range
            (((standardTypeABoundaryPrismRankFunction g).b j).app
              (op ⦋2⦌)) at hmem
    rcases hmem with ⟨x, rfl⟩ | ⟨y, rfl⟩
    · have hx :
          (standardTypeABoundaryPrismRankStageScaling g j).thin x := by
        change
          (scaledSimplexCylinder (standardTypeASimplexScaling g.i)).scaling.thin
            (((standardTypeABoundaryPrismRankFunction g).filtration j).ι.app
              (op ⦋2⦌) x)
        change
          (scaledSimplexCylinder (standardTypeASimplexScaling g.i)).scaling.thin
            ((((SSet.Subcomplex.homOfLE
              ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                (Order.le_succ j))) ≫
              ((standardTypeABoundaryPrismRankFunction g).filtration (j + 1)).ι).app
                (op ⦋2⦌)) x) at ht
        have hι := ConcreteCategory.congr_hom
          (congr_app
            (SSet.Subcomplex.homOfLE_ι
              ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                (Order.le_succ j)))
            (op ⦋2⦌)) x
        simpa only [hι] using ht
      exact Or.inr (Or.inl ⟨x, hx, rfl⟩)
    · have hy :
          (standardTypeABoundaryPrismRankSigmaStdSimplexScaling g j).thin y := by
        exact ht
      exact Or.inr (Or.inr ⟨y, hy, rfl⟩)

/-! ## Every Mathlib rank successor square is an exact scaled pushout -/

/-- The simultaneous rank successor square from v1.61 lifts to a genuine
pushout square in `ScaledSSet`, with the *existing* exact v1.71 scaling on the
successor stage rather than an auxiliary scaling. -/
noncomputable def standardTypeABoundaryPrism_rankStep_scaled_isPushout
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    IsPushout
      (standardTypeABoundaryPrismRankSigmaHornToStage g j)
      (standardTypeABoundaryPrismRankSigmaCellHom g j)
      (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j))
      (standardTypeABoundaryPrismRankSigmaStdSimplexToSucc g j) := by
  have h :=
    generatedPushout_isPushout
      (standardTypeABoundaryPrismRankSigmaHornToStage g j)
      (standardTypeABoundaryPrismRankSigmaCellHom g j)
      (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map
      ((standardTypeABoundaryPrismRankFunction g).b j)
      (standardTypeABoundaryPrism_rankStep_isPushout g j)
  simp only [generatedPushoutTarget,
    standardTypeABoundaryPrismRankGeneratedPushoutScaling_eq_succ g j] at h
  convert h using 1 <;> apply ScaledSSet.ScaledMap.ext <;> rfl

/-!
The global rank filtration is now genuinely scaled:

```text
scaled sigmaHorn(j)  ---->  scaled rank stage j
       |                         |
       | exact coproduct map     | scaled filtration inclusion
       v                         v
scaled sigmaDelta(j) ---->  scaled rank stage (j+1)
```

and the square is a categorical pushout in `ScaledSSet` for every `j`.
Moreover the target scaling is not merely comparable with the ambient one: it
is exactly the ambient-pullback scaling of v1.71.

This removes the final ambiguity between the ordinary Mathlib relative-cell
filtration and the scaled KuuOS carrier.  The next unit may work purely in the
morphism-property calculus: split the exact coproduct map into simultaneous A
and exceptional-B coproduct phases, show each induced rank map belongs to
`standardABCRawCellularStep`, and take the natural-number transfinite
composition required by `StandardABCTypeAEndpointLeibnizCellularCertificate`.
-/

end

end KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseScaledPushoutV1_73