import KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseSimultaneousAPhaseV1_74

namespace KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseSimultaneousBPhaseV1_75

open CategoryTheory
open CategoryTheory.Category
open CategoryTheory.Limits
open Opposite
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
open KUOS.DependentOriginationStandardTypeBScalingPushoutV1_56
open KUOS.DependentOriginationStandardTypeBThreeSimplexCompletionV1_57
open KUOS.DependentOriginationStandardTypeCCollapsedEdgeV1_58
open KUOS.DependentOriginationStandardABCLeibnizCellularComparisonV1_59
open KUOS.DependentOriginationStandardTypeABoundaryPrismRelativeCellV1_61
open KUOS.DependentOriginationStandardTypeABoundaryPrismScaledCellsV1_62
open KUOS.DependentOriginationStandardTypeABoundaryPrismCellPushoutCriterionV1_65
open KUOS.DependentOriginationStandardTypeABoundaryPrismCellACompatibilityV1_66
open KUOS.DependentOriginationStandardTypeABoundaryPrismCellwiseABClassificationV1_70
open KUOS.DependentOriginationStandardTypeABoundaryPrismScaledRankFiltrationV1_71
open KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseABCellularityV1_72
open KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseScaledPushoutV1_73
open KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseSimultaneousAPhaseV1_74

universe u

noncomputable section

/-!
# Simultaneous exceptional type-(B) rank phase v1.75

Version v1.74 constructed, for every natural-number rank, the first half

```text
R_j -- all standard A cells at once --> A_j
```

as one raw cellular step.  The carrier of `A_j` is already the carrier of
`R_(j+1)`; only some thin triangles are missing.  Version v1.70 identified
those residuals exactly: every nontrivial completion is q12 or q23, and v1.72
identified both completions with pushouts of the literal standard type-(B)
generator.

This file performs all such type-(B) completions simultaneously.  We index
copies of the same `Delta[4]` type-(B) generator by the *data* of a q12 or q23
factorization, form their categorical coproduct, and attach that coproduct to
`A_j`.  Since the standard B generator is identity-underlying, the ordinary
pushout carrier is still the successor filtration.  The only substantive
global theorem is equality of scalings.

For the reverse scaling inclusion we use two nested ordinary coproduct
surjectivity statements:

* every successor simplex comes from the previous rank stage or from
  `sigmaStdSimplex j`;
* every simplex of `sigmaStdSimplex j` comes from one actual rank cell.

The cellwise trichotomy then gives exactly three cases.  Pure-A cells are
already in `A_j`; q12 and q23 cells are generated by the corresponding copy of
the standard B target.  No staircase geometry is recomputed here.

The outputs are

```text
A_j -> R_(j+1) ∈ pushouts (coproducts E_std)
```

and therefore every exact rank successor is a two-step A/B composite in the
strong unretracted standard cellular closure.
-/

/-! ## Every cellwise A-pushout target maps to the global A phase -/

/-- Compatibility of the cell horn map with the global A-phase inclusion. -/
theorem standardTypeABoundaryPrismCell_mapHorn_to_APhase
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (c : (standardTypeABoundaryPrismRankFunction.{u} g).Cell j) :
    c.mapHorn ≫ (standardTypeABoundaryPrismRankStageToAPhase g j).map =
      c.horn.ι ≫ c.mapToSucc := by
  change
    c.mapHorn ≫
        SSet.Subcomplex.homOfLE
          ((standardTypeABoundaryPrismRankFunction.{u} g).filtration_monotone
            (Nat.le_succ j)) =
      c.horn.ι ≫ c.mapToSucc
  calc
    c.mapHorn ≫
        SSet.Subcomplex.homOfLE
          ((standardTypeABoundaryPrismRankFunction.{u} g).filtration_monotone
            (Nat.le_succ j)) =
        (c.ιSigmaHorn ≫ (standardTypeABoundaryPrismRankFunction.{u} g).t j) ≫
          SSet.Subcomplex.homOfLE
            ((standardTypeABoundaryPrismRankFunction.{u} g).filtration_monotone
              (Nat.le_succ j)) := by rw [c.ι_t]
    _ = c.ιSigmaHorn ≫
        ((standardTypeABoundaryPrismRankFunction.{u} g).t j ≫
          SSet.Subcomplex.homOfLE
            ((standardTypeABoundaryPrismRankFunction.{u} g).filtration_monotone
              (Nat.le_succ j))) := by simp [Category.assoc]
    _ = c.ιSigmaHorn ≫
        ((standardTypeABoundaryPrismRankFunction.{u} g).m j ≫
          (standardTypeABoundaryPrismRankFunction.{u} g).b j) := by
          exact congrArg (fun k => c.ιSigmaHorn ≫ k)
            ((standardTypeABoundaryPrismRankFunction.{u} g).w j)
    _ = (c.ιSigmaHorn ≫ (standardTypeABoundaryPrismRankFunction.{u} g).m j) ≫
        (standardTypeABoundaryPrismRankFunction.{u} g).b j := by simp [Category.assoc]
    _ = (c.horn.ι ≫ c.ιSigmaStdSimplex) ≫
        (standardTypeABoundaryPrismRankFunction.{u} g).b j := by rw [c.ι_m]
    _ = c.horn.ι ≫
        (c.ιSigmaStdSimplex ≫ (standardTypeABoundaryPrismRankFunction.{u} g).b j) := by
          simp [Category.assoc]
    _ = c.horn.ι ≫ c.mapToSucc := by rw [c.ι_b]

/-- The local A-cobase-change target maps canonically into the simultaneous
A-phase target. -/
def standardTypeABoundaryPrismCellAPushoutTargetToAPhase
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (c : (standardTypeABoundaryPrismRankFunction.{u} g).Cell j) :
    standardTypeABoundaryPrismCellAPushoutTarget g j c ⟶
      standardTypeABoundaryPrismRankAPhase g j where
  map := c.mapToSucc
  scaled := by
    intro t ht
    change
      (standardTypeABoundaryPrismRankAPhaseScaling g j).thin
        (c.mapToSucc.app (op ⦋2⦌) t)
    change
      (minimalScaling
          ((standardTypeABoundaryPrismRankFunction.{u} g).filtration (j + 1) : SSet.{u})).thin
          (c.mapToSucc.app (op ⦋2⦌) t) ∨
        (∃ x,
          (standardTypeABoundaryPrismRankStageScaling g j).thin x ∧
            (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map.app
              (op ⦋2⦌) x = c.mapToSucc.app (op ⦋2⦌) t) ∨
        ∃ y,
          (standardTypeABoundaryPrismRankASimplexSigmaScaling g j).thin y ∧
            ((standardTypeABoundaryPrismRankFunction.{u} g).b j).app (op ⦋2⦌) y =
              c.mapToSucc.app (op ⦋2⦌) t
    rcases ht with hA | ⟨x, hx, rfl⟩
    · right
      right
      refine ⟨c.ιSigmaStdSimplex.app (op ⦋2⦌) t, ?_, ?_⟩
      · exact Or.inr ⟨c, t, hA, rfl⟩
      · have h := ConcreteCategory.congr_hom
          (congr_app c.ι_b (op ⦋2⦌)) t
        simpa only [NatTrans.comp_app_apply] using h
    · right
      left
      refine ⟨c.mapHorn.app (op ⦋2⦌) x, ?_, ?_⟩
      · exact
          (standardTypeABoundaryPrismScaledCellSourceToRankStage g j c).scaled x hx
      · have hnat :=
          standardTypeABoundaryPrismCell_mapHorn_to_APhase g j c
        change
          c.mapHorn ≫
              (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map =
            c.horn.ι ≫ c.mapToSucc at hnat
        have h := ConcreteCategory.congr_hom
          (congr_app hnat (op ⦋2⦌)) x
        change
          (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map.app
              (op ⦋2⦌) (c.mapHorn.app (op ⦋2⦌) x) =
            c.mapToSucc.app (op ⦋2⦌) (c.horn.ι.app (op ⦋2⦌) x) at h
        exact h

/-! ## Exceptional cells as data, not a proposition subtype -/

/-- Data indexing exactly the nontrivial B completions at one rank.  Using an
inductive type permits elimination into actual maps without choosing from a
propositional disjunction. -/
inductive StandardTypeABoundaryPrismRankBCell
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : Type u where
  | q12
      (c : (standardTypeABoundaryPrismRankFunction.{u} g).Cell j)
      (h : StandardTypeABoundaryPrismCellQ12Factorization g j c)
  | q23
      (c : (standardTypeABoundaryPrismRankFunction.{u} g).Cell j)
      (h : StandardTypeABoundaryPrismCellQ23Factorization g j c)

/-- Underlying ordinary rank cell of an exceptional B datum. -/
def StandardTypeABoundaryPrismRankBCell.cell
    {g : StandardTypeAHornAttachmentGeneratorIndex}
    {j : ℕ} :
    StandardTypeABoundaryPrismRankBCell.{u} g j →
      (standardTypeABoundaryPrismRankFunction.{u} g).Cell j := fun b =>
  match b with
  | .q12 c _ => c
  | .q23 c _ => c

/-! ## One standard-B copy maps to the corresponding actual completion -/

/-- Source map from one literal standard type-(B) generator into `A_j`. -/
noncomputable def standardTypeABoundaryPrismRankBCellSourceToAPhase
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (b : StandardTypeABoundaryPrismRankBCell.{u} g j) :
    standardTypeBSource.{u} ⟶ standardTypeABoundaryPrismRankAPhase g j := by
  cases b with
  | q12 c h =>
      exact
        scalingEnrichmentPushoutLowerMap
            standardTypeBCollapse12 standardTypeBCollapse12_scaled ≫
          (standardTypeABoundaryPrismCellQ12SourceIso g j c h).inv ≫
          standardTypeABoundaryPrismCellAPushoutTargetToAPhase g j c
  | q23 c h =>
      exact
        scalingEnrichmentPushoutLowerMap
            standardTypeBCollapse23 standardTypeBCollapse23_scaled ≫
          (standardTypeABoundaryPrismCellQ23SourceIso g j c h).inv ≫
          standardTypeABoundaryPrismCellAPushoutTargetToAPhase g j c

/-- Target map from the corresponding literal standard-B target into the exact
successor rank stage. -/
noncomputable def standardTypeABoundaryPrismRankBCellTargetToSucc
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (b : StandardTypeABoundaryPrismRankBCell.{u} g j) :
    standardTypeBTarget.{u} ⟶ standardTypeABoundaryPrismRankStage g (j + 1) := by
  cases b with
  | q12 c h =>
      exact
        scalingEnrichmentPushoutUpperMap
            standardTypeBTargetScaling
            standardTypeBCollapse12BaseScaling
            standardTypeBCollapse12 ≫
          (standardTypeABoundaryPrismCellQ12TargetIso g j c h).inv ≫
          standardTypeABoundaryPrismScaledCellTargetToRankSucc g j c
  | q23 c h =>
      exact
        scalingEnrichmentPushoutUpperMap
            standardTypeBTargetScaling
            standardTypeBCollapse23BaseScaling
            standardTypeBCollapse23 ≫
          (standardTypeABoundaryPrismCellQ23TargetIso g j c h).inv ≫
          standardTypeABoundaryPrismScaledCellTargetToRankSucc g j c

/-- The identity-underlying three-simplex carrier transport is independent of
the scaling structure placed on the actual rank-cell carrier. -/
private theorem standardTypeABoundaryPrismCellScalingIsoToThree_inv_map_eq
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (c : (standardTypeABoundaryPrismRankFunction.{u} g).Cell j)
    (h3 : c.dim + 1 = 3)
    (s t : ScaledSimplicialSet (Δ[c.dim + 1] : SSet.{u})) :
    (standardTypeABoundaryPrismCellScalingIsoToThree g j c h3 s).inv.map =
      (standardTypeABoundaryPrismCellScalingIsoToThree g j c h3 t).inv.map := by
  exact
    KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseABCellularityV1_72.standardTypeABoundaryPrismCellScalingIsoToThree_inv_map_eq
      g j c h3 s t

/-- The source and target maps of one B datum have exactly the same underlying
simplicial map. -/
theorem standardTypeABoundaryPrismRankBCell_source_target_map_eq
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (b : StandardTypeABoundaryPrismRankBCell.{u} g j) :
    (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map =
      (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map := by
  cases b with
  | q12 c h =>
      have htransport :=
        standardTypeABoundaryPrismCellScalingIsoToThree_inv_map_eq
          g j c h.target_three
          (standardTypeABoundaryPrismCellAPushoutScaling g j c)
          (standardTypeABoundaryPrismCellScaling g j c)
      simp [
        Category.assoc,
        standardTypeABoundaryPrismRankBCellSourceToAPhase,
        standardTypeABoundaryPrismRankBCellTargetToSucc,
        standardTypeABoundaryPrismCellQ12SourceIso,
        standardTypeABoundaryPrismCellQ12TargetIso,
        scalingEnrichmentPushoutLowerMap,
        scalingEnrichmentPushoutUpperMap,
        standardTypeABoundaryPrismCellAPushoutTargetToAPhase,
        standardTypeABoundaryPrismScaledCellTargetToRankSucc,
        htransport]
      exact congrArg
        (fun k => standardTypeBCollapse12 ≫ k)
        (Category.assoc (𝟙 _) _ _).symm
  | q23 c h =>
      have htransport :=
        standardTypeABoundaryPrismCellScalingIsoToThree_inv_map_eq
          g j c h.target_three
          (standardTypeABoundaryPrismCellAPushoutScaling g j c)
          (standardTypeABoundaryPrismCellScaling g j c)
      simp [
        Category.assoc,
        standardTypeABoundaryPrismRankBCellSourceToAPhase,
        standardTypeABoundaryPrismRankBCellTargetToSucc,
        standardTypeABoundaryPrismCellQ23SourceIso,
        standardTypeABoundaryPrismCellQ23TargetIso,
        scalingEnrichmentPushoutLowerMap,
        scalingEnrichmentPushoutUpperMap,
        standardTypeABoundaryPrismCellAPushoutTargetToAPhase,
        standardTypeABoundaryPrismScaledCellTargetToRankSucc,
        htransport]
      exact congrArg
        (fun k => standardTypeBCollapse23 ≫ k)
        (Category.assoc (𝟙 _) _ _).symm

/-! ## Coproduct of all literal standard-B copies -/

/-- Ordinary carrier of the exceptional B coproduct. -/
noncomputable abbrev standardTypeABoundaryPrismRankBSigmaCarrier
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : SSet.{u} :=
  ∐ fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => (Δ[4] : SSet.{u})

/-- Source scaling on the exceptional standard-B coproduct. -/
def standardTypeABoundaryPrismRankBSourceSigmaScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    ScaledSimplicialSet (standardTypeABoundaryPrismRankBSigmaCarrier g j) where
  thin := fun t =>
    (minimalScaling (standardTypeABoundaryPrismRankBSigmaCarrier g j)).thin t ∨
      ∃ (b : StandardTypeABoundaryPrismRankBCell.{u} g j)
        (x : (Δ[4] : SSet.{u}).obj (op ⦋2⦌)),
        standardTypeBSourceScaling.thin x ∧
          (Sigma.ι
            (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (Δ[4] : SSet.{u})) b).app (op ⦋2⦌) x = t
  thin_sigma_zero := by
    intro x
    exact Or.inl
      ((minimalScaling
        (standardTypeABoundaryPrismRankBSigmaCarrier g j)).thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl
      ((minimalScaling
        (standardTypeABoundaryPrismRankBSigmaCarrier g j)).thin_sigma_one x)

/-- Target scaling on the same ordinary coproduct carrier. -/
def standardTypeABoundaryPrismRankBTargetSigmaScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    ScaledSimplicialSet (standardTypeABoundaryPrismRankBSigmaCarrier g j) where
  thin := fun t =>
    (minimalScaling (standardTypeABoundaryPrismRankBSigmaCarrier g j)).thin t ∨
      ∃ (b : StandardTypeABoundaryPrismRankBCell.{u} g j)
        (x : (Δ[4] : SSet.{u}).obj (op ⦋2⦌)),
        standardTypeBTargetScaling.thin x ∧
          (Sigma.ι
            (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (Δ[4] : SSet.{u})) b).app (op ⦋2⦌) x = t
  thin_sigma_zero := by
    intro x
    exact Or.inl
      ((minimalScaling
        (standardTypeABoundaryPrismRankBSigmaCarrier g j)).thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl
      ((minimalScaling
        (standardTypeABoundaryPrismRankBSigmaCarrier g j)).thin_sigma_one x)

/-- Scaled source coproduct of all standard-B copies. -/
def standardTypeABoundaryPrismRankBSourceSigma
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : ScaledSSet.{u} :=
  ScaledSSet.of _ (standardTypeABoundaryPrismRankBSourceSigmaScaling g j)

/-- Scaled target coproduct of all standard-B copies. -/
def standardTypeABoundaryPrismRankBTargetSigma
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : ScaledSSet.{u} :=
  ScaledSSet.of _ (standardTypeABoundaryPrismRankBTargetSigmaScaling g j)

/-- Inclusion of one standard-B source copy into the source coproduct. -/
def standardTypeABoundaryPrismRankBSourceSigmaInclusion
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (b : StandardTypeABoundaryPrismRankBCell.{u} g j) :
    standardTypeBSource.{u} ⟶ standardTypeABoundaryPrismRankBSourceSigma g j where
  map := Sigma.ι
    (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => (Δ[4] : SSet.{u})) b
  scaled := by
    intro t ht
    exact Or.inr ⟨b, t, ht, rfl⟩

/-- Inclusion of one standard-B target copy into the target coproduct. -/
def standardTypeABoundaryPrismRankBTargetSigmaInclusion
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (b : StandardTypeABoundaryPrismRankBCell.{u} g j) :
    standardTypeBTarget.{u} ⟶ standardTypeABoundaryPrismRankBTargetSigma g j where
  map := Sigma.ι
    (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => (Δ[4] : SSet.{u})) b
  scaled := by
    intro t ht
    exact Or.inr ⟨b, t, ht, rfl⟩

/-- Source cofan for the standard-B copies. -/
noncomputable def standardTypeABoundaryPrismRankBSourceCofan
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    Cofan.{u}
      (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => standardTypeBSource.{u}) :=
  Cofan.mk (standardTypeABoundaryPrismRankBSourceSigma g j)
    (fun b => standardTypeABoundaryPrismRankBSourceSigmaInclusion g j b)

/-- The source cofan is colimiting in `ScaledSSet`. -/
noncomputable def standardTypeABoundaryPrismRankBSourceCofanIsColimit
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    IsColimit (standardTypeABoundaryPrismRankBSourceCofan g j) where
  desc s :=
    { map := Sigma.desc
        (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j => (s.ι.app ⟨b⟩).map)
      scaled := by
        intro t ht
        rcases ht with hmin | ⟨b, x, hx, rfl⟩
        · exact
            (minimalScaling_map s.pt.scaling
              (Sigma.desc
                (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                  (s.ι.app ⟨b⟩).map))) t hmin
        · have hs := (s.ι.app ⟨b⟩).scaled x hx
          change
            s.pt.scaling.thin
              (((Sigma.ι
                  (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                    (Δ[4] : SSet.{u})) b ≫
                Sigma.desc
                  (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                    (s.ι.app ⟨b⟩).map)).app (op ⦋2⦌)) x)
          have hdesc :
              Sigma.ι
                  (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                    (Δ[4] : SSet.{u})) b ≫
                  Sigma.desc
                    (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                      (s.ι.app ⟨b⟩).map) =
                (s.ι.app ⟨b⟩).map := by
            exact Sigma.ι_desc _ b
          have hdescApp :=
            ConcreteCategory.congr_hom
              (congr_app hdesc (op ⦋2⦌)) x
          exact hdescApp.symm ▸ hs }
  fac s b := by
    rcases b with ⟨b⟩
    apply ScaledSSet.ScaledMap.ext
    change
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫
          Sigma.desc
            (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (s.ι.app ⟨b⟩).map) =
        (s.ι.app ⟨b⟩).map
    exact Sigma.ι_desc _ b
  uniq s m hm := by
    apply ScaledSSet.ScaledMap.ext
    apply Sigma.hom_ext
    intro b
    have hb := congrArg ScaledSSet.ScaledMap.map (hm ⟨b⟩)
    change
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫ m.map =
        (s.ι.app ⟨b⟩).map at hb
    change
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫ m.map =
        Sigma.ι
            (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (Δ[4] : SSet.{u})) b ≫
          Sigma.desc
            (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (s.ι.app ⟨b⟩).map)
    have hdesc :
        Sigma.ι
            (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (Δ[4] : SSet.{u})) b ≫
            Sigma.desc
              (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (s.ι.app ⟨b⟩).map) =
          (s.ι.app ⟨b⟩).map := by
      exact Sigma.ι_desc _ b
    exact hb.trans hdesc.symm

/-- Target cofan for the standard-B copies. -/
noncomputable def standardTypeABoundaryPrismRankBTargetCofan
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    Cofan.{u}
      (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => standardTypeBTarget.{u}) :=
  Cofan.mk (standardTypeABoundaryPrismRankBTargetSigma g j)
    (fun b => standardTypeABoundaryPrismRankBTargetSigmaInclusion g j b)

/-- The target cofan is colimiting in `ScaledSSet`. -/
noncomputable def standardTypeABoundaryPrismRankBTargetCofanIsColimit
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    IsColimit (standardTypeABoundaryPrismRankBTargetCofan g j) where
  desc s :=
    { map := Sigma.desc
        (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j => (s.ι.app ⟨b⟩).map)
      scaled := by
        intro t ht
        rcases ht with hmin | ⟨b, x, hx, rfl⟩
        · exact
            (minimalScaling_map s.pt.scaling
              (Sigma.desc
                (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                  (s.ι.app ⟨b⟩).map))) t hmin
        · have hs := (s.ι.app ⟨b⟩).scaled x hx
          change
            s.pt.scaling.thin
              (((Sigma.ι
                  (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                    (Δ[4] : SSet.{u})) b ≫
                Sigma.desc
                  (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                    (s.ι.app ⟨b⟩).map)).app (op ⦋2⦌)) x)
          have hdesc :
              Sigma.ι
                  (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                    (Δ[4] : SSet.{u})) b ≫
                  Sigma.desc
                    (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                      (s.ι.app ⟨b⟩).map) =
                (s.ι.app ⟨b⟩).map := by
            exact Sigma.ι_desc _ b
          have hdescApp :=
            ConcreteCategory.congr_hom
              (congr_app hdesc (op ⦋2⦌)) x
          exact hdescApp.symm ▸ hs }
  fac s b := by
    rcases b with ⟨b⟩
    apply ScaledSSet.ScaledMap.ext
    change
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫
          Sigma.desc
            (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (s.ι.app ⟨b⟩).map) =
        (s.ι.app ⟨b⟩).map
    exact Sigma.ι_desc _ b
  uniq s m hm := by
    apply ScaledSSet.ScaledMap.ext
    apply Sigma.hom_ext
    intro b
    have hb := congrArg ScaledSSet.ScaledMap.map (hm ⟨b⟩)
    change
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫ m.map =
        (s.ι.app ⟨b⟩).map at hb
    change
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫ m.map =
        Sigma.ι
            (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (Δ[4] : SSet.{u})) b ≫
          Sigma.desc
            (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (s.ι.app ⟨b⟩).map)
    have hdesc :
        Sigma.ι
            (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (Δ[4] : SSet.{u})) b ≫
            Sigma.desc
              (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (s.ι.app ⟨b⟩).map) =
          (s.ι.app ⟨b⟩).map := by
      exact Sigma.ι_desc _ b
    exact hb.trans hdesc.symm

/-- Coproduct of the literal standard type-(B) generators.  Its underlying
simplicial map is the identity on the common coproduct carrier. -/
def standardTypeABoundaryPrismRankBSigmaGeneratorHom
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankBSourceSigma g j ⟶
      standardTypeABoundaryPrismRankBTargetSigma g j where
  map := 𝟙 _
  scaled := by
    intro t ht
    rcases ht with hmin | ⟨b, x, hx, rfl⟩
    · exact Or.inl hmin
    · exact Or.inr ⟨b, x, standardTypeBSourceScaling_le_target x hx, rfl⟩

@[simp]
theorem standardTypeABoundaryPrismRankBSigmaGeneratorHom_map
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    (standardTypeABoundaryPrismRankBSigmaGeneratorHom g j).map = 𝟙 _ := by
  rfl

/-- Componentwise standard-B natural transformation. -/
noncomputable def standardTypeABoundaryPrismRankBGeneratorNatTrans
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    Discrete.functor
        (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => standardTypeBSource.{u}) ⟶
      Discrete.functor
        (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => standardTypeBTarget.{u}) :=
  Discrete.natTrans (fun _ => standardTypeBGeneratorHom.{u})

/-- The simultaneous B coproduct is literally a coproduct of standard A/B/C
generators. -/
theorem standardTypeABoundaryPrismRankBSigmaGeneratorHom_mem_coproductsABC
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    (MorphismProperty.coproducts.{u}
      (standardScaledAnodyneGeneratorsABC : MorphismProperty (ScaledSSet.{u})))
      (standardTypeABoundaryPrismRankBSigmaGeneratorHom g j) := by
  rw [MorphismProperty.coproducts_iff]
  refine ⟨StandardTypeABoundaryPrismRankBCell.{u} g j, ?_⟩
  refine MorphismProperty.colimitsOfShape.mk'
    (W := (standardScaledAnodyneGeneratorsABC :
      MorphismProperty (ScaledSSet.{u})))
    (Discrete.functor
      (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => standardTypeBSource.{u}))
    (Discrete.functor
      (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j => standardTypeBTarget.{u}))
    (standardTypeABoundaryPrismRankBSourceCofan g j)
    (standardTypeABoundaryPrismRankBTargetCofan g j)
    (standardTypeABoundaryPrismRankBSourceCofanIsColimit g j)
    (standardTypeABoundaryPrismRankBTargetCofanIsColimit g j)
    (standardTypeABoundaryPrismRankBGeneratorNatTrans g j) ?_
    (standardTypeABoundaryPrismRankBSigmaGeneratorHom g j) ?_
  · intro b
    exact standardTypeBGenerator_mem_ABC.{u}
  · intro b
    rcases b with ⟨b⟩
    apply ScaledSSet.ScaledMap.ext
    simp [standardTypeABoundaryPrismRankBSourceCofan,
      standardTypeABoundaryPrismRankBTargetCofan,
      standardTypeABoundaryPrismRankBSourceSigmaInclusion,
      standardTypeABoundaryPrismRankBTargetSigmaInclusion,
      standardTypeABoundaryPrismRankBSigmaGeneratorHom,
      standardTypeABoundaryPrismRankBGeneratorNatTrans]
    exact (Category.comp_id _).trans (Category.id_comp _).symm

/-! ## Attach the B coproduct to `A_j` -/

/-- Source attaching map from the standard-B coproduct into `A_j`. -/
noncomputable def standardTypeABoundaryPrismRankBSourceSigmaToAPhase
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankBSourceSigma g j ⟶
      standardTypeABoundaryPrismRankAPhase g j where
  map := Sigma.desc
    (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
      (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map)
  scaled := by
    intro t ht
    rcases ht with hmin | ⟨b, x, hx, rfl⟩
    · exact
        (minimalScaling_map
          (standardTypeABoundaryPrismRankAPhaseScaling g j)
          (Sigma.desc
            (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map)))
          t hmin
    · have hs := (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).scaled x hx
      change
        (standardTypeABoundaryPrismRankAPhaseScaling g j).thin
          (((Sigma.ι
              (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (Δ[4] : SSet.{u})) b ≫
            Sigma.desc
              (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map)).app
              (op ⦋2⦌)) x)
      have hdesc :
          Sigma.ι
              (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (Δ[4] : SSet.{u})) b ≫
              Sigma.desc
                (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                  (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map) =
            (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map := by
        exact Sigma.ι_desc _ b
      have hdescApp :=
        ConcreteCategory.congr_hom (congr_app hdesc (op ⦋2⦌)) x
      exact hdescApp.symm ▸ hs

/-- Target attaching map from the standard-B target coproduct into the exact
successor stage. -/
noncomputable def standardTypeABoundaryPrismRankBTargetSigmaToSucc
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankBTargetSigma g j ⟶
      standardTypeABoundaryPrismRankStage g (j + 1) where
  map := Sigma.desc
    (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
      (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map)
  scaled := by
    intro t ht
    rcases ht with hmin | ⟨b, x, hx, rfl⟩
    · exact
        (minimalScaling_map
          (standardTypeABoundaryPrismRankStageScaling g (j + 1))
          (Sigma.desc
            (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map)))
          t hmin
    · have hs := (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).scaled x hx
      change
        (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin
          (((Sigma.ι
              (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (Δ[4] : SSet.{u})) b ≫
            Sigma.desc
              (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map)).app
              (op ⦋2⦌)) x)
      have hdesc :
          Sigma.ι
              (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (Δ[4] : SSet.{u})) b ≫
              Sigma.desc
                (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                  (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map) =
            (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map := by
        exact Sigma.ι_desc _ b
      have hdescApp :=
        ConcreteCategory.congr_hom (congr_app hdesc (op ⦋2⦌)) x
      exact hdescApp.symm ▸ hs

/-- The two attaching maps have the same underlying simplicial map. -/
theorem standardTypeABoundaryPrismRankBSourceTargetSigma_map_eq
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    (standardTypeABoundaryPrismRankBSourceSigmaToAPhase.{u} g j).map =
      (standardTypeABoundaryPrismRankBTargetSigmaToSucc.{u} g j).map := by
  apply Sigma.hom_ext
    (f := fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
      (Δ[4] : SSet.{u}))
  intro b
  have hsrc :
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫
          Sigma.desc
            (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map) =
        (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map := by
    exact Sigma.ι_desc _ b
  have htgt :
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫
          Sigma.desc
            (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
              (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map) =
        (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map := by
    exact Sigma.ι_desc _ b
  change
    Sigma.ι
        (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
          (Δ[4] : SSet.{u})) b ≫
        Sigma.desc
          (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (standardTypeABoundaryPrismRankBCellSourceToAPhase g j b).map) =
      Sigma.ι
          (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (Δ[4] : SSet.{u})) b ≫
        Sigma.desc
          (fun b : StandardTypeABoundaryPrismRankBCell.{u} g j =>
            (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map)
  exact hsrc.trans
    ((standardTypeABoundaryPrismRankBCell_source_target_map_eq g j b).trans htgt.symm)

/-- Underlying ordinary B-phase square. -/
noncomputable def standardTypeABoundaryPrism_rankB_underlying_isPushout
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    IsPushout
      (standardTypeABoundaryPrismRankBSourceSigmaToAPhase g j).map
      (standardTypeABoundaryPrismRankBSigmaGeneratorHom g j).map
      (𝟙 _)
      (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map := by
  rw [standardTypeABoundaryPrismRankBSigmaGeneratorHom_map,
    standardTypeABoundaryPrismRankBSourceTargetSigma_map_eq]
  exact IsPushout.of_id_snd

/-! ## Local exact-cell thinness is generated by A or one B target -/

/-- On a q12 or q23 exceptional cell, every exact thin triangle is either
already present after the A phase or is the image of a standard-B target-thin
triangle. -/
theorem standardTypeABoundaryPrismRankBCell_exactThin_generated
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (b : StandardTypeABoundaryPrismRankBCell.{u} g j)
    (z : (Δ[b.cell.dim + 1] : SSet.{u}).obj (op ⦋2⦌))
    (hz : (standardTypeABoundaryPrismCellScaling g j b.cell).thin z) :
    (standardTypeABoundaryPrismRankAPhaseScaling g j).thin
        (b.cell.mapToSucc.app (op ⦋2⦌) z) ∨
      ∃ x : (Δ[4] : SSet.{u}).obj (op ⦋2⦌),
        standardTypeBTargetScaling.thin x ∧
          (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map.app
              (op ⦋2⦌) x =
            b.cell.mapToSucc.app (op ⦋2⦌) z := by
  cases b with
  | q12 c h =>
      let eS := standardTypeABoundaryPrismCellQ12SourceIso g j c h
      let eT := standardTypeABoundaryPrismCellQ12TargetIso g j c h
      have hcarrier : eS.inv.map = eT.inv.map := by
        dsimp [eS, eT, standardTypeABoundaryPrismCellQ12SourceIso,
          standardTypeABoundaryPrismCellQ12TargetIso]
        simp only [Iso.trans_inv, ScaledSSet.comp_map, scalingEqualityIso_inv_map,
          Category.id_comp]
        exact standardTypeABoundaryPrismCellScalingIsoToThree_inv_map_eq
          g j c h.target_three
          (standardTypeABoundaryPrismCellAPushoutScaling g j c)
          (standardTypeABoundaryPrismCellScaling g j c)
      have hz' := eT.hom.scaled z hz
      change
        standardTypeBCollapse12BaseScaling.thin
            (eT.hom.map.app (op ⦋2⦌) z) ∨
          ∃ x : (Δ[4] : SSet.{u}).obj (op ⦋2⦌),
            standardTypeBTargetScaling.thin x ∧
              standardTypeBCollapse12.app (op ⦋2⦌) x =
                eT.hom.map.app (op ⦋2⦌) z at hz'
      rcases hz' with hbase | ⟨x, hx, hcollapse⟩
      · left
        have hbase' := eS.inv.scaled (eT.hom.map.app (op ⦋2⦌) z) hbase
        have hs :=
          (standardTypeABoundaryPrismCellAPushoutTargetToAPhase g j c).scaled
            (eS.inv.map.app (op ⦋2⦌) (eT.hom.map.app (op ⦋2⦌) z)) hbase'
        have hi := congrArg ScaledSSet.ScaledMap.map eT.hom_inv_id
        have hp := ConcreteCategory.congr_hom (congr_app hi (op ⦋2⦌)) z
        change eT.inv.map.app (op ⦋2⦌) (eT.hom.map.app (op ⦋2⦌) z) = z at hp
        have hp' :
            eS.inv.map.app (op ⦋2⦌) (eT.hom.map.app (op ⦋2⦌) z) = z := by
          rw [hcarrier]
          exact hp
        rw [hp'] at hs
        exact hs
      · right
        refine ⟨x, hx, ?_⟩
        change
          c.mapToSucc.app (op ⦋2⦌)
              (eT.inv.map.app (op ⦋2⦌)
                (standardTypeBCollapse12.app (op ⦋2⦌) x)) =
            c.mapToSucc.app (op ⦋2⦌) z
        rw [hcollapse]
        have hi := congrArg ScaledSSet.ScaledMap.map eT.hom_inv_id
        have hp := ConcreteCategory.congr_hom (congr_app hi (op ⦋2⦌)) z
        change eT.inv.map.app (op ⦋2⦌) (eT.hom.map.app (op ⦋2⦌) z) = z at hp
        exact congrArg (c.mapToSucc.app (op ⦋2⦌)) hp
  | q23 c h =>
      let eS := standardTypeABoundaryPrismCellQ23SourceIso g j c h
      let eT := standardTypeABoundaryPrismCellQ23TargetIso g j c h
      have hcarrier : eS.inv.map = eT.inv.map := by
        dsimp [eS, eT, standardTypeABoundaryPrismCellQ23SourceIso,
          standardTypeABoundaryPrismCellQ23TargetIso]
        simp only [Iso.trans_inv, ScaledSSet.comp_map, scalingEqualityIso_inv_map,
          Category.id_comp]
        exact standardTypeABoundaryPrismCellScalingIsoToThree_inv_map_eq
          g j c h.target_three
          (standardTypeABoundaryPrismCellAPushoutScaling g j c)
          (standardTypeABoundaryPrismCellScaling g j c)
      have hz' := eT.hom.scaled z hz
      change
        standardTypeBCollapse23BaseScaling.thin
            (eT.hom.map.app (op ⦋2⦌) z) ∨
          ∃ x : (Δ[4] : SSet.{u}).obj (op ⦋2⦌),
            standardTypeBTargetScaling.thin x ∧
              standardTypeBCollapse23.app (op ⦋2⦌) x =
                eT.hom.map.app (op ⦋2⦌) z at hz'
      rcases hz' with hbase | ⟨x, hx, hcollapse⟩
      · left
        have hbase' := eS.inv.scaled (eT.hom.map.app (op ⦋2⦌) z) hbase
        have hs :=
          (standardTypeABoundaryPrismCellAPushoutTargetToAPhase g j c).scaled
            (eS.inv.map.app (op ⦋2⦌) (eT.hom.map.app (op ⦋2⦌) z)) hbase'
        have hi := congrArg ScaledSSet.ScaledMap.map eT.hom_inv_id
        have hp := ConcreteCategory.congr_hom (congr_app hi (op ⦋2⦌)) z
        change eT.inv.map.app (op ⦋2⦌) (eT.hom.map.app (op ⦋2⦌) z) = z at hp
        have hp' :
            eS.inv.map.app (op ⦋2⦌) (eT.hom.map.app (op ⦋2⦌) z) = z := by
          rw [hcarrier]
          exact hp
        rw [hp'] at hs
        exact hs
      · right
        refine ⟨x, hx, ?_⟩
        change
          c.mapToSucc.app (op ⦋2⦌)
              (eT.inv.map.app (op ⦋2⦌)
                (standardTypeBCollapse23.app (op ⦋2⦌) x)) =
            c.mapToSucc.app (op ⦋2⦌) z
        rw [hcollapse]
        have hi := congrArg ScaledSSet.ScaledMap.map eT.hom_inv_id
        have hp := ConcreteCategory.congr_hom (congr_app hi (op ⦋2⦌)) z
        change eT.inv.map.app (op ⦋2⦌) (eT.hom.map.app (op ⦋2⦌) z) = z at hp
        exact congrArg (c.mapToSucc.app (op ⦋2⦌)) hp

/-! ## The simultaneous B-generated scaling is exactly the successor scaling -/

/-- The pushout scaling generated by `A_j` and all exceptional standard-B
targets is exactly the ambient successor rank scaling. -/
theorem standardTypeABoundaryPrismRankBGeneratedPushoutScaling_eq_succ
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    generatedPushoutScaling
        (standardTypeABoundaryPrismRankAPhaseScaling g j)
        (standardTypeABoundaryPrismRankBTargetSigmaScaling g j)
        (𝟙 _)
        (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map =
      standardTypeABoundaryPrismRankStageScaling g (j + 1) := by
  apply scaling_eq_of_le_antisymm
  · intro t ht
    rcases ht with hmin | ⟨x, hx, hxt⟩ | ⟨y, hy, hyt⟩
    · rcases hmin with ⟨x, rfl⟩ | ⟨x, rfl⟩
      · exact
          (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin_sigma_zero x
      · exact
          (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin_sigma_one x
    · have hxt' : x = t := by
        simpa only [NatTrans.id_app, ConcreteCategory.id_apply] using hxt
      subst t
      exact standardTypeABoundaryPrismRankAPhaseScaling_le_succ g j x hx
    · rw [← hyt]
      exact (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).scaled y hy
  · intro t ht
    have hmem :
        t ∈
          Set.range
              ((SSet.Subcomplex.homOfLE
                ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                  (Order.le_succ j))).app (op ⦋2⦌)) ⊔
            Set.range
              (((standardTypeABoundaryPrismRankFunction g).b j).app
                (op ⦋2⦌)) := by
      rw [(standardTypeABoundaryPrismRankFunction g).range_homOfLE_app_union_range_b_app
        j (op ⦋2⦌)]
      exact Set.mem_univ t
    change
      t ∈
        Set.range
            ((SSet.Subcomplex.homOfLE
              ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                (Order.le_succ j))).app (op ⦋2⦌)) ∪
          Set.range
            (((standardTypeABoundaryPrismRankFunction g).b j).app
              (op ⦋2⦌)) at hmem
    rcases hmem with ⟨x, rfl⟩ | ⟨y, rfl⟩
    · have hx :
          (standardTypeABoundaryPrismRankStageScaling g j).thin x := by
        change
          (scaledSimplexCylinder (standardTypeASimplexScaling g.i)).scaling.thin
            (((standardTypeABoundaryPrismRankFunction g).filtration j).ι.app
              (op ⦋2⦌) x)
        change
          (scaledSimplexCylinder (standardTypeASimplexScaling g.i)).scaling.thin
            ((((SSet.Subcomplex.homOfLE
              ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                (Order.le_succ j))) ≫
              ((standardTypeABoundaryPrismRankFunction g).filtration (j + 1)).ι).app
                (op ⦋2⦌)) x) at ht
        have hι := ConcreteCategory.congr_hom
          (congr_app
            (SSet.Subcomplex.homOfLE_ι
              ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                (Order.le_succ j)))
            (op ⦋2⦌)) x
        exact hι ▸ ht
      have hxA :
          (standardTypeABoundaryPrismRankAPhaseScaling g j).thin
            ((SSet.Subcomplex.homOfLE
              ((standardTypeABoundaryPrismRankFunction g).filtration_monotone
                (Order.le_succ j))).app (op ⦋2⦌) x) :=
        Or.inr (Or.inl ⟨x, hx, rfl⟩)
      exact Or.inr (Or.inl ⟨_, hxA, by simp⟩)
    · obtain ⟨c, z, hz⟩ :=
        (standardTypeABoundaryPrismRankFunction g).ιSigmaStdSimplex_jointly_surjective y
      have hb := ConcreteCategory.congr_hom
        (congr_app c.ι_b (op ⦋2⦌)) z
      have hzcell :
          (standardTypeABoundaryPrismCellScaling g j c).thin z := by
        rw [hz] at ht
        rw [show
          ((standardTypeABoundaryPrismRankFunction g).b j).app (op ⦋2⦌)
              (c.ιSigmaStdSimplex.app (op ⦋2⦌) z) =
            c.mapToSucc.app (op ⦋2⦌) z by
              simpa only [NatTrans.comp_app_apply] using hb] at ht
        rw [← standardTypeABoundaryPrismRankSuccScaling_pullback_cell g j c]
        exact ht
      rcases standardTypeABoundaryPrismCellCompletion_complete_classification
          g j c with hpure | h12 | h23
      · have hzA :
            (standardTypeABoundaryPrismCellAPushoutScaling g j c).thin z := by
          rw [hpure]
          exact hzcell
        have hphase :=
          (standardTypeABoundaryPrismCellAPushoutTargetToAPhase g j c).scaled z hzA
        refine Or.inr (Or.inl ⟨c.mapToSucc.app (op ⦋2⦌) z, hphase, ?_⟩)
        simpa only [Functor.id_obj, NatTrans.id_app, id_eq,
          CategoryTheory.FunctorToTypes.map_id_apply] using hb.symm
      · rcases standardTypeABoundaryPrismRankBCell_exactThin_generated
          g j (.q12 c h12) z hzcell with hphase | ⟨x, hx, hxmap⟩
        · refine Or.inr (Or.inl ⟨c.mapToSucc.app (op ⦋2⦌) z, hphase, ?_⟩)
          simpa only [Functor.id_obj, NatTrans.id_app, id_eq,
            CategoryTheory.FunctorToTypes.map_id_apply] using hb.symm
        · right
          right
          let b : StandardTypeABoundaryPrismRankBCell.{u} g j := .q12 c h12
          let yB : (standardTypeABoundaryPrismRankBSigmaCarrier g j).obj (op ⦋2⦌) :=
            (Sigma.ι
              (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (Δ[4] : SSet.{u})) b).app (op ⦋2⦌) x
          refine ⟨yB, ?_, ?_⟩
          · exact Or.inr ⟨b, x, hx, rfl⟩
          · change
              (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map.app
                  (op ⦋2⦌) yB =
                ((standardTypeABoundaryPrismRankFunction.{u} g).b j).app
                  (op ⦋2⦌) y
            rw [hz]
            change
              (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map.app
                  (op ⦋2⦌) x =
                ((standardTypeABoundaryPrismRankFunction.{u} g).b j).app
                  (op ⦋2⦌)
                  (c.ιSigmaStdSimplex.app (op ⦋2⦌) z)
            rw [hxmap]
            simpa only [NatTrans.comp_app_apply] using hb.symm
      · rcases standardTypeABoundaryPrismRankBCell_exactThin_generated
          g j (.q23 c h23) z hzcell with hphase | ⟨x, hx, hxmap⟩
        · refine Or.inr (Or.inl ⟨c.mapToSucc.app (op ⦋2⦌) z, hphase, ?_⟩)
          simpa only [Functor.id_obj, NatTrans.id_app, id_eq,
            CategoryTheory.FunctorToTypes.map_id_apply] using hb.symm
        · right
          right
          let b : StandardTypeABoundaryPrismRankBCell.{u} g j := .q23 c h23
          let yB : (standardTypeABoundaryPrismRankBSigmaCarrier g j).obj (op ⦋2⦌) :=
            (Sigma.ι
              (fun _ : StandardTypeABoundaryPrismRankBCell.{u} g j =>
                (Δ[4] : SSet.{u})) b).app (op ⦋2⦌) x
          refine ⟨yB, ?_, ?_⟩
          · exact Or.inr ⟨b, x, hx, rfl⟩
          · change
              (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map.app
                  (op ⦋2⦌) yB =
                ((standardTypeABoundaryPrismRankFunction.{u} g).b j).app
                  (op ⦋2⦌) y
            rw [hz]
            change
              (standardTypeABoundaryPrismRankBCellTargetToSucc g j b).map.app
                  (op ⦋2⦌) x =
                ((standardTypeABoundaryPrismRankFunction.{u} g).b j).app
                  (op ⦋2⦌)
                  (c.ιSigmaStdSimplex.app (op ⦋2⦌) z)
            rw [hxmap]
            simpa only [NatTrans.comp_app_apply] using hb.symm

/-! ## Exact B pushout and rank-step cellularity -/

/-- The simultaneous exceptional-B square is a genuine pushout whose target is
exactly the ambient successor stage. -/
noncomputable def standardTypeABoundaryPrism_rankB_scaled_isPushout
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    IsPushout
      (standardTypeABoundaryPrismRankBSourceSigmaToAPhase g j)
      (standardTypeABoundaryPrismRankBSigmaGeneratorHom g j)
      (standardTypeABoundaryPrismRankAPhaseToSucc g j)
      (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j) := by
  have h := generatedPushout_isPushout
    (standardTypeABoundaryPrismRankBSourceSigmaToAPhase g j)
    (standardTypeABoundaryPrismRankBSigmaGeneratorHom g j)
    (𝟙 _)
    (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map
    (standardTypeABoundaryPrism_rankB_underlying_isPushout g j)
  have hScaling :
      generatedPushoutScaling
          (standardTypeABoundaryPrismRankAPhaseScaling g j)
          (standardTypeABoundaryPrismRankBTargetSigmaScaling g j)
          (𝟙 _)
          (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map =
        standardTypeABoundaryPrismRankStageScaling g (j + 1) :=
    standardTypeABoundaryPrismRankBGeneratedPushoutScaling_eq_succ g j
  let eSucc :
      generatedPushoutTarget
          (standardTypeABoundaryPrismRankAPhaseScaling g j)
          (standardTypeABoundaryPrismRankBTargetSigmaScaling g j)
          (𝟙 _)
          (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map ≅
        standardTypeABoundaryPrismRankStage g (j + 1) :=
    scalingEqualityIso
      (generatedPushoutScaling
        (standardTypeABoundaryPrismRankAPhaseScaling g j)
        (standardTypeABoundaryPrismRankBTargetSigmaScaling g j)
        (𝟙 _)
        (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map)
      (standardTypeABoundaryPrismRankStageScaling g (j + 1))
      hScaling
  refine h.of_iso (Iso.refl _) (Iso.refl _) (Iso.refl _) eSucc ?_ ?_ ?_ ?_
  · change
      standardTypeABoundaryPrismRankBSourceSigmaToAPhase g j ≫ 𝟙 _ =
        𝟙 _ ≫ standardTypeABoundaryPrismRankBSourceSigmaToAPhase g j
    rw [Category.comp_id, Category.id_comp]
  · change
      standardTypeABoundaryPrismRankBSigmaGeneratorHom g j ≫ 𝟙 _ =
        𝟙 _ ≫ standardTypeABoundaryPrismRankBSigmaGeneratorHom g j
    rw [Category.comp_id, Category.id_comp]
  · rw [Category.id_comp]
    apply ScaledSSet.ScaledMap.ext
    change
      (𝟙 ((standardTypeABoundaryPrismRankFunction.{u} g).filtration (j + 1) : SSet.{u})) ≫
          (scalingEqualityIso
            (generatedPushoutScaling
              (standardTypeABoundaryPrismRankAPhaseScaling g j)
              (standardTypeABoundaryPrismRankBTargetSigmaScaling g j)
              (𝟙 _)
              (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map)
            (standardTypeABoundaryPrismRankStageScaling g (j + 1))
            hScaling).hom.map =
        (𝟙 ((standardTypeABoundaryPrismRankFunction.{u} g).filtration (j + 1) : SSet.{u}))
    rw [scalingEqualityIso_hom_map]
    exact Category.comp_id _
  · rw [Category.id_comp]
    apply ScaledSSet.ScaledMap.ext
    change
      (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map ≫
          (scalingEqualityIso
            (generatedPushoutScaling
              (standardTypeABoundaryPrismRankAPhaseScaling g j)
              (standardTypeABoundaryPrismRankBTargetSigmaScaling g j)
              (𝟙 _)
              (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map)
            (standardTypeABoundaryPrismRankStageScaling g (j + 1))
            hScaling).hom.map =
        (standardTypeABoundaryPrismRankBTargetSigmaToSucc g j).map
    rw [scalingEqualityIso_hom_map]
    exact Category.comp_id _

/-- Main B-phase output: all exceptional completions at rank `j` form one raw
standard cellular step. -/
theorem standardTypeABoundaryPrismRankAPhaseToSucc_mem_rawCellular
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    (standardABCRawCellularStep : MorphismProperty (ScaledSSet.{u}))
      (standardTypeABoundaryPrismRankAPhaseToSucc.{u} g j) := by
  unfold standardABCRawCellularStep
  exact
    (MorphismProperty.coproducts.{u}
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u}))).pushouts_mk
      (standardTypeABoundaryPrism_rankB_scaled_isPushout.{u} g j)
      (standardTypeABoundaryPrismRankBSigmaGeneratorHom_mem_coproductsABC.{u} g j)

/-- Each exact rank successor is a two-step raw A/B composite, hence belongs to
the strong unretracted standard cellular closure. -/
theorem standardTypeABoundaryPrismRankStageHom_mem_strongCellular
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    (standardABCStrongCellularClosure : MorphismProperty (ScaledSSet.{u}))
      (standardTypeABoundaryPrismRankStageHom.{u} g (Nat.le_succ j)) := by
  have hAraw :
      (standardABCRawCellularStep : MorphismProperty (ScaledSSet.{u}))
        (standardTypeABoundaryPrismRankStageToAPhase.{u} g j) :=
    standardTypeABoundaryPrismRankStageToAPhase_mem_rawCellular.{u} g j
  have hBraw :
      (standardABCRawCellularStep : MorphismProperty (ScaledSSet.{u}))
        (standardTypeABoundaryPrismRankAPhaseToSucc.{u} g j) :=
    standardTypeABoundaryPrismRankAPhaseToSucc_mem_rawCellular.{u} g j
  have hshape :=
    (MorphismProperty.TransfiniteCompositionOfShape.ofOrderIso
      (MorphismProperty.TransfiniteCompositionOfShape.ofComp
        (standardTypeABoundaryPrismRankStageToAPhase.{u} g j)
        (standardTypeABoundaryPrismRankAPhaseToSucc.{u} g j)
        hAraw hBraw)
      (orderIsoShrink.{u} (Fin 3)).symm).mem
  have hcomp :
      (standardABCStrongCellularClosure : MorphismProperty (ScaledSSet.{u}))
        (standardTypeABoundaryPrismRankStageToAPhase.{u} g j ≫
          standardTypeABoundaryPrismRankAPhaseToSucc.{u} g j) :=
    (MorphismProperty.transfiniteCompositionsOfShape_le_transfiniteCompositions
      (W := (standardABCRawCellularStep : MorphismProperty (ScaledSSet.{u})))
      (Shrink.{u} (Fin 3))) _ hshape
  simpa only [standardTypeABoundaryPrismRankStep_factor_A_residual] using hcomp

/-- Retracted-closure form of the preceding rank theorem. -/
theorem standardTypeABoundaryPrismRankStageHom_mem_cellular
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardABCCellularClosure
      (standardTypeABoundaryPrismRankStageHom.{u} g (Nat.le_succ j)) :=
  standardABCStrongCellularClosure_le_standardABCCellularClosure _
    (standardTypeABoundaryPrismRankStageHom_mem_strongCellular g j)

/-!
Every successor of the exact scaled boundary-prism rank filtration now has the
promised standard presentation:

```text
R_j -- coproduct/pushout of type A --> A_j
    -- coproduct/pushout of type B --> R_(j+1).
```

Both arrows are raw steps `pushouts (coproducts E_std)`, and their composite is
the existing exact ambient-pullback rank inclusion.  No type-(C) cell occurs.

The remaining global task is no longer local geometry: package the natural-
number rank filtration as one transfinite composition, identify rank zero with
the boundary prism, identify its colimit with the full scaled cylinder, and
prepend the single missing-endpoint type-(A) cell from v1.60.  That produces
the v1.59 `StandardABCTypeAEndpointLeibnizCellularCertificate`.
-/

end

end KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseSimultaneousBPhaseV1_75