import Mathlib
import KUOS.DependentOriginationGeneratedRefinementTopologyV2_4

namespace KUOS.DependentOriginationBaseChangeDescentV2_5

open CategoryTheory
open Opposite
open KUOS.DependentOriginationFunctorialTransportV0_1
open KUOS.DependentOriginationContextualDescentV1_1
open KUOS.DependentOriginationEffectiveDescentComparisonV2_1
open KUOS.DependentOriginationOppositeSiteVarianceBridgeV2_3
open KUOS.DependentOriginationGeneratedRefinementTopologyV2_4

universe u v w

/-!
# Base-change closed contextual descent v2.5

The v2.4 layer proves the exact one-cover theorem

```text
Presieve.IsSheafFor (asOppositeSitePresheaf D) (coverPresieve C)
  ↔ HasEffectiveStateDescent D C O
```

when the chosen overlap system is formed by categorical pushouts.

A Grothendieck topology, however, is not generated by the declared covering
families alone: it is also closed under base change.  Mathlib makes this exact in
`Precoverage.isSheaf_toGrothendieck_iff`, whose right hand side asks for the sheaf
condition on every pullback of every generating presieve.

This file isolates the corresponding geometric hypothesis on a KuuOS
`RefinementAtlas`.  We require the *generated covering sieve* of the atlas family
to be stable under every base change on the opposite refinement site.  Equality
of generated sieves is the appropriate invariant condition: it is independent of
presentation of a covering family and is exactly what the sheaf condition sees.

Under that hypothesis, sheafness for the whole freely generated Grothendieck
topology is equivalent to sheafness for the one declared atlas cover at every
context.  Adding a pushout overlap system at every context then turns the latter
condition into v2.1 effective contextual descent everywhere.
-/

section AtlasGeometry

variable {Context : Type u} [Category.{v} Context]

namespace RefinementAtlas

/-- The ordinary v1.1 refinement cover underlying the atlas family at one
context. -/
def coverAt (A : RefinementAtlas Context) (X : Context) :
    RefinementCover Context (A.Index X) where
  rootContext := X
  chart := A.chart X
  toChart := A.toChart X

@[simp] theorem coverAt_rootContext
    (A : RefinementAtlas Context) (X : Context) :
    (A.coverAt X).rootContext = X := rfl

@[simp] theorem coverAt_chart
    (A : RefinementAtlas Context) (X : Context) (i : A.Index X) :
    (A.coverAt X).chart i = A.chart X i := rfl

@[simp] theorem coverAt_toChart
    (A : RefinementAtlas Context) (X : Context) (i : A.Index X) :
    (A.coverAt X).toChart i = A.toChart X i := rfl

/-- The presieve attached to the atlas at `X` is definitionally the presieve of
its underlying v1.1 refinement cover. -/
@[simp] theorem coverPresieve_coverAt
    (A : RefinementAtlas Context) (X : Context) :
    coverPresieve (A.coverAt X) = A.presieveAt (op X) := by
  rfl

/-- Base-change closure at the level actually seen by sheaf theory.

For a site arrow `f : Y ⟶ X` in `Contextᵒᵖ`, pull back the sieve generated by the
atlas cover at `X`.  The atlas is base-change closed when the resulting sieve is
exactly the sieve generated by the atlas cover at `Y`.
-/
def IsBaseChangeClosed (A : RefinementAtlas Context) : Prop :=
  ∀ {X Y : Contextᵒᵖ} (f : Y ⟶ X),
    (Sieve.generate (A.presieveAt X)).pullback f =
      Sieve.generate (A.presieveAt Y)

/-- A choice of pairwise universal overlaps for every declared atlas cover. -/
structure PushoutOverlapAtlas (A : RefinementAtlas Context) where
  overlap : (X : Context) → OverlapSystem (A.coverAt X)
  isPushout : ∀ X : Context,
    IsPushoutOverlapSystem (A.coverAt X) (overlap X)

end RefinementAtlas

end AtlasGeometry

section GlobalSheafCriterion

variable {Context : Type u} [Category.{v} Context]

/-- For a base-change-closed atlas, a Type-valued presheaf is a sheaf for the
whole freely generated topology iff it satisfies the sheaf condition for the
single declared atlas cover at every site object.

This is the exact global closure step missing from v2.4. -/
theorem presieveIsSheaf_generatedTopology_iff_declaredCovers
    (A : RefinementAtlas Context)
    (hbc : A.IsBaseChangeClosed)
    (P : (Contextᵒᵖ)ᵒᵖ ⥤ Type w) :
    Presieve.IsSheaf A.generatedTopology P ↔
      ∀ X : Contextᵒᵖ, Presieve.IsSheafFor P (A.presieveAt X) := by
  rw [Precoverage.isSheaf_toGrothendieck_iff]
  constructor
  · intro h X
    have hX := h (f := 𝟙 X) (A.presieveAt X) (by
      simp [RefinementAtlas.precoverage])
    simpa [Presieve.isSheafFor_iff_generate] using hX
  · intro h X Y f R hR
    have hReq : R = A.presieveAt X := by
      simpa [RefinementAtlas.precoverage] using hR
    subst R
    rw [hbc f]
    exact (Presieve.isSheafFor_iff_generate (A.presieveAt Y)).1 (h Y)

/-- The same criterion expressed in the v2.3 KuuOS contextual-transport
language. -/
theorem isGrothendieckDescentComplete_iff_declaredCovers
    (A : RefinementAtlas Context)
    (hbc : A.IsBaseChangeClosed)
    (D : FunctorialTransportSystem Context) :
    IsGrothendieckDescentComplete A.generatedTopology D ↔
      ∀ X : Contextᵒᵖ,
        Presieve.IsSheafFor (asOppositeSitePresheaf D) (A.presieveAt X) := by
  unfold IsGrothendieckDescentComplete
  rw [isSheaf_iff_isSheaf_of_type]
  exact presieveIsSheaf_generatedTopology_iff_declaredCovers
    A hbc (asOppositeSitePresheaf D)

/-- Global `J`-axis theorem for KuuOS dependent origination.

If the refinement atlas is stable under site base change and every declared
cover carries universal pushout overlaps, then Grothendieck descent completeness
for the whole generated topology is equivalent to v2.1 effective contextual
descent at every context.
-/
theorem isGrothendieckDescentComplete_iff_allEffectiveStateDescent
    (A : RefinementAtlas Context)
    (hbc : A.IsBaseChangeClosed)
    (O : A.PushoutOverlapAtlas)
    (D : FunctorialTransportSystem Context) :
    IsGrothendieckDescentComplete A.generatedTopology D ↔
      ∀ X : Context,
        HasEffectiveStateDescent D (A.coverAt X) (O.overlap X) := by
  rw [isGrothendieckDescentComplete_iff_declaredCovers A hbc D]
  constructor
  · intro h X
    have hX := h (op X)
    rw [← A.coverPresieve_coverAt X] at hX
    exact
      (cover_isSheafFor_iff_effectiveStateDescent
        D (A.coverAt X) (O.overlap X) (O.isPushout X)).1 hX
  · intro h X
    have hX :=
      (cover_isSheafFor_iff_effectiveStateDescent
        D (A.coverAt (unop X)) (O.overlap (unop X))
          (O.isPushout (unop X))).2 (h (unop X))
    simpa using hX

/-!
The `J` axis is now globally closed at the 1-categorical level:

```text
base-change-closed refinement atlas
        + universal pushout overlaps
        + effective contextual descent at every context
                ↕
Type-valued sheaf on the generated opposite-site topology.
```

The next universal step should combine this global `J` theorem with the v2.0
presentation-localization `W` theorem.  The mathematically clean carrier is to
place the refinement atlas on the localized category `C[W⁻¹]` itself, so that
presentation invariance is built into the site before sheafification rather than
requiring a separate transport-of-topology theorem on the raw context category.
-/

end GlobalSheafCriterion

end KUOS.DependentOriginationBaseChangeDescentV2_5
