import Mathlib
import KUOS.DependentOriginationRefinementTransitivityV1_2

namespace KUOS.DependentOriginationDirectedCofinalSemanticsV1_3

open CategoryTheory
open KUOS.DependentOriginationFunctorialTransportV0_1
open KUOS.DependentOriginationContextualCoreV1_0
open KUOS.DependentOriginationContextualDescentV1_1
open KUOS.DependentOriginationRefinementTransitivityV1_2

universe u v w z y

/-!
# Directed refinement and cofinal semantics v1.3

The v1.1-v1.2 layers formalized finite contextual covers and finite-depth
refinement-of-refinement.  This layer passes to a directed family of contexts.

The parent orientation remains covariant:

```text
root -> X_i -> X_j      whenever i <= j.
```

No categorical colimit is assumed or manufactured.  The structure only records
an order-directed refinement net and exact compatibility of its context paths.

The key distinction is again state versus semantic descent.

* A coherent state family can be read on every refinement stage.
* An invariant readout has one unique value on the whole directed net.
* The same semantic value is already determined by any order-cofinal refinement
  lens.
* Recovering a root-state witness from a cofinal subfamily requires an explicit
  state-separation hypothesis.  Cofinality alone is not promoted to state
  descent.
-/

/--
A directed family of contextual refinements rooted at one context.

`refine h : chart i -> chart j` is available whenever `i <= j`.  The fields
`refine_refl`, `refine_trans`, and `root_refine` make the chosen contextual paths
strictly coherent.  `directed` says every pair of indices has a common upper
refinement.
-/
structure DirectedRefinementSystem
    (Context : Type u) [Category.{v} Context]
    (Index : Type w) [Preorder Index] where
  rootContext : Context
  chart : Index -> Context
  toChart : (i : Index) -> rootContext ⟶ chart i
  refine : {i j : Index} -> i <= j -> chart i ⟶ chart j
  refine_refl : forall i,
    refine (le_refl i) = 𝟙 (chart i)
  refine_trans : forall {i j k} (hij : i <= j) (hjk : j <= k),
    refine (le_trans hij hjk) = refine hij ≫ refine hjk
  root_refine : forall {i j} (hij : i <= j),
    toChart i ≫ refine hij = toChart j
  directed : forall i j, exists k, i <= k ∧ j <= k

/--
Transporting a root state first to `i` and then along a refinement `i <= j` is
exactly the direct root-to-`j` transport.
-/
theorem root_transport_refine
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (x : D.state.obj R.rootContext)
    {i j : Index} (hij : i <= j) :
    D.transport (R.refine hij) (D.transport (R.toChart i) x) =
      D.transport (R.toChart j) x := by
  rw [← D.transport_comp_apply (R.toChart i) (R.refine hij) x]
  rw [R.root_refine hij]

/-- A state at every refinement stage, coherent under every chosen refinement. -/
structure DirectedStateFamily
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index) where
  state : (i : Index) -> D.state.obj (R.chart i)
  coherent : forall {i j : Index} (hij : i <= j),
    D.transport (R.refine hij) (state i) = state j

namespace DirectedStateFamily

/-- A single root state induces a coherent state family on the entire net. -/
def ofGlobal
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (x : D.state.obj R.rootContext) :
    DirectedStateFamily D R where
  state := fun i => D.transport (R.toChart i) x
  coherent := by
    intro i j hij
    exact root_transport_refine D R x hij

end DirectedStateFamily

/-- A directed family has a root-state witness when all stages come from one root state. -/
def StateDescendsOnNet
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R) : Prop :=
  exists x : D.state.obj R.rootContext,
    forall i, D.transport (R.toChart i) x = s.state i

/-- The family generated by a root state descends with that state as witness. -/
theorem ofGlobal_stateDescendsOnNet
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (x : D.state.obj R.rootContext) :
    StateDescendsOnNet D R (DirectedStateFamily.ofGlobal D R x) := by
  refine ⟨x, ?_⟩
  intro i
  rfl

/--
Semantic descent on a directed net means one unique context-independent value
is shared by all refinement stages.
-/
def NetSemanticDescends
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R) : Prop :=
  exists! value : Semantic,
    forall i, Q.readout (R.chart i) (s.state i) = value

/-- Invariant semantics agree along every directed refinement arrow. -/
theorem semantic_eq_of_le
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    {i j : Index} (hij : i <= j) :
    Q.readout (R.chart i) (s.state i) =
      Q.readout (R.chart j) (s.state j) := by
  have hInvariant := Q.transport_invariant (R.refine hij) (s.state i)
  rw [s.coherent hij] at hInvariant
  exact hInvariant.symm

/-- Directedness upgrades comparable-stage equality to equality at any two stages. -/
theorem semantic_eq
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (i j : Index) :
    Q.readout (R.chart i) (s.state i) =
      Q.readout (R.chart j) (s.state j) := by
  rcases R.directed i j with ⟨k, hik, hjk⟩
  calc
    Q.readout (R.chart i) (s.state i) =
        Q.readout (R.chart k) (s.state k) :=
      semantic_eq_of_le Q R s hik
    _ = Q.readout (R.chart j) (s.state j) :=
      (semantic_eq_of_le Q R s hjk).symm

/-- Every nonempty coherent directed state family has one unique invariant meaning. -/
theorem netSemanticDescends_of_coherent
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index] [Nonempty Index]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R) :
    NetSemanticDescends Q R s := by
  classical
  let anchor : Index := Classical.choice (inferInstance : Nonempty Index)
  refine ⟨Q.readout (R.chart anchor) (s.state anchor), ?_, ?_⟩
  · intro i
    exact semantic_eq Q R s i anchor
  · intro value hValue
    exact (hValue anchor).symm

/-!
## Cofinal refinement lenses
-/

/--
An order-cofinal refinement lens picks a monotone family of stages such that
every original stage refines into at least one selected stage.

This is an order-theoretic cofinality notion.  It does not assert a categorical
final functor or a colimit theorem.
-/
structure CofinalRefinementLens
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    (R : DirectedRefinementSystem Context Index)
    (SubIndex : Type z) [Preorder SubIndex] where
  indexMap : SubIndex -> Index
  monotone : Monotone indexMap
  cofinal : forall i : Index, exists j : SubIndex, i <= indexMap j

/-- Semantic stabilization at one value on the entire directed net. -/
def SemanticStabilizesAt
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (value : Semantic) : Prop :=
  forall i, Q.readout (R.chart i) (s.state i) = value

/-- Semantic stabilization tested only on a chosen cofinal refinement lens. -/
def CofinalSemanticStabilizesAt
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex)
    (value : Semantic) : Prop :=
  forall j,
    Q.readout (R.chart (F.indexMap j)) (s.state (F.indexMap j)) = value

/--
A fixed semantic value stabilizes on the whole net iff it stabilizes on any
cofinal refinement lens.

The reverse implication is where order-cofinality is used: every original stage
can be compared to a selected later stage, and invariant semantics agree along
that refinement.
-/
theorem semanticStabilizesAt_iff_cofinal
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex)
    (value : Semantic) :
    SemanticStabilizesAt Q R s value <->
      CofinalSemanticStabilizesAt Q R s F value := by
  constructor
  · intro h j
    exact h (F.indexMap j)
  · intro h i
    rcases F.cofinal i with ⟨j, hij⟩
    calc
      Q.readout (R.chart i) (s.state i) =
          Q.readout (R.chart (F.indexMap j)) (s.state (F.indexMap j)) :=
        semantic_eq_of_le Q R s hij
      _ = value := h j

/-- Unique semantic descent tested only on a cofinal refinement lens. -/
def CofinalSemanticDescends
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex) : Prop :=
  exists! value : Semantic,
    CofinalSemanticStabilizesAt Q R s F value

/--
Full-net semantic descent is exactly equivalent to descent on any cofinal lens.
This is an `ExistsUnique` theorem, not merely pointwise constancy.
-/
theorem netSemanticDescends_iff_cofinal
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex) :
    NetSemanticDescends Q R s <->
      CofinalSemanticDescends Q R s F := by
  constructor
  · rintro ⟨value, hValue, hUnique⟩
    refine ⟨value, ?_, ?_⟩
    · intro j
      exact hValue (F.indexMap j)
    · intro value' hValue'
      apply hUnique
      exact (semanticStabilizesAt_iff_cofinal Q R s F value').2 hValue'
  · rintro ⟨value, hValue, hUnique⟩
    refine ⟨value, ?_, ?_⟩
    · exact (semanticStabilizesAt_iff_cofinal Q R s F value).2 hValue
    · intro value' hValue'
      apply hUnique
      intro j
      exact hValue' (F.indexMap j)

/-- Every nonempty coherent net therefore has unique semantics on every cofinal lens. -/
theorem cofinalSemanticDescends_of_coherent
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index] [Nonempty Index]
    {SubIndex : Type z} [Preorder SubIndex]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex) :
    CofinalSemanticDescends Q R s F := by
  apply (netSemanticDescends_iff_cofinal Q R s F).1
  exact netSemanticDescends_of_coherent Q R s

/-!
## State recovery from a cofinal lens requires separation
-/

/-- A root state matches a directed family on all stages selected by a cofinal lens. -/
def CofinalStateWitness
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex) : Prop :=
  exists x : D.state.obj R.rootContext,
    forall j, D.transport (R.toChart (F.indexMap j)) x =
      s.state (F.indexMap j)

/-- Full state descent always restricts to a cofinal state witness. -/
theorem cofinalStateWitness_of_stateDescends
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex)
    (hDescends : StateDescendsOnNet D R s) :
    CofinalStateWitness D R s F := by
  rcases hDescends with ⟨x, hx⟩
  refine ⟨x, ?_⟩
  intro j
  exact hx (F.indexMap j)

/--
A cofinal lens separates local states when equality after transport to every
selected later refinement forces equality at the original stage.

This is deliberately extra structure.  It is not implied merely by order
cofinality.
-/
def CofinalLensSeparatesLocalStates
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (F : CofinalRefinementLens R SubIndex) : Prop :=
  forall (i : Index) (x y : D.state.obj (R.chart i)),
    (forall (j : SubIndex) (hij : i <= F.indexMap j),
      D.transport (R.refine hij) x = D.transport (R.refine hij) y) ->
    x = y

/--
Under local-state separation, a root witness verified only on a cofinal lens
extends to a root witness on every stage of the directed net.
-/
theorem stateDescends_of_cofinalWitness_of_separation
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex)
    (hWitness : CofinalStateWitness D R s F)
    (hSeparate : CofinalLensSeparatesLocalStates D R F) :
    StateDescendsOnNet D R s := by
  rcases hWitness with ⟨x, hx⟩
  refine ⟨x, ?_⟩
  intro i
  apply hSeparate i (D.transport (R.toChart i) x) (s.state i)
  intro j hij
  calc
    D.transport (R.refine hij) (D.transport (R.toChart i) x) =
        D.transport (R.toChart (F.indexMap j)) x :=
      root_transport_refine D R x hij
    _ = s.state (F.indexMap j) := hx j
    _ = D.transport (R.refine hij) (s.state i) :=
      (s.coherent hij).symm

/-- With separation, full state descent can also be tested on the cofinal lens. -/
theorem stateDescendsOnNet_iff_cofinal_of_separation
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex)
    (hSeparate : CofinalLensSeparatesLocalStates D R F) :
    StateDescendsOnNet D R s <-> CofinalStateWitness D R s F := by
  constructor
  · exact cofinalStateWitness_of_stateDescends D R s F
  · intro hWitness
    exact stateDescends_of_cofinalWitness_of_separation
      D R s F hWitness hSeparate

/--
If the full net has no root-state witness and the cofinal lens separates local
states, then no root-state witness can appear merely by restricting attention to
the cofinal lens.
-/
theorem no_cofinalStateWitness_of_no_stateDescends
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index]
    {SubIndex : Type z} [Preorder SubIndex]
    (D : FunctorialTransportSystem Context)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex)
    (hSeparate : CofinalLensSeparatesLocalStates D R F)
    (hNoState : ¬ StateDescendsOnNet D R s) :
    ¬ CofinalStateWitness D R s F := by
  intro hWitness
  exact hNoState
    (stateDescends_of_cofinalWitness_of_separation
      D R s F hWitness hSeparate)

/--
Cofinal semantic descent does not require state-separation.  The theorem keeps
that missing hypothesis visible rather than silently strengthening the parent
notion of dependent origination.
-/
theorem semantic_cofinality_without_state_separation
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index] [Nonempty Index]
    {SubIndex : Type z} [Preorder SubIndex]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex)
    (hNoSeparation : ¬ CofinalLensSeparatesLocalStates D R F) :
    (¬ CofinalLensSeparatesLocalStates D R F) ∧
      CofinalSemanticDescends Q R s F := by
  exact ⟨hNoSeparation, cofinalSemanticDescends_of_coherent Q R s F⟩

/--
Even when a separating cofinal lens certifies that no root-state carrier exists,
the invariant semantic value still descends uniquely on that same cofinal lens.
-/
theorem semantic_persists_without_cofinal_root_carrier
    {Context : Type u} [Category.{v} Context]
    {Index : Type w} [Preorder Index] [Nonempty Index]
    {SubIndex : Type z} [Preorder SubIndex]
    {D : FunctorialTransportSystem Context}
    {Semantic : Type y}
    (Q : FunctorialTransportSystem.InvariantReadout D Semantic)
    (R : DirectedRefinementSystem Context Index)
    (s : DirectedStateFamily D R)
    (F : CofinalRefinementLens R SubIndex)
    (hSeparate : CofinalLensSeparatesLocalStates D R F)
    (hNoState : ¬ StateDescendsOnNet D R s) :
    (¬ CofinalStateWitness D R s F) ∧
      CofinalSemanticDescends Q R s F := by
  exact ⟨no_cofinalStateWitness_of_no_stateDescends
      D R s F hSeparate hNoState,
    cofinalSemanticDescends_of_coherent Q R s F⟩

end KUOS.DependentOriginationDirectedCofinalSemanticsV1_3
