import KUOS.DependentOriginationScaledHornAttachmentLiftingV1_40
import Mathlib.CategoryTheory.LiftingProperties.Basic

namespace KUOS.DependentOriginationScaledTerminalRLPV1_41

open CategoryTheory
open CategoryTheory.Category
open CategoryTheory.Limits
open MonoidalCategory
open Simplicial
open Opposite
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationGlobalDuskinScaledHornCoherenceV1_22
open KUOS.DependentOriginationBiequivalencePresentationInvariantV1_26
open KUOS.DependentOriginationHomotopyClassScaledHornInvariantV1_37
open KUOS.DependentOriginationHomotopyClassStrictificationV1_38
open KUOS.DependentOriginationScaledHornCylinderExtensionV1_39
open KUOS.DependentOriginationScaledHornAttachmentLiftingV1_40

universe u u₁ u₂ v₁ v₂ w₁ w₂

/-!
# Scaled terminal right-lifting property v1.41

Version 1.40 reduced strictification to extension across the canonical
horn-cylinder attachments

`(Δ[n] × {ε}) ∪ (Λ[n,i] × Δ[1]) -> Δ[n] × Δ[1]`.

This layer identifies that extension problem with a genuine categorical right
lifting property.  The key point is to work in the category of explicitly
scaled simplicial sets rather than in bare `SSet`:

* morphisms are simplicial maps preserving thin 2-simplices;
* every simplicial set has a minimal scaling generated by the two degenerate
  2-simplex families;
* the cylinder `Δ[n] × Δ[1]` is scaled by projecting thinness to `Δ[n]`;
* each attachment is given the minimal scaling, so every canonical attachment
  map into a scaled target is automatically a scaled morphism;
* both endpoint inclusions `Δ[n] -> Δ[n] × Δ[1]` are scaled for the cylinder
  scaling.

Consequently a lift in the scaled category is not merely an ordinary cylinder
extension: its composite with the opposite endpoint is automatically scaled.
Thus the extra endpoint-stability clause of v1.40 is recovered from the
categorical lift itself.

No scaled-anodyne theorem is assumed.  The remaining independent input becomes
exactly a native Mathlib `HasLiftingProperty` statement against the terminal
map of a scaled simplicial set.
-/

/-! ## Minimal scaling and the cylinder scaling -/

/-- The minimal scaling generated by the two degeneracies of 1-simplices. -/
def minimalScaling (X : SSet.{u}) : ScaledSimplicialSet X where
  thin := fun t =>
    (∃ x : X _⦋1⦌, X.σ 0 x = t) ∨
      (∃ x : X _⦋1⦌, X.σ 1 x = t)
  thin_sigma_zero := by
    intro x
    exact Or.inl ⟨x, rfl⟩
  thin_sigma_one := by
    intro x
    exact Or.inr ⟨x, rfl⟩

/-- Every simplicial map out of the minimally scaled source is scaled. -/
theorem minimalScaling_map
    {X Y : SSet.{u}}
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y) :
    IsScaledMap (minimalScaling X) sY f := by
  intro t ht
  rcases ht with ⟨x, rfl⟩ | ⟨x, rfl⟩
  · rw [SSet.σ_naturality_apply f 0 x]
    exact sY.thin_sigma_zero _
  · rw [SSet.σ_naturality_apply f 1 x]
    exact sY.thin_sigma_one _

/-- The cylinder scaling remembers thinness only in the simplex coordinate. -/
def simplexCylinderScaling
    {n : Nat}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) :
    ScaledSimplicialSet ((Δ[n] : SSet.{u}) ⊗ Δ[1]) where
  thin := fun t => sΔ.thin t.1
  thin_sigma_zero := by
    intro x
    simpa using sΔ.thin_sigma_zero x.1
  thin_sigma_one := by
    intro x
    simpa using sΔ.thin_sigma_one x.1

/-- Endpoint zero preserves the cylinder scaling. -/
theorem endpointZero_scaled
    {n : Nat}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) :
    IsScaledMap sΔ (simplexCylinderScaling sΔ)
      (SSet.ι₀ : (Δ[n] : SSet.{u}) ⟶ (Δ[n] : SSet.{u}) ⊗ Δ[1]) := by
  intro t ht
  change sΔ.thin ((((SSet.ι₀ : (Δ[n] : SSet.{u}) ⟶
    (Δ[n] : SSet.{u}) ⊗ Δ[1])).app _ t).1)
  simpa using ht

/-- Endpoint one preserves the cylinder scaling. -/
theorem endpointOne_scaled
    {n : Nat}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) :
    IsScaledMap sΔ (simplexCylinderScaling sΔ)
      (SSet.ι₁ : (Δ[n] : SSet.{u}) ⟶ (Δ[n] : SSet.{u}) ⊗ Δ[1]) := by
  intro t ht
  change sΔ.thin ((((SSet.ι₁ : (Δ[n] : SSet.{u}) ⟶
    (Δ[n] : SSet.{u}) ⊗ Δ[1])).app _ t).1)
  simpa using ht

/-! ## The category of explicitly scaled simplicial sets -/

/-- A simplicial set together with an explicit scaling. -/
structure ScaledSSet where
  carrier : SSet.{u}
  scaling : ScaledSimplicialSet carrier

namespace ScaledSSet

/-- Morphisms of scaled simplicial sets are exactly scaled simplicial maps. -/
structure ScaledMap (X Y : ScaledSSet.{u}) where
  map : X.carrier ⟶ Y.carrier
  scaled : IsScaledMap X.scaling Y.scaling map

@[ext]
theorem ScaledMap.ext
    {X Y : ScaledSSet.{u}}
    {f g : ScaledMap X Y}
    (h : f.map = g.map) : f = g := by
  cases f with
  | mk f hf =>
      cases g with
      | mk g hg =>
          dsimp at h
          cases h
          rfl

instance : Category (ScaledSSet.{u}) where
  Hom := ScaledMap
  id := fun X => ⟨𝟙 X.carrier, isScaledMap_id X.scaling⟩
  comp := fun f g => ⟨f.map ≫ g.map, f.scaled.comp g.scaled⟩
  id_comp := by
    intro X Y f
    apply ScaledMap.ext
    change (𝟙 X.carrier) ≫ f.map = f.map
    simp
  comp_id := by
    intro X Y f
    apply ScaledMap.ext
    change f.map ≫ 𝟙 Y.carrier = f.map
    simp
  assoc := by
    intro W X Y Z f g h
    apply ScaledMap.ext
    change (f.map ≫ g.map) ≫ h.map = f.map ≫ g.map ≫ h.map
    simp

@[simp]
theorem id_map (X : ScaledSSet.{u}) :
    (𝟙 X : X ⟶ X).map = 𝟙 X.carrier := rfl

@[simp]
theorem comp_map
    {X Y Z : ScaledSSet.{u}}
    (f : X ⟶ Y) (g : Y ⟶ Z) :
    (f ≫ g).map = f.map ≫ g.map := rfl

/-- Repackage a chosen scaled simplicial set as an object. -/
def of (X : SSet.{u}) (sX : ScaledSimplicialSet X) : ScaledSSet.{u} :=
  ⟨X, sX⟩

/-- The scaled point, using maximal scaling. -/
def point : ScaledSSet.{u} :=
  of (Δ[0] : SSet.{u}) (ScaledSimplicialSet.maximal _)

/-- The unique underlying map to the point is a scaled morphism. -/
noncomputable def toPoint (X : ScaledSSet.{u}) : X ⟶ point where
  map := SSet.stdSimplex.isTerminalObj₀.from X.carrier
  scaled := by
    intro t ht
    exact ScaledSimplicialSet.maximal_thin _ _

/-- The scaled point is terminal. -/
noncomputable def pointIsTerminal : IsTerminal (point : ScaledSSet.{u}) :=
  IsTerminal.ofUniqueHom
    (fun X => toPoint X)
    (by
      intro X f
      apply ScaledMap.ext
      exact SSet.stdSimplex.isTerminalObj₀.hom_ext _ _)

/-- A lifting square against the terminal map associated to a top morphism. -/
def terminalSquare
    {A B X : ScaledSSet.{u}}
    (i : A ⟶ B)
    (f : A ⟶ X) :
    CommSq f i (toPoint X) (toPoint B) where
  w := by
    apply ScaledMap.ext
    exact SSet.stdSimplex.isTerminalObj₀.hom_ext _ _

/-- RLP against the terminal map is exactly the extension property for all
scaled top maps. -/
theorem hasLiftingProperty_toPoint_iff
    {A B X : ScaledSSet.{u}}
    (i : A ⟶ B) :
    HasLiftingProperty i (toPoint X) ↔
      ∀ f : A ⟶ X, ∃ l : B ⟶ X, i ≫ l = f := by
  constructor
  · intro h f
    let sq := terminalSquare i f
    rcases (h.sq_hasLift sq).exists_lift with ⟨L⟩
    exact ⟨L.l, L.fac_left⟩
  · intro h
    refine ⟨?_⟩
    intro f g sq
    rcases h f with ⟨l, hl⟩
    exact CommSq.HasLift.mk'
      { l := l
        fac_left := hl
        fac_right := by
          apply ScaledMap.ext
          exact SSet.stdSimplex.isTerminalObj₀.hom_ext _ _ }

end ScaledSSet

/-! ## Scaled attachment and cylinder objects -/

/-- The simplex with its chosen scaling. -/
def scaledSimplex
    {n : Nat}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) : ScaledSSet.{u} :=
  ScaledSSet.of (Δ[n] : SSet.{u}) sΔ

/-- The cylinder with thinness projected from the simplex coordinate. -/
def scaledSimplexCylinder
    {n : Nat}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) : ScaledSSet.{u} :=
  ScaledSSet.of ((Δ[n] : SSet.{u}) ⊗ Δ[1])
    (simplexCylinderScaling sΔ)

/-- The canonical horn-cylinder attachment with minimal scaling. -/
def minimallyScaledHornCylinderAttachment
    (n : Nat) (i : Fin (n + 1)) (ε : Fin 2) : ScaledSSet.{u} :=
  ScaledSSet.of (hornCylinderAttachment n i ε : SSet.{u})
    (minimalScaling _)

/-- The attachment inclusion is automatically scaled because its source has
minimal scaling. -/
def scaledHornCylinderAttachmentInclusion
    {n : Nat} (i : Fin (n + 1)) (ε : Fin 2)
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) :
    minimallyScaledHornCylinderAttachment n i ε ⟶
      scaledSimplexCylinder sΔ where
  map := (hornCylinderAttachment n i ε).ι
  scaled := minimalScaling_map _ _

/-- Endpoint zero as a morphism of scaled simplicial sets. -/
noncomputable def scaledEndpointZero
    {n : Nat}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) :
    scaledSimplex sΔ ⟶ scaledSimplexCylinder sΔ where
  map := (SSet.ι₀ : (Δ[n] : SSet.{u}) ⟶ (Δ[n] : SSet.{u}) ⊗ Δ[1])
  scaled := endpointZero_scaled sΔ

/-- Endpoint one as a morphism of scaled simplicial sets. -/
noncomputable def scaledEndpointOne
    {n : Nat}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) :
    scaledSimplex sΔ ⟶ scaledSimplexCylinder sΔ where
  map := (SSet.ι₁ : (Δ[n] : SSet.{u}) ⟶ (Δ[n] : SSet.{u}) ⊗ Δ[1])
  scaled := endpointOne_scaled sΔ

/-- The canonical forward attachment map is automatically a scaled morphism
from the minimally scaled attachment. -/
noncomputable def scaledForwardAttachmentMap
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ f) :
    minimallyScaledHornCylinderAttachment n i 0 ⟶ ScaledSSet.of X sX where
  map := forwardAttachmentMap H Q
  scaled := minimalScaling_map _ _

/-- The canonical backward attachment map is automatically scaled from the
minimal attachment. -/
noncomputable def scaledBackwardAttachmentMap
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ g) :
    minimallyScaledHornCylinderAttachment n i 1 ⟶ ScaledSSet.of X sX where
  map := backwardAttachmentMap H Q
  scaled := minimalScaling_map _ _

/-! ## Native terminal RLP implies v1.40 attachment lifting -/

section

set_option backward.isDefEq.respectTransparency false

/-- Forward v1.40 attachment lifting follows from the native scaled RLP. -/
noncomputable def forwardAttachmentLiftingOfTerminalRLP
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u}))
    (R : HasLiftingProperty
      (scaledHornCylinderAttachmentInclusion i 0 sΔ)
      (ScaledSSet.toPoint (ScaledSSet.of X sX))) :
    ForwardScaledHornAttachmentLifting (i := i) sX sΔ where
  lift := by
    intro f g H Q
    let a := scaledForwardAttachmentMap H Q
    let sq := ScaledSSet.terminalSquare
      (scaledHornCylinderAttachmentInclusion i 0 sΔ) a
    rcases (R.sq_hasLift sq).exists_lift with ⟨L⟩
    refine ⟨L.l.map, ?_, ?_⟩
    · have h := congrArg ScaledSSet.ScaledMap.map L.fac_left
      simpa [a, sq, scaledForwardAttachmentMap,
        scaledHornCylinderAttachmentInclusion] using h
    · exact (endpointOne_scaled sΔ).comp L.l.scaled

/-- Backward v1.40 attachment lifting follows from the native scaled RLP. -/
noncomputable def backwardAttachmentLiftingOfTerminalRLP
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    (R : HasLiftingProperty
      (scaledHornCylinderAttachmentInclusion i 1 sΔ)
      (ScaledSSet.toPoint (ScaledSSet.of X sX))) :
    BackwardScaledHornAttachmentLifting (i := i) sX sΔ where
  lift := by
    intro f g H Q
    let a := scaledBackwardAttachmentMap H Q
    let sq := ScaledSSet.terminalSquare
      (scaledHornCylinderAttachmentInclusion i 1 sΔ) a
    rcases (R.sq_hasLift sq).exists_lift with ⟨L⟩
    refine ⟨L.l.map, ?_, ?_⟩
    · have h := congrArg ScaledSSet.ScaledMap.map L.fac_left
      simpa [a, sq, scaledBackwardAttachmentMap,
        scaledHornCylinderAttachmentInclusion] using h
    · exact (endpointZero_scaled sΔ).comp L.l.scaled

end

/-- Two-sided terminal RLP for one scaled horn problem. -/
structure ScaledHornProblemTerminalRLP
    {X : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    {n : Nat} {i : Fin (n + 1)}
    (P : ScaledHornExtensionProblem X sX n i) : Prop where
  forward : HasLiftingProperty
    (scaledHornCylinderAttachmentInclusion i 0 P.simplexScaling)
    (ScaledSSet.toPoint (ScaledSSet.of X sX))
  backward : HasLiftingProperty
    (scaledHornCylinderAttachmentInclusion i 1 P.simplexScaling)
    (ScaledSSet.toPoint (ScaledSSet.of X sX))

namespace ScaledHornProblemTerminalRLP

/-- Native terminal RLP recovers the exact attachment-lifting interface of
v1.40. -/
noncomputable def toAttachmentLifting
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {P : ScaledHornExtensionProblem X sX n i}
    (R : ScaledHornProblemTerminalRLP sX P) :
    ScaledHornProblemAttachmentLifting sX P where
  forward := forwardAttachmentLiftingOfTerminalRLP R.forward
  backward := backwardAttachmentLiftingOfTerminalRLP R.backward

/-- Hence terminal RLP already strictifies a homotopy-class filler. -/
noncomputable def strictify
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {P : ScaledHornExtensionProblem X sX n i}
    (R : ScaledHornProblemTerminalRLP sX P)
    (Q : HomotopyClassScaledHornFiller P) :
    Nonempty (ScaledHornFiller P) :=
  R.toAttachmentLifting.toStrictification Q

end ScaledHornProblemTerminalRLP

/-! ## Family-level RLP and presentation-independent strict fibrancy -/

/-- Terminal RLP for every horn problem selected by one family. -/
structure ScaledHornFamilyTerminalRLP
    {X : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    (F : ScaledHornFamily X sX) : Prop where
  lifting :
    ∀ {n : Nat} {i : Fin (n + 1)}
      (P : ScaledHornExtensionProblem X sX n i),
      F.admissible P →
      ScaledHornProblemTerminalRLP sX P

namespace ScaledHornFamilyTerminalRLP

/-- Family terminal RLP gives family attachment lifting. -/
noncomputable def toAttachmentLifting
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {F : ScaledHornFamily X sX}
    (R : ScaledHornFamilyTerminalRLP sX F) :
    ScaledHornFamilyAttachmentLifting sX F where
  lifting := by
    intro n i P hP
    exact (R.lifting P hP).toAttachmentLifting

/-- Family terminal RLP gives family homotopy-class strictification. -/
noncomputable def toStrictification
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {F : ScaledHornFamily X sX}
    (R : ScaledHornFamilyTerminalRLP sX F) :
    ScaledHornFamilyHomotopyClassStrictification X sX F :=
  R.toAttachmentLifting.toStrictification

end ScaledHornFamilyTerminalRLP

open KUOS.DependentOriginationGlobalDuskinScaledNerveV1_21
open KUOS.DependentOriginationStrictlyUnitaryDuskinModelTransportV1_27

universe v w

/-- A coherent normalized scaled model equivalence whose global Duskin
presentations satisfy the native scaled-terminal RLP for their selected horn
families. -/
structure CoherentNormalizedScaledTerminalRLPModelEquivalence
    {B C : Type u}
    [Bicategory.{w, v} B] [Bicategory.{w, v} C]
    (E : BicategoricalModelEquivalence B C)
    (G : BicategoricalModelEquivalence C B)
    (HB : GlobalDuskinScaledHornFamily B)
    (HC : GlobalDuskinScaledHornFamily C) where
  homotopyClassModel :
    CoherentNormalizedScaledHomotopyClassModelEquivalence E G HB HC
  sourceTerminalRLP :
    ScaledHornFamilyTerminalRLP (duskinScaling B) HB
  targetTerminalRLP :
    ScaledHornFamilyTerminalRLP (duskinScaling C) HC

namespace CoherentNormalizedScaledTerminalRLPModelEquivalence

variable
    {B C : Type u}
    [Bicategory.{w, v} B] [Bicategory.{w, v} C]
    {E : BicategoricalModelEquivalence B C}
    {G : BicategoricalModelEquivalence C B}
    {HB : GlobalDuskinScaledHornFamily B}
    {HC : GlobalDuskinScaledHornFamily C}
    (K : CoherentNormalizedScaledTerminalRLPModelEquivalence E G HB HC)

/-- Forget the categorical RLP only after deriving the v1.40 attachment
lifting package. -/
noncomputable def toAttachmentLiftableModelEquivalence :
    CoherentNormalizedScaledAttachmentLiftableModelEquivalence E G HB HC where
  homotopyClassModel := K.homotopyClassModel
  sourceAttachmentLifting := K.sourceTerminalRLP.toAttachmentLifting
  targetAttachmentLifting := K.targetTerminalRLP.toAttachmentLifting

include K in
/-- Strict global scaled-Duskin fibrancy is presentation-independent under the
native scaled-terminal RLP on both presentations. -/
theorem globalDuskinStrictFibrancy_iff :
    HasScaledHornFillers (duskinNerve B) (duskinScaling B) HB ↔
      HasScaledHornFillers (duskinNerve C) (duskinScaling C) HC :=
  K.toAttachmentLiftableModelEquivalence.globalDuskinStrictFibrancy_iff

end CoherentNormalizedScaledTerminalRLPModelEquivalence

/-!
The strict-fibrancy spine is now expressed by an actual categorical lifting
property:

```text
scaled category:
  objects  = simplicial sets + explicit scaling
  morphisms = scaled simplicial maps

minimal attachment scaling
  -> every canonical attachment map is a scaled morphism

simplex-projection cylinder scaling
  -> both endpoint inclusions are scaled

HasLiftingProperty
  attachment_inclusion
  (target -> scaled point)
  -> globally scaled cylinder lift
  -> opposite endpoint automatically scaled
  -> v1.40 attachment lifting
  -> v1.39 two-sided cylinder extension
  -> homotopy-class strictification
  -> strict fibrancy = homotopy-class fibrancy

coherent normalized scaled model equivalence
  -> presentation-independent homotopy-class fibrancy
  + terminal RLP on both presentations
  -> presentation-independent strict scaled fibrancy.
```

The remaining independent theorem is now categorical and sharply localized:
prove the native terminal RLP for the canonical minimally-scaled horn-cylinder
attachment inclusions associated to the chosen standard scaled-anodyne family.
No ordinary-anodyne or unscaled RLP theorem is silently promoted to this scaled
statement.
-/

end KUOS.DependentOriginationScaledTerminalRLPV1_41