import KUOS.DependentOriginationStandardABCPositiveCanonicalResidualSplitV1_79

namespace KUOS.DependentOriginationGeneratedPresentationEndpointInvariantV1_80

open CategoryTheory
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationScaledAnodyneGeneratorClosureV1_42
open KUOS.DependentOriginationScaledAnodyneWFSUniversalityV1_43
open KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49
open KUOS.DependentOriginationStandardTypeAEndpointPushoutProductV1_50
open KUOS.DependentOriginationStandardTypeAScaledLeibnizPushoutV1_55
open KUOS.DependentOriginationStandardTypeCCollapsedEdgeV1_58
open KUOS.DependentOriginationStandardABCLeibnizCellularComparisonV1_59
open KUOS.DependentOriginationStandardTypeAEndpointOppositeCellCertificateV1_77
open KUOS.DependentOriginationStandardABCPositiveCanonicalResidualSplitV1_79

universe u

/-!
# Generated-presentation endpoint invariant v1.80

Version v1.77 gave a concrete A/B cellular proof of the standard type-(A)
endpoint Leibniz theorem.  Versions v1.78-v1.79 kept the stronger canonical
arbitrary-scaling comparison honest: equality with the standard A/B/C family is
conditional on genuinely separate residual geometry.

The correct presentation-independent statement is therefore not equality of
literal generator lists.  It is invariance under *mutual generation*.

For two morphism properties `E` and `F`, write

```text
A_E = E.rlp.llp
R_E = E.rlp.
```

We call the presentations generated-equivalent when

```text
E <= A_F
F <= A_E.
```

Orthogonal saturation then forces

```text
A_E = A_F
R_E = R_F.
```

This file proves that equivalence generically and transports the conclusions
that actually depend only on these generated classes:

* generated-anodyne membership;
* generated-fibration membership and fibrancy;
* standard type-(A) endpoint Leibniz generator membership;
* stability under the genuine scaled endpoint Leibniz construction;
* the right-lifting formulation;
* the existing v1.55 external type-(A) comparison, hence the induced
  attachment and endpoint-pushout-product conclusions.

The concrete v1.77 cellular decomposition itself is intentionally *not*
transported: a cell presentation is presentation-dependent even when its
orthogonally generated class is not.

At the end we expose the v1.79 full canonical comparison only conditionally as
one instance of this generic equivalence.  No arbitrary canonical scaling is
identified with a standard scaling in this file.
-/

/-! ## Mutual generation as presentation equivalence -/

/-- Two scaled-anodyne generator presentations are equivalent when each
literal generator family lies in the orthogonal left closure generated by the
other.  This is closure-level equivalence, not equality of generator lists. -/
structure GeneratedScaledAnodynePresentationEquivalence
    (E F : MorphismProperty (ScaledSSet.{u})) : Prop where
  left_generators_le_right_generated :
    E ≤ externalGeneratedScaledAnodyne F
  right_generators_le_left_generated :
    F ≤ externalGeneratedScaledAnodyne E

namespace GeneratedScaledAnodynePresentationEquivalence

variable
    {E F G : MorphismProperty (ScaledSSet.{u})}
    (K : GeneratedScaledAnodynePresentationEquivalence E F)

/-- Mutual generation identifies the two orthogonally generated left classes.
No small-object argument is needed: both targets are already orthogonally
saturated. -/
theorem generatedAnodyne_eq :
    externalGeneratedScaledAnodyne E =
      externalGeneratedScaledAnodyne F := by
  apply le_antisymm
  · exact externalGeneratedScaledAnodyne_le_of_le_saturated
      K.left_generators_le_right_generated
      (externalGeneratedScaledAnodyne_isOrthogonallySaturated F)
  · exact externalGeneratedScaledAnodyne_le_of_le_saturated
      K.right_generators_le_left_generated
      (externalGeneratedScaledAnodyne_isOrthogonallySaturated E)

/-- Conversely equality of generated left classes recovers mutual generation.
Thus the structure above contains exactly the information relevant to the
orthogonal closure. -/
def ofGeneratedAnodyneEq
    (h : externalGeneratedScaledAnodyne E =
      externalGeneratedScaledAnodyne F) :
    GeneratedScaledAnodynePresentationEquivalence E F where
  left_generators_le_right_generated := by
    intro A B f hf
    rw [← h]
    change E.rlp.llp f
    exact (MorphismProperty.le_llp_rlp E) f hf
  right_generators_le_left_generated := by
    intro A B f hf
    rw [h]
    change F.rlp.llp f
    exact (MorphismProperty.le_llp_rlp F) f hf

/-- Generated presentation equivalence is exactly equality of the generated
left classes. -/
theorem iff_generatedAnodyne_eq :
    GeneratedScaledAnodynePresentationEquivalence E F ↔
      externalGeneratedScaledAnodyne E =
        externalGeneratedScaledAnodyne F := by
  constructor
  · intro h
    exact h.generatedAnodyne_eq
  · exact ofGeneratedAnodyneEq

/-- Reflexivity of generated presentation equivalence. -/
def refl (E : MorphismProperty (ScaledSSet.{u})) :
    GeneratedScaledAnodynePresentationEquivalence E E :=
  ofGeneratedAnodyneEq rfl

/-- Symmetry of generated presentation equivalence. -/
def symm : GeneratedScaledAnodynePresentationEquivalence F E :=
  ofGeneratedAnodyneEq K.generatedAnodyne_eq.symm

/-- Transitivity of generated presentation equivalence. -/
def trans
    (L : GeneratedScaledAnodynePresentationEquivalence F G) :
    GeneratedScaledAnodynePresentationEquivalence E G :=
  ofGeneratedAnodyneEq
    (K.generatedAnodyne_eq.trans L.generatedAnodyne_eq)

/-- Equality of the generated left classes implies equality of the corresponding
right lifting classes. -/
theorem generatedFibration_eq :
    externalGeneratedScaledFibration E =
      externalGeneratedScaledFibration F := by
  have hleft : E.rlp.llp = F.rlp.llp := by
    simpa [externalGeneratedScaledAnodyne] using K.generatedAnodyne_eq
  change E.rlp = F.rlp
  calc
    E.rlp = (E.rlp.llp).rlp :=
      (MorphismProperty.rlp_llp_rlp E).symm
    _ = (F.rlp.llp).rlp := by rw [hleft]
    _ = F.rlp := MorphismProperty.rlp_llp_rlp F

/-- Generated-anodyne membership is presentation-independent under mutual
generation. -/
theorem generatedAnodyne_mem_iff
    {A B : ScaledSSet.{u}} (f : A ⟶ B) :
    externalGeneratedScaledAnodyne E f ↔
      externalGeneratedScaledAnodyne F f := by
  rw [K.generatedAnodyne_eq]

/-- Generated-fibration membership is likewise presentation-independent. -/
theorem generatedFibration_mem_iff
    {A B : ScaledSSet.{u}} (p : A ⟶ B) :
    externalGeneratedScaledFibration E p ↔
      externalGeneratedScaledFibration F p := by
  rw [K.generatedFibration_eq]

/-- Whether the generated pair is already a weak factorization system is also
an invariant of the generated presentation. -/
theorem weakFactorizationSystem_iff :
    MorphismProperty.IsWeakFactorizationSystem
        (externalGeneratedScaledAnodyne E)
        (externalGeneratedScaledFibration E) ↔
      MorphismProperty.IsWeakFactorizationSystem
        (externalGeneratedScaledAnodyne F)
        (externalGeneratedScaledFibration F) := by
  rw [K.generatedAnodyne_eq, K.generatedFibration_eq]

/-! ## Endpoint properties depending only on the generated classes -/

/-- Direct generator-membership form of the standard type-(A) endpoint
Leibniz conclusion for an arbitrary presentation. -/
def TypeAEndpointLeibnizGeneratorsGeneratedBy
    (E : MorphismProperty (ScaledSSet.{u})) : Prop :=
  (standardTypeAScaledLeibnizPushoutProductGenerators :
    MorphismProperty (ScaledSSet.{u})) ≤
    externalGeneratedScaledAnodyne E

/-- Stability form of the same endpoint operation relative to a generated left
class.  This does not require the literal presentation itself to contain the
standard type-(A) horns. -/
def TypeAEndpointLeibnizStableForPresentation
    (E : MorphismProperty (ScaledSSet.{u})) : Prop :=
  StandardTypeAScaledLeibnizPushoutProductStable
    (externalGeneratedScaledAnodyne E)

/-- Right-lifting form of the endpoint conclusion relative to the right class
of a presentation. -/
def TypeAEndpointLeibnizLiftingForPresentation
    (E : MorphismProperty (ScaledSSet.{u})) : Prop :=
  ∀ (g : StandardTypeAHornAttachmentGeneratorIndex)
    {X Y : ScaledSSet.{u}} (p : X ⟶ Y),
    externalGeneratedScaledFibration E p →
      HasLiftingProperty
        (standardTypeAEndpointScaledLeibnizPushoutProductHom g) p

/-- Endpoint Leibniz generator membership is invariant under generated
presentation equivalence. -/
theorem typeAEndpointLeibnizGeneratorsGenerated_iff :
    TypeAEndpointLeibnizGeneratorsGeneratedBy E ↔
      TypeAEndpointLeibnizGeneratorsGeneratedBy F := by
  unfold TypeAEndpointLeibnizGeneratorsGeneratedBy
  rw [K.generatedAnodyne_eq]

/-- Endpoint Leibniz stability is invariant because its ambient left class is
literally the same morphism property. -/
theorem typeAEndpointLeibnizStable_iff :
    TypeAEndpointLeibnizStableForPresentation E ↔
      TypeAEndpointLeibnizStableForPresentation F := by
  unfold TypeAEndpointLeibnizStableForPresentation
  rw [K.generatedAnodyne_eq]

/-- The endpoint right-lifting statement is invariant because the right
classes are literally equal. -/
theorem typeAEndpointLeibnizLifting_iff :
    TypeAEndpointLeibnizLiftingForPresentation E ↔
      TypeAEndpointLeibnizLiftingForPresentation F := by
  constructor
  · intro h g X Y p hp
    apply h g p
    have : externalGeneratedScaledFibration E p := by
      rw [K.generatedFibration_eq]
      exact hp
    exact this
  · intro h g X Y p hp
    apply h g p
    have : externalGeneratedScaledFibration F p := by
      rw [← K.generatedFibration_eq]
      exact hp
    exact this

/-- Fibrancy measured directly by the generator RLP is independent of any
mutually generated presentation. -/
theorem fibrantForExternalGenerators_iff
    (X : ScaledSSet.{u}) :
    IsFibrantForExternalGenerators E X ↔
      IsFibrantForExternalGenerators F X := by
  change
    externalGeneratedScaledFibration E (ScaledSSet.toPoint X) ↔
      externalGeneratedScaledFibration F (ScaledSSet.toPoint X)
  rw [K.generatedFibration_eq]

end GeneratedScaledAnodynePresentationEquivalence

/-! ## The standard A/B/C theorem as a presentation-independent baseline -/

/-- The v1.77 cellular theorem says directly that every standard type-(A)
endpoint Leibniz generator is generated by the standard A/B/C presentation. -/
theorem standardABC_typeAEndpointLeibnizGeneratorsGenerated :
    GeneratedScaledAnodynePresentationEquivalence.TypeAEndpointLeibnizGeneratorsGeneratedBy
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) := by
  change
    (standardTypeAScaledLeibnizPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      standardGeneratedScaledAnodyneABC
  exact
    standardABCTypeAEndpointLeibnizStability_iff_generators_le.mp
      standardABCTypeAEndpointLeibnizStability_proved

/-- The same v1.77 theorem in stability form. -/
theorem standardABC_typeAEndpointLeibnizStable :
    GeneratedScaledAnodynePresentationEquivalence.TypeAEndpointLeibnizStableForPresentation
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) := by
  change StandardABCTypeAEndpointLeibnizStability.{u}
  exact standardABCTypeAEndpointLeibnizStability_proved

/-- And in right-lifting form. -/
theorem standardABC_typeAEndpointLeibnizLifting :
    GeneratedScaledAnodynePresentationEquivalence.TypeAEndpointLeibnizLiftingForPresentation
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) := by
  change StandardABCTypeAEndpointLeibnizLifting.{u}
  exact standardABCTypeAEndpointLeibnizLifting_proved

/-! ## Transport the standard theorem to any equivalent presentation -/

namespace GeneratedScaledAnodynePresentationEquivalence

variable {E : MorphismProperty (ScaledSSet.{u})}

/-- Any presentation mutually generated-equivalent to standard A/B/C inherits
the exact endpoint Leibniz generator-membership theorem. -/
theorem typeAEndpointLeibnizGeneratorsGenerated_of_standardEquivalent
    (K : GeneratedScaledAnodynePresentationEquivalence
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) E) :
    TypeAEndpointLeibnizGeneratorsGeneratedBy E :=
  K.typeAEndpointLeibnizGeneratorsGenerated_iff.mp
    standardABC_typeAEndpointLeibnizGeneratorsGenerated

/-- The stability theorem itself transports to any equivalent presentation. -/
theorem typeAEndpointLeibnizStable_of_standardEquivalent
    (K : GeneratedScaledAnodynePresentationEquivalence
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) E) :
    TypeAEndpointLeibnizStableForPresentation E :=
  K.typeAEndpointLeibnizStable_iff.mp
    standardABC_typeAEndpointLeibnizStable

/-- The right-lifting theorem transports independently through equality of the
right classes. -/
theorem typeAEndpointLeibnizLifting_of_standardEquivalent
    (K : GeneratedScaledAnodynePresentationEquivalence
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) E) :
    TypeAEndpointLeibnizLiftingForPresentation E :=
  K.typeAEndpointLeibnizLifting_iff.mp
    standardABC_typeAEndpointLeibnizLifting

/-- The existing v1.55 external comparison structure can be reconstructed for
any presentation equivalent to standard A/B/C.  Hence all downstream type-A
induced-attachment theorems can be reused without another prism argument. -/
def standardTypeAExternalComparison_of_standardEquivalent
    (K : GeneratedScaledAnodynePresentationEquivalence
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) E) :
    StandardTypeAExternalScaledLeibnizComparison E where
  typeAHorns_le_externalGenerated := by
    rw [← K.generatedAnodyne_eq]
    change
      (standardTypeAScaledHornGenerators :
        MorphismProperty (ScaledSSet.{u})) ≤
        standardGeneratedScaledAnodyneABC
    exact standardTypeAHorns_le_standardGeneratedABC
  scaledLeibnizPushoutProductStable :=
    K.typeAEndpointLeibnizStable_of_standardEquivalent

/-- Therefore the v1.49 induced type-A attachments are generated by every
presentation equivalent to standard A/B/C. -/
theorem inducedTypeAAttachments_le_of_standardEquivalent
    (K : GeneratedScaledAnodynePresentationEquivalence
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) E) :
    (standardTypeAInducedScaledHornAttachmentGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E :=
  (K.standardTypeAExternalComparison_of_standardEquivalent)
    .inducedTypeAAttachments_le_externalGenerated

/-- The v1.50 endpoint-pushout-product presentation transports as well. -/
theorem endpointPushoutProducts_le_of_standardEquivalent
    (K : GeneratedScaledAnodynePresentationEquivalence
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) E) :
    (standardTypeAEndpointPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E :=
  (K.standardTypeAExternalComparison_of_standardEquivalent)
    .endpointPushoutProducts_le_externalGenerated

end GeneratedScaledAnodynePresentationEquivalence

/-! ## Conditional connection to the stronger canonical KuuOS family -/

/-- If the positive v1.79 canonical comparison obligations are eventually
proved, they instantiate the generic presentation-equivalence notion between
standard A/B/C and the canonical arbitrary-scaling attachment family.

This definition is deliberately conditional: v1.80 does not assert that such a
certificate exists. -/
def StandardABCCanonicalPositiveComparisonCertificate.toGeneratedPresentationEquivalence
    (K : StandardABCCanonicalPositiveComparisonCertificate.{u}) :
    GeneratedScaledAnodynePresentationEquivalence
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u}))
      (scaledHornAttachmentGenerators :
        MorphismProperty (ScaledSSet.{u})) := by
  apply GeneratedScaledAnodynePresentationEquivalence.ofGeneratedAnodyneEq
  change
    standardGeneratedScaledAnodyneABC =
      (canonicalGeneratedScaledAnodyne :
        MorphismProperty (ScaledSSet.{u}))
  exact K.generatedAnodyne_eq

/-- Under that same explicitly conditional comparison, the canonical generated
presentation inherits the standard endpoint stability theorem. -/
theorem canonical_typeAEndpointLeibnizStable_of_positiveComparison
    (K : StandardABCCanonicalPositiveComparisonCertificate.{u}) :
    GeneratedScaledAnodynePresentationEquivalence.TypeAEndpointLeibnizStableForPresentation
      (scaledHornAttachmentGenerators :
        MorphismProperty (ScaledSSet.{u})) :=
  K.toGeneratedPresentationEquivalence
    .typeAEndpointLeibnizStable_of_standardEquivalent

/-- And it inherits the endpoint right-lifting theorem through equality of the
right orthogonals. -/
theorem canonical_typeAEndpointLeibnizLifting_of_positiveComparison
    (K : StandardABCCanonicalPositiveComparisonCertificate.{u}) :
    GeneratedScaledAnodynePresentationEquivalence.TypeAEndpointLeibnizLiftingForPresentation
      (scaledHornAttachmentGenerators :
        MorphismProperty (ScaledSSet.{u})) :=
  K.toGeneratedPresentationEquivalence
    .typeAEndpointLeibnizLifting_of_standardEquivalent

/-!
The presentation-independent endpoint theorem is now separated cleanly from
any particular generator list:

```text
E <= F.rlp.llp
F <= E.rlp.llp
        |
        v
E.rlp.llp = F.rlp.llp
E.rlp     = F.rlp
        |
        +--> generated-anodyne membership invariant
        +--> generated-fibration/fibrancy invariant
        +--> endpoint Leibniz generator membership invariant
        +--> endpoint Leibniz stability invariant
        +--> endpoint right-lifting invariant.
```

The concrete standard A/B cellular proof from v1.77 supplies one authoritative
representative of this invariant.  Any other presentation only has to prove
mutual generation; it does not have to replay the boundary-prism filtration.

In particular, the stronger arbitrary-scaling canonical KuuOS family remains
separate until the positive v1.79 comparison fields are genuinely inhabited.
No literal equality of standard and canonical generators has been introduced.
-/

end KUOS.DependentOriginationGeneratedPresentationEndpointInvariantV1_80
