import KUOS.DependentOriginationGeneratedPresentationQuotientInvariantV1_81

namespace KUOS.DependentOriginationCanonicalEndpointLeibnizEpiDescentV1_82

open CategoryTheory
open CategoryTheory.Category
open KUOS.DependentOriginationScaledHornAttachmentLiftingV1_40
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationScaledAnodyneGeneratorClosureV1_42
open KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49
open KUOS.DependentOriginationStandardTypeAEndpointPushoutProductV1_50
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
open KUOS.DependentOriginationStandardTypeAGeneratedPushoutLLPDescentV1_54
open KUOS.DependentOriginationStandardTypeAScaledLeibnizPushoutV1_55
open KUOS.DependentOriginationGeneratedPresentationEndpointInvariantV1_80
open KUOS.DependentOriginationGeneratedPresentationEndpointInvariantV1_80.GeneratedScaledAnodynePresentationEquivalence
open KUOS.DependentOriginationGeneratedPresentationQuotientInvariantV1_81

universe u

/-!
# Canonical endpoint Leibniz epi descent v1.82

The standard A/B/C endpoint theorem was proved geometrically in v1.77 and was
then made presentation-independent in v1.80-v1.81.  The canonical KuuOS
presentation, however, has an even more direct route to the same endpoint
maps.

Fix a standard type-(A) attachment index `g`.  Its canonical KuuOS generator
uses the same ordinary endpoint union-product carrier but equips the source
with the *minimal* scaling:

```text
A_min(g) ------------------------------> Cyl_A(g)
          canonical KuuOS generator
```

The genuine scaled Leibniz source of v1.55 has the least scaling generated by
the two pushout legs.  Minimality therefore gives an identity-underlying
source enrichment

```text
A_min(g) --e_g--> A_Leib(g).
```

The canonical generator factors exactly as

```text
A_min(g) --e_g--> A_Leib(g) --J_g--> Cyl_A(g).
```

The map `e_g` is an epimorphism because its underlying simplicial map is the
identity.  Hence the general v1.54 epi-precomposition lemma applies:
if the composite `e_g >> J_g` has LLP against a map, then `J_g` itself has LLP
against that map.

But `e_g >> J_g` is literally one of the canonical generators, and therefore
belongs to the canonical orthogonal left closure unconditionally.  We conclude
that every standard type-(A) endpoint Leibniz map is canonical generated-
anodyne *without* any standard-vs-canonical presentation comparison.

This gives unconditional canonical endpoint generator membership, endpoint
stability, and endpoint lifting.  The positive comparison residuals from
v1.79 remain relevant for identifying the full standard and canonical
presentation classes, and in particular for transporting the canonical WFS to
the standard presentation, but they are no longer needed for the canonical
endpoint theorem itself.
-/

/-! ## Minimal source to the genuine scaled Leibniz source -/

/-- Enrich the minimally scaled canonical attachment source to the genuine
least-generated scaled Leibniz source.  The underlying carrier is literally the
same `unionProd`, because `hornCylinderAttachment` is defined by that
`unionProd`. -/
def standardTypeAEndpointMinimalToGenerated
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    minimallyScaledHornCylinderAttachment g.n g.i g.endpoint ⟶
      standardTypeAEndpointGeneratedPushoutSource g where
  map := 𝟙 _
  scaled := minimalScaling_map _ _

@[simp]
theorem standardTypeAEndpointMinimalToGenerated_map
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointMinimalToGenerated g).map = 𝟙 _ :=
  rfl

/-- The minimal-to-generated source enrichment is epi: equality after
precomposition is equality after an identity underlying simplicial map. -/
instance standardTypeAEndpointMinimalToGenerated_epi
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    Epi (standardTypeAEndpointMinimalToGenerated g) where
  left_cancellation := by
    intro Z f h w
    apply ScaledSSet.ScaledMap.ext
    change
      @Eq
        (((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint) : SSet.{u}) ⟶ Z.carrier)
        f.map h.map
    have hw := congrArg ScaledSSet.ScaledMap.map w
    change
      (𝟙 ((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint) : SSet.{u}) ≫ f.map) =
        (𝟙 ((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint) : SSet.{u}) ≫ h.map)
      at hw
    simpa only [Category.id_comp] using hw

/-! ## Exact factorization of the canonical generator -/

/-- At the standard type-(A) simplex scaling, the canonical minimally-scaled
horn-cylinder generator is exactly the minimal-source enrichment followed by
the genuine scaled categorical Leibniz map. -/
theorem standardTypeAEndpointMinimalToGenerated_comp_scaledLeibniz
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointMinimalToGenerated g ≫
        standardTypeAEndpointScaledLeibnizPushoutProductHom g =
      scaledHornAttachmentGeneratorHom g.toCanonical := by
  apply ScaledSSet.ScaledMap.ext
  change
    (standardTypeAEndpointMinimalToGenerated g).map ≫
        (standardTypeAEndpointScaledLeibnizPushoutProductHom g).map =
      (scaledHornAttachmentGeneratorHom g.toCanonical).map
  rw [standardTypeAEndpointMinimalToGenerated_map,
    standardTypeAEndpointScaledLeibnizPushoutProductHom_map]
  change
    𝟙 ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint) : SSet.{u}) ≫
        ((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint)).ι =
      ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint)).ι
  simp only [Category.id_comp]

/-! ## Generic orthogonal descent through an epi left factor -/

/-- A right factor of an epi-precomposed left map remains in any `llp` class.
This is the morphism-property form of the pointwise v1.54 lifting lemma. -/
theorem llp_mem_of_epi_precomp
    (T : MorphismProperty (ScaledSSet.{u}))
    {A B D : ScaledSSet.{u}}
    (e : A ⟶ B)
    (i : B ⟶ D)
    [Epi e]
    (h : T.llp (e ≫ i)) :
    T.llp i := by
  intro X Y p hp
  exact hasLiftingProperty_of_epi_precomp e i p (h p hp)

/-! ## Unconditional canonical endpoint membership -/

/-- Every genuine standard type-(A) endpoint scaled Leibniz map belongs to the
canonical KuuOS generated left class.  No standard A/B/C comparison hypothesis
is used. -/
theorem standardTypeAEndpointScaledLeibniz_mem_canonicalGenerated
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u}))
      (standardTypeAEndpointScaledLeibnizPushoutProductHom g) := by
  change
    (scaledHornAttachmentGenerators :
      MorphismProperty (ScaledSSet.{u})).rlp.llp
      (standardTypeAEndpointScaledLeibnizPushoutProductHom g)
  apply llp_mem_of_epi_precomp
    ((scaledHornAttachmentGenerators :
      MorphismProperty (ScaledSSet.{u})).rlp)
    (standardTypeAEndpointMinimalToGenerated g)
    (standardTypeAEndpointScaledLeibnizPushoutProductHom g)
  rw [standardTypeAEndpointMinimalToGenerated_comp_scaledLeibniz]
  exact scaledHornAttachmentGenerators_le_generated _
    (scaledHornAttachmentGenerator_mem g.toCanonical)

/-- Hence the entire explicit endpoint Leibniz generator family is contained
in the canonical generated left class. -/
theorem standardTypeAScaledLeibnizPushoutProductGenerators_le_canonicalGenerated :
    (standardTypeAScaledLeibnizPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      (canonicalGeneratedScaledAnodyne :
        MorphismProperty (ScaledSSet.{u})) := by
  intro A B f hf
  dsimp [standardTypeAScaledLeibnizPushoutProductGenerators] at hf
  cases hf with
  | mk g =>
      exact standardTypeAEndpointScaledLeibniz_mem_canonicalGenerated g

/-- The canonical generated left class is therefore endpoint-Leibniz stable.
In fact the conclusion for each endpoint map is unconditional, so the input
horn-membership hypothesis is not needed in the proof. -/
def canonicalTypeAEndpointLeibnizStabilityUnconditional :
    StandardTypeAScaledLeibnizPushoutProductStable
      (canonicalGeneratedScaledAnodyne :
        MorphismProperty (ScaledSSet.{u})) where
  pushoutProduct_mem := by
    intro g _
    exact standardTypeAEndpointScaledLeibniz_mem_canonicalGenerated g

/-- Every canonical generated fibration lifts against every standard type-(A)
endpoint Leibniz map, unconditionally. -/
theorem canonicalTypeAEndpointLeibnizLiftingUnconditional :
    TypeAEndpointLeibnizLiftingForPresentation
      (scaledHornAttachmentGenerators :
        MorphismProperty (ScaledSSet.{u})) := by
  intro g X Y p hp
  exact
    standardTypeAEndpointScaledLeibniz_mem_canonicalGenerated g p hp

/-! ## Quotient-level canonical endpoint invariants -/

/-- The canonical KuuOS quotient point carries endpoint generator membership
without identifying it with the standard A/B/C quotient point. -/
theorem canonicalKuuOSPresentation_endpointGeneratorsGenerated_unconditional :
    typeAEndpointGeneratorsGenerated.{u} canonicalKuuOSPresentation := by
  change
    TypeAEndpointLeibnizGeneratorsGeneratedBy
      (scaledHornAttachmentGenerators :
        MorphismProperty (ScaledSSet.{u}))
  change
    (standardTypeAScaledLeibnizPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      (canonicalGeneratedScaledAnodyne :
        MorphismProperty (ScaledSSet.{u}))
  exact standardTypeAScaledLeibnizPushoutProductGenerators_le_canonicalGenerated

/-- The canonical quotient point carries endpoint stability independently of
any standard-vs-canonical quotient equality. -/
theorem canonicalKuuOSPresentation_endpointStable_unconditional :
    typeAEndpointStable.{u} canonicalKuuOSPresentation := by
  change
    TypeAEndpointLeibnizStableForPresentation
      (scaledHornAttachmentGenerators :
        MorphismProperty (ScaledSSet.{u}))
  change
    StandardTypeAScaledLeibnizPushoutProductStable
      (canonicalGeneratedScaledAnodyne :
        MorphismProperty (ScaledSSet.{u}))
  exact canonicalTypeAEndpointLeibnizStabilityUnconditional

/-- The canonical quotient point likewise carries endpoint right lifting
unconditionally. -/
theorem canonicalKuuOSPresentation_endpointLifting_unconditional :
    typeAEndpointLifting.{u} canonicalKuuOSPresentation := by
  change
    TypeAEndpointLeibnizLiftingForPresentation
      (scaledHornAttachmentGenerators :
        MorphismProperty (ScaledSSet.{u}))
  exact canonicalTypeAEndpointLeibnizLiftingUnconditional

/-!
After v1.82 the two distinguished presentation classes have the following
unconditional structure:

```text
[standard A/B/C]
  endpoint Leibniz theorem by explicit A/B cellular geometry (v1.77)

[canonical KuuOS]
  native WFS by small-object argument                    (v1.45)
  endpoint Leibniz theorem by epi right-factor descent  (v1.82)
```

Thus the v1.79 standard-vs-canonical comparison is no longer an endpoint-
stability prerequisite.  Its remaining role is genuinely presentation-level:
identify the full generated left/right classes, and thereby transfer structures
such as the canonical WFS to the standard presentation.

This distinction is stronger than merely transporting the v1.77 theorem across
an assumed equality: the canonical endpoint theorem now comes from the
canonical generators themselves.
-/

end KUOS.DependentOriginationCanonicalEndpointLeibnizEpiDescentV1_82
