import KUOS.DependentOriginationStandardArbitraryScalingWaypointV1_89
import KUOS.DependentOriginationStandardTypeBScalingPushoutV1_56

namespace KUOS.DependentOriginationSingleTriangleScalingFiltrationV1_90

open CategoryTheory
open CategoryTheory.Category
open Opposite
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
open KUOS.DependentOriginationStandardTypeBScalingPushoutV1_56
open KUOS.DependentOriginationStandardTypeCCollapsedEdgeV1_58
open KUOS.DependentOriginationGeneratedPresentationQuotientInvariantV1_81
open KUOS.DependentOriginationGeneratedPresentationOrderReflectionV1_84
open KUOS.DependentOriginationCanonicalAttachmentScalingObstructionRetractV1_88
open KUOS.DependentOriginationStandardArbitraryScalingWaypointV1_89

universe u

/-!
# Single-triangle scaling filtrations v1.90

Version v1.88 extracted every pure simplex-scaling enrichment from the
canonical attachment family by an arrow retract.  Version v1.89 then isolated
the presentation generated by all such enrichments as a distinguished point
inside the standard/canonical interval.

The remaining scaling family still quantifies over an arbitrary scaling on
every standard simplex.  This file reduces that family to its atomic finite
pieces.

A scaling on `Delta[n]` is determined in degree two, and the set of
2-simplices of a standard simplex is finite.  We therefore introduce the
single-triangle enrichment

```text
minimal -> minimal + {t}
```

for one 2-simplex `t`.  The generic scaling-pushout theorem of v1.56 pushes
such an atomic enrichment across any already-built finite scaling.  Repeating
that operation and using multiplicativity of a left lifting class gives the
whole minimal-to-finite-scaling enrichment.

Finally, for an arbitrary chosen scaling `sDelta`, we take the finite set of
all triangles declared thin by `sDelta`.  Minimal thin triangles are already
present, so the finite scaling generated by that set is exactly `sDelta`.
Consequently the presentation generated by all arbitrary simplex-scaling
enrichments is exactly the presentation generated by the single-triangle
family.

Thus the v1.89 scaling obstruction closes precisely when every atomic
single-triangle enrichment is standard-generated.  No higher-dimensional
presentation comparison is used in this reduction.
-/

/-! ## Atomic one-triangle scalings -/

/-- Add one chosen 2-simplex to the minimal scaling of `Delta[n]`. -/
def singleTriangleScaling
    {n : Nat}
    (t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌)) :
    ScaledSimplicialSet (Delta[n] : SSet.{u}) where
  thin := fun u =>
    (minimalScaling (Delta[n] : SSet.{u})).thin u ∨ u = t
  thin_sigma_zero := by
    intro x
    exact Or.inl ((minimalScaling (Delta[n] : SSet.{u})).thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl ((minimalScaling (Delta[n] : SSet.{u})).thin_sigma_one x)

/-- Minimal scaling is contained in every one-triangle enlargement. -/
theorem minimalScaling_le_singleTriangleScaling
    {n : Nat}
    (t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌)) :
    ScalingLE
      (minimalScaling (Delta[n] : SSet.{u}))
      (singleTriangleScaling t) := by
  intro u hu
  exact Or.inl hu

/-- The atomic identity-underlying enrichment. -/
def minimalToSingleTriangleScaling
    {n : Nat}
    (t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌)) :
    minimallyScaledSimplex n ⟶ scaledSimplex (singleTriangleScaling t) :=
  scalingEnrichmentHom (minimalScaling_le_singleTriangleScaling t)

/-- Index for the atomic scaling family in all dimensions. -/
structure SingleTriangleScalingEnrichmentIndex where
  n : Nat
  triangle : (Delta[n] : SSet.{u}).obj (op ⦋2⦌)

/-- Atomic enrichment represented by one index. -/
def singleTriangleScalingEnrichmentHom
    (q : SingleTriangleScalingEnrichmentIndex.{u}) :
    minimallyScaledSimplex q.n ⟶
      scaledSimplex (singleTriangleScaling q.triangle) :=
  minimalToSingleTriangleScaling q.triangle

/-- Morphism property of all one-triangle scaling enrichments. -/
def singleTriangleScalingEnrichments :
    MorphismProperty (ScaledSSet.{u}) :=
  MorphismProperty.ofHoms
    (fun q : SingleTriangleScalingEnrichmentIndex.{u} =>
      singleTriangleScalingEnrichmentHom q)

/-- Every indexed atomic enrichment lies in the atomic family. -/
theorem singleTriangleScalingEnrichment_mem
    (q : SingleTriangleScalingEnrichmentIndex.{u}) :
    (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u}))
      (singleTriangleScalingEnrichmentHom q) := by
  exact MorphismProperty.ofHoms.mk q

/-- Every atomic enrichment is already one of the arbitrary pure-scaling
enrichments of v1.88. -/
theorem singleTriangleScalingEnrichments_le_simplexScalingEnrichments :
    (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u})) <=
      simplexScalingEnrichments := by
  intro X Y f hf
  dsimp [singleTriangleScalingEnrichments] at hf
  cases hf with
  | mk q =>
      let r : SimplexScalingEnrichmentIndex.{u} :=
        { n := q.n
          simplexScaling := singleTriangleScaling q.triangle }
      have hr := simplexScalingEnrichment_mem r
      have heq :
          singleTriangleScalingEnrichmentHom q =
            simplexScalingEnrichmentHom r := by
        apply ScaledSSet.ScaledMap.ext
        rfl
      rw [heq]
      exact hr

/-! ## Finite scalings generated by a set of triangles -/

/-- Minimal scaling together with a finite set `F` of explicitly thin
triangles. -/
def finiteTriangleScaling
    {n : Nat}
    (F : Finset ((Delta[n] : SSet.{u}).obj (op ⦋2⦌))) :
    ScaledSimplicialSet (Delta[n] : SSet.{u}) where
  thin := fun t =>
    (minimalScaling (Delta[n] : SSet.{u})).thin t ∨ t ∈ F
  thin_sigma_zero := by
    intro x
    exact Or.inl ((minimalScaling (Delta[n] : SSet.{u})).thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl ((minimalScaling (Delta[n] : SSet.{u})).thin_sigma_one x)

/-- The empty finite scaling is exactly minimal. -/
@[simp]
theorem finiteTriangleScaling_empty
    (n : Nat) :
    finiteTriangleScaling (n := n) ∅ =
      minimalScaling (Delta[n] : SSet.{u}) := by
  apply scaling_eq_of_le_antisymm
  · intro t ht
    simpa [finiteTriangleScaling] using ht
  · intro t ht
    exact Or.inl ht

/-- Minimal scaling maps into every finite scaling. -/
theorem minimalScaling_le_finiteTriangleScaling
    {n : Nat}
    (F : Finset ((Delta[n] : SSet.{u}).obj (op ⦋2⦌))) :
    ScalingLE
      (minimalScaling (Delta[n] : SSet.{u}))
      (finiteTriangleScaling F) := by
  intro t ht
  exact Or.inl ht

/-- Identity-underlying enrichment from minimal scaling to a finite scaling. -/
def minimalToFiniteTriangleScaling
    {n : Nat}
    (F : Finset ((Delta[n] : SSet.{u}).obj (op ⦋2⦌))) :
    minimallyScaledSimplex n ⟶ scaledSimplex (finiteTriangleScaling F) :=
  scalingEnrichmentHom (minimalScaling_le_finiteTriangleScaling F)

/-- Add one triangle to an already-built finite scaling. -/
def finiteTriangleInsertEnrichment
    {n : Nat}
    (F : Finset ((Delta[n] : SSet.{u}).obj (op ⦋2⦌)))
    (t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌)) :
    scaledSimplex (finiteTriangleScaling F) ⟶
      scaledSimplex (finiteTriangleScaling (insert t F)) :=
  scalingEnrichmentHom (by
    intro u hu
    rcases hu with hu | hu
    · exact Or.inl hu
    · exact Or.inr (Finset.mem_insert_of_mem hu))

/-- Pushing the atomic enrichment for `t` across the identity map into the
finite scaling `F` produces exactly the scaling obtained by inserting `t`. -/
theorem singleTrianglePushoutScaling_eq_finiteInsert
    {n : Nat}
    (F : Finset ((Delta[n] : SSet.{u}).obj (op ⦋2⦌)))
    (t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌)) :
    scalingEnrichmentPushoutScaling
        (singleTriangleScaling t)
        (finiteTriangleScaling F)
        (𝟙 (Delta[n] : SSet.{u})) =
      finiteTriangleScaling (insert t F) := by
  apply scaling_eq_of_le_antisymm
  · intro u hu
    dsimp [scalingEnrichmentPushoutScaling] at hu
    rcases hu with hu | ⟨x, hx, hxu⟩
    · rcases hu with hmin | hF
      · exact Or.inl hmin
      · exact Or.inr (Finset.mem_insert_of_mem hF)
    · have hxu' : x = u := by simpa using hxu
      subst u
      rcases hx with hmin | hxt
      · exact Or.inl hmin
      · subst x
        exact Or.inr (Finset.mem_insert_self t F)
  · intro u hu
    rcases hu with hmin | hmem
    · exact Or.inl (Or.inl hmin)
    · rcases Finset.mem_insert.mp hmem with hut | hF
      · subst u
        exact Or.inr ⟨t, Or.inr rfl, by simp⟩
      · exact Or.inl (Or.inr hF)

/-! ## One atomic step pushes out to every finite stage -/

/-- In any left lifting class, membership of the atomic enrichment implies
membership of its pushout step over a finite scaling. -/
theorem finiteTriangleInsertEnrichment_mem_llp
    (T : MorphismProperty (ScaledSSet.{u}))
    {n : Nat}
    (F : Finset ((Delta[n] : SSet.{u}).obj (op ⦋2⦌)))
    (t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌))
    (ht : T.llp (minimalToSingleTriangleScaling t)) :
    T.llp (finiteTriangleInsertEnrichment F t) := by
  have hpush :
      T.llp
        (scalingEnrichmentPushoutTargetEnrichment
          (singleTriangleScaling t)
          (finiteTriangleScaling F)
          (𝟙 (Delta[n] : SSet.{u}))) := by
    apply scalingEnrichmentPushoutTarget_mem_llp
      T
      (minimalScaling_le_singleTriangleScaling t)
      (finiteTriangleScaling F)
      (𝟙 (Delta[n] : SSet.{u}))
      (minimalScaling_map _ _)
    simpa [minimalToSingleTriangleScaling] using ht
  have hscale := singleTrianglePushoutScaling_eq_finiteInsert F t
  rw [hscale] at hpush
  have heq :
      scalingEnrichmentPushoutTargetEnrichment
          (singleTriangleScaling t)
          (finiteTriangleScaling F)
          (𝟙 (Delta[n] : SSet.{u})) =
        finiteTriangleInsertEnrichment F t := by
    apply ScaledSSet.ScaledMap.ext
    rfl
  rw [← heq]
  exact hpush

/-! ## Finite composition of atomic steps -/

/-- If a left lifting class contains every atomic one-triangle enrichment,
then it contains the enrichment from minimal scaling to every finite scaling. -/
theorem minimalToFiniteTriangleScaling_mem_llp
    (T : MorphismProperty (ScaledSSet.{u}))
    {n : Nat}
    (hatomic :
      ∀ t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌),
        T.llp (minimalToSingleTriangleScaling t))
    (F : Finset ((Delta[n] : SSet.{u}).obj (op ⦋2⦌))) :
    T.llp (minimalToFiniteTriangleScaling F) := by
  classical
  induction F using Finset.induction_on with
  | empty =>
      rw [finiteTriangleScaling_empty]
      have heq :
          minimalToFiniteTriangleScaling (n := n) ∅ =
            𝟙 (minimallyScaledSimplex n) := by
        apply ScaledSSet.ScaledMap.ext
        rfl
      rw [heq]
      exact T.llp.id_mem _
  | @insert t F hnot ih =>
      have hstep : T.llp (finiteTriangleInsertEnrichment F t) :=
        finiteTriangleInsertEnrichment_mem_llp T F t (hatomic t)
      have hcomp :
          T.llp
            (minimalToFiniteTriangleScaling F ≫
              finiteTriangleInsertEnrichment F t) :=
        T.llp.comp_mem _ _ ih hstep
      have heq :
          minimalToFiniteTriangleScaling (insert t F) =
            minimalToFiniteTriangleScaling F ≫
              finiteTriangleInsertEnrichment F t := by
        apply ScaledSSet.ScaledMap.ext
        simp [minimalToFiniteTriangleScaling, finiteTriangleInsertEnrichment,
          scalingEnrichmentHom]
      rw [heq]
      exact hcomp

/-! ## Every chosen scaling is finite in degree two -/

/-- The finite set of all triangles declared thin by a chosen scaling on a
standard simplex. -/
noncomputable def chosenThinTriangles
    {n : Nat}
    (sDelta : ScaledSimplicialSet (Delta[n] : SSet.{u})) :
    Finset ((Delta[n] : SSet.{u}).obj (op ⦋2⦌)) := by
  classical
  letI := Fintype.ofFinite ((Delta[n] : SSet.{u}).obj (op ⦋2⦌))
  exact Finset.univ.filter sDelta.thin

@[simp]
theorem mem_chosenThinTriangles
    {n : Nat}
    (sDelta : ScaledSimplicialSet (Delta[n] : SSet.{u}))
    (t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌)) :
    t ∈ chosenThinTriangles sDelta ↔ sDelta.thin t := by
  classical
  letI := Fintype.ofFinite ((Delta[n] : SSet.{u}).obj (op ⦋2⦌))
  simp [chosenThinTriangles]

/-- Minimal scaling is contained in any scaling on the same carrier. -/
theorem minimalScaling_le_any
    {X : SSet.{u}}
    (sX : ScaledSimplicialSet X) :
    ScalingLE (minimalScaling X) sX := by
  intro t ht
  simpa using (minimalScaling_map sX (𝟙 X)) t ht

/-- The finite scaling generated by all chosen thin triangles is exactly the
chosen scaling. -/
theorem finiteTriangleScaling_chosenThinTriangles_eq
    {n : Nat}
    (sDelta : ScaledSimplicialSet (Delta[n] : SSet.{u})) :
    finiteTriangleScaling (chosenThinTriangles sDelta) = sDelta := by
  apply scaling_eq_of_le_antisymm
  · intro t ht
    rcases ht with hmin | hmem
    · exact minimalScaling_le_any sDelta t hmin
    · exact (mem_chosenThinTriangles sDelta t).1 hmem
  · intro t ht
    exact Or.inr ((mem_chosenThinTriangles sDelta t).2 ht)

/-- Atomic membership in `T.llp` therefore implies membership of every
minimal-to-chosen simplex scaling enrichment. -/
theorem minimalToChosenSimplexScaling_mem_llp_of_singleTriangles
    (T : MorphismProperty (ScaledSSet.{u}))
    {n : Nat}
    (hatomic :
      ∀ t : (Delta[n] : SSet.{u}).obj (op ⦋2⦌),
        T.llp (minimalToSingleTriangleScaling t))
    (sDelta : ScaledSimplicialSet (Delta[n] : SSet.{u})) :
    T.llp (minimalToChosenSimplexScaling sDelta) := by
  have hfinite :=
    minimalToFiniteTriangleScaling_mem_llp
      T hatomic (chosenThinTriangles sDelta)
  have hscale := finiteTriangleScaling_chosenThinTriangles_eq sDelta
  rw [hscale] at hfinite
  have heq :
      minimalToFiniteTriangleScaling (chosenThinTriangles sDelta) =
        minimalToChosenSimplexScaling sDelta := by
    apply ScaledSSet.ScaledMap.ext
    rfl
  rw [← heq]
  exact hfinite

/-! ## Equality of the atomic and arbitrary pure-scaling presentations -/

/-- Every arbitrary pure-scaling enrichment is generated by the atomic
single-triangle family. -/
theorem simplexScalingEnrichments_le_singleTriangleGenerated :
    (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u})) <=
      externalGeneratedScaledAnodyne
        (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u})) := by
  intro X Y f hf
  dsimp [simplexScalingEnrichments] at hf
  cases hf with
  | mk q =>
      change
        (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u})).rlp.llp
          (minimalToChosenSimplexScaling q.simplexScaling)
      apply minimalToChosenSimplexScaling_mem_llp_of_singleTriangles
        ((singleTriangleScalingEnrichments :
          MorphismProperty (ScaledSSet.{u})).rlp)
      intro t
      exact MorphismProperty.le_llp_rlp
        (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u}))
        _ (singleTriangleScalingEnrichment_mem
          { n := q.n, triangle := t })

/-- Conversely every atomic enrichment is generated by the arbitrary family. -/
theorem singleTriangleScalingEnrichments_le_arbitraryGenerated :
    (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u})) <=
      externalGeneratedScaledAnodyne
        (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u})) := by
  exact singleTriangleScalingEnrichments_le_simplexScalingEnrichments.trans
    (MorphismProperty.le_llp_rlp
      (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u})))

/-- The two literal pure-scaling generator families define the same intrinsic
presentation point. -/
theorem singleTriangle_presentation_eq_arbitraryScalingPresentation :
    presentationClass
        (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u})) =
      arbitrarySimplexScalingPresentation := by
  unfold arbitrarySimplexScalingPresentation
  apply
    (presentationClass_eq_iff_mutual_preorder
      (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u}))
      (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u}))).2
  exact
    ⟨singleTriangleScalingEnrichments_le_arbitraryGenerated,
      simplexScalingEnrichments_le_singleTriangleGenerated⟩

/-! ## Atomic criterion for the v1.89 scaling waypoint -/

/-- The entire arbitrary-scaling obstruction closes exactly when every atomic
one-triangle enrichment is standard-generated. -/
theorem standardArbitraryScalingObstructionClosed_iff_singleTriangles :
    StandardArbitraryScalingObstructionClosed.{u} ↔
      (singleTriangleScalingEnrichments : MorphismProperty (ScaledSSet.{u})) <=
        standardGeneratedScaledAnodyneABC := by
  constructor
  · intro hclosed
    have hall :=
      standardArbitraryScalingObstructionClosed_iff_generators_le.1 hclosed
    exact singleTriangleScalingEnrichments_le_simplexScalingEnrichments.trans hall
  · intro hatomic
    apply standardArbitraryScalingObstructionClosed_iff_generators_le.2
    intro X Y f hf
    dsimp [simplexScalingEnrichments] at hf
    cases hf with
    | mk q =>
        change standardGeneratedScaledAnodyneABC
          (minimalToChosenSimplexScaling q.simplexScaling)
        change
          (standardScaledAnodyneGeneratorsABC :
            MorphismProperty (ScaledSSet.{u})).rlp.llp
            (minimalToChosenSimplexScaling q.simplexScaling)
        apply minimalToChosenSimplexScaling_mem_llp_of_singleTriangles
          ((standardScaledAnodyneGeneratorsABC :
            MorphismProperty (ScaledSSet.{u})).rlp)
        intro t
        exact hatomic _
          (singleTriangleScalingEnrichment_mem
            { n := q.n, triangle := t })

/-- A single atomic enrichment outside the standard generated class is enough
to keep the scaling waypoint open. -/
theorem not_standardArbitraryScalingObstructionClosed_of_singleTriangle_not_mem
    (q : SingleTriangleScalingEnrichmentIndex.{u})
    (hnot :
      ¬ standardGeneratedScaledAnodyneABC
        (singleTriangleScalingEnrichmentHom q)) :
    ¬ StandardArbitraryScalingObstructionClosed.{u} := by
  intro hclosed
  have hall :=
    standardArbitraryScalingObstructionClosed_iff_singleTriangles.1 hclosed
  exact hnot (hall _ (singleTriangleScalingEnrichment_mem q))

/-- Consequently one atomic witness also prevents closure of the full
standard/canonical presentation gap. -/
theorem not_standardCanonicalPresentationGapClosed_of_singleTriangle_not_mem
    (q : SingleTriangleScalingEnrichmentIndex.{u})
    (hnot :
      ¬ standardGeneratedScaledAnodyneABC
        (singleTriangleScalingEnrichmentHom q)) :
    ¬ StandardCanonicalPresentationGapClosed.{u} := by
  intro hgap
  exact
    not_standardArbitraryScalingObstructionClosed_of_singleTriangle_not_mem
      q hnot
      (standardArbitraryScalingObstructionClosed_of_gapClosed hgap)

/-!
The scaling frontier is now atomic:

```text
all arbitrary simplex scalings
  = finite composites of pushouts of
    minimal -> minimal + one thin triangle.
```

At the intrinsic presentation level,

```text
presentation(single-triangle enrichments)
  = arbitrarySimplexScalingPresentation.
```

Therefore the middle condition in the v1.89 three-piece gap criterion can be
settled by studying only one-triangle scaling maps.  A positive proof needs a
uniform standard-generation theorem for those atomic maps; a negative result
needs only one atomic witness outside the standard generated class.
-/

end KUOS.DependentOriginationSingleTriangleScalingFiltrationV1_90
