import Mathlib.CategoryTheory.Discrete.Basic
import KUOS.DependentOriginationWeakCoherentTwoAxisObstructionV2_42
import KUOS.DependentOriginationStoredTriangleModificationNaturalityV2_23

namespace KUOS.DependentOriginationDiscreteBaseObstructionEliminationV2_43

open CategoryTheory
open KUOS.DependentOriginationHigherLocalizationInterfaceV2_10
open KUOS.DependentOriginationWeakHigherLocalizationUniversalPropertyV2_18
open KUOS.DependentOriginationCoherentWeakHigherLocalizationV2_19
open KUOS.DependentOriginationFactorCoherenceLiftingV2_21
open KUOS.DependentOriginationModificationTriangleNormalFormV2_22
open KUOS.DependentOriginationStoredTriangleModificationNaturalityV2_23
open KUOS.DependentOriginationStoredTriangleCorrectionV2_26
open KUOS.DependentOriginationStageIIIRouteCompletenessV2_33
open KUOS.DependentOriginationWeakCoherentTwoAxisObstructionV2_42

universe u uH vH

/-!
# Discrete-base elimination of the weak/coherent obstruction v2.43

The v2.42 layer isolates two genuine failure axes for an already supplied
coherent weak higher-localization datum `U`:

* Axis E: no v2.18 weak universal property exists;
* Axis R: a v2.18 weak universal property exists, but the fixed coherent route
  fails.

This file gives a first non-vacuous structural class on which both axes disappear.
When the raw context is a Mathlib discrete category `Discrete I`, every context
arrow is definitionally generated by equality.  Hence the objectwise comparison
triangle already stored in every v2.18 factor morphism is automatically
modification-natural: after reducing the unique arrow to an identity, the
required equation is exactly the standard StrongTrans identity coherence law.

Therefore no correction equation is needed on a discrete base:

```text
Context = Discrete I
  -> stored v2.18 triangle is modification-natural
  -> factor modification-triangle lifting
  -> factor-coherence lifting
  -> weak universality on the coherent chosen carrier
  -> route completeness
  -> no local E/R obstruction.
```

This is a genuine obstruction-killing theorem, not a renaming of a completion
principle.  It is intentionally a sufficient subclass, not a claim that an
arbitrary context is discrete.  Coherent universal-data existence itself remains
an explicit premise at the global level.
-/

variable {I : Type u}
variable (W : MorphismProperty (Discrete I))

/-- On a discrete context, the objectwise v2.18 comparison triangle is already
modification-natural.  The only possible base arrow reduces to an identity, and
Mathlib's StrongTrans identity coherence discharges the resulting equation. -/
theorem storedV2_18TriangleIsModificationNatural_of_discrete
    {R : RawHigherContextualSystem
      (Context := Discrete I) (uH := uH) (vH := vH)}
    {H K : HigherLocalizationFactorization (W := W) R}
    (alpha : HigherLocalizationFactorMorphism (W := W) H K) :
    StoredV2_18TriangleIsModificationNatural (W := W) alpha := by
  intro X Y f
  rcases X with ⟨x⟩
  rcases Y with ⟨y⟩
  rcases f with ⟨⟨h⟩⟩
  cases h
  simp

/-- Uniformly, every weak factor into the chosen coherent carrier has a stored
triangle that is already modification-natural. -/
theorem higherStoredV2_18TriangleModificationNaturality_of_discrete
    {R : RawHigherContextualSystem
      (Context := Discrete I) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R) :
    HigherStoredV2_18TriangleModificationNaturality (W := W) U := by
  intro H alpha
  exact storedV2_18TriangleIsModificationNatural_of_discrete (W := W) alpha

/-- Hence factor-coherence lifting is automatic for coherent universal data on a
discrete base. -/
theorem higherFactorCoherenceLifting_of_discrete
    {R : RawHigherContextualSystem
      (Context := Discrete I) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R) :
    HigherFactorCoherenceLifting (W := W) U :=
  higherFactorCoherenceLifting_of_storedTriangleNaturality
    W U (higherStoredV2_18TriangleModificationNaturality_of_discrete (W := W) U)

/-- A coherent universal datum on a discrete base therefore already determines a
full v2.18 weak universal property on the same chosen factorization. -/
theorem hasWeakHigherLocalizationUniversalProperty_of_discrete_coherent
    {R : RawHigherContextualSystem
      (Context := Discrete I) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R) :
    HasWeakHigherLocalizationUniversalProperty (W := W) R := by
  exact ⟨weakHigherLocalizationUniversalPropertyOfCoherent
    W U (higherFactorCoherenceLifting_of_discrete (W := W) U)⟩

/-- The same discrete-base coherence gives correction lifting independently of
which weak universal-property witness is supplied, so the fixed coherent route
is complete. -/
theorem higherCoherentRouteCompleteness_of_discrete
    {R : RawHigherContextualSystem
      (Context := Discrete I) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R) :
    HigherCoherentRouteCompleteness (W := W) U := by
  intro _hUniversal
  apply
    (higherStoredTriangleCorrectionLifting_iff_modificationTriangleLifting
      (W := W) U).mpr
  exact
    higherFactorModificationTriangleLifting_of_storedTriangleNaturality
      W U (higherStoredV2_18TriangleModificationNaturality_of_discrete (W := W) U)

/-- Local discrete-base obstruction elimination: a coherent datum is aligned, so
neither Axis E nor Axis R can occur. -/
theorem higherWeakCoherentAlignment_of_discrete
    {R : RawHigherContextualSystem
      (Context := Discrete I) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R) :
    HigherWeakCoherentAlignment (W := W) U :=
  ⟨hasWeakHigherLocalizationUniversalProperty_of_discrete_coherent (W := W) U,
    higherCoherentRouteCompleteness_of_discrete (W := W) U⟩

/-- Equivalently, the exact local v2.42 two-axis obstruction is absent on every
discrete base carrying coherent universal data. -/
theorem no_twoAxisObstruction_of_discrete
    {R : RawHigherContextualSystem
      (Context := Discrete I) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R) :
    ¬ HigherWeakCoherentTwoAxisObstruction (W := W) U :=
  (higherWeakCoherentAlignment_iff_no_twoAxisObstruction
    (W := W) U).mp (higherWeakCoherentAlignment_of_discrete (W := W) U)

/-- Global structural consequence.  On a discrete base, coherent universal-data
existence is the only remaining premise: once coherent data exist for every
admissible raw system, both the weak universal principle and coherent route
completeness follow automatically. -/
theorem universal_and_route_of_discrete_coherentPrinciple
    (hCoherent : CoherentHigherWeakLocalizationUniversalPrinciple
      (W := W) (uH := uH) (vH := vH)) :
    HigherWeakLocalizationUniversalPrinciple
        (W := W) (uH := uH) (vH := vH) ∧
      HigherCoherentRouteCompletenessPrinciple
        (W := W) (uH := uH) (vH := vH) := by
  apply
    (higherWeakCoherentAlignmentPrinciple_iff_universal_and_route_of_coherent
      (W := W) hCoherent).mp
  intro R U
  exact higherWeakCoherentAlignment_of_discrete (W := W) U

end KUOS.DependentOriginationDiscreteBaseObstructionEliminationV2_43
