import KUOS.DependentOriginationStandardTypeAScaledLeibnizPushoutV1_55
import Mathlib.CategoryTheory.LiftingProperties.Limits

namespace KUOS.DependentOriginationStandardTypeBScalingPushoutV1_56

open CategoryTheory
open CategoryTheory.Category
open CategoryTheory.Limits
open Opposite
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationGlobalDuskinScaledHornCoherenceV1_22
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
open KUOS.DependentOriginationStandardTypeAScaledLeibnizPushoutV1_55

universe u

/-!
# Standard type-(B) scaling pushouts v1.56

Version 1.55 identifies the standard type-(A) endpoint construction with an
actual Leibniz pushout in `ScaledSSet`.  The remaining endpoint stability is a
substantive scaled-anodyne statement: it is not a formal consequence of weak
saturation of type-(A) horns alone.

The next standard generator which enters the scaled-anodyne calculus is the
four-simplex scaling enrichment usually called type-(B).  This file introduces
that generator literally, but first proves a reusable categorical theorem for
all identity-underlying scaling enrichments.

Suppose two scalings `sX <= sX'` live on the same simplicial set `X`, and a map
`f : X -> Y` is scaled from `sX` to a scaling `sY`.  Put on `Y` the least
scaling containing `sY` and the images under `f` of all `sX'`-thin triangles.
Then the square

```text
(X,sX)  --f-->  (Y,sY)
   |                |
   | id             | id
   v                v
(X,sX') --f-->  (Y,pushforward scaling)
```

is an actual pushout in `ScaledSSet`.

This is exactly the categorical operation needed for scaling-only generators:
a pushout of a scaling enrichment is again an identity-underlying scaling
enrichment, with the target scaling generated by the old target thin triangles
and the images of the newly thin source triangles.

We then instantiate this theorem for the standard type-(B) map on `Delta[4]`.
The source scaling contains the five nondegenerate triangles

`024, 123, 013, 134, 012`,

in addition to all degeneracies, and the target also contains `014` and `034`.
Finally we prove directly from Mathlib lifting properties that every class of
the form `T.llp`, in particular every external generated class `E.rlp.llp`,
contains every such pushout once it contains the type-(B) generator itself.

No type-(C) generator and no full pushout-product theorem is asserted here.
The purpose is to make the scaling-enrichment part of the standard presentation
available to the same native orthogonality machinery already used by KuuOS.
-/

/-! ## Generic pushout of an identity-underlying scaling enrichment -/

/-- The least scaling on `Y` generated by an existing scaling `sY` together
with the images under `f` of the triangles thin for the enlarged source
scaling `sX'`. -/
def scalingEnrichmentPushoutScaling
    {X Y : SSet.{u}}
    (sX' : ScaledSimplicialSet X)
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y) : ScaledSimplicialSet Y where
  thin := fun t =>
    sY.thin t ∨
      ∃ x : X.obj (op ⦋2⦌),
        sX'.thin x ∧ f.app (op ⦋2⦌) x = t
  thin_sigma_zero := by
    intro x
    exact Or.inl (sY.thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl (sY.thin_sigma_one x)

/-- Identity-underlying morphism attached to an inclusion of scalings on a
fixed simplicial carrier. -/
def scalingEnrichmentHom
    {X : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (h : ScalingLE sX sX') :
    ScaledSSet.of X sX ⟶ ScaledSSet.of X sX' where
  map := 𝟙 X
  scaled := by
    intro t ht
    change sX'.thin t
    exact h t ht

/-- The original lower map in the scaling-enrichment pushout square. -/
def scalingEnrichmentPushoutLowerMap
    {X Y : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {sY : ScaledSimplicialSet Y}
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f) :
    ScaledSSet.of X sX ⟶ ScaledSSet.of Y sY where
  map := f
  scaled := hf

/-- The upper-source map into the target equipped with the generated pushout
scaling. -/
def scalingEnrichmentPushoutUpperMap
    {X Y : SSet.{u}}
    (sX' : ScaledSimplicialSet X)
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y) :
    ScaledSSet.of X sX' ⟶
      ScaledSSet.of Y (scalingEnrichmentPushoutScaling sX' sY f) where
  map := f
  scaled := by
    intro t ht
    exact Or.inr ⟨t, ht, rfl⟩

/-- The induced identity-underlying scaling enrichment on the target of a
pushout. -/
def scalingEnrichmentPushoutTargetEnrichment
    {X Y : SSet.{u}}
    (sX' : ScaledSimplicialSet X)
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y) :
    ScaledSSet.of Y sY ⟶
      ScaledSSet.of Y (scalingEnrichmentPushoutScaling sX' sY f) where
  map := 𝟙 Y
  scaled := by
    intro t ht
    change (scalingEnrichmentPushoutScaling sX' sY f).thin t
    exact Or.inl ht

/-- The generic scaling-enrichment pushout square commutes. -/
theorem scalingEnrichmentPushout_commutes
    {X Y : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (hXX' : ScalingLE sX sX')
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f) :
    scalingEnrichmentPushoutLowerMap f hf ≫
        scalingEnrichmentPushoutTargetEnrichment sX' sY f =
      scalingEnrichmentHom hXX' ≫
        scalingEnrichmentPushoutUpperMap sX' sY f := by
  apply ScaledSSet.ScaledMap.ext
  change f ≫ 𝟙 Y = 𝟙 X ≫ f
  simp

/-- Compatibility in a scaled cocone gives the underlying simplicial equation
used to prove scaledness of the universal desc map. -/
theorem scalingEnrichmentPushout_compatibility_map
    {X Y : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (hXX' : ScalingLE sX sX')
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f)
    {W : ScaledSSet.{u}}
    (b : ScaledSSet.of Y sY ⟶ W)
    (a : ScaledSSet.of X sX' ⟶ W)
    (w : scalingEnrichmentPushoutLowerMap f hf ≫ b =
      scalingEnrichmentHom hXX' ≫ a) :
    f ≫ b.map = a.map := by
  have hw := congrArg ScaledSSet.ScaledMap.map w
  change f ≫ b.map = (𝟙 X) ≫ a.map at hw
  simpa using hw

/-- The universal desc map for the generated target scaling.  Its underlying
simplicial map is the map already prescribed on the old target `Y`. -/
noncomputable def scalingEnrichmentPushoutDesc
    {X Y : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (hXX' : ScalingLE sX sX')
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f)
    {W : ScaledSSet.{u}}
    (b : ScaledSSet.of Y sY ⟶ W)
    (a : ScaledSSet.of X sX' ⟶ W)
    (w : scalingEnrichmentPushoutLowerMap f hf ≫ b =
      scalingEnrichmentHom hXX' ≫ a) :
    ScaledSSet.of Y (scalingEnrichmentPushoutScaling sX' sY f) ⟶ W where
  map := b.map
  scaled := by
    intro t ht
    dsimp [scalingEnrichmentPushoutScaling] at ht
    rcases ht with ht | ⟨x, hx, rfl⟩
    · exact b.scaled t ht
    · have hmap := scalingEnrichmentPushout_compatibility_map
        hXX' sY f hf b a w
      change W.scaling.thin (((f ≫ b.map).app (op ⦋2⦌)) x)
      rw [hmap]
      exact a.scaled x hx

@[simp, reassoc]
theorem scalingEnrichmentPushout_target_desc
    {X Y : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (hXX' : ScalingLE sX sX')
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f)
    {W : ScaledSSet.{u}}
    (b : ScaledSSet.of Y sY ⟶ W)
    (a : ScaledSSet.of X sX' ⟶ W)
    (w : scalingEnrichmentPushoutLowerMap f hf ≫ b =
      scalingEnrichmentHom hXX' ≫ a) :
    scalingEnrichmentPushoutTargetEnrichment sX' sY f ≫
        scalingEnrichmentPushoutDesc hXX' sY f hf b a w = b := by
  apply ScaledSSet.ScaledMap.ext
  change (𝟙 Y) ≫ b.map = b.map
  simp

@[simp, reassoc]
theorem scalingEnrichmentPushout_upper_desc
    {X Y : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (hXX' : ScalingLE sX sX')
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f)
    {W : ScaledSSet.{u}}
    (b : ScaledSSet.of Y sY ⟶ W)
    (a : ScaledSSet.of X sX' ⟶ W)
    (w : scalingEnrichmentPushoutLowerMap f hf ≫ b =
      scalingEnrichmentHom hXX' ≫ a) :
    scalingEnrichmentPushoutUpperMap sX' sY f ≫
        scalingEnrichmentPushoutDesc hXX' sY f hf b a w = a := by
  apply ScaledSSet.ScaledMap.ext
  change f ≫ b.map = a.map
  exact scalingEnrichmentPushout_compatibility_map
    hXX' sY f hf b a w

/-- Uniqueness of the desc map follows already from the identity-underlying
target enrichment leg. -/
theorem scalingEnrichmentPushout_hom_ext
    {X Y : SSet.{u}}
    (sX' : ScaledSimplicialSet X)
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    {W : ScaledSSet.{u}}
    {k l : ScaledSSet.of Y
      (scalingEnrichmentPushoutScaling sX' sY f) ⟶ W}
    (h : scalingEnrichmentPushoutTargetEnrichment sX' sY f ≫ k =
      scalingEnrichmentPushoutTargetEnrichment sX' sY f ≫ l) :
    k = l := by
  apply ScaledSSet.ScaledMap.ext
  have hm := congrArg ScaledSSet.ScaledMap.map h
  simpa only [ScaledSSet.comp_map,
    scalingEnrichmentPushoutTargetEnrichment, ScaledSSet.of,
    Category.id_comp] using hm

/-- Pushout theorem for an arbitrary identity-underlying scaling enrichment. -/
noncomputable def scalingEnrichmentPushout_isPushout
    {X Y : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (hXX' : ScalingLE sX sX')
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f) :
    IsPushout
      (scalingEnrichmentPushoutLowerMap f hf)
      (scalingEnrichmentHom hXX')
      (scalingEnrichmentPushoutTargetEnrichment sX' sY f)
      (scalingEnrichmentPushoutUpperMap sX' sY f) := by
  refine {
    w := scalingEnrichmentPushout_commutes hXX' sY f hf
    isColimit' := ⟨?_⟩
  }
  exact PushoutCocone.IsColimit.mk
    (scalingEnrichmentPushout_commutes hXX' sY f hf)
    (fun s => scalingEnrichmentPushoutDesc
      hXX' sY f hf s.inl s.inr s.condition)
    (fun s => scalingEnrichmentPushout_target_desc
      hXX' sY f hf s.inl s.inr s.condition)
    (fun s => scalingEnrichmentPushout_upper_desc
      hXX' sY f hf s.inl s.inr s.condition)
    (by
      intro s m hm₁ hm₂
      apply scalingEnrichmentPushout_hom_ext sX' sY f
      rw [hm₁, scalingEnrichmentPushout_target_desc])

/-- Left lifting properties descend through this pushout square: if the source
scaling enrichment lifts against `p`, then so does its pushed-out target
scaling enrichment. -/
theorem scalingEnrichmentPushoutTarget_hasLiftingProperty
    {X Y : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (hXX' : ScalingLE sX sX')
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f)
    {P Q : ScaledSSet.{u}}
    (p : P ⟶ Q)
    (h : HasLiftingProperty (scalingEnrichmentHom hXX') p) :
    HasLiftingProperty
      (scalingEnrichmentPushoutTargetEnrichment sX' sY f) p := by
  letI : HasLiftingProperty (scalingEnrichmentHom hXX') p := h
  exact (scalingEnrichmentPushout_isPushout hXX' sY f hf).hasLiftingProperty p

/-- Consequently every left orthogonal class `T.llp` is closed under these
explicit scaling-enrichment pushouts. -/
theorem scalingEnrichmentPushoutTarget_mem_llp
    (T : MorphismProperty (ScaledSSet.{u}))
    {X Y : SSet.{u}}
    {sX sX' : ScaledSimplicialSet X}
    (hXX' : ScalingLE sX sX')
    (sY : ScaledSimplicialSet Y)
    (f : X ⟶ Y)
    (hf : IsScaledMap sX sY f)
    (h : T.llp (scalingEnrichmentHom hXX')) :
    T.llp (scalingEnrichmentPushoutTargetEnrichment sX' sY f) := by
  intro P Q p hp
  exact scalingEnrichmentPushoutTarget_hasLiftingProperty
    hXX' sY f hf p (h p hp)

/-! ## The literal standard type-(B) four-simplex generator -/

/-- A triangle of a standard simplex has the specified ordered vertices. -/
def IsStandardVertexTriangle
    {n : Nat}
    (a b c : Fin (n + 1))
    (t : (Δ[n] : SSet.{u}).obj (op ⦋2⦌)) : Prop :=
  t 0 = a ∧ t 1 = b ∧ t 2 = c

/-- The five additional nondegenerate thin triangles in the source of the
standard type-(B) generator. -/
def IsStandardTypeBSourceTriangle
    (t : (Δ[4] : SSet.{u}).obj (op ⦋2⦌)) : Prop :=
  IsStandardVertexTriangle (0 : Fin 5) 2 4 t ∨
  IsStandardVertexTriangle (1 : Fin 5) 2 3 t ∨
  IsStandardVertexTriangle (0 : Fin 5) 1 3 t ∨
  IsStandardVertexTriangle (1 : Fin 5) 3 4 t ∨
  IsStandardVertexTriangle (0 : Fin 5) 1 2 t

/-- Source scaling `T` of the standard type-(B) generator. -/
def standardTypeBSourceScaling :
    ScaledSimplicialSet (Δ[4] : SSet.{u}) where
  thin := fun t =>
    (minimalScaling (Δ[4] : SSet.{u})).thin t ∨
      IsStandardTypeBSourceTriangle t
  thin_sigma_zero := by
    intro x
    exact Or.inl ((minimalScaling (Δ[4] : SSet.{u})).thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl ((minimalScaling (Δ[4] : SSet.{u})).thin_sigma_one x)

/-- Target scaling of the standard type-(B) generator: in addition to the
source scaling, the triangles `014` and `034` are thin. -/
def standardTypeBTargetScaling :
    ScaledSimplicialSet (Δ[4] : SSet.{u}) where
  thin := fun t =>
    (standardTypeBSourceScaling :
      ScaledSimplicialSet (Δ[4] : SSet.{u})).thin t ∨
    IsStandardVertexTriangle (0 : Fin 5) 1 4 t ∨
    IsStandardVertexTriangle (0 : Fin 5) 3 4 t
  thin_sigma_zero := by
    intro x
    exact Or.inl (standardTypeBSourceScaling.thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl (standardTypeBSourceScaling.thin_sigma_one x)

/-- The source scaling is contained in the target scaling. -/
theorem standardTypeBSourceScaling_le_target :
    ScalingLE
      (standardTypeBSourceScaling :
        ScaledSimplicialSet (Δ[4] : SSet.{u}))
      standardTypeBTargetScaling := by
  intro t ht
  exact Or.inl ht

/-- Source object of the standard type-(B) generator. -/
def standardTypeBSource : ScaledSSet.{u} :=
  ScaledSSet.of (Δ[4] : SSet.{u}) standardTypeBSourceScaling

/-- Target object of the standard type-(B) generator. -/
def standardTypeBTarget : ScaledSSet.{u} :=
  ScaledSSet.of (Δ[4] : SSet.{u}) standardTypeBTargetScaling

/-- The standard type-(B) generator is the identity simplicial map which adds
exactly the two thin triangles `014` and `034` to the source scaling. -/
def standardTypeBGeneratorHom :
    standardTypeBSource ⟶ standardTypeBTarget :=
  scalingEnrichmentHom standardTypeBSourceScaling_le_target

@[simp]
theorem standardTypeBGeneratorHom_map :
    standardTypeBGeneratorHom.map = 𝟙 (Δ[4] : SSet.{u}) :=
  rfl

/-- The type-(B) generator as a morphism property. -/
def standardTypeBScaledAnodyneGenerators :
    MorphismProperty (ScaledSSet.{u}) :=
  MorphismProperty.ofHoms (fun _ : Unit => standardTypeBGeneratorHom)

/-- The standard type-(B) map belongs to its generator property. -/
theorem standardTypeBGenerator_mem :
    (standardTypeBScaledAnodyneGenerators : MorphismProperty (ScaledSSet.{u}))
      standardTypeBGeneratorHom :=
  MorphismProperty.ofHoms.mk ()

/-- The first newly thin type-(B) triangle `014` is thin in the target. -/
theorem standardTypeB_triangle_014_thin
    (t : (Δ[4] : SSet.{u}).obj (op ⦋2⦌))
    (ht : IsStandardVertexTriangle (0 : Fin 5) 1 4 t) :
    standardTypeBTargetScaling.thin t := by
  exact Or.inr (Or.inl ht)

/-- The second newly thin type-(B) triangle `034` is thin in the target. -/
theorem standardTypeB_triangle_034_thin
    (t : (Δ[4] : SSet.{u}).obj (op ⦋2⦌))
    (ht : IsStandardVertexTriangle (0 : Fin 5) 3 4 t) :
    standardTypeBTargetScaling.thin t := by
  exact Or.inr (Or.inr ht)

/-! ## Pushouts of the type-(B) generator and orthogonal closure -/

/-- The scaling produced on an arbitrary target by pushing out the standard
type-(B) generator along a scaled map from its source. -/
def standardTypeBPushoutScaling
    {Y : SSet.{u}}
    (sY : ScaledSimplicialSet Y)
    (f : (Δ[4] : SSet.{u}) ⟶ Y) :
    ScaledSimplicialSet Y :=
  scalingEnrichmentPushoutScaling standardTypeBTargetScaling sY f

/-- The pushed-out target enrichment associated to a type-(B) source map. -/
def standardTypeBPushoutEnrichment
    {Y : SSet.{u}}
    (sY : ScaledSimplicialSet Y)
    (f : (Δ[4] : SSet.{u}) ⟶ Y) :
    ScaledSSet.of Y sY ⟶
      ScaledSSet.of Y (standardTypeBPushoutScaling sY f) :=
  scalingEnrichmentPushoutTargetEnrichment
    standardTypeBTargetScaling sY f

/-- The standard type-(B) pushout is an actual categorical pushout in
`ScaledSSet`. -/
noncomputable def standardTypeBPushout_isPushout
    {Y : SSet.{u}}
    (sY : ScaledSimplicialSet Y)
    (f : (Δ[4] : SSet.{u}) ⟶ Y)
    (hf : IsScaledMap standardTypeBSourceScaling sY f) :
    IsPushout
      (scalingEnrichmentPushoutLowerMap f hf)
      standardTypeBGeneratorHom
      (standardTypeBPushoutEnrichment sY f)
      (scalingEnrichmentPushoutUpperMap
        standardTypeBTargetScaling sY f) := by
  exact scalingEnrichmentPushout_isPushout
    standardTypeBSourceScaling_le_target sY f hf

/-- Any left orthogonal class containing the type-(B) generator also contains
all of its explicit scaling pushouts. -/
theorem standardTypeBPushoutEnrichment_mem_llp
    (T : MorphismProperty (ScaledSSet.{u}))
    {Y : SSet.{u}}
    (sY : ScaledSimplicialSet Y)
    (f : (Δ[4] : SSet.{u}) ⟶ Y)
    (hf : IsScaledMap standardTypeBSourceScaling sY f)
    (hB : T.llp standardTypeBGeneratorHom) :
    T.llp (standardTypeBPushoutEnrichment sY f) := by
  exact scalingEnrichmentPushoutTarget_mem_llp
    T standardTypeBSourceScaling_le_target sY f hf hB

/-- In particular an external generated class `E.rlp.llp` is closed under all
standard type-(B) scaling pushouts once it contains the type-(B) generator. -/
theorem standardTypeBPushoutEnrichment_mem_externalGenerated
    {E : MorphismProperty (ScaledSSet.{u})}
    {Y : SSet.{u}}
    (sY : ScaledSimplicialSet Y)
    (f : (Δ[4] : SSet.{u}) ⟶ Y)
    (hf : IsScaledMap standardTypeBSourceScaling sY f)
    (hB : externalGeneratedScaledAnodyne E standardTypeBGeneratorHom) :
    externalGeneratedScaledAnodyne E
      (standardTypeBPushoutEnrichment sY f) := by
  change E.rlp.llp standardTypeBGeneratorHom at hB
  change E.rlp.llp (standardTypeBPushoutEnrichment sY f)
  exact standardTypeBPushoutEnrichment_mem_llp
    E.rlp sY f hf hB

/-!
The standard comparison spine now has a native scaling-only cell operation:

```text
source scaling <= enlarged source scaling
  -> generated target scaling
  -> actual ScaledSSet pushout
  -> LLP preservation by IsPushout.hasLiftingProperty
  -> standard type-(B) Delta[4] generator
  -> all type-(B) scaling pushouts lie in E.rlp.llp once type-(B) itself does.
```

This is the mechanism needed for the exceptional scaling-completion steps in
the scaled pushout-product theorem and, separately, for analysing the residual
identity-underlying scaling enrichments isolated in v1.48.

The next unit can add the two explicit `Delta[4] -> Delta[3]` collapse maps of
the standard type-(B) argument and identify their pushouts with the corresponding
three-simplex thin-triangle completions before integrating type-(C).
-/

end KUOS.DependentOriginationStandardTypeBScalingPushoutV1_56
