import KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49

namespace KUOS.DependentOriginationStandardTypeAEndpointPushoutProductV1_50

open CategoryTheory
open CategoryTheory.Category
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationGlobalDuskinScaledHornCoherenceV1_22
open KUOS.DependentOriginationScaledHornAttachmentLiftingV1_40
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationScaledAnodyneGeneratorClosureV1_42
open KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
open KUOS.DependentOriginationScaledAnodyneAttachmentFactorizationV1_48
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49

universe u

/-!
# Standard type-(A) endpoint pushout-product geometry v1.50

Version 1.49 cut the standard type-(A) inner horns out of the arbitrary-scaling
KuuOS horn carrier and restricted the induced horn-cylinder attachment family to
those indexes.  This file identifies the ordinary geometry of that restricted
family exactly.

For the standard type-(A) scaled horn inclusion

```text
(Λ_i^n, T|_{Λ_i^n}) --> (Δ^n, T),
```

and an endpoint inclusion `{ε} --> Δ[1]`, the pushout-product source is

```text
(Δ[n] × {ε}) ∪ (Λ_i^n × Δ[1]).
```

This is literally the `Subcomplex.unionProd` object already constructed in
v1.40.  The scaling used by the v1.48 induced attachment is the pullback of the
cylinder scaling along the resulting union inclusion.  Therefore the
v1.49 restricted induced generators are exactly the scaled endpoint
pushout-product family.

The final section separates geometry from the remaining model-structure input.
For an external generator family `E`, it is enough that

1. its generated left class contains the standard type-(A) horn generators;
2. that left class is stable under these endpoint pushout-products.

Under precisely those two assumptions we prove

`T_induced^(A) ≤ E.rlp.llp`.

No stability theorem for a full Lurie scaled-anodyne class is asserted here;
that is now an isolated subsequent target rather than being hidden inside the
geometric identification.
-/

/-! ## Standard type-(A) horn generators as scaled morphisms -/

/-- Index of one standard type-(A) inner horn inclusion. -/
structure StandardTypeAHornGeneratorIndex where
  n : Nat
  i : Fin (n + 1)
  inner_left : 0 < i
  inner_right : i < Fin.last n

/-- The type-(A) scaled horn object. -/
def standardTypeAScaledHorn
    (g : StandardTypeAHornGeneratorIndex) : ScaledSSet.{u} :=
  ScaledSSet.of (Λ[g.n, g.i] : SSet.{u})
    (standardTypeAHornScaling g.i)

/-- The type-(A) scaled simplex object. -/
def standardTypeAScaledSimplex
    (g : StandardTypeAHornGeneratorIndex) : ScaledSSet.{u} :=
  scaledSimplex (standardTypeASimplexScaling g.i)

/-- The standard type-(A) inner horn inclusion as a morphism of scaled
simplicial sets. -/
def standardTypeAScaledHornGeneratorHom
    (g : StandardTypeAHornGeneratorIndex) :
    standardTypeAScaledHorn g ⟶ standardTypeAScaledSimplex g where
  map := Λ[g.n, g.i].ι
  scaled := standardTypeAHornInclusion_scaled g.i

/-- The morphism property generated by the standard type-(A) inner horn
inclusions themselves, before taking any weak/orthogonal saturation. -/
def standardTypeAScaledHornGenerators :
    MorphismProperty (ScaledSSet.{u}) :=
  MorphismProperty.ofHoms
    (fun g : StandardTypeAHornGeneratorIndex =>
      standardTypeAScaledHornGeneratorHom g)

/-- Every type-(A) horn inclusion lies in the type-(A) generator property. -/
theorem standardTypeAScaledHornGenerator_mem
    (g : StandardTypeAHornGeneratorIndex) :
    (standardTypeAScaledHornGenerators : MorphismProperty (ScaledSSet.{u}))
      (standardTypeAScaledHornGeneratorHom g) :=
  MorphismProperty.ofHoms.mk g

/-! ## Endpoint pushout-product indexes and the v1.40 pushout -/

/-- Forget the endpoint from a type-(A) attachment index. -/
def StandardTypeAHornAttachmentGeneratorIndex.toHornGenerator
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    StandardTypeAHornGeneratorIndex where
  n := g.n
  i := g.i
  inner_left := g.inner_left
  inner_right := g.inner_right

/-- The unscaled pushout square whose pushout object is the endpoint
pushout-product domain

`(Δ[n] × {ε}) ∪ (Λ_i^n × Δ[1])`.

This is exactly Mathlib's `Subcomplex.unionProd.isPushout`. -/
noncomputable def standardTypeAEndpointPushoutSquare
    (g : StandardTypeAHornAttachmentGeneratorIndex) :=
  SSet.Subcomplex.unionProd.isPushout
    (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)

/-- The endpoint pushout-product source subcomplex is literally the v1.40
horn-cylinder attachment. -/
theorem standardTypeAEndpointPushoutDomain_eq_hornCylinderAttachment
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (SSet.horn g.n g.i).unionProd (intervalEndpoint g.endpoint) =
      hornCylinderAttachment g.n g.i g.endpoint := by
  rfl

/-- The scaling on the endpoint pushout-product source is the scaling induced
from the standard type-(A) cylinder along the union inclusion. -/
def standardTypeAEndpointPushoutProductSource
    (g : StandardTypeAHornAttachmentGeneratorIndex) : ScaledSSet.{u} :=
  ScaledSSet.of
    ((SSet.horn g.n g.i).unionProd (intervalEndpoint g.endpoint) : SSet.{u})
    (pullbackScaling
      (simplexCylinderScaling (standardTypeASimplexScaling g.i))
      ((SSet.horn g.n g.i).unionProd (intervalEndpoint g.endpoint)).ι)

/-- The standard type-(A) endpoint pushout-product inclusion with induced
source scaling. -/
def standardTypeAEndpointPushoutProductHom
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointPushoutProductSource g ⟶
      scaledSimplexCylinder (standardTypeASimplexScaling g.i) where
  map := ((SSet.horn g.n g.i).unionProd (intervalEndpoint g.endpoint)).ι
  scaled := pullbackScaling_map _ _

/-- The explicitly pushout-product source is definitionally the same scaled
object as the v1.48 induced attachment specialized in v1.49. -/
theorem standardTypeAEndpointPushoutProductSource_eq_induced
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointPushoutProductSource g =
      inducedScaledHornCylinderAttachment
        g.i g.endpoint (standardTypeASimplexScaling g.i) := by
  rfl

/-- Consequently the endpoint pushout-product morphism is exactly the v1.49
restricted induced attachment generator. -/
theorem standardTypeAEndpointPushoutProductHom_eq_induced
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointPushoutProductHom g =
      standardTypeAInducedScaledHornAttachmentGeneratorHom g := by
  rfl

/-! ## The endpoint pushout-product generator family -/

/-- Standard type-(A) endpoint pushout-products at both interval endpoints. -/
def standardTypeAEndpointPushoutProductGenerators :
    MorphismProperty (ScaledSSet.{u}) :=
  MorphismProperty.ofHoms
    (fun g : StandardTypeAHornAttachmentGeneratorIndex =>
      standardTypeAEndpointPushoutProductHom g)

/-- Every endpoint pushout-product lies in its generator property. -/
theorem standardTypeAEndpointPushoutProductGenerator_mem
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u}))
      (standardTypeAEndpointPushoutProductHom g) :=
  MorphismProperty.ofHoms.mk g

/-- The geometric endpoint pushout-product family is exactly the restricted
induced attachment family of v1.49. -/
theorem standardTypeAEndpointPushoutProductGenerators_eq_induced :
    (standardTypeAEndpointPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u})) =
    standardTypeAInducedScaledHornAttachmentGenerators := by
  apply le_antisymm
  · intro A B f hf
    dsimp [standardTypeAEndpointPushoutProductGenerators] at hf
    cases hf with
    | mk g =>
        rw [standardTypeAEndpointPushoutProductHom_eq_induced]
        exact standardTypeAInducedScaledHornAttachmentGenerator_mem g
  · intro A B f hf
    dsimp [standardTypeAInducedScaledHornAttachmentGenerators] at hf
    cases hf with
    | mk g =>
        rw [← standardTypeAEndpointPushoutProductHom_eq_induced]
        exact standardTypeAEndpointPushoutProductGenerator_mem g

/-! ## Isolate the remaining closure input -/

/-- A morphism property is stable under the endpoint pushout-products of
standard type-(A) horns when membership of each type-(A) horn generator implies
membership of the corresponding endpoint pushout-product. -/
structure StandardTypeAEndpointPushoutProductStable
    (L : MorphismProperty (ScaledSSet.{u})) : Prop where
  pushoutProduct_mem :
    ∀ g : StandardTypeAHornAttachmentGeneratorIndex,
      L (standardTypeAScaledHornGeneratorHom
        (StandardTypeAHornAttachmentGeneratorIndex.toHornGenerator g)) →
      L (standardTypeAEndpointPushoutProductHom g)

/-- External comparison data needed specifically for the type-(A) induced
attachment side of v1.48.  It separates containment of the basic standard
horns from endpoint pushout-product stability of the generated class. -/
structure StandardTypeAExternalGeneratedComparison
    (E : MorphismProperty (ScaledSSet.{u})) : Prop where
  typeAHorns_le_externalGenerated :
    (standardTypeAScaledHornGenerators : MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E
  endpointPushoutProductStable :
    StandardTypeAEndpointPushoutProductStable
      (externalGeneratedScaledAnodyne E)

namespace StandardTypeAExternalGeneratedComparison

variable {E : MorphismProperty (ScaledSSet.{u})}

/-- Every standard type-(A) endpoint pushout-product belongs to the external
generated scaled-anodyne class. -/
theorem endpointPushoutProducts_le_externalGenerated
    (K : StandardTypeAExternalGeneratedComparison E) :
    (standardTypeAEndpointPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E := by
  intro A B f hf
  dsimp [standardTypeAEndpointPushoutProductGenerators] at hf
  cases hf with
  | mk g =>
      apply StandardTypeAEndpointPushoutProductStable.pushoutProduct_mem
        (StandardTypeAExternalGeneratedComparison.endpointPushoutProductStable K) g
      exact StandardTypeAExternalGeneratedComparison.typeAHorns_le_externalGenerated K
        (standardTypeAScaledHornGeneratorHom
          (StandardTypeAHornAttachmentGeneratorIndex.toHornGenerator g))
        (standardTypeAScaledHornGenerator_mem
          (StandardTypeAHornAttachmentGeneratorIndex.toHornGenerator g))

/-- Rewriting through the geometric identification gives the desired v1.48
comparison statement

`T_induced^(A) ≤ E.rlp.llp`. -/
theorem inducedTypeAAttachments_le_externalGenerated
    (K : StandardTypeAExternalGeneratedComparison E) :
    (standardTypeAInducedScaledHornAttachmentGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E := by
  rw [← standardTypeAEndpointPushoutProductGenerators_eq_induced]
  exact endpointPushoutProducts_le_externalGenerated K

end StandardTypeAExternalGeneratedComparison

/-!
The comparison frontier is now factored one level more finely:

```text
standard type-(A) horn generators
  + endpoint pushout-product stability of E.rlp.llp
  -> endpoint pushout-products lie in E.rlp.llp
  = T_induced^(A)
  -> T_induced^(A) ≤ E.rlp.llp.
```

Thus the geometry no longer remains implicit.  What is still genuinely open is
the model-structure theorem that the chosen external standard scaled-anodyne
closure has the stated endpoint pushout-product stability.  Type-(B)/(C)
generators and the separate minimal-to-induced scaling enrichments remain
independent obligations.
-/

end KUOS.DependentOriginationStandardTypeAEndpointPushoutProductV1_50
