import KUOS.DependentOriginationScaledHornCylinderExtensionV1_39
import Mathlib.AlgebraicTopology.SimplicialSet.Monoidal

namespace KUOS.DependentOriginationScaledHornAttachmentLiftingV1_40

open CategoryTheory
open CategoryTheory.Category
open MonoidalCategory
open CartesianMonoidalCategory
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationGlobalDuskinScaledHornCoherenceV1_22
open KUOS.DependentOriginationBiequivalencePresentationInvariantV1_26
open KUOS.DependentOriginationHomotopyClassScaledHornInvariantV1_37
open KUOS.DependentOriginationHomotopyClassStrictificationV1_38
open KUOS.DependentOriginationScaledHornCylinderExtensionV1_39

universe u v w

/-!
# Scaled horn attachment lifting v1.40

Version 1.39 reduced homotopy-class strictification to two-sided relative horn
cylinder extension.  This layer moves one geometric level further down: the
cylinder extension is obtained from an extension problem for the canonical
horn-cylinder attachment

`(Δ[n] × {ε}) ∪ (Λ[n,i] × Δ[1]) ⊂ Δ[n] × Δ[1]`,

with `ε = 0` in the forward direction and `ε = 1` in the backward direction.

The attachment is Mathlib's `Subcomplex.unionProd`.  Its two pieces form an
actual pushout (`Subcomplex.unionProd.isPushout`).  Hence the current simplex
on the endpoint face and the prescribed relative horn homotopy glue uniquely
to a map from the attachment.  The only independent lifting input is then that
this glued attachment map extends over the whole cylinder while the opposite
endpoint remains scaled.

This is strictly below the v1.39 cylinder-extension interface: the latter is
derived below from the former.  No ordinary-anodyne theorem is promoted to a
scaled-anodyne statement.
-/

/-! ## Endpoint subcomplexes and horn-cylinder attachments -/

/-- The endpoint `ε` of `Δ[1]` as the subcomplex generated by its vertex. -/
def intervalEndpoint (ε : Fin 2) : (Δ[1] : SSet.{u}).Subcomplex :=
  SSet.Subcomplex.ofSimplex (SSet.stdSimplex.obj₀Equiv.symm ε)

/-- The inclusion of an endpoint subcomplex is the corresponding constant map. -/
@[simp]
theorem intervalEndpoint_ι (ε : Fin 2) :
    (intervalEndpoint ε).ι =
      SSet.const (SSet.stdSimplex.obj₀Equiv.symm ε) := by
  simpa [intervalEndpoint] using
    (SSet.Subcomplex.ofSimplex_ι (SSet.stdSimplex.obj₀Equiv.symm ε))

/-- The horn-cylinder attachment at endpoint `ε`. -/
def hornCylinderAttachment
    (n : Nat) (i : Fin (n + 1)) (ε : Fin 2) :
    ((Δ[n] : SSet.{u}) ⊗ Δ[1]).Subcomplex :=
  (SSet.horn n i).unionProd (intervalEndpoint ε)

/-- The distinguished vertex in the endpoint subcomplex. -/
def intervalEndpointVertex (ε : Fin 2) :
    (intervalEndpoint ε : SSet.{u}) _⦋0⦌ :=
  ⟨SSet.stdSimplex.obj₀Equiv.symm ε,
    SSet.Subcomplex.mem_ofSimplex_obj _⟩

/-- The endpoint section `Δ[n] -> Δ[n] × {ε}`. -/
noncomputable def endpointSection (n : Nat) (ε : Fin 2) :
    (Δ[n] : SSet.{u}) ⟶
      (Δ[n] : SSet.{u}) ⊗ (intervalEndpoint ε : SSet.{u}) :=
  CartesianMonoidalCategory.lift (𝟙 _)
    (SSet.const (intervalEndpointVertex ε))

/-- The endpoint-zero section followed by the endpoint-subcomplex inclusion is
Mathlib's simplicial endpoint inclusion. -/
@[simp, reassoc]
theorem endpointSection_ι_zero (n : Nat) :
    endpointSection n 0 ≫
        ((Δ[n] : SSet.{u}) ◁ (intervalEndpoint 0).ι) =
      (SSet.ι₀ : (Δ[n] : SSet.{u}) ⟶ (Δ[n] : SSet.{u}) ⊗ Δ[1]) := by
  apply CartesianMonoidalCategory.hom_ext
  · simp [endpointSection, Category.assoc]
  · simp [endpointSection, intervalEndpoint_ι, Category.assoc]

/-- The endpoint-one section followed by the endpoint-subcomplex inclusion is
Mathlib's simplicial endpoint inclusion. -/
@[simp, reassoc]
theorem endpointSection_ι_one (n : Nat) :
    endpointSection n 1 ≫
        ((Δ[n] : SSet.{u}) ◁ (intervalEndpoint 1).ι) =
      (SSet.ι₁ : (Δ[n] : SSet.{u}) ⟶ (Δ[n] : SSet.{u}) ⊗ Δ[1]) := by
  apply CartesianMonoidalCategory.hom_ext
  · simp [endpointSection, Category.assoc]
  · simp [endpointSection, intervalEndpoint_ι, Category.assoc]

/-- On a product with the endpoint-zero subcomplex, including the second factor
is the same as projecting to the first factor and then taking endpoint zero. -/
@[simp, reassoc]
theorem whiskerLeft_intervalEndpoint_zero (X : SSet.{u}) :
    X ◁ (intervalEndpoint 0).ι =
      CartesianMonoidalCategory.fst X (intervalEndpoint 0 : SSet.{u}) ≫
        (SSet.ι₀ : X ⟶ X ⊗ Δ[1]) := by
  apply CartesianMonoidalCategory.hom_ext
  · simp [Category.assoc]
  · simp [intervalEndpoint_ι, Category.assoc]

/-- On a product with the endpoint-one subcomplex, including the second factor
is the same as projecting to the first factor and then taking endpoint one. -/
@[simp, reassoc]
theorem whiskerLeft_intervalEndpoint_one (X : SSet.{u}) :
    X ◁ (intervalEndpoint 1).ι =
      CartesianMonoidalCategory.fst X (intervalEndpoint 1 : SSet.{u}) ≫
        (SSet.ι₁ : X ⟶ X ⊗ Δ[1]) := by
  apply CartesianMonoidalCategory.hom_ext
  · simp [Category.assoc]
  · simp [intervalEndpoint_ι, Category.assoc]

/-- The endpoint face factors through the horn-cylinder attachment. -/
noncomputable def endpointIntoAttachment
    (n : Nat) (i : Fin (n + 1)) (ε : Fin 2) :
    (Δ[n] : SSet.{u}) ⟶ hornCylinderAttachment n i ε :=
  endpointSection n ε ≫
    SSet.Subcomplex.unionProd.ι₁ (SSet.horn n i) (intervalEndpoint ε)

@[simp, reassoc]
theorem endpointIntoAttachment_ι_zero
    (n : Nat) (i : Fin (n + 1)) :
    endpointIntoAttachment n i 0 ≫ (hornCylinderAttachment n i 0).ι =
      (SSet.ι₀ : (Δ[n] : SSet.{u}) ⟶ (Δ[n] : SSet.{u}) ⊗ Δ[1]) := by
  simp only [endpointIntoAttachment, hornCylinderAttachment, Category.assoc,
    SSet.Subcomplex.unionProd.ι₁_ι, endpointSection_ι_zero]

@[simp, reassoc]
theorem endpointIntoAttachment_ι_one
    (n : Nat) (i : Fin (n + 1)) :
    endpointIntoAttachment n i 1 ≫ (hornCylinderAttachment n i 1).ι =
      (SSet.ι₁ : (Δ[n] : SSet.{u}) ⟶ (Δ[n] : SSet.{u}) ⊗ Δ[1]) := by
  simp only [endpointIntoAttachment, hornCylinderAttachment, Category.assoc,
    SSet.Subcomplex.unionProd.ι₁_ι, endpointSection_ι_one]

/-! ## Canonical pushout gluing of endpoint simplex and horn homotopy -/

/-- On `Δ[n] × {ε}`, a boundary realization is evaluated through the first
projection. -/
def endpointTensorMap
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f : HornRelativeMap X n i}
    (ε : Fin 2)
    (Q : ScaledHornBoundaryRealization sX sΔ f) :
    (Δ[n] : SSet.{u}) ⊗ (intervalEndpoint ε : SSet.{u}) ⟶ X :=
  CartesianMonoidalCategory.fst _ _ ≫ Q.simplexMap

/-- Compatibility on `Λ[n,i] × {0}` between the endpoint simplex and the
relative horn homotopy. -/
theorem forwardAttachment_compatibility
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ f) :
    (SSet.horn n i).ι ▷ (intervalEndpoint 0 : SSet.{u}) ≫
        endpointTensorMap 0 Q =
      (SSet.horn n i : SSet.{u}) ◁ (intervalEndpoint 0).ι ≫ H.h := by
  dsimp [endpointTensorMap]
  rw [← Category.assoc]
  rw [CartesianMonoidalCategory.whiskerRight_fst
    (SSet.horn n i).ι (intervalEndpoint 0 : SSet.{u})]
  rw [whiskerLeft_intervalEndpoint_zero (SSet.horn n i : SSet.{u})]
  simp only [Category.assoc, Q.boundary_eq, H.h₀]

/-- Compatibility on `Λ[n,i] × {1}` for the backward attachment. -/
theorem backwardAttachment_compatibility
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ g) :
    (SSet.horn n i).ι ▷ (intervalEndpoint 1 : SSet.{u}) ≫
        endpointTensorMap 1 Q =
      (SSet.horn n i : SSet.{u}) ◁ (intervalEndpoint 1).ι ≫ H.h := by
  dsimp [endpointTensorMap]
  rw [← Category.assoc]
  rw [CartesianMonoidalCategory.whiskerRight_fst
    (SSet.horn n i).ι (intervalEndpoint 1 : SSet.{u})]
  rw [whiskerLeft_intervalEndpoint_one (SSet.horn n i : SSet.{u})]
  simp only [Category.assoc, Q.boundary_eq, H.h₁]

/-- The canonical forward attachment map obtained from the pushout. -/
noncomputable def forwardAttachmentMap
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ f) :
    (hornCylinderAttachment n i 0 : SSet.{u}) ⟶ X :=
  (SSet.Subcomplex.unionProd.isPushout
    (SSet.horn n i) (intervalEndpoint 0)).desc
      (endpointTensorMap 0 Q) H.h
      (forwardAttachment_compatibility H Q)

/-- The canonical backward attachment map obtained from the pushout. -/
noncomputable def backwardAttachmentMap
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ g) :
    (hornCylinderAttachment n i 1 : SSet.{u}) ⟶ X :=
  (SSet.Subcomplex.unionProd.isPushout
    (SSet.horn n i) (intervalEndpoint 1)).desc
      (endpointTensorMap 1 Q) H.h
      (backwardAttachment_compatibility H Q)

/-- The pushout desc restricts to the prescribed endpoint-zero simplex map on
the endpoint product piece. -/
@[simp, reassoc]
theorem forwardAttachmentMap_on_endpointPiece
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ f) :
    SSet.Subcomplex.unionProd.ι₁ (SSet.horn n i) (intervalEndpoint 0) ≫
      forwardAttachmentMap H Q = endpointTensorMap 0 Q := by
  simpa only [forwardAttachmentMap] using
    (SSet.Subcomplex.unionProd.isPushout
      (SSet.horn n i) (intervalEndpoint 0)).inl_desc
        (endpointTensorMap 0 Q) H.h
        (forwardAttachment_compatibility H Q)

/-- The pushout desc restricts to the prescribed endpoint-one simplex map on
the endpoint product piece. -/
@[simp, reassoc]
theorem backwardAttachmentMap_on_endpointPiece
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ g) :
    SSet.Subcomplex.unionProd.ι₁ (SSet.horn n i) (intervalEndpoint 1) ≫
      backwardAttachmentMap H Q = endpointTensorMap 1 Q := by
  simpa only [backwardAttachmentMap] using
    (SSet.Subcomplex.unionProd.isPushout
      (SSet.horn n i) (intervalEndpoint 1)).inl_desc
        (endpointTensorMap 1 Q) H.h
        (backwardAttachment_compatibility H Q)

@[simp, reassoc]
theorem forwardAttachmentMap_on_endpoint
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ f) :
    endpointIntoAttachment n i 0 ≫ forwardAttachmentMap H Q = Q.simplexMap := by
  simp only [endpointIntoAttachment, Category.assoc,
    forwardAttachmentMap_on_endpointPiece]
  simp [endpointSection, endpointTensorMap]

@[simp, reassoc]
theorem backwardAttachmentMap_on_endpoint
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ g) :
    endpointIntoAttachment n i 1 ≫ backwardAttachmentMap H Q = Q.simplexMap := by
  simp only [endpointIntoAttachment, Category.assoc,
    backwardAttachmentMap_on_endpointPiece]
  simp [endpointSection, endpointTensorMap]

@[simp, reassoc]
theorem forwardAttachmentMap_on_horn
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ f) :
    SSet.Subcomplex.unionProd.ι₂ (SSet.horn n i) (intervalEndpoint 0) ≫
      forwardAttachmentMap H Q = H.h := by
  simpa only [forwardAttachmentMap] using
    (SSet.Subcomplex.unionProd.isPushout
      (SSet.horn n i) (intervalEndpoint 0)).inr_desc
        (endpointTensorMap 0 Q) H.h
        (forwardAttachment_compatibility H Q)

@[simp, reassoc]
theorem backwardAttachmentMap_on_horn
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ g) :
    SSet.Subcomplex.unionProd.ι₂ (SSet.horn n i) (intervalEndpoint 1) ≫
      backwardAttachmentMap H Q = H.h := by
  simpa only [backwardAttachmentMap] using
    (SSet.Subcomplex.unionProd.isPushout
      (SSet.horn n i) (intervalEndpoint 1)).inr_desc
        (endpointTensorMap 1 Q) H.h
        (backwardAttachment_compatibility H Q)

/-! ## Attachment lifting and derivation of v1.39 cylinder extension -/

/-- Forward extension of the canonically glued attachment map to the whole
cylinder, with scaled opposite endpoint. -/
structure ForwardScaledHornAttachmentLifting
    {X : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    {n : Nat} {i : Fin (n + 1)}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) : Prop where
  lift :
    ∀ {f g : HornRelativeMap X n i}
      (H : f.Homotopy g)
      (Q : ScaledHornBoundaryRealization sX sΔ f),
      ∃ extension : (Δ[n] : SSet.{u}) ⊗ Δ[1] ⟶ X,
        (hornCylinderAttachment n i 0).ι ≫ extension =
            forwardAttachmentMap H Q ∧
        IsScaledMap sΔ sX (SSet.ι₁ ≫ extension)

/-- Backward extension of the endpoint-1 attachment map, with scaled endpoint 0. -/
structure BackwardScaledHornAttachmentLifting
    {X : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    {n : Nat} {i : Fin (n + 1)}
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) : Prop where
  lift :
    ∀ {f g : HornRelativeMap X n i}
      (H : f.Homotopy g)
      (Q : ScaledHornBoundaryRealization sX sΔ g),
      ∃ extension : (Δ[n] : SSet.{u}) ⊗ Δ[1] ⟶ X,
        (hornCylinderAttachment n i 1).ι ≫ extension =
            backwardAttachmentMap H Q ∧
        IsScaledMap sΔ sX (SSet.ι₀ ≫ extension)

namespace ForwardScaledHornAttachmentLifting

/-- Attachment lifting implies the forward cylinder-extension interface of
v1.39. -/
noncomputable def toCylinderExtension
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    (R : ForwardScaledHornAttachmentLifting (i := i) sX sΔ)
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ f) :
    Nonempty (ForwardScaledHornCylinderExtension sX sΔ H Q) := by
  rcases R.lift H Q with ⟨E, hE, hScaled⟩
  exact ⟨{
    extension := E
    endpoint_zero := by
      have h := congrArg (fun k => endpointIntoAttachment n i 0 ≫ k) hE
      simpa only [← Category.assoc, endpointIntoAttachment_ι_zero,
        forwardAttachmentMap_on_endpoint] using h
    on_horn := by
      have h := congrArg
        (fun k => SSet.Subcomplex.unionProd.ι₂
          (SSet.horn n i) (intervalEndpoint 0) ≫ k) hE
      simpa only [hornCylinderAttachment, ← Category.assoc,
        SSet.Subcomplex.unionProd.ι₂_ι,
        forwardAttachmentMap_on_horn] using h
    endpoint_one_scaled := hScaled
  }⟩

end ForwardScaledHornAttachmentLifting

namespace BackwardScaledHornAttachmentLifting

/-- Attachment lifting implies the backward cylinder-extension interface of
v1.39. -/
noncomputable def toCylinderExtension
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})}
    (R : BackwardScaledHornAttachmentLifting (i := i) sX sΔ)
    {f g : HornRelativeMap X n i}
    (H : f.Homotopy g)
    (Q : ScaledHornBoundaryRealization sX sΔ g) :
    Nonempty (BackwardScaledHornCylinderExtension sX sΔ H Q) := by
  rcases R.lift H Q with ⟨E, hE, hScaled⟩
  exact ⟨{
    extension := E
    endpoint_one := by
      have h := congrArg (fun k => endpointIntoAttachment n i 1 ≫ k) hE
      simpa only [← Category.assoc, endpointIntoAttachment_ι_one,
        backwardAttachmentMap_on_endpoint] using h
    on_horn := by
      have h := congrArg
        (fun k => SSet.Subcomplex.unionProd.ι₂
          (SSet.horn n i) (intervalEndpoint 1) ≫ k) hE
      simpa only [hornCylinderAttachment, ← Category.assoc,
        SSet.Subcomplex.unionProd.ι₂_ι,
        backwardAttachmentMap_on_horn] using h
    endpoint_zero_scaled := hScaled
  }⟩

end BackwardScaledHornAttachmentLifting

/-- Two-sided attachment lifting for one scaled horn problem. -/
structure ScaledHornProblemAttachmentLifting
    {X : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    {n : Nat} {i : Fin (n + 1)}
    (P : ScaledHornExtensionProblem X sX n i) : Prop where
  forward : ForwardScaledHornAttachmentLifting (i := i) sX P.simplexScaling
  backward : BackwardScaledHornAttachmentLifting (i := i) sX P.simplexScaling

namespace ScaledHornProblemAttachmentLifting

/-- Canonical attachment lifting recovers the two-sided cylinder extension of
v1.39. -/
noncomputable def toCylinderExtension
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {P : ScaledHornExtensionProblem X sX n i}
    (R : ScaledHornProblemAttachmentLifting sX P) :
    ScaledHornProblemCylinderExtension sX P where
  forward := by
    intro f g H Q
    exact R.forward.toCylinderExtension H Q
  backward := by
    intro f g H Q
    exact R.backward.toCylinderExtension H Q

/-- Therefore attachment lifting already strictifies homotopy-class fillers. -/
noncomputable def toStrictification
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {n : Nat} {i : Fin (n + 1)}
    {P : ScaledHornExtensionProblem X sX n i}
    (R : ScaledHornProblemAttachmentLifting sX P)
    (Q : HomotopyClassScaledHornFiller P) :
    Nonempty (ScaledHornFiller P) :=
  R.toCylinderExtension.strictify Q

end ScaledHornProblemAttachmentLifting

/-! ## Family and presentation-independent consequences -/

/-- Attachment lifting for every horn problem selected by a family. -/
structure ScaledHornFamilyAttachmentLifting
    {X : SSet.{u}}
    (sX : ScaledSimplicialSet X)
    (F : ScaledHornFamily X sX) : Prop where
  lifting :
    ∀ {n : Nat} {i : Fin (n + 1)}
      (P : ScaledHornExtensionProblem X sX n i),
      F.admissible P →
      ScaledHornProblemAttachmentLifting sX P

namespace ScaledHornFamilyAttachmentLifting

noncomputable def toCylinderExtension
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {F : ScaledHornFamily X sX}
    (R : ScaledHornFamilyAttachmentLifting sX F) :
    ScaledHornFamilyCylinderExtension sX F where
  extension := by
    intro n i P hP
    exact (R.lifting P hP).toCylinderExtension

noncomputable def toStrictification
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    {F : ScaledHornFamily X sX}
    (R : ScaledHornFamilyAttachmentLifting sX F) :
    ScaledHornFamilyHomotopyClassStrictification X sX F :=
  R.toCylinderExtension.toStrictification

end ScaledHornFamilyAttachmentLifting

open KUOS.DependentOriginationGlobalDuskinScaledNerveV1_21
open KUOS.DependentOriginationStrictlyUnitaryDuskinModelTransportV1_27

/-- A coherent normalized scaled model equivalence whose two global Duskin
presentations satisfy the lower-level horn-attachment lifting principle. -/
structure CoherentNormalizedScaledAttachmentLiftableModelEquivalence
    {B C : Type u}
    [Bicategory.{w, v} B] [Bicategory.{w, v} C]
    (E : BicategoricalModelEquivalence B C)
    (G : BicategoricalModelEquivalence C B)
    (HB : GlobalDuskinScaledHornFamily B)
    (HC : GlobalDuskinScaledHornFamily C) where
  homotopyClassModel :
    CoherentNormalizedScaledHomotopyClassModelEquivalence E G HB HC
  sourceAttachmentLifting :
    ScaledHornFamilyAttachmentLifting (duskinScaling B) HB
  targetAttachmentLifting :
    ScaledHornFamilyAttachmentLifting (duskinScaling C) HC

namespace CoherentNormalizedScaledAttachmentLiftableModelEquivalence

variable
    {B C : Type u}
    [Bicategory.{w, v} B] [Bicategory.{w, v} C]
    {E : BicategoricalModelEquivalence B C}
    {G : BicategoricalModelEquivalence C B}
    {HB : GlobalDuskinScaledHornFamily B}
    {HC : GlobalDuskinScaledHornFamily C}
    (K : CoherentNormalizedScaledAttachmentLiftableModelEquivalence E G HB HC)

noncomputable def toCylinderExtendableModelEquivalence :
    CoherentNormalizedScaledCylinderExtendableModelEquivalence E G HB HC where
  homotopyClassModel := K.homotopyClassModel
  sourceCylinderExtension := K.sourceAttachmentLifting.toCylinderExtension
  targetCylinderExtension := K.targetAttachmentLifting.toCylinderExtension

include K in
/-- Strict global scaled-Duskin fibrancy is presentation-independent once the
canonical horn-cylinder attachments lift on both presentations. -/
theorem globalDuskinStrictFibrancy_iff :
    HasScaledHornFillers (duskinNerve B) (duskinScaling B) HB ↔
      HasScaledHornFillers (duskinNerve C) (duskinScaling C) HC :=
  K.toCylinderExtendableModelEquivalence.globalDuskinStrictFibrancy_iff

end CoherentNormalizedScaledAttachmentLiftableModelEquivalence

/-!
The strict-fibrancy spine is now:

```text
endpoint simplex + relative horn homotopy
  -> Mathlib union-product pushout
  -> canonical attachment map

attachment-map extension across
  (Δ[n] × {0}) ∪ (Λ[n,i] × Δ[1]) -> Δ[n] × Δ[1]
  and the endpoint-1 analogue
  -> two-sided cylinder extension                         -- v1.39
  -> homotopy-class strictification                       -- v1.39
  -> strict fibrancy = homotopy-class fibrancy            -- v1.38

coherent normalized scaled model equivalence
  -> presentation-independent homotopy-class fibrancy     -- v1.37
  + attachment lifting on both presentations
  -> presentation-independent strict scaled fibrancy      -- v1.40
```

The remaining independent theorem is no longer an opaque strictification or
cylinder principle.  It is the concrete extension/lifting theorem for these
canonical union-product horn-cylinder attachments in the chosen global scaled
Duskin presentation.
-/

end KUOS.DependentOriginationScaledHornAttachmentLiftingV1_40