import KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53

namespace KUOS.DependentOriginationStandardTypeAGeneratedPushoutLLPDescentV1_54

open CategoryTheory
open CategoryTheory.Category
open Simplicial
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49
open KUOS.DependentOriginationStandardTypeAEndpointPushoutProductV1_50
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53

universe u

/-!
# Standard type-(A) generated-pushout LLP descent v1.54

Version 1.53 separated the standard type-(A) endpoint map into

```text
least-generated scaled Leibniz source
  -- identity-underlying source enrichment -->
induced pullback-scaled source
  -- induced endpoint inclusion -->
scaled cylinder.
```

The source-enrichment map is an epimorphism in `ScaledSSet`: its underlying
simplicial map is literally the identity, and equality of scaled morphisms is
controlled by equality of their underlying simplicial maps.

This gives a useful lifting principle.  If `e : A ⟶ B` is epi and
`e ≫ i` has the left lifting property against `p`, then `i` itself has the
left lifting property against `p`.  Indeed, precompose a lifting square for
`i` with `e`, obtain a lift for `e ≫ i`, and cancel `e` in the left triangle.

Applied to v1.53, left lifting for the least-generated endpoint map therefore
descends to the v1.50 induced endpoint map.  Consequently the external
comparison no longer needs stability for the already enriched source.  It is
enough to prove stability for the genuinely least-generated scaled Leibniz
pushout.
-/

/-! ## LLP descends through an epi source refinement -/

/-- If an epimorphism is precomposed with a left map and the composite lifts
against `p`, then the right factor also lifts against `p`. -/
theorem hasLiftingProperty_of_epi_precomp
    {A B D X Y : ScaledSSet.{u}}
    (e : A ⟶ B)
    (i : B ⟶ D)
    (p : X ⟶ Y)
    [Epi e]
    (h : HasLiftingProperty (e ≫ i) p) :
    HasLiftingProperty i p := by
  letI : HasLiftingProperty (e ≫ i) p := h
  refine ⟨?_⟩
  intro f g sq
  let sq' : CommSq (e ≫ f) (e ≫ i) p g := by
    constructor
    simpa only [Category.assoc] using
      congrArg (fun k => e ≫ k) sq.w
  letI : sq'.HasLift := inferInstance
  exact
    CommSq.HasLift.mk'
      { l := sq'.lift
        fac_left := by
          apply (cancel_epi e).1
          simpa only [Category.assoc] using sq'.fac_left
        fac_right := sq'.fac_right }

/-! ## The v1.53 source enrichment is epi -/

/-- The least-generated-to-induced source enrichment is epi.  Its carrier map
is the identity, so cancellation reduces to `ScaledMap.ext`. -/
instance standardTypeAEndpointGeneratedToInduced_epi
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    Epi (standardTypeAEndpointGeneratedToInduced g :
      (standardTypeAEndpointGeneratedPushoutSource g : ScaledSSet.{u}) ⟶
        (standardTypeAEndpointPushoutProductSource g : ScaledSSet.{u})) where
  left_cancellation := by
    intro Z f h w
    apply ScaledSSet.ScaledMap.ext
    have hw := congrArg ScaledSSet.ScaledMap.map w
    simpa [standardTypeAEndpointGeneratedToInduced,
      standardTypeAEndpointGeneratedPushoutSource,
      standardTypeAEndpointPushoutProductSource] using hw

/-- Lifting against the least-generated endpoint map descends to lifting
against the v1.50 induced endpoint map. -/
theorem standardTypeAEndpointPushoutProduct_hasLiftingProperty_of_generated
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    {X Y : ScaledSSet.{u}}
    (p : X ⟶ Y)
    (h : HasLiftingProperty
      (standardTypeAEndpointGeneratedPushoutProductHom g) p) :
    HasLiftingProperty
      (standardTypeAEndpointPushoutProductHom g) p := by
  apply hasLiftingProperty_of_epi_precomp
    (standardTypeAEndpointGeneratedToInduced g)
    (standardTypeAEndpointPushoutProductHom g)
    p
  simpa [standardTypeAEndpointGeneratedPushoutProductHom] using h

/-! ## Package the least-generated endpoint family -/

/-- The standard type-(A) endpoint maps whose source carries only the least
scaling generated by the two Leibniz legs. -/
def standardTypeAEndpointGeneratedPushoutProductGenerators :
    MorphismProperty (ScaledSSet.{u}) :=
  MorphismProperty.ofHoms
    (fun g : StandardTypeAHornAttachmentGeneratorIndex =>
      standardTypeAEndpointGeneratedPushoutProductHom g)

/-- Every least-generated endpoint map lies in its generator property. -/
theorem standardTypeAEndpointGeneratedPushoutProductGenerator_mem
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointGeneratedPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u}))
      (standardTypeAEndpointGeneratedPushoutProductHom g) :=
  MorphismProperty.ofHoms.mk g

/-- A left class is stable under the least-generated standard type-(A)
endpoint construction when membership of the type-(A) horn implies membership
of the corresponding least-generated endpoint map. -/
structure StandardTypeAEndpointGeneratedPushoutProductStable
    (L : MorphismProperty (ScaledSSet.{u})) : Prop where
  pushoutProduct_mem :
    ∀ g : StandardTypeAHornAttachmentGeneratorIndex,
      L (standardTypeAScaledHornGeneratorHom
        (StandardTypeAHornAttachmentGeneratorIndex.toHornGenerator g)) →
      L (standardTypeAEndpointGeneratedPushoutProductHom g)

/-! ## Orthogonal left classes only need least-generated stability -/

/-- For a class of the form `T.llp`, stability under the least-generated
endpoint maps implies the v1.50 stability statement for the induced endpoint
maps.  No membership assumption on the source-enrichment morphism is needed. -/
theorem standardTypeAEndpointPushoutProductStable_of_generated
    (T : MorphismProperty (ScaledSSet.{u}))
    (K : StandardTypeAEndpointGeneratedPushoutProductStable T.llp) :
    StandardTypeAEndpointPushoutProductStable T.llp where
  pushoutProduct_mem := by
    intro g hHorn
    intro X Y p hp
    have hGenerated := K.pushoutProduct_mem g hHorn
    exact
      standardTypeAEndpointPushoutProduct_hasLiftingProperty_of_generated
        g p (hGenerated p hp)

/-- External comparison data can therefore ask only for type-(A) horn
containment and least-generated endpoint stability of `E.rlp.llp`. -/
structure StandardTypeAExternalGeneratedPushoutComparison
    (E : MorphismProperty (ScaledSSet.{u})) : Prop where
  typeAHorns_le_externalGenerated :
    (standardTypeAScaledHornGenerators : MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E
  generatedEndpointPushoutProductStable :
    StandardTypeAEndpointGeneratedPushoutProductStable
      (externalGeneratedScaledAnodyne E)

namespace StandardTypeAExternalGeneratedPushoutComparison

variable {E : MorphismProperty (ScaledSSet.{u})}

/-- Least-generated endpoint stability induces the older v1.50 comparison
interface automatically. -/
def toStandardTypeAExternalGeneratedComparison
    (K : StandardTypeAExternalGeneratedPushoutComparison E) :
    StandardTypeAExternalGeneratedComparison E where
  typeAHorns_le_externalGenerated :=
    StandardTypeAExternalGeneratedPushoutComparison.typeAHorns_le_externalGenerated K
  endpointPushoutProductStable := by
    change StandardTypeAEndpointPushoutProductStable (E.rlp.llp)
    apply standardTypeAEndpointPushoutProductStable_of_generated (T := E.rlp)
    simpa [externalGeneratedScaledAnodyne] using
      StandardTypeAExternalGeneratedPushoutComparison.generatedEndpointPushoutProductStable K

/-- Hence all v1.50 induced type-(A) attachments belong to the externally
generated left class from the strictly weaker least-generated stability input. -/
theorem inducedTypeAAttachments_le_externalGenerated
    (K : StandardTypeAExternalGeneratedPushoutComparison E) :
    (standardTypeAInducedScaledHornAttachmentGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E :=
  StandardTypeAExternalGeneratedComparison.inducedTypeAAttachments_le_externalGenerated
    (toStandardTypeAExternalGeneratedComparison K)

/-- The endpoint-pushout-product presentation itself is therefore externally
generated as well. -/
theorem endpointPushoutProducts_le_externalGenerated
    (K : StandardTypeAExternalGeneratedPushoutComparison E) :
    (standardTypeAEndpointPushoutProductGenerators :
      MorphismProperty (ScaledSSet.{u})) ≤
      externalGeneratedScaledAnodyne E :=
  StandardTypeAExternalGeneratedComparison.endpointPushoutProducts_le_externalGenerated
    (toStandardTypeAExternalGeneratedComparison K)

end StandardTypeAExternalGeneratedPushoutComparison

/-!
The type-(A) comparison burden is now sharpened to

```text
standard type-(A) horn in E.rlp.llp
  -> least-generated scaled Leibniz endpoint map in E.rlp.llp
  -> epi source-enrichment cancellation
  -> induced endpoint map in E.rlp.llp
  = T_induced^(A) in E.rlp.llp.
```

The source-enrichment map itself need not be inserted into the left class for
this induced-attachment step.  The remaining task is therefore to identify the
least-generated endpoint construction with an actual pushout-product in the
scaled category and connect its lifting condition to the native Leibniz mate
from v1.51.
-/

end KUOS.DependentOriginationStandardTypeAGeneratedPushoutLLPDescentV1_54