import KUOS.DependentOriginationHexagramInnerHexagonV3_88
import Mathlib

namespace KUOS.DependentOriginationPentagramInnerPentagonV3_89

open KUOS.DependentOriginationTruncatedIcosahedralStarRefinementV3_83

set_option autoImplicit false

/-!
# Pentagram crossing pattern and recursive inner pentagon v3.89

The hexagonal side of the truncated-icosahedral carrier has been refined in
v3.88 by two interlaced triangles and an inner hexagon.  This file gives the
pentagonal side the analogous combinatorial refinement.

Five outer tips are placed cyclically.  The pentagram joins every second tip.
Its five diagonal edges have five consecutive crossing pairs, and those
crossings form a closed inner five-cycle.

As in v3.88, this is incidence-only.  No Euclidean coordinates, golden-ratio
scale, or metric self-similarity is asserted here.
-/

/-- Five cyclic outer tips of the pentagonal face. -/
inductive PentagramOuterTip
  | p0 | p1 | p2 | p3 | p4
  deriving DecidableEq, Repr, Fintype

@[simp] theorem pentagramOuterTip_card :
    Fintype.card PentagramOuterTip = 5 := by
  native_decide

/-- The five diagonals of the pentagram. -/
inductive PentagramStarEdge
  | e0 | e1 | e2 | e3 | e4
  deriving DecidableEq, Repr, Fintype

@[simp] theorem pentagramStarEdge_card :
    Fintype.card PentagramStarEdge = 5 := by
  native_decide

/-- Endpoints of the pentagram diagonals: each edge skips one boundary tip. -/
def pentagramStarEdgeEndpoints :
    PentagramStarEdge → PentagramOuterTip × PentagramOuterTip
  | .e0 => (.p0, .p2)
  | .e1 => (.p1, .p3)
  | .e2 => (.p2, .p4)
  | .e3 => (.p3, .p0)
  | .e4 => (.p4, .p1)

/-- Five crossings of consecutive pentagram diagonals, ordered around the
inner pentagon. -/
inductive PentagramInnerVertex
  | q0 | q1 | q2 | q3 | q4
  deriving DecidableEq, Repr, Fintype

@[simp] theorem pentagramInnerVertex_card :
    Fintype.card PentagramInnerVertex = 5 := by
  native_decide

/-- First pentagram edge through each inner crossing. -/
def pentagramInnerVertexFirstEdge :
    PentagramInnerVertex → PentagramStarEdge
  | .q0 => .e0
  | .q1 => .e1
  | .q2 => .e2
  | .q3 => .e3
  | .q4 => .e4

/-- Second pentagram edge through each inner crossing. -/
def pentagramInnerVertexSecondEdge :
    PentagramInnerVertex → PentagramStarEdge
  | .q0 => .e1
  | .q1 => .e2
  | .q2 => .e3
  | .q3 => .e4
  | .q4 => .e0

/-- Cyclic successor on the five inner crossings. -/
def pentagramInnerVertexNext :
    PentagramInnerVertex → PentagramInnerVertex
  | .q0 => .q1
  | .q1 => .q2
  | .q2 => .q3
  | .q3 => .q4
  | .q4 => .q0

/-- The pentagram edge shared by a crossing and its successor. -/
def pentagramInnerSharedEdgeToNext :
    PentagramInnerVertex → PentagramStarEdge
  | .q0 => .e1
  | .q1 => .e2
  | .q2 => .e3
  | .q3 => .e4
  | .q4 => .e0

/-- Incidence of an inner crossing with one of its two pentagram edges. -/
def pentagramInnerIncident
    (q : PentagramInnerVertex)
    (e : PentagramStarEdge) : Prop :=
  e = pentagramInnerVertexFirstEdge q ∨
    e = pentagramInnerVertexSecondEdge q

/-- The designated shared edge is incident to the current inner crossing. -/
theorem pentagramInnerSharedEdge_incident_current
    (q : PentagramInnerVertex) :
    pentagramInnerIncident q
      (pentagramInnerSharedEdgeToNext q) := by
  cases q <;>
    simp [pentagramInnerIncident,
      pentagramInnerSharedEdgeToNext,
      pentagramInnerVertexFirstEdge,
      pentagramInnerVertexSecondEdge]

/-- The same designated edge is incident to the next inner crossing. -/
theorem pentagramInnerSharedEdge_incident_next
    (q : PentagramInnerVertex) :
    pentagramInnerIncident (pentagramInnerVertexNext q)
      (pentagramInnerSharedEdgeToNext q) := by
  cases q <;>
    simp [pentagramInnerIncident,
      pentagramInnerSharedEdgeToNext,
      pentagramInnerVertexNext,
      pentagramInnerVertexFirstEdge,
      pentagramInnerVertexSecondEdge]

/-- Ordered inner-pentagon boundary vertices. -/
def pentagramInnerBoundary : List PentagramInnerVertex :=
  [.q0, .q1, .q2, .q3, .q4]

@[simp] theorem pentagramInnerBoundary_length :
    pentagramInnerBoundary.length = 5 := by
  rfl

/-- The final inner crossing closes back to the first. -/
@[simp] theorem pentagramInnerBoundary_closes :
    pentagramInnerVertexNext .q4 = .q0 := by
  rfl

/-- The central cell generated by the pentagram is again pentagonal at the
level of face kind. -/
def pentagramInnerFaceKind : TruncatedIcosahedralFaceKind :=
  .pentagon

@[simp] theorem pentagramInnerFaceKind_sides :
    truncatedIcosahedralFaceSides pentagramInnerFaceKind = 5 := by
  rfl

/-- The inner pentagon has the same five-fold arity as the recursive pentagram
profile from v3.83. -/
theorem pentagramInnerBoundary_matches_refinement :
    pentagramInnerBoundary.length =
      pentagramRefinement.sectors := by
  rfl

/-!
## Boundary after v3.89

Both face types of the truncated-icosahedral 5.6.6 carrier now have explicit
recursive star incidence:

* pentagon -> pentagram -> inner pentagon;
* hexagon -> hexagram -> inner hexagon.

Both constructions preserve the face kind of the central cell and regenerate
the same boundary arity without introducing metric assumptions.

The next synthesis unit should package these as one face-kind-indexed
star-refinement operator and show that the local 5.6.6 signature is preserved
under one simultaneous refinement step.  This will provide the finite
self-similar carrier needed before any recursive obstruction iteration is
attempted.
-/

end KUOS.DependentOriginationPentagramInnerPentagonV3_89
