import KUOS.DependentOriginationScaledTerminalRLPV1_41
import Mathlib.CategoryTheory.MorphismProperty.LiftingProperty

namespace KUOS.DependentOriginationScaledAnodyneGeneratorClosureV1_42

open CategoryTheory
open CategoryTheory.Category
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationGlobalDuskinScaledHornCoherenceV1_22
open KUOS.DependentOriginationScaledTerminalRLPV1_41

universe u u₁ u₂ v₁ v₂ w₁ w₂

/-!
# Scaled-anodyne generator closure v1.42

Version 1.41 reduced the strictification frontier to native terminal right
lifting properties against the canonical minimally-scaled horn-cylinder
attachments.  This layer packages those attachment inclusions as an actual
Mathlib `MorphismProperty` and takes its canonical lifting-theoretic closure.

For a class `T` of morphisms, Mathlib supplies the Galois closure

`T.rlp.llp`

and proves `(T.rlp.llp).rlp = T.rlp`.  We therefore define the canonical
KuuOS scaled-anodyne closure to be the left class generated by the attachment
inclusions under this Galois connection.  This has two consequences:

* passing from generators to the generated closure does not change fibrant
  objects;
* any alternative scaled-anodyne presentation lying between the generators
  and their Galois closure has exactly the same right class.

This is a genuine presentation-independence statement for the lifting class.
It does not identify the resulting class with a future external/Lurie scaled
anodyne implementation in Mathlib; such an identification is now isolated to
an inclusion/equality theorem between morphism properties.
-/

/-! ## Canonical horn-cylinder generators -/

/-- Index data for one canonical scaled horn-cylinder attachment inclusion. -/
structure ScaledHornAttachmentGeneratorIndex where
  n : Nat
  i : Fin (n + 1)
  endpoint : Fin 2
  simplexScaling : ScaledSimplicialSet (Δ[n] : SSet.{u})

/-- The canonical scaled attachment inclusion associated to one generator
index. -/
def scaledHornAttachmentGeneratorHom
    (g : ScaledHornAttachmentGeneratorIndex.{u}) :
    minimallyScaledHornCylinderAttachment g.n g.i g.endpoint ⟶
      scaledSimplexCylinder g.simplexScaling :=
  scaledHornCylinderAttachmentInclusion g.i g.endpoint g.simplexScaling

/-- The morphism property generated by all canonical scaled horn-cylinder
attachment inclusions, for all dimensions, distinguished horns, endpoints,
and simplex scalings. -/
def scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u}) :=
  MorphismProperty.ofHoms
    (fun g : ScaledHornAttachmentGeneratorIndex.{u} =>
      scaledHornAttachmentGeneratorHom g)

/-- Every canonical attachment inclusion belongs to the generator property. -/
theorem scaledHornAttachmentGenerator_mem
    (g : ScaledHornAttachmentGeneratorIndex.{u}) :
    (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u}))
      (scaledHornAttachmentGeneratorHom g) := by
  exact MorphismProperty.ofHoms.mk g

/-! ## Canonical Galois / weakly saturated closure -/

/-- The canonical scaled-anodyne closure generated by the horn-cylinder
attachments.  It is the left orthogonal of the right orthogonal of the
canonical generator property. -/
def canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u}) :=
  (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})).rlp.llp

/-- Every attachment generator belongs to the canonical generated closure. -/
theorem scaledHornAttachmentGenerators_le_generated :
    (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})) ≤
      canonicalGeneratedScaledAnodyne :=
  MorphismProperty.le_llp_rlp _

/-- Passing from the generators to their Galois closure does not change the
right lifting class. -/
theorem canonicalGeneratedScaledAnodyne_rlp :
    (canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u})).rlp =
      (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})).rlp := by
  simpa [canonicalGeneratedScaledAnodyne] using
    (MorphismProperty.rlp_llp_rlp
      (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})))

/-- A scaled-anodyne presentation compatible with the canonical generators.

The sandwich condition is deliberately exact: a presentation contains every
canonical attachment generator and introduces no morphism beyond the canonical
Galois closure.  Such presentations may choose different intermediate weak
saturations without changing their fibrant objects. -/
structure ScaledAnodynePresentation where
  anodyne : MorphismProperty (ScaledSSet.{u})
  generators_le :
    (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})) ≤ anodyne
  le_generatedClosure : anodyne ≤ canonicalGeneratedScaledAnodyne

namespace ScaledAnodynePresentation

/-- Any compatible scaled-anodyne presentation has exactly the same right
class as the canonical attachment generators. -/
theorem rlp_eq_generators
    (P : ScaledAnodynePresentation.{u}) :
    P.anodyne.rlp =
      (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})).rlp := by
  apply le_antisymm
  · exact MorphismProperty.antitone_rlp P.generators_le
  · rw [← canonicalGeneratedScaledAnodyne_rlp]
    exact MorphismProperty.antitone_rlp P.le_generatedClosure

/-- In particular every compatible presentation also has the same right class
as the canonical generated closure. -/
theorem rlp_eq_generated
    (P : ScaledAnodynePresentation.{u}) :
    P.anodyne.rlp =
      (canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u})).rlp := by
  rw [P.rlp_eq_generators, canonicalGeneratedScaledAnodyne_rlp]

/-- The maximal compatible presentation: the full canonical Galois closure. -/
def canonical : ScaledAnodynePresentation.{u} where
  anodyne := canonicalGeneratedScaledAnodyne
  generators_le := scaledHornAttachmentGenerators_le_generated
  le_generatedClosure := le_rfl

/-- The minimal compatible presentation: just the chosen attachment
generators. -/
def generators : ScaledAnodynePresentation.{u} where
  anodyne := scaledHornAttachmentGenerators
  generators_le := le_rfl
  le_generatedClosure := scaledHornAttachmentGenerators_le_generated

end ScaledAnodynePresentation

/-! ## Fibrant objects are independent of the compatible presentation -/

/-- A scaled simplicial set is attachment-fibrant when its terminal map lies
in the right orthogonal of the canonical attachment generators. -/
def IsAttachmentFibrant (X : ScaledSSet.{u}) : Prop :=
  (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})).rlp
    (ScaledSSet.toPoint X)

/-- Fibrancy relative to a compatible scaled-anodyne presentation. -/
def IsFibrantForPresentation
    (P : ScaledAnodynePresentation.{u})
    (X : ScaledSSet.{u}) : Prop :=
  P.anodyne.rlp (ScaledSSet.toPoint X)

/-- Compatible scaled-anodyne presentations define exactly the attachment-
fibrant objects. -/
theorem isFibrantForPresentation_iff_attachmentFibrant
    (P : ScaledAnodynePresentation.{u})
    (X : ScaledSSet.{u}) :
    IsFibrantForPresentation P X ↔ IsAttachmentFibrant X := by
  change P.anodyne.rlp (ScaledSSet.toPoint X) ↔
    (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})).rlp
      (ScaledSSet.toPoint X)
  rw [P.rlp_eq_generators]

/-- Attachment fibrancy supplies the native lifting property against any one
canonical generator. -/
theorem attachmentFibrant_hasLiftingProperty
    {X : ScaledSSet.{u}}
    (hX : IsAttachmentFibrant X)
    {n : Nat}
    (i : Fin (n + 1))
    (endpoint : Fin 2)
    (sΔ : ScaledSimplicialSet (Δ[n] : SSet.{u})) :
    HasLiftingProperty
      (scaledHornCylinderAttachmentInclusion i endpoint sΔ)
      (ScaledSSet.toPoint X) := by
  let g : ScaledHornAttachmentGeneratorIndex.{u} :=
    { n := n
      i := i
      endpoint := endpoint
      simplexScaling := sΔ }
  change
    (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u})).rlp
      (ScaledSSet.toPoint X) at hX
  have h := hX (scaledHornAttachmentGeneratorHom g)
    (scaledHornAttachmentGenerator_mem g)
  simpa [g, scaledHornAttachmentGeneratorHom] using h

/-- Attachment fibrancy supplies the exact two-sided terminal-RLP package for
any scaled horn problem, independently of which horn family later selects it. -/
noncomputable def problemTerminalRLPOfAttachmentFibrant
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    (hX : IsAttachmentFibrant (ScaledSSet.of X sX))
    {n : Nat} {i : Fin (n + 1)}
    (P : ScaledHornExtensionProblem X sX n i) :
    ScaledHornProblemTerminalRLP sX P where
  forward :=
    attachmentFibrant_hasLiftingProperty hX i 0 P.simplexScaling
  backward :=
    attachmentFibrant_hasLiftingProperty hX i 1 P.simplexScaling

/-- Hence attachment fibrancy supplies terminal RLP for every horn family on
the target, without adding family-specific lifting fields. -/
noncomputable def familyTerminalRLPOfAttachmentFibrant
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    (hX : IsAttachmentFibrant (ScaledSSet.of X sX))
    (F : ScaledHornFamily X sX) :
    ScaledHornFamilyTerminalRLP sX F where
  lifting := by
    intro n i P _
    exact problemTerminalRLPOfAttachmentFibrant hX P

/-- A presentation-fibrant target therefore supplies terminal RLP for every
chosen scaled horn family. -/
noncomputable def familyTerminalRLPOfPresentationFibrant
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    (P : ScaledAnodynePresentation.{u})
    (hX : IsFibrantForPresentation P (ScaledSSet.of X sX))
    (F : ScaledHornFamily X sX) :
    ScaledHornFamilyTerminalRLP sX F :=
  familyTerminalRLPOfAttachmentFibrant
    ((isFibrantForPresentation_iff_attachmentFibrant P _).mp hX) F

/-- Presentation fibrancy therefore also supplies the v1.38 homotopy-class
strictification for every chosen family. -/
noncomputable def familyStrictificationOfPresentationFibrant
    {X : SSet.{u}}
    {sX : ScaledSimplicialSet X}
    (P : ScaledAnodynePresentation.{u})
    (hX : IsFibrantForPresentation P (ScaledSSet.of X sX))
    (F : ScaledHornFamily X sX) :
    ScaledHornFamilyHomotopyClassStrictification X sX F :=
  (familyTerminalRLPOfPresentationFibrant P hX F).toStrictification

/-! ## Presentation-independent strict global Duskin fibrancy -/

open KUOS.DependentOriginationGlobalDuskinScaledNerveV1_21
open KUOS.DependentOriginationStrictlyUnitaryDuskinModelTransportV1_27

/-- A coherent normalized scaled model equivalence whose two global Duskin
nerves are fibrant for the canonical attachment-generated right class.

Unlike v1.41, the lifting input is now target-level and independent of the
chosen horn families `HB` and `HC`. -/
structure CoherentNormalizedScaledAttachmentFibrantModelEquivalence
    {B : Type u₁} [Bicategory.{w₁, v₁} B]
    {C : Type u₂} [Bicategory.{w₂, v₂} C]
    (E : BicategoricalModelEquivalence B C)
    (G : BicategoricalModelEquivalence C B)
    (HB : GlobalDuskinScaledHornFamily B)
    (HC : GlobalDuskinScaledHornFamily C) where
  homotopyClassModel :
    CoherentNormalizedScaledHomotopyClassModelEquivalence E G HB HC
  sourceAttachmentFibrant :
    IsAttachmentFibrant
      (ScaledSSet.of (duskinNerve B) (duskinScaling B))
  targetAttachmentFibrant :
    IsAttachmentFibrant
      (ScaledSSet.of (duskinNerve C) (duskinScaling C))

namespace CoherentNormalizedScaledAttachmentFibrantModelEquivalence

variable
    {B : Type u₁} [Bicategory.{w₁, v₁} B]
    {C : Type u₂} [Bicategory.{w₂, v₂} C]
    {E : BicategoricalModelEquivalence B C}
    {G : BicategoricalModelEquivalence C B}
    {HB : GlobalDuskinScaledHornFamily B}
    {HC : GlobalDuskinScaledHornFamily C}
    (K : CoherentNormalizedScaledAttachmentFibrantModelEquivalence E G HB HC)

/-- Target-level attachment fibrancy recovers the v1.41 family-specific
terminal-RLP package only when needed. -/
noncomputable def toTerminalRLPModelEquivalence :
    CoherentNormalizedScaledTerminalRLPModelEquivalence E G HB HC where
  homotopyClassModel := K.homotopyClassModel
  sourceTerminalRLP :=
    familyTerminalRLPOfAttachmentFibrant K.sourceAttachmentFibrant HB
  targetTerminalRLP :=
    familyTerminalRLPOfAttachmentFibrant K.targetAttachmentFibrant HC

/-- Strict global scaled-Duskin fibrancy is presentation-independent once both
global nerves are fibrant for the canonical attachment-generated right class. -/
theorem globalDuskinStrictFibrancy_iff :
    HasScaledHornFillers (duskinNerve B) (duskinScaling B) HB ↔
      HasScaledHornFillers (duskinNerve C) (duskinScaling C) HC :=
  K.toTerminalRLPModelEquivalence.globalDuskinStrictFibrancy_iff

end CoherentNormalizedScaledAttachmentFibrantModelEquivalence

/-!
The strict-fibrancy spine is now controlled by a morphism-property Galois
closure rather than by per-family lifting fields:

```text
canonical horn-cylinder attachment inclusions
  -> MorphismProperty T
  -> canonical scaled-anodyne closure T.rlp.llp

Mathlib theorem:
  (T.rlp.llp).rlp = T.rlp

therefore:
  generator RLP
  = canonical generated-anodyne RLP
  = RLP of every compatible intermediate presentation

terminal map in this common right class
  -> terminal RLP for every scaled horn problem
  -> terminal RLP for every chosen horn family
  -> homotopy-class strictification
  -> strict fibrancy

coherent normalized scaled model equivalence
  + attachment-fibrancy of both global Duskin nerves
  -> presentation-independent strict scaled fibrancy.
```

The remaining external comparison problem is now a statement between morphism
properties: identify a future standard scaled-anodyne class with, or sandwich
it between, the canonical attachment generators and their Galois closure.  No
ordinary/unscaled anodyne theorem is used for that identification here.
-/

end KUOS.DependentOriginationScaledAnodyneGeneratorClosureV1_42
