import KUOS.DependentOriginationScaledCartesianIntervalCylinderV1_52

namespace KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53

open CategoryTheory
open CategoryTheory.Category
open MonoidalCategory
open Opposite
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationGlobalDuskinScaledHornCoherenceV1_22
open KUOS.DependentOriginationScaledHornAttachmentLiftingV1_40
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationScaledAnodyneAttachmentFactorizationV1_48
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49
open KUOS.DependentOriginationStandardTypeAEndpointPushoutProductV1_50
open KUOS.DependentOriginationStandardTypeANativeLeibnizLiftingMateV1_51
open KUOS.DependentOriginationScaledCartesianIntervalCylinderV1_52

universe u

/-!
# Standard type-(A) scaled pushout source enrichment v1.53

Version 1.52 identified the cylinder scaling used by the KuuOS type-(A)
attachment with the cartesian-product scaling of the scaled simplex and the
simplicial interval.  The remaining difference from the native Leibniz
pushout is therefore entirely a source-scaling issue.

This file isolates that issue without inserting any model-structure axiom.
On the ordinary union-product carrier

```text
(Delta[n] x {epsilon}) union (Lambda_i^n x Delta[1])
```

we construct the least KuuOS scaling generated by the two restriction legs.
The construction contains only

* the mandatory degenerate 2-simplices; and
* images of thin 2-simplices from either leg.

It satisfies the expected universal property among scalings on the fixed
union-product carrier.  Since both restriction legs already map to the full
pullback scaling induced from the product target, the generated scaling is
contained in that induced scaling.  Hence the identity underlying simplicial
map gives a canonical source-scaling enrichment

```text
least generated pushout source
  --> induced pullback-scaled source.
```

Composing this enrichment with the v1.50 induced attachment inclusion recovers
exactly the endpoint pushout-product map.  Thus native Leibniz geometry and the
extra source thinness are now separated by an explicit theorem-level factor.
-/

/-! ## Ordering explicit scalings on a fixed carrier -/

/-- Inclusion of thin 2-simplices between two scalings on the same simplicial
set. -/
def ScalingLE
    {X : SSet.{u}}
    (s₁ s₂ : ScaledSimplicialSet X) : Prop :=
  ∀ t, s₁.thin t → s₂.thin t

@[refl]
theorem ScalingLE.refl
    {X : SSet.{u}}
    (s : ScaledSimplicialSet X) :
    ScalingLE s s := by
  intro t ht
  exact ht

@[trans]
theorem ScalingLE.trans
    {X : SSet.{u}}
    {s₁ s₂ s₃ : ScaledSimplicialSet X}
    (h₁₂ : ScalingLE s₁ s₂)
    (h₂₃ : ScalingLE s₂ s₃) :
    ScalingLE s₁ s₃ := by
  intro t ht
  exact h₂₃ t (h₁₂ t ht)

/-- Mutual inclusion of thin triangles identifies the scalings. -/
theorem scaling_eq_of_le_antisymm
    {X : SSet.{u}}
    {s₁ s₂ : ScaledSimplicialSet X}
    (h₁₂ : ScalingLE s₁ s₂)
    (h₂₁ : ScalingLE s₂ s₁) :
    s₁ = s₂ := by
  apply scaling_eq_of_thin_iff
  intro t
  exact ⟨h₁₂ t, h₂₁ t⟩

/-! ## The product target and its restriction to the union-product source -/

/-- The canonical cartesian-product scaling on the type-(A) simplex cylinder,
using the unique/maximal interval scaling from v1.52. -/
def standardTypeAEndpointCylinderProductScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScaledSimplicialSet ((Δ[g.n] : SSet.{u}) ⊗ Δ[1]) :=
  cartesianProductScaling
    (standardTypeASimplexScaling g.i)
    (ScaledSimplicialSet.maximal (Δ[1] : SSet.{u}))

/-- Pull the cartesian-product target scaling back to the ordinary endpoint
union-product carrier. -/
def standardTypeAEndpointInducedProductPullbackScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScaledSimplicialSet
      ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint) : SSet.{u}) :=
  pullbackScaling
    (standardTypeAEndpointCylinderProductScaling g)
    ((SSet.horn g.n g.i).unionProd
      (intervalEndpoint g.endpoint)).ι

/-- This product-pullback presentation is literally the scaling of the v1.50
induced endpoint-pushout-product source. -/
theorem standardTypeAEndpointPushoutProductSource_scaling_eq_inducedProductPullback
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointPushoutProductSource g).scaling =
      standardTypeAEndpointInducedProductPullbackScaling g := by
  simpa [standardTypeAEndpointInducedProductPullbackScaling,
    standardTypeAEndpointCylinderProductScaling] using
    standardTypeAEndpointPushoutProductSource_scaling_eq_pullback_product
      g (ScaledSimplicialSet.maximal (Δ[1] : SSet.{u}))

/-! ## Restriction scalings on the two Leibniz legs -/

/-- The scaling on `Delta[n] x {epsilon}` obtained by restricting the induced
union-product scaling along the first union leg. -/
def standardTypeAEndpointSimplexEndpointLegScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScaledSimplicialSet
      ((Δ[g.n] : SSet.{u}) ⊗
        (intervalEndpoint g.endpoint : SSet.{u})) :=
  pullbackScaling
    (standardTypeAEndpointInducedProductPullbackScaling g)
    (SSet.Subcomplex.unionProd.ι₁
      (SSet.horn g.n g.i) (intervalEndpoint g.endpoint))

/-- The scaling on `Lambda_i^n x Delta[1]` obtained by restricting the induced
union-product scaling along the second union leg. -/
def standardTypeAEndpointHornIntervalLegScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScaledSimplicialSet
      ((SSet.horn g.n g.i : SSet.{u}) ⊗ Δ[1]) :=
  pullbackScaling
    (standardTypeAEndpointInducedProductPullbackScaling g)
    (SSet.Subcomplex.unionProd.ι₂
      (SSet.horn g.n g.i) (intervalEndpoint g.endpoint))

/-! ## Least scaling generated by the two legs -/

/-- The least explicit scaling on the union-product carrier generated by the
two restriction legs.  Besides the mandatory degeneracies, a triangle is thin
exactly when it is the image of a thin triangle from one of the two legs. -/
def standardTypeAEndpointGeneratedPushoutScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScaledSimplicialSet
      ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint) : SSet.{u}) where
  thin := fun t =>
    (∃ x :
        ((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint) : SSet.{u}).obj (op ⦋1⦌),
      ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint) : SSet.{u}).σ 0 x = t) ∨
    (∃ x :
        ((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint) : SSet.{u}).obj (op ⦋1⦌),
      ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint) : SSet.{u}).σ 1 x = t) ∨
    (∃ x :
        ((Δ[g.n] : SSet.{u}) ⊗
          (intervalEndpoint g.endpoint : SSet.{u})).obj (op ⦋2⦌),
      (standardTypeAEndpointSimplexEndpointLegScaling g).thin x ∧
        (SSet.Subcomplex.unionProd.ι₁
          (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)).app
            (op ⦋2⦌) x = t) ∨
    ∃ x :
        ((SSet.horn g.n g.i : SSet.{u}) ⊗ Δ[1]).obj (op ⦋2⦌),
      (standardTypeAEndpointHornIntervalLegScaling g).thin x ∧
        (SSet.Subcomplex.unionProd.ι₂
          (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)).app
            (op ⦋2⦌) x = t
  thin_sigma_zero := by
    intro x
    exact Or.inl ⟨x, rfl⟩
  thin_sigma_one := by
    intro x
    exact Or.inr (Or.inl ⟨x, rfl⟩)

/-- The first union leg is scaled for the generated pushout scaling. -/
theorem standardTypeAEndpointGeneratedPushout_inl_scaled
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    IsScaledMap
      (standardTypeAEndpointSimplexEndpointLegScaling g)
      (standardTypeAEndpointGeneratedPushoutScaling g)
      (SSet.Subcomplex.unionProd.ι₁
        (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)) := by
  intro t ht
  exact Or.inr (Or.inr (Or.inl ⟨t, ht, rfl⟩))

/-- The second union leg is scaled for the generated pushout scaling. -/
theorem standardTypeAEndpointGeneratedPushout_inr_scaled
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    IsScaledMap
      (standardTypeAEndpointHornIntervalLegScaling g)
      (standardTypeAEndpointGeneratedPushoutScaling g)
      (SSet.Subcomplex.unionProd.ι₂
        (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)) := by
  intro t ht
  exact Or.inr (Or.inr (Or.inr ⟨t, ht, rfl⟩))

/-- Universal property on the fixed carrier: the generated scaling is below
any scaling for which both union legs are scaled. -/
theorem standardTypeAEndpointGeneratedPushoutScaling_le_of_legs_scaled
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (s : ScaledSimplicialSet
      ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint) : SSet.{u}))
    (h₁ : IsScaledMap
      (standardTypeAEndpointSimplexEndpointLegScaling g) s
      (SSet.Subcomplex.unionProd.ι₁
        (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)))
    (h₂ : IsScaledMap
      (standardTypeAEndpointHornIntervalLegScaling g) s
      (SSet.Subcomplex.unionProd.ι₂
        (SSet.horn g.n g.i) (intervalEndpoint g.endpoint))) :
    ScalingLE (standardTypeAEndpointGeneratedPushoutScaling g) s := by
  intro t ht
  rcases ht with ⟨x, rfl⟩ | ⟨x, rfl⟩ | ⟨x, hx, rfl⟩ | ⟨x, hx, rfl⟩
  · exact s.thin_sigma_zero x
  · exact s.thin_sigma_one x
  · exact h₁ x hx
  · exact h₂ x hx

/-- Both restriction legs are scaled into the full induced pullback scaling by
construction. -/
theorem standardTypeAEndpointLegs_scaled_to_inducedProductPullback
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    IsScaledMap
        (standardTypeAEndpointSimplexEndpointLegScaling g)
        (standardTypeAEndpointInducedProductPullbackScaling g)
        (SSet.Subcomplex.unionProd.ι₁
          (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)) ∧
      IsScaledMap
        (standardTypeAEndpointHornIntervalLegScaling g)
        (standardTypeAEndpointInducedProductPullbackScaling g)
        (SSet.Subcomplex.unionProd.ι₂
          (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)) := by
  constructor
  · exact pullbackScaling_map _ _
  · exact pullbackScaling_map _ _

/-- Therefore the least generated pushout scaling is contained in the full
pullback scaling induced from the cartesian-product cylinder. -/
theorem standardTypeAEndpointGeneratedPushoutScaling_le_induced
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScalingLE
      (standardTypeAEndpointGeneratedPushoutScaling g)
      (standardTypeAEndpointInducedProductPullbackScaling g) := by
  rcases standardTypeAEndpointLegs_scaled_to_inducedProductPullback g with
    ⟨h₁, h₂⟩
  exact standardTypeAEndpointGeneratedPushoutScaling_le_of_legs_scaled
    g (standardTypeAEndpointInducedProductPullbackScaling g) h₁ h₂

/-! ## The explicit source-scaling enrichment -/

/-- The endpoint Leibniz source equipped with only the least scaling generated
by the two restriction legs. -/
def standardTypeAEndpointGeneratedPushoutSource
    (g : StandardTypeAHornAttachmentGeneratorIndex) : ScaledSSet.{u} :=
  ScaledSSet.of
    ((SSet.horn g.n g.i).unionProd
      (intervalEndpoint g.endpoint) : SSet.{u})
    (standardTypeAEndpointGeneratedPushoutScaling g)

/-- Canonical source-scaling enrichment from the least generated scaling to the
full induced pullback scaling.  Its underlying simplicial map is the identity. -/
def standardTypeAEndpointGeneratedToInduced
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointGeneratedPushoutSource g ⟶
      standardTypeAEndpointPushoutProductSource g where
  map := 𝟙 _
  scaled := by
    intro t ht
    rw [standardTypeAEndpointPushoutProductSource_scaling_eq_inducedProductPullback g]
    simpa using
      standardTypeAEndpointGeneratedPushoutScaling_le_induced g t ht

@[simp]
theorem standardTypeAEndpointGeneratedToInduced_map
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointGeneratedToInduced g).map = 𝟙 _ :=
  rfl

/-- The actual endpoint inclusion from the least generated source is obtained
by composing the source enrichment with the v1.50 induced inclusion. -/
def standardTypeAEndpointGeneratedPushoutProductHom
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointGeneratedPushoutSource g ⟶
      scaledSimplexCylinder (standardTypeASimplexScaling g.i) :=
  standardTypeAEndpointGeneratedToInduced g ≫
    standardTypeAEndpointPushoutProductHom g

/-- Its underlying map is still exactly the ordinary union-product inclusion. -/
theorem standardTypeAEndpointGeneratedPushoutProductHom_map
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointGeneratedPushoutProductHom g).map =
      ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint)).ι := by
  simp [standardTypeAEndpointGeneratedPushoutProductHom,
    standardTypeAEndpointGeneratedToInduced,
    standardTypeAEndpointPushoutProductHom]

/-- The endpoint map factors exactly into least-generated geometry followed by
source-scaling enrichment and then the induced attachment inclusion. -/
theorem standardTypeAEndpointGeneratedPushoutProduct_factorization
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointGeneratedToInduced g ≫
        standardTypeAEndpointPushoutProductHom g =
      standardTypeAEndpointGeneratedPushoutProductHom g := by
  rfl

/-! ## Package the residual source-enrichment family -/

/-- The residual type-(A) source-scaling enrichments separating the least
scaled Leibniz pushout source from the v1.50 induced source. -/
def standardTypeAEndpointSourceEnrichments :
    MorphismProperty (ScaledSSet.{u}) :=
  MorphismProperty.ofHoms
    (fun g : StandardTypeAHornAttachmentGeneratorIndex =>
      standardTypeAEndpointGeneratedToInduced g)

/-- Every residual source enrichment lies in its generator property. -/
theorem standardTypeAEndpointSourceEnrichment_mem
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointSourceEnrichments : MorphismProperty (ScaledSSet.{u}))
      (standardTypeAEndpointGeneratedToInduced g) :=
  MorphismProperty.ofHoms.mk g

/-!
The type-(A) comparison has now been split into three theorem-level layers:

```text
ordinary unionProd / native Leibniz geometry          (v1.50-v1.51)
  -> least scaling generated by its two restriction legs
  -> identity source-scaling enrichment               (v1.53)
  -> full induced pullback scaling
  -> induced endpoint attachment into the cylinder.
```

The key point is that the extra thin triangles are no longer hidden in the
word "pushout-product": they are carried by the explicit morphism family
`standardTypeAEndpointSourceEnrichments`.

A subsequent closure theorem can therefore treat native Leibniz stability and
source-scaling enrichment as separate hypotheses or prove them separately.
No type-(B)/(C) generator and no full Lurie comparison is asserted here.
-/

end KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
