import KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseScaledPushoutV1_73

namespace KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseSimultaneousAPhaseV1_74

open CategoryTheory
open CategoryTheory.Category
open CategoryTheory.Limits
open Opposite
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationScaledAnodyneAttachmentFactorizationV1_48
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49
open KUOS.DependentOriginationStandardTypeAEndpointPushoutProductV1_50
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
open KUOS.DependentOriginationStandardTypeCCollapsedEdgeV1_58
open KUOS.DependentOriginationStandardABCLeibnizCellularComparisonV1_59
open KUOS.DependentOriginationStandardTypeABoundaryPrismRelativeCellV1_61
open KUOS.DependentOriginationStandardTypeABoundaryPrismScaledCellsV1_62
open KUOS.DependentOriginationStandardTypeABoundaryPrismCellPushoutCriterionV1_65
open KUOS.DependentOriginationStandardTypeABoundaryPrismCellACompatibilityV1_66
open KUOS.DependentOriginationStandardTypeABoundaryPrismScaledRankFiltrationV1_71
open KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseABCellularityV1_72
open KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseScaledPushoutV1_73

universe u

noncomputable section

/-!
# Simultaneous type-(A) rank phase for the boundary prism v1.74

Version v1.73 proved that the ordinary Mathlib rank square is already an exact
pushout in `ScaledSSet` when the coproduct of attached simplices carries its
*exact ambient* scaling.  That square is not yet one raw standard cellular
step: an exceptional exact cell is locally `A ; B`, so its exact simplex
scaling is stronger than the standard type-(A) target scaling.

The correct global factorization is therefore

```text
R_j  -- simultaneous standard A attachments -->  A_j
     -- simultaneous exceptional B completions --> R_(j+1).
```

This file constructs the first arrow without serializing cells.

For every rank cell `c`, take the literal standard type-(A) horn generator at
`c.index`.  On Mathlib's existing coproduct carriers `sigmaHorn j` and
`sigmaStdSimplex j`, put the least scalings generated by the images of those
standard A source and target scalings.  We prove directly that these are
categorical coproducts in `ScaledSSet`; consequently Mathlib's ordinary
coproduct horn map `m j` is literally a coproduct of standard A generators.

We then push that one coproduct map along the ordinary attaching map `t j`.
The underlying ordinary pushout is exactly the existing rank square, so the
intermediate A-phase carrier is already the ordinary successor filtration.
Only its scaling is weaker: it is generated by the current rank stage and all
standard-A target images.  The generic generated-pushout theorem of v1.73
upgrades the square to a genuine scaled pushout.

The main output is

```text
R_j -> A_j ∈ pushouts (coproducts E_std),
```

i.e. one raw standard A/B/C cellular step, using only type-(A) generators.
Finally we prove `A_j -> R_(j+1)` is the identity on the underlying simplicial
set and is scaled.  This is the exact interface needed for the simultaneous
exceptional-B phase in the next unit.
-/

/-! ## Rankwise coproduct scalings generated by literal standard A cells -/

/-- Least scaling on Mathlib's coproduct of rank-`j` horns generated by the
literal standard type-(A) horn scaling of every cell. -/
def standardTypeABoundaryPrismRankAHornSigmaScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    ScaledSimplicialSet
      ((standardTypeABoundaryPrismRankFunction g).sigmaHorn j) where
  thin := fun t =>
    (minimalScaling
      ((standardTypeABoundaryPrismRankFunction g).sigmaHorn j)).thin t ∨
      ∃ (c : (standardTypeABoundaryPrismRankFunction g).Cell j)
        (x : (c.horn : SSet.{u}).obj (op ⦋2⦌)),
        (standardTypeAHornScaling c.index).thin x ∧
          c.ιSigmaHorn.app (op ⦋2⦌) x = t
  thin_sigma_zero := by
    intro x
    exact Or.inl
      ((minimalScaling
        ((standardTypeABoundaryPrismRankFunction g).sigmaHorn j)).thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl
      ((minimalScaling
        ((standardTypeABoundaryPrismRankFunction g).sigmaHorn j)).thin_sigma_one x)

/-- Least scaling on Mathlib's coproduct of rank-`j` simplices generated by the
literal standard type-(A) simplex scaling of every cell. -/
def standardTypeABoundaryPrismRankASimplexSigmaScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    ScaledSimplicialSet
      ((standardTypeABoundaryPrismRankFunction g).sigmaStdSimplex j) where
  thin := fun t =>
    (minimalScaling
      ((standardTypeABoundaryPrismRankFunction g).sigmaStdSimplex j)).thin t ∨
      ∃ (c : (standardTypeABoundaryPrismRankFunction g).Cell j)
        (x : (Δ[c.dim + 1] : SSet.{u}).obj (op ⦋2⦌)),
        (standardTypeASimplexScaling c.index).thin x ∧
          c.ιSigmaStdSimplex.app (op ⦋2⦌) x = t
  thin_sigma_zero := by
    intro x
    exact Or.inl
      ((minimalScaling
        ((standardTypeABoundaryPrismRankFunction g).sigmaStdSimplex j)).thin_sigma_zero x)
  thin_sigma_one := by
    intro x
    exact Or.inl
      ((minimalScaling
        ((standardTypeABoundaryPrismRankFunction g).sigmaStdSimplex j)).thin_sigma_one x)

/-- Rankwise standard-A coproduct horn object on the exact ordinary Mathlib
carrier. -/
def standardTypeABoundaryPrismRankAHornSigma
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : ScaledSSet.{u} :=
  ScaledSSet.of
    ((standardTypeABoundaryPrismRankFunction g).sigmaHorn j)
    (standardTypeABoundaryPrismRankAHornSigmaScaling g j)

/-- Rankwise standard-A coproduct simplex object on the exact ordinary Mathlib
carrier. -/
def standardTypeABoundaryPrismRankASimplexSigma
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : ScaledSSet.{u} :=
  ScaledSSet.of
    ((standardTypeABoundaryPrismRankFunction g).sigmaStdSimplex j)
    (standardTypeABoundaryPrismRankASimplexSigmaScaling g j)

/-- The literal standard-A horn object associated to one rank cell. -/
abbrev standardTypeABoundaryPrismRankAHornCell
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (c : (standardTypeABoundaryPrismRankFunction g).Cell j) : ScaledSSet.{u} :=
  standardTypeAScaledHorn
    (standardTypeABoundaryPrismCellHornIndex g j c)

/-- The literal standard-A simplex object associated to one rank cell. -/
abbrev standardTypeABoundaryPrismRankASimplexCell
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (c : (standardTypeABoundaryPrismRankFunction g).Cell j) : ScaledSSet.{u} :=
  standardTypeAScaledSimplex
    (standardTypeABoundaryPrismCellHornIndex g j c)

/-- Inclusion of one literal standard-A horn into the rankwise A-source
coproduct. -/
def standardTypeABoundaryPrismRankAHornSigmaInclusion
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (c : (standardTypeABoundaryPrismRankFunction g).Cell j) :
    standardTypeABoundaryPrismRankAHornCell g j c ⟶
      standardTypeABoundaryPrismRankAHornSigma g j where
  map := c.ιSigmaHorn
  scaled := by
    intro t ht
    exact Or.inr ⟨c, t, ht, rfl⟩

/-- Inclusion of one literal standard-A simplex into the rankwise A-target
coproduct. -/
def standardTypeABoundaryPrismRankASimplexSigmaInclusion
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ)
    (c : (standardTypeABoundaryPrismRankFunction g).Cell j) :
    standardTypeABoundaryPrismRankASimplexCell g j c ⟶
      standardTypeABoundaryPrismRankASimplexSigma g j where
  map := c.ιSigmaStdSimplex
  scaled := by
    intro t ht
    exact Or.inr ⟨c, t, ht, rfl⟩

/-! ## These exact ordinary carriers are categorical coproducts in ScaledSSet -/

/-- Cofan of all literal standard-A horn sources. -/
noncomputable def standardTypeABoundaryPrismRankAHornCofan
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    Cofan
      (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
        standardTypeABoundaryPrismRankAHornCell g j c) :=
  Cofan.mk (standardTypeABoundaryPrismRankAHornSigma g j)
    (fun c => standardTypeABoundaryPrismRankAHornSigmaInclusion g j c)

/-- The preceding horn cofan is colimiting in `ScaledSSet`. -/
noncomputable def standardTypeABoundaryPrismRankAHornCofanIsColimit
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    IsColimit (standardTypeABoundaryPrismRankAHornCofan g j) where
  desc s :=
    { map := Sigma.desc
        (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
          (s.ι.app ⟨c⟩).map)
      scaled := by
        intro t ht
        rcases ht with hmin | ⟨c, x, hx, rfl⟩
        · exact
            (minimalScaling_map s.pt.scaling
              (Sigma.desc
                (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
                  (s.ι.app ⟨c⟩).map))) t hmin
        · have hs := (s.ι.app ⟨c⟩).scaled x hx
          change
            s.pt.scaling.thin
              (((c.ιSigmaHorn ≫
                Sigma.desc
                  (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
                    (s.ι.app ⟨c⟩).map)).app (op ⦋2⦌)) x)
          have hdesc :
              c.ιSigmaHorn ≫
                  Sigma.desc
                    (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
                      (s.ι.app ⟨c⟩).map) =
                (s.ι.app ⟨c⟩).map := by
            exact Sigma.ι_desc _ c
          rw [hdesc]
          exact hs }
  fac s c := by
    rcases c with ⟨c⟩
    apply ScaledSSet.ScaledMap.ext
    change
      c.ιSigmaHorn ≫
          Sigma.desc
            (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
              (s.ι.app ⟨c⟩).map) =
        (s.ι.app ⟨c⟩).map
    exact Sigma.ι_desc _ c
  uniq s m hm := by
    apply ScaledSSet.ScaledMap.ext
    apply Sigma.hom_ext
    intro c
    have hc := congrArg ScaledSSet.ScaledMap.map (hm ⟨c⟩)
    change
      c.ιSigmaHorn ≫ m.map =
        c.ιSigmaHorn ≫
          Sigma.desc
            (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
              (s.ι.app ⟨c⟩).map)
    rw [hc]
    exact (Sigma.ι_desc _ c).symm

/-- Cofan of all literal standard-A simplex targets. -/
noncomputable def standardTypeABoundaryPrismRankASimplexCofan
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    Cofan
      (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
        standardTypeABoundaryPrismRankASimplexCell g j c) :=
  Cofan.mk (standardTypeABoundaryPrismRankASimplexSigma g j)
    (fun c => standardTypeABoundaryPrismRankASimplexSigmaInclusion g j c)

/-- The preceding simplex cofan is colimiting in `ScaledSSet`. -/
noncomputable def standardTypeABoundaryPrismRankASimplexCofanIsColimit
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    IsColimit (standardTypeABoundaryPrismRankASimplexCofan g j) where
  desc s :=
    { map := Sigma.desc
        (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
          (s.ι.app ⟨c⟩).map)
      scaled := by
        intro t ht
        rcases ht with hmin | ⟨c, x, hx, rfl⟩
        · exact
            (minimalScaling_map s.pt.scaling
              (Sigma.desc
                (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
                  (s.ι.app ⟨c⟩).map))) t hmin
        · have hs := (s.ι.app ⟨c⟩).scaled x hx
          change
            s.pt.scaling.thin
              (((c.ιSigmaStdSimplex ≫
                Sigma.desc
                  (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
                    (s.ι.app ⟨c⟩).map)).app (op ⦋2⦌)) x)
          have hdesc :
              c.ιSigmaStdSimplex ≫
                  Sigma.desc
                    (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
                      (s.ι.app ⟨c⟩).map) =
                (s.ι.app ⟨c⟩).map := by
            exact Sigma.ι_desc _ c
          rw [hdesc]
          exact hs }
  fac s c := by
    rcases c with ⟨c⟩
    apply ScaledSSet.ScaledMap.ext
    change
      c.ιSigmaStdSimplex ≫
          Sigma.desc
            (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
              (s.ι.app ⟨c⟩).map) =
        (s.ι.app ⟨c⟩).map
    exact Sigma.ι_desc _ c
  uniq s m hm := by
    apply ScaledSSet.ScaledMap.ext
    apply Sigma.hom_ext
    intro c
    have hc := congrArg ScaledSSet.ScaledMap.map (hm ⟨c⟩)
    change
      c.ιSigmaStdSimplex ≫ m.map =
        c.ιSigmaStdSimplex ≫
          Sigma.desc
            (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
              (s.ι.app ⟨c⟩).map)
    rw [hc]
    exact (Sigma.ι_desc _ c).symm

/-! ## The coproduct map is literally the coproduct of standard A generators -/

/-- Mathlib's ordinary coproduct horn map, now between the literal standard-A
coproduct scalings. -/
def standardTypeABoundaryPrismRankASigmaCellHom
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankAHornSigma g j ⟶
      standardTypeABoundaryPrismRankASimplexSigma g j where
  map := (standardTypeABoundaryPrismRankFunction g).m j
  scaled := by
    intro t ht
    rcases ht with hmin | ⟨c, x, hx, rfl⟩
    · exact
        (minimalScaling_map
          (standardTypeABoundaryPrismRankASimplexSigmaScaling g j)
          ((standardTypeABoundaryPrismRankFunction g).m j)) t hmin
    · right
      refine ⟨c, c.horn.ι.app (op ⦋2⦌) x, ?_, ?_⟩
      · exact standardTypeAHornInclusion_scaled c.index x hx
      · have h := ConcreteCategory.congr_hom
          (congr_app c.ι_m (op ⦋2⦌)) x
        exact h.symm

/-- Naturality package of the rankwise family of literal standard-A
generators. -/
noncomputable def standardTypeABoundaryPrismRankAGeneratorNatTrans
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    Discrete.functor
        (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
          standardTypeABoundaryPrismRankAHornCell g j c) ⟶
      Discrete.functor
        (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
          standardTypeABoundaryPrismRankASimplexCell g j c) :=
  Discrete.natTrans
    (fun ⟨c⟩ =>
      standardTypeAScaledHornGeneratorHom
        (standardTypeABoundaryPrismCellHornIndex g j c))

/-- The exact rankwise A coproduct map belongs to `coproducts E_std`. -/
theorem standardTypeABoundaryPrismRankASigmaCellHom_mem_coproductsABC
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    (MorphismProperty.coproducts.{u}
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})))
      (standardTypeABoundaryPrismRankASigmaCellHom g j) := by
  rw [MorphismProperty.coproducts_iff]
  refine ⟨(standardTypeABoundaryPrismRankFunction g).Cell j, ?_⟩
  refine MorphismProperty.colimitsOfShape.mk'
    (W := (standardScaledAnodyneGeneratorsABC :
      MorphismProperty (ScaledSSet.{u})))
    (Discrete.functor
      (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
        standardTypeABoundaryPrismRankAHornCell g j c))
    (Discrete.functor
      (fun c : (standardTypeABoundaryPrismRankFunction g).Cell j =>
        standardTypeABoundaryPrismRankASimplexCell g j c))
    (standardTypeABoundaryPrismRankAHornCofan g j)
    (standardTypeABoundaryPrismRankASimplexCofan g j)
    (standardTypeABoundaryPrismRankAHornCofanIsColimit g j)
    (standardTypeABoundaryPrismRankASimplexCofanIsColimit g j)
    (standardTypeABoundaryPrismRankAGeneratorNatTrans g j) ?_
    (standardTypeABoundaryPrismRankASigmaCellHom g j) ?_
  · intro c
    rcases c with ⟨c⟩
    exact standardTypeAGenerator_mem_ABC
      (standardTypeABoundaryPrismCellHornIndex g j c)
  · intro c
    rcases c with ⟨c⟩
    apply ScaledSSet.ScaledMap.ext
    exact c.ι_m

/-! ## Attach the simultaneous A coproduct to the current rank stage -/

/-- The rankwise standard-A coproduct horn maps to the current exact rank
stage.  Standard A horn thinness enters the exact horn scaling by v1.66. -/
def standardTypeABoundaryPrismRankAHornSigmaToStage
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankAHornSigma g j ⟶
      standardTypeABoundaryPrismRankStage g j where
  map := (standardTypeABoundaryPrismRankFunction g).t j
  scaled := by
    intro t ht
    rcases ht with hmin | ⟨c, x, hx, rfl⟩
    · exact
        (minimalScaling_map
          (standardTypeABoundaryPrismRankStageScaling g j)
          ((standardTypeABoundaryPrismRankFunction g).t j)) t hmin
    · have hx' :=
        standardTypeABoundaryPrismCellHorn_ACompatible
          g j c (standardTypeABoundaryPrismCellACompatible_all g j c) x hx
      have hs :=
        (standardTypeABoundaryPrismScaledCellSourceToRankStage g j c).scaled x hx'
      change
        (standardTypeABoundaryPrismRankStageScaling g j).thin
          (((c.ιSigmaHorn ≫
            (standardTypeABoundaryPrismRankFunction g).t j).app
              (op ⦋2⦌)) x)
      rw [c.ι_t]
      exact hs

/-- Scaling on the intermediate A-phase carrier.  Its underlying simplicial
set is already the ordinary successor rank stage. -/
def standardTypeABoundaryPrismRankAPhaseScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    ScaledSimplicialSet
      ((standardTypeABoundaryPrismRankFunction g).filtration (j + 1) : SSet.{u}) :=
  generatedPushoutScaling
    (standardTypeABoundaryPrismRankStageScaling g j)
    (standardTypeABoundaryPrismRankASimplexSigmaScaling g j)
    (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map
    ((standardTypeABoundaryPrismRankFunction g).b j)

/-- Intermediate rank object after all standard-A cells have been attached
simultaneously. -/
def standardTypeABoundaryPrismRankAPhase
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) : ScaledSSet.{u} :=
  ScaledSSet.of
    ((standardTypeABoundaryPrismRankFunction g).filtration (j + 1) : SSet.{u})
    (standardTypeABoundaryPrismRankAPhaseScaling g j)

/-- First leg `R_j -> A_j` of the rankwise A/B factorization. -/
def standardTypeABoundaryPrismRankStageToAPhase
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankStage g j ⟶
      standardTypeABoundaryPrismRankAPhase g j :=
  generatedPushoutInl
    (standardTypeABoundaryPrismRankStageScaling g j)
    (standardTypeABoundaryPrismRankASimplexSigmaScaling g j)
    (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map
    ((standardTypeABoundaryPrismRankFunction g).b j)

/-- Bottom leg from the coproduct of standard-A simplex targets into `A_j`. -/
def standardTypeABoundaryPrismRankASimplexSigmaToAPhase
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankASimplexSigma g j ⟶
      standardTypeABoundaryPrismRankAPhase g j :=
  generatedPushoutInr
    (standardTypeABoundaryPrismRankStageScaling g j)
    (standardTypeABoundaryPrismRankASimplexSigmaScaling g j)
    (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map
    ((standardTypeABoundaryPrismRankFunction g).b j)

/-- The simultaneous all-A square is a genuine categorical pushout in
`ScaledSSet`. -/
noncomputable def standardTypeABoundaryPrism_rankA_scaled_isPushout
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    IsPushout
      (standardTypeABoundaryPrismRankAHornSigmaToStage g j)
      (standardTypeABoundaryPrismRankASigmaCellHom g j)
      (standardTypeABoundaryPrismRankStageToAPhase g j)
      (standardTypeABoundaryPrismRankASimplexSigmaToAPhase g j) := by
  exact generatedPushout_isPushout
    (standardTypeABoundaryPrismRankAHornSigmaToStage g j)
    (standardTypeABoundaryPrismRankASigmaCellHom g j)
    (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).map
    ((standardTypeABoundaryPrismRankFunction g).b j)
    (standardTypeABoundaryPrism_rankStep_isPushout g j)

/-- Main cellular output of v1.74: attaching *all* rank-`j` standard A cells
simultaneously is one raw standard cellular step. -/
theorem standardTypeABoundaryPrismRankStageToAPhase_mem_rawCellular
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardABCRawCellularStep
      (standardTypeABoundaryPrismRankStageToAPhase g j) := by
  let P : MorphismProperty (ScaledSSet.{u}) :=
    MorphismProperty.coproducts.{u}
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u}))
  change P.pushouts (standardTypeABoundaryPrismRankStageToAPhase g j)
  exact P.pushouts_mk
    (standardTypeABoundaryPrism_rankA_scaled_isPushout g j)
    (standardTypeABoundaryPrismRankASigmaCellHom_mem_coproductsABC g j)

/-! ## Compare the A-phase scaling with the exact successor scaling -/

/-- Every A-phase thin triangle is already thin in the exact ambient successor
rank scaling.  The only extra thin triangles still missing from `A_j` are the
exceptional type-(B) completion triangles classified in v1.70. -/
theorem standardTypeABoundaryPrismRankAPhaseScaling_le_succ
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    ScalingLE
      (standardTypeABoundaryPrismRankAPhaseScaling g j)
      (standardTypeABoundaryPrismRankStageScaling g (j + 1)) := by
  intro t ht
  rcases ht with hmin | ⟨x, hx, rfl⟩ | ⟨y, hy, rfl⟩
  · rcases hmin with ⟨x, rfl⟩ | ⟨x, rfl⟩
    · exact
        (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin_sigma_zero x
    · exact
        (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin_sigma_one x
  · exact
      (standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j)).scaled x hx
  · rcases hy with hmin | ⟨c, x, hx, rfl⟩
    · exact
        (minimalScaling_map
          (standardTypeABoundaryPrismRankStageScaling g (j + 1))
          ((standardTypeABoundaryPrismRankFunction g).b j)) y hmin
    · have hcell :=
        standardTypeABoundaryPrismCellACompatible_all g j c x hx
      have hs :=
        (standardTypeABoundaryPrismScaledCellTargetToRankSucc g j c).scaled x hcell
      change
        (standardTypeABoundaryPrismRankStageScaling g (j + 1)).thin
          (((c.ιSigmaStdSimplex ≫
            (standardTypeABoundaryPrismRankFunction g).b j).app
              (op ⦋2⦌)) x)
      rw [c.ι_b]
      exact hs

/-- The residual map `A_j -> R_(j+1)` changes only scaling; its underlying
simplicial map is literally the identity. -/
def standardTypeABoundaryPrismRankAPhaseToSucc
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankAPhase g j ⟶
      standardTypeABoundaryPrismRankStage g (j + 1) where
  map := 𝟙 _
  scaled := standardTypeABoundaryPrismRankAPhaseScaling_le_succ g j

@[simp]
theorem standardTypeABoundaryPrismRankAPhaseToSucc_map
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    (standardTypeABoundaryPrismRankAPhaseToSucc g j).map = 𝟙 _ := by
  rfl

/-- The exact successor rank inclusion factors literally as simultaneous A
attachment followed by the residual scaling enrichment. -/
theorem standardTypeABoundaryPrismRankStep_factor_A_residual
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (j : ℕ) :
    standardTypeABoundaryPrismRankStageToAPhase g j ≫
        standardTypeABoundaryPrismRankAPhaseToSucc g j =
      standardTypeABoundaryPrismRankStageHom g (Nat.le_succ j) := by
  apply ScaledSSet.ScaledMap.ext
  rfl

/-!
The first half of every scaled rank successor is now completely standard:

```text
coproduct of literal standard type-(A) horns
                 |
                 |  pushout
                 v
R_j  -------------------------->  A_j
```

and

```text
R_j -> A_j ∈ pushouts (coproducts E_std).
```

No cell ordering and no q12/q23 split was used.  The carrier of `A_j` is
already the carrier of `R_(j+1)`, and the remaining map

```text
A_j -> R_(j+1)
```

is identity-underlying.  The exhaustive v1.70 classification says exactly
which rank cells contribute a residual thin triangle to this enrichment.  The
next unit can therefore take the subtype of exceptional cells, coproduct the
literal standard type-(B) generator over that subtype, and prove that its
pushout target scaling is exactly the successor scaling.  That will make every
rank successor a two-step raw A/B cellular composite.
-/

end

end KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseSimultaneousAPhaseV1_74
