import KUOS.DependentOriginationFreePathEvaluatorV2_57

namespace KUOS.DependentOriginationQuotientRelationIsoExistenceV2_58

open CategoryTheory
open KUOS.DependentOriginationHigherLocalizationInterfaceV2_10
open KUOS.DependentOriginationPointwiseWAdjointEquivalenceV2_56
open KUOS.DependentOriginationFreePathEvaluatorV2_57

universe u v uH vH

/-!
# Quotient-relation evaluation isomorphism existence v2.58

The v2.57 layer constructs, for a general weakly `W`-admissible raw
Cat-valued pseudofunctor, an honest evaluator on the free path category

```text
Paths (Localization.Construction.LocQuiver W) ⥤ Cat.
```

The canonical ordinary localization `W.Localization` is the quotient of that
path category by the composition closure and equivalence closure generated by
four relations:

```text
id, comp, Winv₁, Winv₂.
```

Because the target is the bicategory `Cat`, the correct first higher statement
is not equality of the evaluations of related paths.  It is existence of a
2-isomorphism, i.e. a natural isomorphism between the corresponding functors.

This file proves that existence all the way from a single generating relation,
through `HomRel.CompClosure`, through `Relation.EqvGen`, and finally for any two
paths identified by the quotient functor into `W.Localization`.

A crucial logical boundary is kept explicit.  The relation predicates live in
`Prop`, while an actual `Iso` lives in `Type`; therefore the closure theorems
return `Nonempty (F.map p ≅ F.map q)`.  This records existence without silently
choosing a relation transport.  Such a choice, together with pentagon/unit and
composition compatibility, is precisely the next coherence obligation.
-/

variable {Context : Type u} [Category.{v} Context]
variable (W : MorphismProperty Context)

/-- The chosen quasi-inverse from v2.56 forms the right half of the unit
isomorphism with the original image `R.map w`.

This is an isomorphism of 1-cells in `Cat`, obtained from the ordinary natural
isomorphism `unitIso.symm` of the chosen half-adjoint equivalence. -/
noncomputable def forwardInverseIso
    (R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    {X Y : Context} (w : X ⟶ Y) (hw : W w) :
    R.map w.toLoc ≫ D.inverse w hw ≅ 𝟙 (R.obj (.mk X)) := by
  apply Cat.Hom.isoMk
  change
    (R.map w.toLoc).toFunctor ⋙ (D.chosen w hw).inverse ≅
      𝟭 (R.obj (.mk X))
  rw [← D.chosen_functor w hw]
  exact (D.chosen w hw).unitIso.symm

/-- The chosen quasi-inverse from v2.56 forms the left half of the counit
isomorphism with the original image `R.map w`. -/
noncomputable def inverseForwardIso
    (R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    {X Y : Context} (w : X ⟶ Y) (hw : W w) :
    D.inverse w hw ≫ R.map w.toLoc ≅ 𝟙 (R.obj (.mk Y)) := by
  apply Cat.Hom.isoMk
  change
    (D.chosen w hw).inverse ⋙ (R.map w.toLoc).toFunctor ≅
      𝟭 (R.obj (.mk Y))
  rw [← D.chosen_functor w hw]
  exact (D.chosen w hw).counitIso

/-- Every one of Mathlib's four generating localization relations is sent by the
v2.57 free-path evaluator to a pair of naturally isomorphic functors.

The four cases are exactly:

* `id`    → `R.mapId`;
* `comp`  → `R.mapComp`;
* `Winv₁` → the chosen adjoint-equivalence unit;
* `Winv₂` → the chosen adjoint-equivalence counit.
-/
theorem generatingRelation_hasEvaluationIso
    (R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    {X Y : Paths (Localization.Construction.LocQuiver W)}
    {p q : X ⟶ Y}
    (h : Localization.Construction.relations W p q) :
    Nonempty
      ((freePathEvaluator W R D).map p ≅
        (freePathEvaluator W R D).map q) := by
  cases h with
  | id X =>
      refine ⟨?_⟩
      simpa using R.mapId (.mk X)
  | comp f g =>
      refine ⟨?_⟩
      simpa [Functor.map_comp] using R.mapComp f.toLoc g.toLoc
  | Winv₁ w hw =>
      refine ⟨?_⟩
      simpa [Functor.map_comp] using forwardInverseIso W R D w hw
  | Winv₂ w hw =>
      refine ⟨?_⟩
      simpa [Functor.map_comp] using inverseForwardIso W R D w hw

/-- Composition closure does not introduce a new obstruction to *existence* of
an evaluation 2-isomorphism.  A generating isomorphism is whiskered on the left
and right by the evaluations of the surrounding paths. -/
theorem compClosure_hasEvaluationIso
    (R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    {X Y : Paths (Localization.Construction.LocQuiver W)}
    {p q : X ⟶ Y}
    (h : HomRel.CompClosure
      (Localization.Construction.relations W) p q) :
    Nonempty
      ((freePathEvaluator W R D).map p ≅
        (freePathEvaluator W R D).map q) := by
  rcases h with ⟨a, b, f, m₁, m₂, g, hm⟩
  rcases generatingRelation_hasEvaluationIso W R D hm with ⟨e⟩
  refine ⟨?_⟩
  simpa only [Functor.map_comp] using
    (Bicategory.whiskerRightIso
      (Bicategory.whiskerLeftIso ((freePathEvaluator W R D).map f) e)
      ((freePathEvaluator W R D).map g))

/-- The equivalence closure of the composition closure also preserves existence
of evaluation 2-isomorphisms.

`refl`, `symm`, and `trans` are interpreted as identity, inverse, and vertical
composition of isomorphisms.  The target remains `Nonempty` so that no
proof-dependent transport choice is introduced. -/
theorem eqvGenCompClosure_hasEvaluationIso
    (R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    {X Y : Paths (Localization.Construction.LocQuiver W)}
    {p q : X ⟶ Y}
    (h : Relation.EqvGen
      (@HomRel.CompClosure
        (Paths (Localization.Construction.LocQuiver W)) _
        (Localization.Construction.relations W) X Y) p q) :
    Nonempty
      ((freePathEvaluator W R D).map p ≅
        (freePathEvaluator W R D).map q) := by
  induction h with
  | rel x y hxy =>
      exact compClosure_hasEvaluationIso W R D hxy
  | refl x =>
      exact ⟨Iso.refl _⟩
  | symm x y hxy ih =>
      rcases ih with ⟨e⟩
      exact ⟨e.symm⟩
  | trans x y z hxy hyz ihxy ihyz =>
      rcases ihxy with ⟨e₁⟩
      rcases ihyz with ⟨e₂⟩
      exact ⟨e₁ ≪≫ e₂⟩

/-- If two free paths have the same image in Mathlib's canonical localization,
their v2.57 evaluations are naturally isomorphic.

This is the exact existence statement induced by the quotient construction. -/
theorem equalInLocalization_hasEvaluationIso
    (R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    {X Y : Paths (Localization.Construction.LocQuiver W)}
    {p q : X ⟶ Y}
    (h :
      (Quotient.functor (Localization.Construction.relations W)).map p =
      (Quotient.functor (Localization.Construction.relations W)).map q) :
    Nonempty
      ((freePathEvaluator W R D).map p ≅
        (freePathEvaluator W R D).map q) := by
  apply eqvGenCompClosure_hasEvaluationIso W R D
  exact
    (Quotient.functor_homRel_eq_compClosure_eqvGen
      (r := Localization.Construction.relations W) p q).mp h

/-- Weak `W`-admissibility alone therefore guarantees natural-isomorphism
existence for the evaluations of any two paths identified in `W.Localization`.
No coherent choice of those isomorphisms is made. -/
theorem equalInLocalization_hasEvaluationIso_of_admissible
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (hR : IsHigherWAdmissible W R)
    {X Y : Paths (Localization.Construction.LocQuiver W)}
    {p q : X ⟶ Y}
    (h :
      (Quotient.functor (Localization.Construction.relations W)).map p =
      (Quotient.functor (Localization.Construction.relations W)).map q) :
    Nonempty
      ((freePathEvaluatorOfAdmissible W hR).map p ≅
        (freePathEvaluatorOfAdmissible W hR).map q) := by
  exact equalInLocalization_hasEvaluationIso W R
    (pointwiseWAdjointEquivalenceDataOfAdmissible W hR) h

/-!
## Boundary fixed by v2.58

The exact theorem chain is now

```text
IsHigherWAdmissible W R
  → chosen pointwise adjoint equivalences
  → free-path evaluator F
  → generating relation p ~ q
      ⇒ Nonempty (F p ≅ F q)
  → CompClosure / EqvGen
      ⇒ Nonempty (F p ≅ F q)
  → equal images in W.Localization
      ⇒ Nonempty (F p ≅ F q).
```

This removes *existence of local relation 2-isomorphisms* as an obstruction.
What remains is genuinely higher: one must choose these transports coherently so
that identity, inverse, transitivity, left/right whiskering, and the resulting
pseudofunctor `mapId`/`mapComp` satisfy the required unit and pentagon equations.

No such coherent choice is asserted in this file.  Consequently there is still
no claimed pseudofunctor on `W.Localization` and no general theorem

```text
IsHigherWAdmissible W R
  ⇒ HasHigherLocalizationFactorization W R.
```

The next layer should package the exact coherent quotient-transport datum needed
to construct that pseudofunctor and prove factorization existence *from that
data*, before attacking existence of the coherence datum itself.
-/

end KUOS.DependentOriginationQuotientRelationIsoExistenceV2_58
