import Mathlib.CategoryTheory.ObjectProperty.FullSubcategory
import KUOS.DependentOriginationPointwise2CellRigidityObstructionEliminationV2_47

namespace KUOS.DependentOriginationImageEnvelopeThinObstructionEliminationV2_48

open CategoryTheory
open KUOS.DependentOriginationHigherLocalizationInterfaceV2_10
open KUOS.DependentOriginationWeakHigherLocalizationUniversalPropertyV2_18
open KUOS.DependentOriginationCoherentWeakHigherLocalizationV2_19
open KUOS.DependentOriginationStageIIIRouteCompletenessV2_33
open KUOS.DependentOriginationWeakCoherentTwoAxisObstructionV2_42
open KUOS.DependentOriginationFiberwiseThinObstructionEliminationV2_45
open KUOS.DependentOriginationLocal2CellRigidityObstructionEliminationV2_46
open KUOS.DependentOriginationPointwise2CellRigidityObstructionEliminationV2_47

universe u v uH vH

/-!
# Image-envelope thin obstruction elimination v2.48

v2.47 reduces the target-side coherence requirement to uniqueness of the
component morphisms occurring in the exact stored v2.18 naturality square.
This file supplies a structural sufficient condition for that pointwise
uniqueness without requiring the entire target fiber to be thin.

For two Cat 1-morphisms `F G : C ⟶ D`, consider the full subcategory of `D`
spanned by objects lying in the object-image of either `F` or `G`.  If that
image envelope is thin, then in particular every component hom

```text
F.obj Z ⟶ G.obj Z
```

is a subsingleton.  Hence:

```text
whole target fiber thin                    (v2.45)
        |
        v
image-envelope full subcategory thin       (v2.48)
        |
        v
pointwise component-hom uniqueness         (v2.47)
        |
        v
exact Cat 2-cell hom uniqueness             (v2.46)
        |
        v
stored modification naturality
        |
        v
weak universality + coherent route completeness
        |
        v
no local v2.42 E/R obstruction.
```

The v2.48 condition may ignore arbitrary objects outside the two relevant
functor images.  It is therefore a localized structural condition rather than
a global thinness assumption on the raw fiber.  We do not claim it is necessary:
v2.47 only needs the corresponding component pairs, whereas image-envelope
thinness also controls morphisms between other pairs of image objects.
-/

variable {Context : Type u} [Category.{v} Context]
variable (W : MorphismProperty Context)

/-- The object property generated by the object-images of two Cat 1-morphisms.
Its full subcategory is the image envelope relevant to the two functors. -/
def CatHom₂ImageEnvelope
    {C D : Cat.{vH, uH}} (F G : C ⟶ D) : ObjectProperty D :=
  fun X =>
    (∃ Z : C, X = F.obj Z) ∨
      ∃ Z : C, X = G.obj Z

/-- Thinness of a full subcategory forces uniqueness of ambient morphisms
between any two objects known to lie in that subcategory. -/
theorem subsingleton_hom_of_thin_fullSubcategory
    {D : Cat.{vH, uH}} (P : ObjectProperty D)
    (hThin : Quiver.IsThin P.FullSubcategory)
    {X Y : D} (hX : P X) (hY : P Y) :
    Subsingleton (X ⟶ Y) := by
  letI : Quiver.IsThin P.FullSubcategory := hThin
  constructor
  intro f g
  let X' : P.FullSubcategory := ⟨X, hX⟩
  let Y' : P.FullSubcategory := ⟨Y, hY⟩
  let f' : X' ⟶ Y' := ObjectProperty.homMk f
  let g' : X' ⟶ Y' := ObjectProperty.homMk g
  have hfg : f' = g' := Subsingleton.elim _ _
  have hhom := congrArg (fun k => k.hom) hfg
  simpa [f', g', X', Y'] using hhom

/-- If the full subcategory spanned by the object-images of `F` and `G` is
thin, then the corresponding component hom sets are subsingletons. -/
theorem catHom₂PointwiseSubsingleton_of_imageEnvelopeThin
    {C D : Cat.{vH, uH}} (F G : C ⟶ D)
    (hThin : Quiver.IsThin (CatHom₂ImageEnvelope F G).FullSubcategory) :
    CatHom₂PointwiseSubsingleton F G := by
  intro Z
  exact subsingleton_hom_of_thin_fullSubcategory
    (CatHom₂ImageEnvelope F G) hThin
      (Or.inl ⟨Z, rfl⟩) (Or.inr ⟨Z, rfl⟩)

/-- Global thinness of the target category descends to thinness of any image
 envelope full subcategory.  This makes the v2.45 -> v2.48 bridge explicit. -/
theorem imageEnvelopeThin_of_targetThin
    {C D : Cat.{vH, uH}} [Quiver.IsThin D] (F G : C ⟶ D) :
    Quiver.IsThin (CatHom₂ImageEnvelope F G).FullSubcategory := by
  intro X Y
  constructor
  intro f g
  apply ObjectProperty.hom_ext
  exact Subsingleton.elim _ _

/-- For every raw base arrow, the full subcategory generated by the two functor
images occurring in the exact v2.23 naturality square is thin. -/
def StoredV2_18NaturalityImageEnvelopeThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    {H K : HigherLocalizationFactorization (W := W) R}
    (alpha : HigherLocalizationFactorMorphism (W := W) H K) : Prop :=
  ∀ {X Y : Context} (f : X ⟶ Y),
    Quiver.IsThin
      (CatHom₂ImageEnvelope
        ((restrictHigherLocalizedSystem W H.lift).map f.toLoc ≫
          (restrictHigherLocalizedStrongTrans (W := W) alpha.hom ≫
            K.comparison).app (.mk Y))
        (H.comparison.app (.mk X) ≫ R.map f.toLoc)).FullSubcategory

/-- Image-envelope thinness implies the pointwise component-hom rigidity
criterion isolated in v2.47. -/
theorem storedV2_18NaturalityComponentHomSubsingleton_of_imageEnvelopeThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    {H K : HigherLocalizationFactorization (W := W) R}
    (alpha : HigherLocalizationFactorMorphism (W := W) H K)
    (hEnvelope : StoredV2_18NaturalityImageEnvelopeThin (W := W) alpha) :
    StoredV2_18NaturalityComponentHomSubsingleton (W := W) alpha := by
  intro X Y f
  exact catHom₂PointwiseSubsingleton_of_imageEnvelopeThin _ _ (hEnvelope f)

/-- Fiberwise thinness from v2.45 implies image-envelope thinness for every
stored v2.18 naturality square. -/
theorem storedV2_18NaturalityImageEnvelopeThin_of_fiberwiseThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (hThin : HigherRawFiberwiseThin R)
    {H K : HigherLocalizationFactorization (W := W) R}
    (alpha : HigherLocalizationFactorMorphism (W := W) H K) :
    StoredV2_18NaturalityImageEnvelopeThin (W := W) alpha := by
  intro X Y f
  letI : Quiver.IsThin (R.obj (.mk Y)) := hThin Y
  exact imageEnvelopeThin_of_targetThin _ _

/-- Uniform image-envelope thinness for all v2.18 factors into one coherent
chosen carrier. -/
def HigherStoredV2_18NaturalityImageEnvelopeThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R) : Prop :=
  ∀ (H : HigherLocalizationFactorization (W := W) R)
    (alpha : HigherLocalizationFactorMorphism (W := W) H U.chosen),
    StoredV2_18NaturalityImageEnvelopeThin (W := W) alpha

/-- Uniform image-envelope thinness implies the uniform v2.47 pointwise
criterion. -/
theorem higherStoredV2_18NaturalityComponentHomSubsingleton_of_imageEnvelopeThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R)
    (hEnvelope : HigherStoredV2_18NaturalityImageEnvelopeThin (W := W) U) :
    HigherStoredV2_18NaturalityComponentHomSubsingleton (W := W) U := by
  intro H alpha
  exact storedV2_18NaturalityComponentHomSubsingleton_of_imageEnvelopeThin
    (W := W) alpha (hEnvelope H alpha)

/-- The v2.45 fiberwise-thin route factors through the v2.48 image-envelope
criterion. -/
theorem higherStoredV2_18NaturalityImageEnvelopeThin_of_fiberwiseThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (hThin : HigherRawFiberwiseThin R)
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R) :
    HigherStoredV2_18NaturalityImageEnvelopeThin (W := W) U := by
  intro H alpha
  exact storedV2_18NaturalityImageEnvelopeThin_of_fiberwiseThin
    (W := W) hThin alpha

/-- Coherent universal data plus uniform image-envelope thinness give the v2.18
weak universal property on the same chosen carrier. -/
theorem hasWeakHigherLocalizationUniversalProperty_of_imageEnvelopeThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R)
    (hEnvelope : HigherStoredV2_18NaturalityImageEnvelopeThin (W := W) U) :
    HasWeakHigherLocalizationUniversalProperty (W := W) R :=
  hasWeakHigherLocalizationUniversalProperty_of_pointwise2CellRigidity
    (W := W) U
      (higherStoredV2_18NaturalityComponentHomSubsingleton_of_imageEnvelopeThin
        (W := W) U hEnvelope)

/-- The coherent Stage III route obstruction disappears under image-envelope
thinness. -/
theorem higherCoherentRouteCompleteness_of_imageEnvelopeThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R)
    (hEnvelope : HigherStoredV2_18NaturalityImageEnvelopeThin (W := W) U) :
    HigherCoherentRouteCompleteness (W := W) U :=
  higherCoherentRouteCompleteness_of_pointwise2CellRigidity
    (W := W) U
      (higherStoredV2_18NaturalityComponentHomSubsingleton_of_imageEnvelopeThin
        (W := W) U hEnvelope)

/-- Image-envelope thinness gives the aligned state in the v2.42 local
classification. -/
theorem higherWeakCoherentAlignment_of_imageEnvelopeThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R)
    (hEnvelope : HigherStoredV2_18NaturalityImageEnvelopeThin (W := W) U) :
    HigherWeakCoherentAlignment (W := W) U :=
  ⟨hasWeakHigherLocalizationUniversalProperty_of_imageEnvelopeThin
      (W := W) U hEnvelope,
    higherCoherentRouteCompleteness_of_imageEnvelopeThin
      (W := W) U hEnvelope⟩

/-- Exact local E/R obstruction elimination under image-envelope thinness. -/
theorem no_twoAxisObstruction_of_imageEnvelopeThin
    {R : RawHigherContextualSystem
      (Context := Context) (uH := uH) (vH := vH)}
    (U : CoherentWeakHigherLocalizationUniversalProperty (W := W) R)
    (hEnvelope : HigherStoredV2_18NaturalityImageEnvelopeThin (W := W) U) :
    ¬ HigherWeakCoherentTwoAxisObstruction (W := W) U :=
  (higherWeakCoherentAlignment_iff_no_twoAxisObstruction
    (W := W) U).mp
      (higherWeakCoherentAlignment_of_imageEnvelopeThin
        (W := W) U hEnvelope)

end KUOS.DependentOriginationImageEnvelopeThinObstructionEliminationV2_48
