import KUOS.DependentOriginationStandardTypeBScalingPushoutV1_56

namespace KUOS.DependentOriginationStandardTypeBThreeSimplexCompletionV1_57

open CategoryTheory
open CategoryTheory.Category
open CategoryTheory.Limits
open Opposite
open Simplicial
open KUOS.DependentOriginationNativeInfinityTwoScaledV1_19
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
open KUOS.DependentOriginationStandardTypeBScalingPushoutV1_56

universe u

/-!
# Standard type-(B) three-simplex completions v1.57

Version 1.56 constructed the standard type-(B) scaling enrichment on `Delta[4]`
and proved a general pushout theorem for identity-underlying scaling
enrichments in `ScaledSSet`.  This file carries out the two low-dimensional
collapse pushouts which are used in the standard scaled-anodyne calculus.

There are two monotone quotient maps of vertex sets

```text
q12 : [4] -> [3],   0,1,2,3,4 |-> 0,1,1,2,3,
q23 : [4] -> [3],   0,1,2,3,4 |-> 0,1,2,2,3.
```

Under `q12`, the type-(B) source triangle `024` maps to `013`, while the
additional target triangle `014` also maps to `013`; hence that target
addition is already present before the type-(B) pushout.  The other new
target triangle `034` maps to `023`, so the pushout forces `023` thin.

Dually, under `q23`, `024` maps to `023` and the additional target triangle
`034` maps to the same `023`, while `014` maps to `013`; hence the pushout
forces `013` thin.

We formalize the two collapse maps, their triangle images, the pre-pushout
base scalings generated by the type-(B) source scaling, the completed scalings,
and the actual categorical pushout squares.  Finally we prove that every left
orthogonal class containing the type-(B) generator contains both completion
maps.  Thus the low-dimensional completion mechanism is no longer an informal
part of the scaled pushout-product argument: it is a direct consequence of the
v1.56 categorical pushout theorem.
-/

/-! ## The two monotone collapses `[4] -> [3]` -/

/-- Collapse vertices `1` and `2`. -/
def standardTypeBCollapse12OrderHom : Fin 5 →o Fin 4 := by
  refine ⟨![(0 : Fin 4), 1, 1, 2, 3], ?_⟩
  rw [Fin.monotone_iff_le_succ]
  decide

/-- Collapse vertices `2` and `3`. -/
def standardTypeBCollapse23OrderHom : Fin 5 →o Fin 4 := by
  refine ⟨![(0 : Fin 4), 1, 2, 2, 3], ?_⟩
  rw [Fin.monotone_iff_le_succ]
  decide

/-- Simplicial collapse `q12 : Delta[4] -> Delta[3]`. -/
def standardTypeBCollapse12 : (Δ[4] : SSet.{u}) ⟶ Δ[3] :=
  SSet.stdSimplex.map
    (SimplexCategory.Hom.mk standardTypeBCollapse12OrderHom)

/-- Simplicial collapse `q23 : Delta[4] -> Delta[3]`. -/
def standardTypeBCollapse23 : (Δ[4] : SSet.{u}) ⟶ Δ[3] :=
  SSet.stdSimplex.map
    (SimplexCategory.Hom.mk standardTypeBCollapse23OrderHom)

/-! ## Canonical triangles and their collapse images -/

/-- The type-(B) source triangle `024`. -/
def standardTypeBTriangle024 :
    (Δ[4] : SSet.{u}).obj (op ⦋2⦌) :=
  SSet.stdSimplex.triangle
    (0 : Fin 5) 2 4 (by decide) (by decide)

/-- The type-(B) target-only triangle `014`. -/
def standardTypeBTriangle014 :
    (Δ[4] : SSet.{u}).obj (op ⦋2⦌) :=
  SSet.stdSimplex.triangle
    (0 : Fin 5) 1 4 (by decide) (by decide)

/-- The type-(B) target-only triangle `034`. -/
def standardTypeBTriangle034 :
    (Δ[4] : SSet.{u}).obj (op ⦋2⦌) :=
  SSet.stdSimplex.triangle
    (0 : Fin 5) 3 4 (by decide) (by decide)

/-- The triangle `013` in `Delta[3]`. -/
def standardTypeBThreeTriangle013 :
    (Δ[3] : SSet.{u}).obj (op ⦋2⦌) :=
  SSet.stdSimplex.triangle
    (0 : Fin 4) 1 3 (by decide) (by decide)

/-- The triangle `023` in `Delta[3]`. -/
def standardTypeBThreeTriangle023 :
    (Δ[3] : SSet.{u}).obj (op ⦋2⦌) :=
  SSet.stdSimplex.triangle
    (0 : Fin 4) 2 3 (by decide) (by decide)

/-- `024` is one of the designated source-thin type-(B) triangles. -/
theorem standardTypeBTriangle024_isSourceTriangle :
    IsStandardTypeBSourceTriangle standardTypeBTriangle024 := by
  exact Or.inl ⟨rfl, rfl, rfl⟩

/-- Hence `024` is thin already in the source scaling. -/
theorem standardTypeBTriangle024_source_thin :
    standardTypeBSourceScaling.thin standardTypeBTriangle024 := by
  exact Or.inr standardTypeBTriangle024_isSourceTriangle

/-- `014` has its specified ordered vertices. -/
theorem standardTypeBTriangle014_isVertexTriangle :
    IsStandardVertexTriangle
      (0 : Fin 5) 1 4 standardTypeBTriangle014 := by
  exact ⟨rfl, rfl, rfl⟩

/-- `034` has its specified ordered vertices. -/
theorem standardTypeBTriangle034_isVertexTriangle :
    IsStandardVertexTriangle
      (0 : Fin 5) 3 4 standardTypeBTriangle034 := by
  exact ⟨rfl, rfl, rfl⟩

/-- Under `q12`, source-thin `024` becomes `013`. -/
theorem standardTypeBCollapse12_triangle_024 :
    standardTypeBCollapse12.app (op ⦋2⦌) standardTypeBTriangle024 =
      standardTypeBThreeTriangle013 := by
  apply SSet.stdSimplex.ext
  intro j
  fin_cases j <;> rfl

/-- Under `q12`, target-only `014` also becomes `013`. -/
theorem standardTypeBCollapse12_triangle_014 :
    standardTypeBCollapse12.app (op ⦋2⦌) standardTypeBTriangle014 =
      standardTypeBThreeTriangle013 := by
  apply SSet.stdSimplex.ext
  intro j
  fin_cases j <;> rfl

/-- Under `q12`, target-only `034` becomes `023`. -/
theorem standardTypeBCollapse12_triangle_034 :
    standardTypeBCollapse12.app (op ⦋2⦌) standardTypeBTriangle034 =
      standardTypeBThreeTriangle023 := by
  apply SSet.stdSimplex.ext
  intro j
  fin_cases j <;> rfl

/-- Under `q23`, source-thin `024` becomes `023`. -/
theorem standardTypeBCollapse23_triangle_024 :
    standardTypeBCollapse23.app (op ⦋2⦌) standardTypeBTriangle024 =
      standardTypeBThreeTriangle023 := by
  apply SSet.stdSimplex.ext
  intro j
  fin_cases j <;> rfl

/-- Under `q23`, target-only `014` becomes `013`. -/
theorem standardTypeBCollapse23_triangle_014 :
    standardTypeBCollapse23.app (op ⦋2⦌) standardTypeBTriangle014 =
      standardTypeBThreeTriangle013 := by
  apply SSet.stdSimplex.ext
  intro j
  fin_cases j <;> rfl

/-- Under `q23`, target-only `034` also becomes `023`. -/
theorem standardTypeBCollapse23_triangle_034 :
    standardTypeBCollapse23.app (op ⦋2⦌) standardTypeBTriangle034 =
      standardTypeBThreeTriangle023 := by
  apply SSet.stdSimplex.ext
  intro j
  fin_cases j <;> rfl

/-! ## Base scalings generated by the source type-(B) scaling -/

/-- Before pushing out the type-(B) enrichment along `q12`, equip `Delta[3]`
with the least scaling containing the minimal scaling and all images of
source-thin type-(B) triangles. -/
def standardTypeBCollapse12BaseScaling :
    ScaledSimplicialSet (Δ[3] : SSet.{u}) :=
  scalingEnrichmentPushoutScaling
    standardTypeBSourceScaling
    (minimalScaling (Δ[3] : SSet.{u}))
    standardTypeBCollapse12

/-- The collapse `q12` is scaled into its source-generated base scaling. -/
theorem standardTypeBCollapse12_scaled :
    IsScaledMap
      standardTypeBSourceScaling
      standardTypeBCollapse12BaseScaling
      standardTypeBCollapse12 := by
  intro t ht
  exact Or.inr ⟨t, ht, rfl⟩

/-- The source-generated `q12` base scaling already contains `013`, because
`024` is source-thin and collapses to `013`. -/
theorem standardTypeBCollapse12Base_triangle_013_thin :
    standardTypeBCollapse12BaseScaling.thin
      standardTypeBThreeTriangle013 := by
  exact Or.inr
    ⟨standardTypeBTriangle024,
      standardTypeBTriangle024_source_thin,
      standardTypeBCollapse12_triangle_024⟩

/-- Before pushing out the type-(B) enrichment along `q23`, equip `Delta[3]`
with the least scaling containing the minimal scaling and all images of
source-thin type-(B) triangles. -/
def standardTypeBCollapse23BaseScaling :
    ScaledSimplicialSet (Δ[3] : SSet.{u}) :=
  scalingEnrichmentPushoutScaling
    standardTypeBSourceScaling
    (minimalScaling (Δ[3] : SSet.{u}))
    standardTypeBCollapse23

/-- The collapse `q23` is scaled into its source-generated base scaling. -/
theorem standardTypeBCollapse23_scaled :
    IsScaledMap
      standardTypeBSourceScaling
      standardTypeBCollapse23BaseScaling
      standardTypeBCollapse23 := by
  intro t ht
  exact Or.inr ⟨t, ht, rfl⟩

/-- The source-generated `q23` base scaling already contains `023`, because
`024` is source-thin and collapses to `023`. -/
theorem standardTypeBCollapse23Base_triangle_023_thin :
    standardTypeBCollapse23BaseScaling.thin
      standardTypeBThreeTriangle023 := by
  exact Or.inr
    ⟨standardTypeBTriangle024,
      standardTypeBTriangle024_source_thin,
      standardTypeBCollapse23_triangle_024⟩

/-! ## Push out the full type-(B) enrichment -/

/-- The completed scaling obtained by pushing the full type-(B) generator
along `q12`. -/
def standardTypeBCollapse12CompletedScaling :
    ScaledSimplicialSet (Δ[3] : SSet.{u}) :=
  standardTypeBPushoutScaling
    standardTypeBCollapse12BaseScaling
    standardTypeBCollapse12

/-- The corresponding identity-underlying completion morphism. -/
def standardTypeBCollapse12CompletionHom :
    ScaledSSet.of (Δ[3] : SSet.{u}) standardTypeBCollapse12BaseScaling ⟶
      ScaledSSet.of (Δ[3] : SSet.{u})
        standardTypeBCollapse12CompletedScaling :=
  standardTypeBPushoutEnrichment
    standardTypeBCollapse12BaseScaling
    standardTypeBCollapse12

/-- This completion square is literally a pushout of the standard type-(B)
generator in `ScaledSSet`. -/
noncomputable def standardTypeBCollapse12Completion_isPushout :
    IsPushout
      (scalingEnrichmentPushoutLowerMap
        standardTypeBCollapse12 standardTypeBCollapse12_scaled)
      standardTypeBGeneratorHom
      standardTypeBCollapse12CompletionHom
      (scalingEnrichmentPushoutUpperMap
        standardTypeBTargetScaling
        standardTypeBCollapse12BaseScaling
        standardTypeBCollapse12) := by
  exact standardTypeBPushout_isPushout
    standardTypeBCollapse12BaseScaling
    standardTypeBCollapse12
    standardTypeBCollapse12_scaled

/-- The `q12` type-(B) pushout forces triangle `023` thin via target-only
triangle `034`. -/
theorem standardTypeBCollapse12Completed_triangle_023_thin :
    standardTypeBCollapse12CompletedScaling.thin
      standardTypeBThreeTriangle023 := by
  exact Or.inr
    ⟨standardTypeBTriangle034,
      standardTypeB_triangle_034_thin
        standardTypeBTriangle034
        standardTypeBTriangle034_isVertexTriangle,
      standardTypeBCollapse12_triangle_034⟩

/-- The other target-only triangle `014` collapses to `013`, which was already
present in the source-generated `q12` base scaling. -/
theorem standardTypeBCollapse12_target014_already_base :
    standardTypeBCollapse12BaseScaling.thin
      (standardTypeBCollapse12.app (op ⦋2⦌) standardTypeBTriangle014) := by
  rw [standardTypeBCollapse12_triangle_014]
  exact standardTypeBCollapse12Base_triangle_013_thin

/-- The completed scaling obtained by pushing the full type-(B) generator
along `q23`. -/
def standardTypeBCollapse23CompletedScaling :
    ScaledSimplicialSet (Δ[3] : SSet.{u}) :=
  standardTypeBPushoutScaling
    standardTypeBCollapse23BaseScaling
    standardTypeBCollapse23

/-- The corresponding identity-underlying completion morphism. -/
def standardTypeBCollapse23CompletionHom :
    ScaledSSet.of (Δ[3] : SSet.{u}) standardTypeBCollapse23BaseScaling ⟶
      ScaledSSet.of (Δ[3] : SSet.{u})
        standardTypeBCollapse23CompletedScaling :=
  standardTypeBPushoutEnrichment
    standardTypeBCollapse23BaseScaling
    standardTypeBCollapse23

/-- This completion square is literally a pushout of the standard type-(B)
generator in `ScaledSSet`. -/
noncomputable def standardTypeBCollapse23Completion_isPushout :
    IsPushout
      (scalingEnrichmentPushoutLowerMap
        standardTypeBCollapse23 standardTypeBCollapse23_scaled)
      standardTypeBGeneratorHom
      standardTypeBCollapse23CompletionHom
      (scalingEnrichmentPushoutUpperMap
        standardTypeBTargetScaling
        standardTypeBCollapse23BaseScaling
        standardTypeBCollapse23) := by
  exact standardTypeBPushout_isPushout
    standardTypeBCollapse23BaseScaling
    standardTypeBCollapse23
    standardTypeBCollapse23_scaled

/-- The `q23` type-(B) pushout forces triangle `013` thin via target-only
triangle `014`. -/
theorem standardTypeBCollapse23Completed_triangle_013_thin :
    standardTypeBCollapse23CompletedScaling.thin
      standardTypeBThreeTriangle013 := by
  exact Or.inr
    ⟨standardTypeBTriangle014,
      standardTypeB_triangle_014_thin
        standardTypeBTriangle014
        standardTypeBTriangle014_isVertexTriangle,
      standardTypeBCollapse23_triangle_014⟩

/-- The other target-only triangle `034` collapses to `023`, which was already
present in the source-generated `q23` base scaling. -/
theorem standardTypeBCollapse23_target034_already_base :
    standardTypeBCollapse23BaseScaling.thin
      (standardTypeBCollapse23.app (op ⦋2⦌) standardTypeBTriangle034) := by
  rw [standardTypeBCollapse23_triangle_034]
  exact standardTypeBCollapse23Base_triangle_023_thin

/-! ## Orthogonal closure of both completion cells -/

/-- Any left orthogonal class containing the standard type-(B) generator
contains the `q12` three-simplex completion. -/
theorem standardTypeBCollapse12Completion_mem_llp
    (T : MorphismProperty (ScaledSSet.{u}))
    (hB : T.llp standardTypeBGeneratorHom) :
    T.llp standardTypeBCollapse12CompletionHom := by
  exact standardTypeBPushoutEnrichment_mem_llp
    T
    standardTypeBCollapse12BaseScaling
    standardTypeBCollapse12
    standardTypeBCollapse12_scaled
    hB

/-- Any left orthogonal class containing the standard type-(B) generator
contains the `q23` three-simplex completion. -/
theorem standardTypeBCollapse23Completion_mem_llp
    (T : MorphismProperty (ScaledSSet.{u}))
    (hB : T.llp standardTypeBGeneratorHom) :
    T.llp standardTypeBCollapse23CompletionHom := by
  exact standardTypeBPushoutEnrichment_mem_llp
    T
    standardTypeBCollapse23BaseScaling
    standardTypeBCollapse23
    standardTypeBCollapse23_scaled
    hB

/-- Package both low-dimensional completion consequences of type-(B). -/
structure StandardTypeBThreeSimplexCompletionStable
    (L : MorphismProperty (ScaledSSet.{u})) : Prop where
  collapse12_mem : L standardTypeBCollapse12CompletionHom
  collapse23_mem : L standardTypeBCollapse23CompletionHom

/-- Every left orthogonal class containing type-(B) contains both completion
cells simultaneously. -/
def standardTypeBThreeSimplexCompletionStable_of_mem_llp
    (T : MorphismProperty (ScaledSSet.{u}))
    (hB : T.llp standardTypeBGeneratorHom) :
    StandardTypeBThreeSimplexCompletionStable T.llp where
  collapse12_mem := standardTypeBCollapse12Completion_mem_llp T hB
  collapse23_mem := standardTypeBCollapse23Completion_mem_llp T hB

/-- In particular, external generated scaled-anodyne classes contain both
three-simplex completion cells as soon as they contain the standard type-(B)
generator. -/
def standardTypeBThreeSimplexCompletionStable_external
    {E : MorphismProperty (ScaledSSet.{u})}
    (hB : externalGeneratedScaledAnodyne E standardTypeBGeneratorHom) :
    StandardTypeBThreeSimplexCompletionStable
      (externalGeneratedScaledAnodyne E) := by
  change StandardTypeBThreeSimplexCompletionStable E.rlp.llp
  exact standardTypeBThreeSimplexCompletionStable_of_mem_llp E.rlp hB

/-!
The low-dimensional type-(B) mechanism is now explicit:

```text
q12 : 024 -> 013, 014 -> 013, 034 -> 023
  source-generated base already has 013
  type-(B) pushout forces 023

q23 : 024 -> 023, 034 -> 023, 014 -> 013
  source-generated base already has 023
  type-(B) pushout forces 013
```

and both completion maps lie in every left orthogonal class containing the
standard type-(B) generator.

The next standard-comparison unit can therefore construct the type-(C)
collapsed-edge generators without leaving the low-dimensional completion steps
implicit, then package type-(A), type-(B), and type-(C) as one explicit
standard scaled-anodyne presentation.
-/

end KUOS.DependentOriginationStandardTypeBThreeSimplexCompletionV1_57
