import Mathlib
import KUOS.DependentOriginationContextualDescentV1_1
import KUOS.DependentOriginationOppositeSiteVarianceBridgeV2_3

namespace KUOS.DependentOriginationRefinementPrecoverageV2_4

open CategoryTheory
open Opposite
open KUOS.DependentOriginationFunctorialTransportV0_1
open KUOS.DependentOriginationContextualDescentV1_1
open KUOS.DependentOriginationOppositeSiteVarianceBridgeV2_3

universe u v w

/-!
# Refinement covers generate an opposite-site Grothendieck topology v2.4

KuuOS refinement arrows are covariant in `Context`:

```text
root -> chart i.
```

After the v2.3 variance bridge, the ordinary sheaf-theoretic site is
`Contextᵒᵖ`.  Hence each refinement arrow becomes a site arrow

```text
(op (chart i)) -> (op root).
```

This file performs the next exact step of the dependent-origination `J` axis:

1. package one KuuOS `RefinementCover` as the corresponding Mathlib presieve;
2. state when an ambient `Precoverage` declares that cover;
3. generate the least Grothendieck topology containing all declared presieves;
4. expose Mathlib's exact sheaf criterion for that generated topology;
5. identify the sheaf condition for one KuuOS refinement family with the
   unique-amalgamation statement for the original contextual transport maps.

No pairwise-overlap simplification is claimed here.  Mathlib's presieve
compatibility quantifies over every common refinement.  The existing v1.1
`OverlapSystem` names one chosen common refinement for each pair but does not
assume its universal property.  Identifying those two compatibility notions is
therefore deliberately postponed to a later theorem unit with an explicit
pushout hypothesis.
-/

variable {Context : Type u} [Category.{v} Context]
variable {Index : Type w}

/-- The opposite-site presieve canonically represented by one KuuOS refinement
cover. -/
def refinementPresieve
    (C : RefinementCover Context Index) :
    Presieve (op C.rootContext) :=
  Presieve.ofArrows
    (fun i => op (C.chart i))
    (fun i => (C.toChart i).op)

/-- An ambient precoverage declares a KuuOS refinement cover precisely when the
associated opposite-site presieve is one of its covering presieves. -/
def DeclaresRefinementCover
    (K : Precoverage (OppositeRefinementSite Context))
    (C : RefinementCover Context Index) : Prop :=
  refinementPresieve C ∈ K (op C.rootContext)

/-- The Grothendieck topology freely generated by a chosen opposite-site
precoverage of contextual refinements. -/
def generatedRefinementTopology
    (K : Precoverage (OppositeRefinementSite Context)) :
    GrothendieckTopology (OppositeRefinementSite Context) :=
  K.toGrothendieck

/-- Every declared KuuOS refinement cover becomes a covering sieve in the
freely generated Grothendieck topology. -/
theorem refinementSieve_mem_generatedTopology
    (K : Precoverage (OppositeRefinementSite Context))
    (C : RefinementCover Context Index)
    (hC : DeclaresRefinementCover K C) :
    Sieve.generate (refinementPresieve C) ∈
      generatedRefinementTopology K (op C.rootContext) := by
  exact K.generate_mem_toGrothendieck hC

/-- The generated refinement topology is the least Grothendieck topology that
contains the sieve generated by every declared presieve. -/
theorem generatedRefinementTopology_le
    (K : Precoverage (OppositeRefinementSite Context))
    (J : GrothendieckTopology (OppositeRefinementSite Context))
    (hJ : ∀ ⦃X : OppositeRefinementSite Context⦄ (R : Presieve X),
      R ∈ K X → Sieve.generate R ∈ J X) :
    generatedRefinementTopology K ≤ J := by
  rw [generatedRefinementTopology, K.toGrothendieck_eq_sInf]
  exact sInf_le hJ

/-- Exact Mathlib characterization of descent completeness for the topology
freely generated by the declared contextual-refinement precoverage.

The pullbacks are essential: saturation to a Grothendieck topology forces the
sheaf condition not only on the declared presieves themselves but on all their
base changes. -/
theorem isGrothendieckDescentComplete_iff_generatedPullbacks
    (K : Precoverage (OppositeRefinementSite Context))
    (D : FunctorialTransportSystem Context) :
    IsGrothendieckDescentComplete (generatedRefinementTopology K) D ↔
      (∀ {X Y : OppositeRefinementSite Context} {f : Y ⟶ X}
        (R : Presieve X), R ∈ K X →
          Presieve.IsSheafFor (asOppositeSitePresheaf D)
            ((Sieve.generate R).pullback f).arrows) := by
  unfold IsGrothendieckDescentComplete generatedRefinementTopology
  rw [isSheaf_iff_isSheaf_of_type]
  exact K.isSheaf_toGrothendieck_iff (asOppositeSitePresheaf D)

/-- A globally descent-complete contextual system satisfies the sheaf condition
for every KuuOS refinement cover explicitly declared by the generating
precoverage. -/
theorem isSheafFor_refinementPresieve_of_descentComplete
    (K : Precoverage (OppositeRefinementSite Context))
    (D : FunctorialTransportSystem Context)
    (hD : IsGrothendieckDescentComplete (generatedRefinementTopology K) D)
    (C : RefinementCover Context Index)
    (hC : DeclaresRefinementCover K C) :
    Presieve.IsSheafFor (asOppositeSitePresheaf D) (refinementPresieve C) := by
  unfold IsGrothendieckDescentComplete at hD
  rw [isSheaf_iff_isSheaf_of_type] at hD
  exact hD.isSheafFor (refinementPresieve C)
    (refinementSieve_mem_generatedTopology K C hC)

/-- For one KuuOS refinement family, Mathlib's presieve sheaf condition is
exactly unique contextual amalgamation for every fully compatible family of
local states.

The compatibility predicate on the right is Mathlib's `Arrows.Compatible` for
all common refinements.  The amalgamation equation itself is definitionally the
original KuuOS transport equation by the v2.3 opposite-site bridge. -/
theorem refinementPresieve_isSheafFor_iff_uniqueAmalgamation
    (D : FunctorialTransportSystem Context)
    (C : RefinementCover Context Index) :
    Presieve.IsSheafFor (asOppositeSitePresheaf D) (refinementPresieve C) ↔
      (∀ (x : (i : Index) → D.state.obj (C.chart i)),
        Presieve.Arrows.Compatible
          (asOppositeSitePresheaf D)
          (fun i => (C.toChart i).op) x →
        ∃! t : D.state.obj C.rootContext,
          ∀ i, D.transport (C.toChart i) t = x i) := by
  simpa [refinementPresieve] using
    (Presieve.isSheafFor_arrows_iff
      (P := asOppositeSitePresheaf D)
      (X := fun i => op (C.chart i))
      (π := fun i => (C.toChart i).op))

/-!
At this point the semantic `J` axis has a canonical, presentation-independent
shape on the opposite site:

```text
KuuOS refinement cover
      -> opposite-site presieve
      -> Precoverage
      -> Precoverage.toGrothendieck
      -> Grothendieck sheaf condition.
```

The remaining local comparison theorem is now sharply isolated.  To recover the
v2.1 type `CompatibleLocalStates D C O`, one must prove that its chosen
pairwise-meet equations are equivalent to `Presieve.Arrows.Compatible`.  That
is valid when the chosen meets are universal common refinements (equivalently,
pushouts of the root-to-chart span in `Context`), and should be stated with that
hypothesis rather than silently strengthening `OverlapSystem`.
-/

end KUOS.DependentOriginationRefinementPrecoverageV2_4
