import Mathlib.CategoryTheory.Sites.Descent.Precoverage
import KUOS.DependentOriginationWJCategoryEquivalenceV2_7

namespace KUOS.DependentOriginationHigherStackDescentV2_8

open CategoryTheory
open CategoryTheory.Limits
open Opposite
open KUOS.DependentOriginationGeneratedRefinementTopologyV2_4
open KUOS.DependentOriginationLocalizedSheafUniversalityV2_6
open KUOS.DependentOriginationWJCategoryEquivalenceV2_7

universe u v uH vH

/-!
# Cat-valued higher stack descent for dependent origination v2.8

The v2.7 layer proves the complete 1-categorical `W + J` classification

```text
RawWJFunctorCategory(C,W,A) ≌ Sh_{J_A}((C[W⁻¹])ᵒᵖ, Type).
```

This file begins the genuine higher-coherence axis `H` using Mathlib's native
2-categorical descent machinery rather than adding informal higher cells to the
Type-valued carrier.

For the localized context category

```text
L := C[W⁻¹],
```

the KuuOS refinement topology from v2.4 lives on the site `Lᵒᵖ`.  A Cat-valued
presheaf on that site is therefore represented by a pseudofunctor

```text
LocallyDiscrete ((Lᵒᵖ)ᵒᵖ) ⥤ᵖ Cat.
```

Mathlib's `Pseudofunctor.IsStack` says exactly that categorical descent is
effective: for every covering sieve, the canonical functor from the category
over the root to the corresponding category of descent data is an equivalence.

We prove two directions.

* Global stack descent implies effective categorical descent for every declared
  KuuOS atlas cover.
* Conversely, when the KuuOS precoverage satisfies Mathlib's standard closure
  hypotheses (`HasIsos`, base-change stability, and composition stability) on a
  site with pullbacks, effective descent for the declared covers implies stack
  descent for the whole generated Grothendieck topology.

Thus v2.8 is the Cat-valued higher analogue of the Type-valued local-to-global
sheaf theorem v2.5.  It is a genuine stack theorem, but it is not yet a universal
`(∞,2)` completion and does not silently identify the existing globular/scaled
simplicial interfaces with an infinity category.
-/

variable {Context : Type u} [Category.{v} Context]
variable (W : MorphismProperty Context)

/-- The site carrying the presentation-independent KuuOS refinement topology. -/
abbrev HigherLocalizedSite := (LocalizedContext W)ᵒᵖ

/-- A Cat-valued higher contextual system on the localized opposite site. -/
abbrev HigherLocalizedDescentSystem :=
  Pseudofunctor
    (LocallyDiscrete ((HigherLocalizedSite W)ᵒᵖ))
    Cat.{vH, uH}

/-- Higher contextual descent completeness is ordinary Mathlib stackness for the
Grothendieck topology generated by the localized KuuOS atlas. -/
def IsHigherGrothendieckDescentComplete
    (A : RefinementAtlas (LocalizedContext W))
    (F : HigherLocalizedDescentSystem (W := W)) : Prop :=
  F.IsStack A.generatedTopology

/-- A globally stack-complete higher contextual system has effective descent for
each declared KuuOS refinement cover. -/
theorem isStackFor_declaredCover
    (A : RefinementAtlas (LocalizedContext W))
    (F : HigherLocalizedDescentSystem (W := W))
    (hF : IsHigherGrothendieckDescentComplete W A F)
    (X : HigherLocalizedSite W) :
    F.IsStackFor (A.presieveAt X) := by
  change F.IsStack A.generatedTopology at hF
  letI : F.IsStack A.generatedTopology := hF
  exact F.isStackFor (A.presieveAt X)
    (A.generate_presieveAt_mem_generatedTopology X)

/-- For every declared atlas family, global higher descent makes the canonical
root-to-descent-data functor an equivalence of categories. -/
theorem declaredCover_toDescentData_isEquivalence
    (A : RefinementAtlas (LocalizedContext W))
    (F : HigherLocalizedDescentSystem (W := W))
    (hF : IsHigherGrothendieckDescentComplete W A F)
    (X : HigherLocalizedSite W) :
    (F.toDescentData
      (fun i : A.Index (unop X) => (A.toChart (unop X) i).op)).IsEquivalence := by
  apply (F.isStackFor_ofArrows_iff).1
  simpa [RefinementAtlas.presieveAt] using
    isStackFor_declaredCover W A F hF X

section LocalToGlobal

variable (A : RefinementAtlas (LocalizedContext W))
variable (F : HigherLocalizedDescentSystem (W := W))
variable [HasPullbacks (HigherLocalizedSite W)]
variable [A.precoverage.HasIsos]
variable [A.precoverage.IsStableUnderBaseChange]
variable [A.precoverage.IsStableUnderComposition]

/-- Under the standard precoverage closure axioms, effective categorical descent
on every declared KuuOS cover promotes to stack descent for the entire freely
generated topology. -/
theorem higherGrothendieckDescentComplete_of_declaredCovers
    (hF : ∀ X : HigherLocalizedSite W, F.IsStackFor (A.presieveAt X)) :
    IsHigherGrothendieckDescentComplete W A F := by
  unfold IsHigherGrothendieckDescentComplete
  change F.IsStack A.precoverage.toGrothendieck
  apply Pseudofunctor.IsStack.of_precoverage (F := F) (J := A.precoverage)
  intro S R hR
  have hReq : R = A.presieveAt S := by
    simpa [RefinementAtlas.precoverage] using hR
  subst R
  exact hF S

/-- Exact local-to-global characterization of Cat-valued higher KuuOS descent
under the precoverage closure hypotheses. -/
theorem isHigherGrothendieckDescentComplete_iff_declaredCovers :
    IsHigherGrothendieckDescentComplete W A F ↔
      ∀ X : HigherLocalizedSite W, F.IsStackFor (A.presieveAt X) := by
  constructor
  · intro hF X
    exact isStackFor_declaredCover W A F hF X
  · intro hF
    exact higherGrothendieckDescentComplete_of_declaredCovers W A F hF

/-- The same theorem in the most concrete higher-descent form: global stackness
is equivalent to saying that the root-to-descent-data functor is an equivalence
of categories for every declared KuuOS atlas family. -/
theorem isHigherGrothendieckDescentComplete_iff_declaredDescentEquivalences :
    IsHigherGrothendieckDescentComplete W A F ↔
      ∀ X : HigherLocalizedSite W,
        (F.toDescentData
          (fun i : A.Index (unop X) => (A.toChart (unop X) i).op)).IsEquivalence := by
  constructor
  · intro hF X
    exact declaredCover_toDescentData_isEquivalence W A F hF X
  · intro hF
    apply (isHigherGrothendieckDescentComplete_iff_declaredCovers W A F).2
    intro X
    change F.IsStackFor
      (Presieve.ofArrows
        (fun i : A.Index (unop X) => op (A.chart (unop X) i))
        (fun i => (A.toChart (unop X) i).op))
    exact (F.isStackFor_ofArrows_iff).2 (hF X)

end LocalToGlobal

/-!
The higher descent boundary established here is therefore

```text
presentation localization W
        ↓
localized opposite refinement site
        ↓
Cat-valued pseudofunctor F
        ↓
local categorical descent equivalences on KuuOS covers
        ↕  (under precoverage closure)
F.IsStack A.generatedTopology.
```

This is a rigorous `H`-axis entry point because the descent data and their
morphisms are categorical and the transition system is pseudofunctorial.
However, `IsStack` is a 2-categorical descent condition, not by itself a proof
of a universal `(∞,2)` localization/stackification.  The next layer must connect
this stack interface to the existing native bicategorical and scaled-simplicial
KuuOS coherence spine while preserving an explicit universal-property boundary.
-/

end KUOS.DependentOriginationHigherStackDescentV2_8