import KUOS.DependentOriginationCoherentBiadjunctionOriginalF45DepthRotationInvariantsV5_152

namespace KUOS.DependentOriginationCoherentBiadjunctionInterleavingExchangeQuotientV5_141.Grid

open CategoryTheory
open scoped CategoryTheory.Bicategory CategoryTheory.Oplax.LaxTrans
open KUOS.DependentOriginationCoherentBiadjunctionFiniteRectangularSubdivisionV5_137.Grid
open KUOS.DependentOriginationCoherentBiadjunctionExchangeQuotientConcatenationV5_141.Grid

set_option autoImplicit false
noncomputable section

/-!
# F56-A / v5.153 — conditional, typed semantic target for F55 higher cells

The original F55-B PresentedCell is a free Type-valued *presentation*,
generated by the actual F55-A five-vertex pentagon (three distinct
F54 rotations versus two) and the square of two disjoint contextual
rotations. F55-C proves the original F44 quotient and both COMPLETE
independent F19/F28 histories are invariant along each route.

F56-A specifies a SEPARATELY CHOSEN cell family, with individually
supplied interpretations of both generators and the exact compositional
and contextual operations. The interpreter is CONSTRUCTED by induction
on the actual F55-B presented witness. No target 3-cell is inferred
from an equality of F44 endpoint classes.

In particular the target is CONDITIONAL: supplying a HigherCellTarget
requires mathematical evidence of pentagon/square and the stated
operations in a chosen independent carrier. This file does not assert
that an arbitrary ambient tricategory, Gray category, or noninvertible
G.toOplax comparison supplies such a structure.
-/

universe uD vD uE vE uH

/-- Independently specified, typed interpretation of the actual F55
presented pentagon/square path cells. This is target DATA, not an axiom.
Every operation has exact original F19/F28 Nat indices, original
Blocks boundary types, and genuine source/target routes. -/
structure OriginalF45BracketTree.DepthRotationRoute.HigherCellTarget
    (D : Type uD) [Category.{vD} D]
    (E : Type uE) [Category.{vE} E] where
  Cell :
    ∀ {a b : D} {x y : E} {n n' m m' : Nat}
      {ma mb : Blocks a b} {pa pb : Blocks x y}
      {first : OriginalF45BracketTree n m ma pa mb pb}
      {last : OriginalF45BracketTree n' m' ma pa mb pb},
      OriginalF45BracketTree.DepthRotationRoute first last →
      OriginalF45BracketTree.DepthRotationRoute first last →
      Type uH
  ident :
    ∀ {a b : D} {x y : E} {n n' m m' : Nat}
      {ma mb : Blocks a b} {pa pb : Blocks x y}
      {first : OriginalF45BracketTree n m ma pa mb pb}
      {last : OriginalF45BracketTree n' m' ma pa mb pb}
      (route : OriginalF45BracketTree.DepthRotationRoute first last),
      Cell route route
  pentagon :
    ∀ {a b : D} {x y : E}
      {n₁ n₂ n₃ n₄ m₁ m₂ m₃ m₄ : Nat}
      {p₀ p₁ p₂ p₃ p₄ : Blocks a b}
      {q₀ q₁ q₂ q₃ q₄ : Blocks x y}
      (t₁ : OriginalF45BracketTree n₁ m₁ p₀ q₀ p₁ q₁)
      (t₂ : OriginalF45BracketTree n₂ m₂ p₁ q₁ p₂ q₂)
      (t₃ : OriginalF45BracketTree n₃ m₃ p₂ q₂ p₃ q₃)
      (t₄ : OriginalF45BracketTree n₄ m₄ p₃ q₃ p₄ q₄),
      Cell
        (OriginalF45BracketTree.DepthRotationRoute.pentagonLong
          t₁ t₂ t₃ t₄)
        (OriginalF45BracketTree.DepthRotationRoute.pentagonShort
          t₁ t₂ t₃ t₄)
  disjointSquare :
    ∀ {a b : D} {x y : E}
      {n m n' m' : Nat}
      {p₀ p₁ p₂ : Blocks a b} {q₀ q₁ q₂ : Blocks x y}
      {leftBefore leftAfter :
        OriginalF45BracketTree n m p₀ q₀ p₁ q₁}
      {rightBefore rightAfter :
        OriginalF45BracketTree n' m' p₁ q₁ p₂ q₂}
      (left : OriginalF45BracketTree.LocalRotation leftBefore leftAfter)
      (right : OriginalF45BracketTree.LocalRotation rightBefore rightAfter),
      Cell
        (OriginalF45BracketTree.DepthRotationRoute.squareLeftFirst left right)
        (OriginalF45BracketTree.DepthRotationRoute.squareRightFirst left right)
  symm :
    ∀ {a b : D} {x y : E} {n n' m m' : Nat}
      {ma mb : Blocks a b} {pa pb : Blocks x y}
      {first : OriginalF45BracketTree n m ma pa mb pb}
      {last : OriginalF45BracketTree n' m' ma pa mb pb}
      {r s : OriginalF45BracketTree.DepthRotationRoute first last},
      Cell r s → Cell s r
  trans :
    ∀ {a b : D} {x y : E} {n n' m m' : Nat}
      {ma mb : Blocks a b} {pa pb : Blocks x y}
      {first : OriginalF45BracketTree n m ma pa mb pb}
      {last : OriginalF45BracketTree n' m' ma pa mb pb}
      {r s t : OriginalF45BracketTree.DepthRotationRoute first last},
      Cell r s → Cell s t → Cell r t
  leftContext :
    ∀ {a b : D} {x y : E} {n n' m m' k l : Nat}
      {ma mb mc : Blocks a b} {pa pb pc : Blocks x y}
      {first : OriginalF45BracketTree n m ma pa mb pb}
      {last : OriginalF45BracketTree n' m' ma pa mb pb}
      {r s : OriginalF45BracketTree.DepthRotationRoute first last},
      Cell r s →
      (later : OriginalF45BracketTree k l mb pb mc pc) →
      Cell
        (OriginalF45BracketTree.DepthRotationRoute.leftContext r later)
        (OriginalF45BracketTree.DepthRotationRoute.leftContext s later)
  rightContext :
    ∀ {a b : D} {x y : E} {k l n n' m m' : Nat}
      {ma mb mc : Blocks a b} {pa pb pc : Blocks x y}
      (earlier : OriginalF45BracketTree k l ma pa mb pb)
      {first : OriginalF45BracketTree n m mb pb mc pc}
      {last : OriginalF45BracketTree n' m' mb pb mc pc}
      {r s : OriginalF45BracketTree.DepthRotationRoute first last},
      Cell r s →
      Cell
        (OriginalF45BracketTree.DepthRotationRoute.rightContext earlier r)
        (OriginalF45BracketTree.DepthRotationRoute.rightContext earlier s)
  precompose :
    ∀ {a b : D} {x y : E}
      {n₁ n₂ n₃ m₁ m₂ m₃ : Nat}
      {ma mb : Blocks a b} {pa pb : Blocks x y}
      {first : OriginalF45BracketTree n₁ m₁ ma pa mb pb}
      {middle : OriginalF45BracketTree n₂ m₂ ma pa mb pb}
      {last : OriginalF45BracketTree n₃ m₃ ma pa mb pb}
      (priorRoute : OriginalF45BracketTree.DepthRotationRoute first middle)
      {r s : OriginalF45BracketTree.DepthRotationRoute middle last},
      Cell r s →
      Cell
        (OriginalF45BracketTree.DepthRotationRoute.trans priorRoute r)
        (OriginalF45BracketTree.DepthRotationRoute.trans priorRoute s)
  postcompose :
    ∀ {a b : D} {x y : E}
      {n₁ n₂ n₃ m₁ m₂ m₃ : Nat}
      {ma mb : Blocks a b} {pa pb : Blocks x y}
      {first : OriginalF45BracketTree n₁ m₁ ma pa mb pb}
      {middle : OriginalF45BracketTree n₂ m₂ ma pa mb pb}
      {last : OriginalF45BracketTree n₃ m₃ ma pa mb pb}
      {r s : OriginalF45BracketTree.DepthRotationRoute first middle},
      Cell r s →
      (suffix : OriginalF45BracketTree.DepthRotationRoute middle last) →
      Cell
        (OriginalF45BracketTree.DepthRotationRoute.trans r suffix)
        (OriginalF45BracketTree.DepthRotationRoute.trans s suffix)

variable {D : Type uD} [Category.{vD} D]
variable {E : Type uE} [Category.{vE} E]

/-- Universally interpret EVERY concrete F55-B freely presented
proof-relevant cell in an INDEPENDENTLY SUPPLIED higher-cell target.
This function is obtained from all nine original constructors,
not from F44 quotient endpoint proof irrelevance. -/
def OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret
    (target : OriginalF45BracketTree.DepthRotationRoute.HigherCellTarget
      D E)
    {a b : D} {x y : E} {n n' m m' : Nat}
    {ma mb : Blocks a b} {pa pb : Blocks x y}
    {first : OriginalF45BracketTree n m ma pa mb pb}
    {last : OriginalF45BracketTree n' m' ma pa mb pb}
    {r s : OriginalF45BracketTree.DepthRotationRoute first last}
    (cell : OriginalF45BracketTree.DepthRotationRoute.PresentedCell r s) :
    target.Cell r s := by
  induction cell with
  | ident route =>
      exact target.ident route
  | pentagon t₁ t₂ t₃ t₄ =>
      exact target.pentagon t₁ t₂ t₃ t₄
  | disjointSquare left right =>
      exact target.disjointSquare left right
  | symm cell ih =>
      exact target.symm ih
  | trans left right ihLeft ihRight =>
      exact target.trans ihLeft ihRight
  | leftContext cell later ih =>
      exact target.leftContext ih later
  | rightContext earlier cell ih =>
      exact target.rightContext earlier ih
  | precompose priorRoute cell ih =>
      exact target.precompose priorRoute ih
  | postcompose cell suffix ih =>
      exact target.postcompose ih suffix

/-- The interpreter sends the ACTUAL three-versus-two F55 pentagon
generator to the separately supplied target pentagon cell. -/
theorem OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret_pentagon
    (target : OriginalF45BracketTree.DepthRotationRoute.HigherCellTarget
      D E)
    {a b : D} {x y : E}
    {n₁ n₂ n₃ n₄ m₁ m₂ m₃ m₄ : Nat}
    {p₀ p₁ p₂ p₃ p₄ : Blocks a b}
    {q₀ q₁ q₂ q₃ q₄ : Blocks x y}
    (t₁ : OriginalF45BracketTree n₁ m₁ p₀ q₀ p₁ q₁)
    (t₂ : OriginalF45BracketTree n₂ m₂ p₁ q₁ p₂ q₂)
    (t₃ : OriginalF45BracketTree n₃ m₃ p₂ q₂ p₃ q₃)
    (t₄ : OriginalF45BracketTree n₄ m₄ p₃ q₃ p₄ q₄) :
    (OriginalF45BracketTree.DepthRotationRoute.PresentedCell.pentagon
      t₁ t₂ t₃ t₄).interpret target =
      target.pentagon t₁ t₂ t₃ t₄ :=
  rfl

/-- The interpreter sends the ACTUAL disjoint-context F55 square
generator to the independently supplied target square. -/
theorem OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret_square
    (target : OriginalF45BracketTree.DepthRotationRoute.HigherCellTarget
      D E)
    {a b : D} {x y : E}
    {n m n' m' : Nat}
    {p₀ p₁ p₂ : Blocks a b} {q₀ q₁ q₂ : Blocks x y}
    {leftBefore leftAfter : OriginalF45BracketTree n m p₀ q₀ p₁ q₁}
    {rightBefore rightAfter : OriginalF45BracketTree n' m' p₁ q₁ p₂ q₂}
    (left : OriginalF45BracketTree.LocalRotation leftBefore leftAfter)
    (right : OriginalF45BracketTree.LocalRotation rightBefore rightAfter) :
    (OriginalF45BracketTree.DepthRotationRoute.PresentedCell.disjointSquare
      left right).interpret target =
      target.disjointSquare left right :=
  rfl

/-- Interpretation of the F55 inverse cell is exactly the chosen
target inverse operation, not an inferred inverse of G.toOplax. -/
theorem OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret_symm
    (target : OriginalF45BracketTree.DepthRotationRoute.HigherCellTarget D E)
    {a b : D} {x y : E} {n n' m m' : Nat}
    {ma mb : Blocks a b} {pa pb : Blocks x y}
    {first : OriginalF45BracketTree n m ma pa mb pb}
    {last : OriginalF45BracketTree n' m' ma pa mb pb}
    {r s : OriginalF45BracketTree.DepthRotationRoute first last}
    (cell : OriginalF45BracketTree.DepthRotationRoute.PresentedCell r s) :
    (OriginalF45BracketTree.DepthRotationRoute.PresentedCell.symm cell).interpret target =
      target.symm (cell.interpret target) :=
  rfl

/-- Vertical pasting of interpreted higher cells preserves the
original chosen target's explicitly supplied pasting operation. -/
theorem OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret_trans
    (target : OriginalF45BracketTree.DepthRotationRoute.HigherCellTarget D E)
    {a b : D} {x y : E} {n n' m m' : Nat}
    {ma mb : Blocks a b} {pa pb : Blocks x y}
    {first : OriginalF45BracketTree n m ma pa mb pb}
    {last : OriginalF45BracketTree n' m' ma pa mb pb}
    {r s t : OriginalF45BracketTree.DepthRotationRoute first last}
    (left : OriginalF45BracketTree.DepthRotationRoute.PresentedCell r s)
    (right : OriginalF45BracketTree.DepthRotationRoute.PresentedCell s t) :
    (OriginalF45BracketTree.DepthRotationRoute.PresentedCell.trans
      left right).interpret target =
      target.trans (left.interpret target) (right.interpret target) :=
  rfl

#print axioms OriginalF45BracketTree.DepthRotationRoute.HigherCellTarget
#print axioms OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret
#print axioms OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret_pentagon
#print axioms OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret_square
#print axioms OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret_symm
#print axioms OriginalF45BracketTree.DepthRotationRoute.PresentedCell.interpret_trans

end
end KUOS.DependentOriginationCoherentBiadjunctionInterleavingExchangeQuotientV5_141.Grid
