import Mathlib
import KUOS.DependentOriginationFreeHistoryFunctorV0_6

namespace KUOS.DependentOriginationMemoryLiftedHistoryTransportV0_7

open KUOS.DependentOriginationHistorySensitiveTransportV0_5
open KUOS.DependentOriginationFreeHistoryFunctorV0_6

universe u v w y

/--
A one-event update on an explicitly enlarged state carrier `Visible × Memory`.

The visible update may depend on the current memory, and the memory update may
depend on both the visible state and the current memory.  No claim is made that
an arbitrary process tensor has this form; this is the explicit state-space
realization used to expose how history dependence can arise after projecting
away memory.
-/
structure MemoryLiftedStep
    (Event : Type u) (Visible : Type v) (Memory : Type w) where
  visibleUpdate : Event → Visible → Memory → Visible
  memoryUpdate : Event → Visible → Memory → Memory

namespace MemoryLiftedStep

variable {Event : Type u} {Visible : Type v} {Memory : Type w}

/-- One event acts on the enlarged state consisting of visible state and memory. -/
def extendedStep
    (S : MemoryLiftedStep Event Visible Memory)
    (event : Event) : Visible × Memory → Visible × Memory :=
  fun state =>
    (S.visibleUpdate event state.1 state.2,
      S.memoryUpdate event state.1 state.2)

/--
The enlarged state evolves by the free finite-history transport generated by
`extendedStep`.  Hence the full visible-plus-memory state is functorial under
finite history concatenation.
-/
def toHistoryTransport
    (S : MemoryLiftedStep Event Visible Memory) :
    HistoryTransport Event (Visible × Memory) :=
  HistoryTransport.ofSingleEventTransport S.extendedStep

/-- The memory-lifted history transport, seen as the free one-object history functor. -/
def toFreeHistoryFunctor
    (S : MemoryLiftedStep Event Visible Memory) :=
  S.toHistoryTransport.toFreeHistoryFunctor

/-- The same construction packaged in the generic functorial dependent-origination interface. -/
def toFunctorialTransportSystem
    (S : MemoryLiftedStep Event Visible Memory) :=
  S.toHistoryTransport.toFunctorialTransportSystem

/-- Visible component after a finite event history from an explicit initial memory. -/
def visibleEval
    (S : MemoryLiftedStep Event Visible Memory)
    (initialMemory : Memory)
    (word : List Event)
    (x : Visible) : Visible :=
  (S.toHistoryTransport.eval word (x, initialMemory)).1

/-- Memory component after a finite event history. -/
def memoryEval
    (S : MemoryLiftedStep Event Visible Memory)
    (initialMemory : Memory)
    (word : List Event)
    (x : Visible) : Memory :=
  (S.toHistoryTransport.eval word (x, initialMemory)).2

/-- Empty history leaves the visible state unchanged. -/
@[simp] theorem visibleEval_nil
    (S : MemoryLiftedStep Event Visible Memory)
    (initialMemory : Memory) (x : Visible) :
    S.visibleEval initialMemory [] x = x := by
  simp [visibleEval, S.toHistoryTransport.eval_nil_apply]

/-- Empty history leaves memory unchanged. -/
@[simp] theorem memoryEval_nil
    (S : MemoryLiftedStep Event Visible Memory)
    (initialMemory : Memory) (x : Visible) :
    S.memoryEval initialMemory [] x = initialMemory := by
  simp [memoryEval, S.toHistoryTransport.eval_nil_apply]

/-- A singleton history is exactly the supplied one-event enlarged-state update. -/
@[simp] theorem toHistoryTransport_eval_singleton
    (S : MemoryLiftedStep Event Visible Memory)
    (event : Event) (state : Visible × Memory) :
    S.toHistoryTransport.eval [event] state = S.extendedStep event state :=
  rfl

/-- Full enlarged-state history composition is exact. -/
theorem extended_eval_append
    (S : MemoryLiftedStep Event Visible Memory)
    (left right : List Event)
    (state : Visible × Memory) :
    S.toHistoryTransport.eval (left ++ right) state =
      S.toHistoryTransport.eval left
        (S.toHistoryTransport.eval right state) :=
  S.toHistoryTransport.eval_append_apply left right state

/--
Projected visible evolution composes only after carrying forward the memory
produced by the right history.

This is the precise state-space form of the non-Markov boundary: the enlarged
state is strictly compositional, while visible dynamics alone requires the
updated hidden/contextual memory.
-/
theorem visibleEval_append
    (S : MemoryLiftedStep Event Visible Memory)
    (initialMemory : Memory)
    (left right : List Event)
    (x : Visible) :
    S.visibleEval initialMemory (left ++ right) x =
      S.visibleEval (S.memoryEval initialMemory right x) left
        (S.visibleEval initialMemory right x) := by
  have h := S.toHistoryTransport.eval_append_apply left right (x, initialMemory)
  simpa [visibleEval, memoryEval] using congrArg Prod.fst h

/-- Memory composition uses the same updated visible state and memory. -/
theorem memoryEval_append
    (S : MemoryLiftedStep Event Visible Memory)
    (initialMemory : Memory)
    (left right : List Event)
    (x : Visible) :
    S.memoryEval initialMemory (left ++ right) x =
      S.memoryEval (S.memoryEval initialMemory right x) left
        (S.visibleEval initialMemory right x) := by
  have h := S.toHistoryTransport.eval_append_apply left right (x, initialMemory)
  simpa [visibleEval, memoryEval] using congrArg Prod.snd h

/-- Two histories are visibly distinguished at a fixed initial memory. -/
def VisibleDistinguishes
    (S : MemoryLiftedStep Event Visible Memory)
    (initialMemory : Memory)
    (left right : List Event) : Prop :=
  ∃ x : Visible,
    S.visibleEval initialMemory left x ≠
      S.visibleEval initialMemory right x

/-- Arbitrary visible readout after a finite history. -/
def visibleReadout
    (S : MemoryLiftedStep Event Visible Memory)
    (readout : Visible → Type y) :=
  readout

end MemoryLiftedStep

section AdditiveSummary

variable {Time : Type u} [AddMonoid Time]
variable {Visible : Type v} {Memory : Type w}

namespace MemoryLiftedStep

/--
Visible history sensitivity relative to an additive coarse summary: two words
have the same total summary but differ after projection to the visible state at
a fixed initial memory.
-/
def GenuinelyVisibleHistorySensitive
    (S : MemoryLiftedStep Time Visible Memory)
    (initialMemory : Memory) : Prop :=
  ∃ left right : List Time,
    left.sum = right.sum ∧
      S.VisibleDistinguishes initialMemory left right

/-- Visible history sensitivity is already a witness of history sensitivity on the enlarged state. -/
theorem extended_genuinelyHistorySensitive_of_visible
    (S : MemoryLiftedStep Time Visible Memory)
    (initialMemory : Memory)
    (h : S.GenuinelyVisibleHistorySensitive initialMemory) :
    S.toHistoryTransport.GenuinelyHistorySensitive := by
  rcases h with ⟨left, right, hSum, x, hx⟩
  refine ⟨left, right, hSum, ?_⟩
  refine ⟨(x, initialMemory), ?_⟩
  intro hEq
  apply hx
  simpa [visibleEval] using congrArg Prod.fst hEq

/--
If the enlarged-state history transport factors through total time, then equal
summary words have identical visible denotation at every fixed initial memory.
-/
theorem visibleEval_eq_of_sum_eq_of_factorization
    (S : MemoryLiftedStep Time Visible Memory)
    (F : TotalTimeFactorization S.toHistoryTransport)
    (initialMemory : Memory)
    (left right : List Time)
    (x : Visible)
    (hSum : left.sum = right.sum) :
    S.visibleEval initialMemory left x =
      S.visibleEval initialMemory right x := by
  have h := F.eval_eq_of_sum_eq left right (x, initialMemory) hSum
  simpa [visibleEval] using congrArg Prod.fst h

/--
A genuine visible history-sensitivity witness obstructs every total-time
factorization of the enlarged-state transport.
-/
theorem no_totalTimeFactorization_of_visible_history_sensitive
    (S : MemoryLiftedStep Time Visible Memory)
    (initialMemory : Memory)
    (h : S.GenuinelyVisibleHistorySensitive initialMemory) :
    ¬ Nonempty (TotalTimeFactorization S.toHistoryTransport) := by
  intro hFactor
  rcases hFactor with ⟨F⟩
  exact
    (S.toHistoryTransport.not_genuinelyHistorySensitive_of_factorization F)
      (S.extended_genuinelyHistorySensitive_of_visible initialMemory h)

end MemoryLiftedStep

end AdditiveSummary

end KUOS.DependentOriginationMemoryLiftedHistoryTransportV0_7
