import KUOS.DependentOriginationFiveGeneratedCorrectionCoboundaryV3_00

namespace KUOS.DependentOriginationCorrectionCoboundarySolvabilityV3_01

open CategoryTheory
open CategoryTheory.Bicategory
open KUOS.DependentOriginationHigherLocalizationInterfaceV2_10
open KUOS.DependentOriginationPointwiseWAdjointEquivalenceV2_56
open KUOS.DependentOriginationCoherentQuotientTransportV2_59
open KUOS.DependentOriginationCoherentComparisonFactorizationV2_60
open KUOS.DependentOriginationPointwiseGeneralWChoiceV2_61
open KUOS.DependentOriginationCoherenceDefectsV2_65
open KUOS.DependentOriginationGaugeObstructionV2_66
open KUOS.DependentOriginationGeneratedPointwiseChoiceV2_68
open KUOS.DependentOriginationFiveGeneratedCorrectionCoboundaryV3_00

universe u v uH vH

/-!
# Solvability of the generated correction coboundary v3.01

v3.00 gives a constructive sufficient route from three lower-dimensional gauge
families and five explicit coboundary equations to higher-localization
factorization.  This file proves that the explicit coboundary language is
extensionally complete for the already isolated coherent-data obstruction.

Every pointwise v2.61 choice determines a normal-form right gauge from the
canonical generated pointwise choice by the quotient
`generated⁻¹ * target`.  Right-composing the generated witnesses with these
three gauge families recovers the target pointwise choice.  Hence every
zero-five-defect representative admits a v3.00 generated-coboundary
presentation.

The main equivalence is

```text
GeneratedCorrectionCoboundarySolvable
        ↔
∃ pointwise choice with FiveCoherenceDefectsTrivial
        ↔
HasCoherentGeneralWFactorizationData.
```

This is an exact characterization of the coherent-data obstruction.  It is not
claimed to characterize every possible `HasHigherLocalizationFactorization`,
because the converse from arbitrary factorization to the chosen coherent-data
package has not been proved.
-/

variable {Context : Type u} [Category.{v} Context]
variable (W : MorphismProperty Context)

/-- Existence of one compatible lower-dimensional gauge whose five induced
faces satisfy the v3.00 coboundary equations. -/
def GeneratedCorrectionCoboundarySolvable
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R) : Prop :=
  ∃ G : GeneratedPointwiseGaugeParameters W R D,
    FiveGeneratedCorrectionCoboundary W R D G

/-- Normal-form gauge parameters from the canonical generated pointwise choice
to an arbitrary target pointwise choice. -/
noncomputable def generatedGaugeParametersToChoice
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (L : PointwiseGeneralWChoiceData (W := W) R D) :
    GeneratedPointwiseGaugeParameters W R D where
  mapIdGauge X :=
    (generatedIdentityMapIso W R D X).symm ≪≫ L.mapId X
  mapCompGauge f g :=
    (generatedCompositionMapIso W R D f g).symm ≪≫ L.mapComp f g
  mapIsoGauge f :=
    (generatedPresentationMapIso W R D f).symm ≪≫ L.mapIso f

@[simp]
theorem gaugeAdjusted_toChoice_mapId
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (L : PointwiseGeneralWChoiceData (W := W) R D)
    (X : W.Localization) :
    (gaugeAdjustedGeneratedPointwiseChoice W R D
      (generatedGaugeParametersToChoice W R D L)).mapId X =
      L.mapId X := by
  change
    generatedIdentityMapIso W R D X ≪≫
        (generatedIdentityMapIso W R D X).symm ≪≫ L.mapId X =
      L.mapId X
  exact Iso.self_symm_id_assoc _ _

@[simp]
theorem gaugeAdjusted_toChoice_mapComp
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (L : PointwiseGeneralWChoiceData (W := W) R D)
    {X Y Z : W.Localization} (f : X ⟶ Y) (g : Y ⟶ Z) :
    (gaugeAdjustedGeneratedPointwiseChoice W R D
      (generatedGaugeParametersToChoice W R D L)).mapComp f g =
      L.mapComp f g := by
  change
    generatedCompositionMapIso W R D f g ≪≫
        (generatedCompositionMapIso W R D f g).symm ≪≫ L.mapComp f g =
      L.mapComp f g
  exact Iso.self_symm_id_assoc _ _

@[simp]
theorem gaugeAdjusted_toChoice_mapIso
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (L : PointwiseGeneralWChoiceData (W := W) R D)
    {X Y : Context} (f : X ⟶ Y) :
    (gaugeAdjustedGeneratedPointwiseChoice W R D
      (generatedGaugeParametersToChoice W R D L)).mapIso f =
      L.mapIso f := by
  change
    generatedPresentationMapIso W R D f ≪≫
        (generatedPresentationMapIso W R D f).symm ≪≫ L.mapIso f =
      L.mapIso f
  exact Iso.self_symm_id_assoc _ _

/-- Extensionality for the v2.61 pointwise bundle, stated locally because the
structure does not carry an autogenerated `@[ext]` theorem. -/
private theorem pointwiseGeneralWChoiceData_ext
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (L L' : PointwiseGeneralWChoiceData (W := W) R D)
    (hId : ∀ X : W.Localization, L.mapId X = L'.mapId X)
    (hComp :
      ∀ {X Y Z : W.Localization} (f : X ⟶ Y) (g : Y ⟶ Z),
        L.mapComp f g = L'.mapComp f g)
    (hIso :
      ∀ {X Y : Context} (f : X ⟶ Y),
        L.mapIso f = L'.mapIso f) :
    L = L' := by
  cases L
  cases L'
  congr
  · funext X
    exact hId X
  · funext X Y Z f g
    exact hComp f g
  · funext X Y f
    exact hIso f

/-- The normal-form gauge adjustment recovers the entire target pointwise
choice, not only each family separately. -/
theorem gaugeAdjustedGeneratedPointwiseChoice_toChoice_eq
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (L : PointwiseGeneralWChoiceData (W := W) R D) :
    gaugeAdjustedGeneratedPointwiseChoice W R D
        (generatedGaugeParametersToChoice W R D L) =
      L := by
  apply pointwiseGeneralWChoiceData_ext W R D
  · intro X
    exact gaugeAdjusted_toChoice_mapId W R D L X
  · intro X Y Z f g
    exact gaugeAdjusted_toChoice_mapComp W R D L f g
  · intro X Y f
    exact gaugeAdjusted_toChoice_mapIso W R D L f

/-- If all five defects already vanish on the gauge-adjusted generated choice,
the five explicit v3.00 coboundary equations follow.  This helper keeps the
dependent quotient-proof transport local: both quotient proofs live over the
same adjusted pointwise choice, so proof irrelevance suffices. -/
noncomputable def fiveGeneratedCorrectionCoboundaryOfAdjustedTrivial
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (G : GeneratedPointwiseGaugeParameters W R D)
    (h : FiveCoherenceDefectsTrivial W R D
      (gaugeAdjustedGeneratedPointwiseChoice W R D G)) :
    FiveGeneratedCorrectionCoboundary W R D G := by
  let L := gaugeAdjustedGeneratedPointwiseChoice W R D G
  let hQ : QuotientTransportDefectsTrivial W R D L := Classical.choose h
  let hC : ComparisonDefectsTrivial W R D L hQ := Classical.choose_spec h
  let Hq : GeneratedGaugeQuotientCoboundary W R D G :=
    { associator := by
        intro X Y Z T f g k
        exact
          (quotientAssociatorDefect_eq_refl_iff W R D L f g k).1
            (hQ.associator f g k)
      leftUnitor := by
        intro X Y f
        exact
          (quotientLeftUnitorDefect_eq_refl_iff W R D L f).1
            (hQ.leftUnitor f)
      rightUnitor := by
        intro X Y f
        exact
          (quotientRightUnitorDefect_eq_refl_iff W R D L f).1
            (hQ.rightUnitor f) }
  have hQeq :
      generatedGaugeQuotientDefectsTrivial W R D G Hq = hQ :=
    Subsingleton.elim _ _
  refine
    { quotient := Hq
      comparisonIdentity := ?_
      comparisonComposition := ?_ }
  · intro X
    have hx :=
      (comparisonIdentityDefect_eq_refl_iff W R D L hQ X).1
        (hC.identity X)
    simpa only [L, hQeq] using hx
  · intro X Y Z f g
    have hfg :=
      (comparisonCompositionDefect_eq_refl_iff W R D L hQ f g).1
        (hC.composition f g)
    simpa only [L, hQeq] using hfg

/-- Every pointwise zero-five-defect representative has a v3.00 coboundary
presentation based at the canonical generated pointwise choice. -/
noncomputable def fiveGeneratedCorrectionCoboundaryToChoice
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (L : PointwiseGeneralWChoiceData (W := W) R D)
    (h : FiveCoherenceDefectsTrivial W R D L) :
    FiveGeneratedCorrectionCoboundary W R D
      (generatedGaugeParametersToChoice W R D L) := by
  let G := generatedGaugeParametersToChoice W R D L
  have hEq :
      gaugeAdjustedGeneratedPointwiseChoice W R D G = L := by
    exact gaugeAdjustedGeneratedPointwiseChoice_toChoice_eq W R D L
  have h' :
      FiveCoherenceDefectsTrivial W R D
        (gaugeAdjustedGeneratedPointwiseChoice W R D G) := by
    simpa only [hEq] using h
  exact fiveGeneratedCorrectionCoboundaryOfAdjustedTrivial W R D G h'

/-- Solvability of the explicit v3.00 coboundary is exactly existence of a
pointwise representative on which all five coherence defects vanish. -/
theorem generatedCorrectionCoboundarySolvable_iff_exists_fiveTrivialDefects
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R) :
    GeneratedCorrectionCoboundarySolvable W R D ↔
      ∃ L : PointwiseGeneralWChoiceData (W := W) R D,
        FiveCoherenceDefectsTrivial W R D L := by
  constructor
  · rintro ⟨G, H⟩
    exact
      ⟨gaugeAdjustedGeneratedPointwiseChoice W R D G,
        fiveCoherenceDefectsTrivial_of_fiveGeneratedCorrectionCoboundary
          W R D G H⟩
  · rintro ⟨L, hL⟩
    exact
      ⟨generatedGaugeParametersToChoice W R D L,
        fiveGeneratedCorrectionCoboundaryToChoice W R D L hL⟩

/-- Main v3.01 characterization: the generated correction coboundary is exactly
the coherent general-W extension obstruction already isolated in v2.66. -/
theorem generatedCorrectionCoboundarySolvable_iff_hasCoherentGeneralWFactorizationData
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R) :
    GeneratedCorrectionCoboundarySolvable W R D ↔
      HasCoherentGeneralWFactorizationData W R D := by
  rw [generatedCorrectionCoboundarySolvable_iff_exists_fiveTrivialDefects W R D]
  exact
    (hasCoherentGeneralWFactorizationData_iff_exists_fiveTrivialDefects
      W R D).symm

/-- In particular, coboundary solvability gives factorization through the exact
coherent-data route. -/
theorem hasHigherLocalizationFactorization_of_generatedCorrectionCoboundarySolvable
    (R : RawHigherContextualSystem.{u, v, uH, vH}
      (Context := Context))
    (D : PointwiseWAdjointEquivalenceData (W := W) R)
    (h : GeneratedCorrectionCoboundarySolvable W R D) :
    HasHigherLocalizationFactorization (W := W) R := by
  have hC : HasCoherentGeneralWFactorizationData W R D :=
    (generatedCorrectionCoboundarySolvable_iff_hasCoherentGeneralWFactorizationData
      W R D).1 h
  exact
    hasHigherLocalizationFactorization_of_hasCoherentGeneralWFactorizationData
      W R D hC

/-!
## Boundary fixed by v3.01

The v2.69--v3.00 correction line is now identified exactly with the v2.66
coherent-data obstruction:

```text
five generated route corrections
arise from one lower-dimensional gauge coboundary
        ↔
some pointwise choice has zero five defects
        ↔
HasCoherentGeneralWFactorizationData.
```

Thus the remaining Stage-I question is exactly the existence question for the
coboundary.  v3.02 can split that question into the quotient three-face problem
and the residual comparison two-face lifting problem.

No converse from arbitrary `HasHigherLocalizationFactorization` to coherent
general-W data is asserted.
-/

end KUOS.DependentOriginationCorrectionCoboundarySolvabilityV3_01
