import KUOS.DependentOriginationCanonicalAttachmentScalingObstructionRetractV1_88

namespace KUOS.DependentOriginationStandardArbitraryScalingWaypointV1_89

open CategoryTheory
open KUOS.DependentOriginationScaledAnodyneGeneratorClosureV1_42
open KUOS.DependentOriginationExternalScaledAnodyneGeneratorComparisonV1_46
open KUOS.DependentOriginationStandardTypeCCollapsedEdgeV1_58
open KUOS.DependentOriginationStandardABCPositiveCanonicalResidualSplitV1_79
open KUOS.DependentOriginationGeneratedPresentationQuotientInvariantV1_81
open KUOS.DependentOriginationGeneratedPresentationOrderReflectionV1_84
open KUOS.DependentOriginationGeneratedPresentationCompleteLatticeV1_86
open KUOS.DependentOriginationStandardCanonicalPresentationGapV1_87
open KUOS.DependentOriginationCanonicalAttachmentScalingObstructionRetractV1_88

universe u

/-!
# The standard arbitrary-scaling waypoint v1.89

Version v1.88 proves that the canonical KuuOS horn-cylinder family detects,
by arrow retracts, every pure simplex scaling enrichment

```text
(Delta[n], minimal) -> (Delta[n], sDelta).
```

Thus a canonical-to-standard comparison necessarily absorbs the whole pure
scaling family into the standard generated left class.  The complete lattice
from v1.86 lets us isolate that obligation as an actual presentation point.

Let

```text
S := standardABCPresentation,
C := canonicalKuuOSPresentation,
A := presentation generated by all pure simplex scaling enrichments.
```

Version v1.88 gives `A <= C`.  We therefore define the waypoint

```text
W := S sup A.
```

It lies inside the v1.87 standard/canonical gap, satisfies `S <= W`, and does
not enlarge the global upper envelope:

```text
W sup C = S sup C.
```

The pure-scaling obstruction is closed exactly when `W = S`, equivalently
when every arbitrary simplex scaling enrichment is standard-generated.
Moreover the forward comparison factors exactly as

```text
C <= S
  <->
(W = S) and (C <= W).
```

The second clause is the residual canonical geometry after the entire pure
scaling family has already been adjoined to the standard point.  Combining
this with the v1.84 reverse generatorwise comparison gives a three-piece exact
criterion for collapse of the full presentation gap:

1. literal standard A/B/C generators are canonical-generated;
2. the pure-scaling waypoint collapses back to standard;
3. the remaining canonical geometry lies below the scaling-adjusted waypoint.

No one of these pieces is asserted automatically.  The point is to separate
the intrinsic scaling obstruction proved in v1.88 from the remaining horn and
attachment geometry without changing the unconditional ambient invariant.
-/

/-! ## The pure-scaling presentation point -/

/-- Presentation generated by every minimal-to-chosen simplex scaling
enrichment isolated in v1.88. -/
def arbitrarySimplexScalingPresentation :
    GeneratedScaledAnodynePresentation.{u} :=
  presentationClass
    (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u}))

/-- The pure-scaling presentation is canonically below the KuuOS presentation,
because every one of its generators is already in the canonical generated
left class by the v1.88 retract theorem. -/
theorem arbitrarySimplexScalingPresentation_le_canonicalKuuOS :
    arbitrarySimplexScalingPresentation.{u} <= canonicalKuuOSPresentation := by
  change
    presentationClass
        (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u})) <=
      presentationClass
        (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u}))
  apply
    (presentationClass_le_iff_generators_le_generated
      (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u}))
      (scaledHornAttachmentGenerators : MorphismProperty (ScaledSSet.{u}))).2
  simpa [externalGeneratedScaledAnodyne, canonicalGeneratedScaledAnodyne] using
    (simplexScalingEnrichments_le_canonicalGenerated :
      (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u})) <=
        (canonicalGeneratedScaledAnodyne : MorphismProperty (ScaledSSet.{u})))

/-- Pure scaling lies below the standard presentation exactly when every pure
scaling generator is standard-generated. -/
theorem arbitrarySimplexScalingPresentation_le_standardABC_iff :
    arbitrarySimplexScalingPresentation.{u} <= standardABCPresentation <->
      (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u})) <=
        standardGeneratedScaledAnodyneABC := by
  simpa [arbitrarySimplexScalingPresentation, standardABCPresentation,
    externalGeneratedScaledAnodyne, standardGeneratedScaledAnodyneABC] using
    (presentationClass_le_iff_generators_le_generated
      (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u}))
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})))

/-! ## The scaling-adjusted standard waypoint -/

/-- Adjoin the complete pure-scaling presentation to the standard A/B/C point. -/
def standardArbitraryScalingWaypoint :
    GeneratedScaledAnodynePresentation.{u} :=
  standardABCPresentation ⊔ arbitrarySimplexScalingPresentation

/-- Standard lies below its scaling-adjusted waypoint. -/
theorem standardABC_le_arbitraryScalingWaypoint :
    standardABCPresentation <= standardArbitraryScalingWaypoint.{u} := by
  exact le_sup_left

/-- The pure-scaling point also lies below the waypoint. -/
theorem arbitrarySimplexScalingPresentation_le_waypoint :
    arbitrarySimplexScalingPresentation.{u} <=
      standardArbitraryScalingWaypoint := by
  exact le_sup_right

/-- The waypoint stays below the original standard/canonical upper envelope.
This uses only the unconditional v1.88 inclusion `A <= C`. -/
theorem arbitraryScalingWaypoint_le_upperEnvelope :
    standardArbitraryScalingWaypoint.{u} <=
      standardCanonicalUpperEnvelope := by
  unfold standardArbitraryScalingWaypoint standardCanonicalUpperEnvelope
  exact sup_le le_sup_left
    (arbitrarySimplexScalingPresentation_le_canonicalKuuOS.trans le_sup_right)

/-- Hence the original lower envelope lies below the waypoint. -/
theorem lowerEnvelope_le_arbitraryScalingWaypoint :
    standardCanonicalLowerEnvelope.{u} <=
      standardArbitraryScalingWaypoint := by
  exact lowerEnvelope_le_standardABC.trans
    standardABC_le_arbitraryScalingWaypoint

/-- The scaling-adjusted waypoint is a genuine point of the intrinsic v1.87
presentation gap. -/
theorem arbitraryScalingWaypoint_mem_standardCanonicalInterval :
    standardArbitraryScalingWaypoint.{u} ∈
      standardCanonicalPresentationInterval := by
  exact
    ⟨lowerEnvelope_le_arbitraryScalingWaypoint,
      arbitraryScalingWaypoint_le_upperEnvelope⟩

/-- Adjoining the waypoint to the canonical point gives exactly the original
upper envelope.  Pure scaling introduces no theory above the canonical point
because it is already canonical-generated. -/
theorem arbitraryScalingWaypoint_sup_canonical_eq_upperEnvelope :
    standardArbitraryScalingWaypoint.{u} ⊔ canonicalKuuOSPresentation =
      standardCanonicalUpperEnvelope := by
  apply le_antisymm
  · exact sup_le
      arbitraryScalingWaypoint_le_upperEnvelope
      canonicalKuuOS_le_upperEnvelope
  · unfold standardCanonicalUpperEnvelope
    exact sup_le
      (standardABC_le_arbitraryScalingWaypoint.trans le_sup_left)
      le_sup_right

/-- Standard is exactly the meet of itself with the scaling waypoint. -/
theorem standardABC_inf_arbitraryScalingWaypoint :
    standardABCPresentation ⊓ standardArbitraryScalingWaypoint.{u} =
      standardABCPresentation := by
  exact inf_eq_left.mpr standardABC_le_arbitraryScalingWaypoint

/-! ## Closing the pure-scaling layer -/

/-- The pure-scaling obstruction is closed when adjoining all arbitrary
simplex scaling enrichments does not move the standard presentation point. -/
def StandardArbitraryScalingObstructionClosed : Prop :=
  standardArbitraryScalingWaypoint.{u} = standardABCPresentation

/-- Closing the scaling layer is exactly containment of the pure-scaling
presentation in the standard point. -/
theorem standardArbitraryScalingObstructionClosed_iff_presentation_le :
    StandardArbitraryScalingObstructionClosed.{u} <->
      arbitrarySimplexScalingPresentation <= standardABCPresentation := by
  unfold StandardArbitraryScalingObstructionClosed
  unfold standardArbitraryScalingWaypoint
  exact sup_eq_left

/-- Generator-level form: the scaling layer closes exactly when every
minimal-to-arbitrary simplex scaling enrichment is standard-generated. -/
theorem standardArbitraryScalingObstructionClosed_iff_generators_le :
    StandardArbitraryScalingObstructionClosed.{u} <->
      (simplexScalingEnrichments : MorphismProperty (ScaledSSet.{u})) <=
        standardGeneratedScaledAnodyneABC := by
  rw [standardArbitraryScalingObstructionClosed_iff_presentation_le,
    arbitrarySimplexScalingPresentation_le_standardABC_iff]

/-- Any canonical-to-standard comparison necessarily closes the pure-scaling
layer, by the intrinsic retract theorem of v1.88. -/
theorem standardArbitraryScalingObstructionClosed_of_canonicalKuuOS_le_standardABC
    (h : canonicalKuuOSPresentation <= standardABCPresentation) :
    StandardArbitraryScalingObstructionClosed.{u} := by
  apply standardArbitraryScalingObstructionClosed_iff_generators_le.2
  exact
    simplexScalingEnrichments_le_standardGenerated_of_canonicalKuuOS_le_standardABC
      h

/-- The existing positive forward residual package therefore closes the
pure-scaling layer as a consequence, not as an extra assumption. -/
theorem standardArbitraryScalingObstructionClosed_of_positiveResidual
    (K : StandardABCCanonicalPositiveResidualComparison.{u}) :
    StandardArbitraryScalingObstructionClosed.{u} := by
  exact
    standardArbitraryScalingObstructionClosed_of_canonicalKuuOS_le_standardABC
      (canonicalKuuOS_le_standardABC_of_positiveResidual K)

/-- Full standard/canonical gap closure also forces the scaling waypoint to
collapse. -/
theorem standardArbitraryScalingObstructionClosed_of_gapClosed
    (hgap : StandardCanonicalPresentationGapClosed.{u}) :
    StandardArbitraryScalingObstructionClosed.{u} := by
  have hmutual := standardCanonicalPresentationGapClosed_iff_mutual_le.1 hgap
  exact
    standardArbitraryScalingObstructionClosed_of_canonicalKuuOS_le_standardABC
      hmutual.2

/-! ## Exact factorization of the forward comparison -/

/-- Residual forward geometry after the complete pure-scaling presentation has
already been adjoined to the standard point. -/
def CanonicalBelowStandardAfterArbitraryScaling : Prop :=
  canonicalKuuOSPresentation <= standardArbitraryScalingWaypoint.{u}

/-- The canonical-to-standard direction factors exactly into closure of the
pure-scaling layer and the residual comparison against the scaling-adjusted
waypoint. -/
theorem canonicalKuuOS_le_standardABC_iff_scalingClosed_and_residual :
    canonicalKuuOSPresentation <= standardABCPresentation <->
      StandardArbitraryScalingObstructionClosed.{u} /\
        CanonicalBelowStandardAfterArbitraryScaling.{u} := by
  constructor
  · intro h
    constructor
    · exact
        standardArbitraryScalingObstructionClosed_of_canonicalKuuOS_le_standardABC h
    · exact h.trans standardABC_le_arbitraryScalingWaypoint
  · rintro ⟨hscale, hresidual⟩
    unfold CanonicalBelowStandardAfterArbitraryScaling at hresidual
    unfold StandardArbitraryScalingObstructionClosed at hscale
    simpa [hscale] using hresidual

/-- If the scaling waypoint does not collapse, canonical-below-standard is
impossible. -/
theorem not_canonicalKuuOS_le_standardABC_of_scalingObstruction_open
    (hopen : ¬ StandardArbitraryScalingObstructionClosed.{u}) :
    ¬ canonicalKuuOSPresentation <= standardABCPresentation := by
  intro h
  exact hopen
    (standardArbitraryScalingObstructionClosed_of_canonicalKuuOS_le_standardABC h)

/-- An open pure-scaling obstruction also prevents full presentation-gap
closure. -/
theorem not_standardCanonicalPresentationGapClosed_of_scalingObstruction_open
    (hopen : ¬ StandardArbitraryScalingObstructionClosed.{u}) :
    ¬ StandardCanonicalPresentationGapClosed.{u} := by
  intro hgap
  exact hopen (standardArbitraryScalingObstructionClosed_of_gapClosed hgap)

/-! ## Three-piece exact criterion for full gap closure -/

/-- Full presentation equality decomposes into the reverse standard-generator
comparison, closure of the pure-scaling layer, and the residual forward
geometry after scaling has been adjoined. -/
theorem standardCanonicalPresentationGapClosed_iff_reverse_scaling_residual :
    StandardCanonicalPresentationGapClosed.{u} <->
      StandardABCCanonicalGeneratorwiseReverseComparison.{u} /\
        StandardArbitraryScalingObstructionClosed.{u} /\
          CanonicalBelowStandardAfterArbitraryScaling.{u} := by
  constructor
  · intro hgap
    have hmutual := standardCanonicalPresentationGapClosed_iff_mutual_le.1 hgap
    have hforward :=
      canonicalKuuOS_le_standardABC_iff_scalingClosed_and_residual.1 hmutual.2
    exact
      ⟨standardABC_le_canonicalKuuOS_iff_generatorwiseReverse.1 hmutual.1,
        hforward.1, hforward.2⟩
  · rintro ⟨hreverse, hscale, hresidual⟩
    apply standardCanonicalPresentationGapClosed_iff_mutual_le.2
    constructor
    · exact standardABC_le_canonicalKuuOS_iff_generatorwiseReverse.2 hreverse
    · exact
        canonicalKuuOS_le_standardABC_iff_scalingClosed_and_residual.2
          ⟨hscale, hresidual⟩

/-!
The v1.87 interval now contains a distinguished scaling waypoint

```text
S <= W <= S sup C,
A <= C,
W sup C = S sup C.
```

The forward comparison is no longer treated as one opaque inclusion:

```text
C <= S
  <-> scaling layer closes and C <= W.
```

Together with the exact v1.84 reverse comparison, full gap closure is
therefore equivalent to three logically distinct geometric obligations:

```text
standard A/B/C generators <= canonicalGenerated,
W = S,
C <= W.
```

The middle equality is precisely the pure arbitrary-scaling obstruction
extracted by the v1.88 arrow retract.  This gives the next geometric work a
clean target: either prove that pure scaling is absorbed by the standard
presentation, or construct a single witness showing that it is not; only after
that layer is settled does the residual attachment geometry need to be
analyzed.
-/

end KUOS.DependentOriginationStandardArbitraryScalingWaypointV1_89
