import Mathlib
import KUOS.DependentOriginationHistorySensitiveTransportV0_5

namespace KUOS.DependentOriginationFreeHistoryFunctorV0_6

open CategoryTheory
open KUOS.DependentOriginationFunctorialTransportV0_1
open KUOS.DependentOriginationHistorySensitiveTransportV0_5

universe u v

/--
The category generated by finite words in `Event`.

`FreeMonoid Event` is the free monoid on the event type, and `SingleObj` turns
that monoid into a one-object category.  Composition is reversed
multiplication in `SingleObj`, exactly matching the KuuOS convention that the
left history acts after the right history:

`eval (left ++ right) x = eval left (eval right x)`.
-/
abbrev FreeHistoryCategory (Event : Type u) :=
  CategoryTheory.SingleObj (FreeMonoid Event)

namespace HistoryTransport

variable {Event : Type u} {State : Type v}

/--
Every compositional finite-history transport is canonically a functor from the
free one-object history category into `Type`.

This is the categorical realization of the v0.5 history spine.  The source
morphisms are finite event words; the unique target object is the supplied
state carrier; functoriality is exactly `eval_nil` plus `eval_append`.
-/
def toFreeHistoryFunctor
    (H : HistoryTransport Event State) :
    FreeHistoryCategory Event ⥤ Type v where
  obj := fun _ => State
  map := fun word => TypeCat.ofHom (H.eval (FreeMonoid.toList word))
  map_id := by
    intro X
    ext x
    change H.eval (FreeMonoid.toList (1 : FreeMonoid Event)) x = x
    simp [H.eval_nil]
  map_comp := by
    intro X Y Z f g
    ext x
    change
      H.eval (FreeMonoid.toList (f ≫ g)) x =
        H.eval (FreeMonoid.toList g) (H.eval (FreeMonoid.toList f) x)
    rw [CategoryTheory.SingleObj.comp_as_mul, FreeMonoid.toList_mul]
    exact H.eval_append (FreeMonoid.toList g) (FreeMonoid.toList f) x

/--
The same free-history functor packaged in the generic v0.1
`FunctorialTransportSystem` interface.
-/
def toFunctorialTransportSystem
    (H : HistoryTransport Event State) :
    FunctorialTransportSystem (FreeHistoryCategory Event) where
  state := toFreeHistoryFunctor H

/-- The transport associated with one generating event. -/
def singleEventTransport
    (H : HistoryTransport Event State)
    (event : Event) : State → State :=
  H.eval [event]

/-- A nonempty history is generated by its head event acting after its tail. -/
theorem eval_cons
    (H : HistoryTransport Event State)
    (event : Event) (tail : List Event) (x : State) :
    H.eval (event :: tail) x =
      singleEventTransport H event (H.eval tail x) := by
  simpa [singleEventTransport] using H.eval_append [event] tail x

/--
Every finite-history denotation is the right fold of the single-event
transports.  Thus a `HistoryTransport` is completely generated by its action on
one-letter histories.
-/
theorem eval_eq_foldr_singleEvent
    (H : HistoryTransport Event State)
    (word : List Event) (x : State) :
    H.eval word x =
      word.foldr (fun event acc => singleEventTransport H event acc) x := by
  induction word with
  | nil =>
      change H.eval [] x = x
      exact H.eval_nil x
  | cons event tail ih =>
      change H.eval (event :: tail) x =
        singleEventTransport H event
          (tail.foldr (fun e acc => singleEventTransport H e acc) x)
      rw [eval_cons H event tail x, ih]

/--
Construct a compositional history transport from arbitrary single-event state
updates.  No commutativity, invertibility, Markov coarse summary, or total-time
factorization is required.
-/
def ofSingleEventTransport
    (step : Event → State → State) :
    HistoryTransport Event State where
  eval := fun word x => word.foldr (fun event acc => step event acc) x
  eval_nil := by
    intro x
    rfl
  eval_append := by
    intro left right x
    induction left with
    | nil =>
        rfl
    | cons event tail ih =>
        change step event
            ((tail ++ right).foldr (fun e acc => step e acc) x) =
          step event
            (tail.foldr (fun e acc => step e acc)
              (right.foldr (fun e acc => step e acc) x))
        rw [ih]

/--
Reconstructing a history transport from its one-event generators recovers its
denotation pointwise on every finite word.
-/
theorem ofSingleEventTransport_eval_eq
    (H : HistoryTransport Event State)
    (word : List Event) (x : State) :
    (ofSingleEventTransport (singleEventTransport H)).eval word x =
      H.eval word x := by
  change
    word.foldr (fun event acc => singleEventTransport H event acc) x =
      H.eval word x
  exact (eval_eq_foldr_singleEvent H word x).symm

/--
Consequently, two history transports with identical one-event action have
identical denotation on every finite word.
-/
theorem eval_eq_of_singleEventTransport_eq
    (H₁ H₂ : HistoryTransport Event State)
    (hStep : ∀ event x,
      singleEventTransport H₁ event x = singleEventTransport H₂ event x)
    (word : List Event) (x : State) :
    H₁.eval word x = H₂.eval word x := by
  rw [eval_eq_foldr_singleEvent H₁ word x,
    eval_eq_foldr_singleEvent H₂ word x]
  induction word with
  | nil =>
      rfl
  | cons event tail ih =>
      change singleEventTransport H₁ event
          (tail.foldr (fun e acc => singleEventTransport H₁ e acc) x) =
        singleEventTransport H₂ event
          (tail.foldr (fun e acc => singleEventTransport H₂ e acc) x)
      rw [hStep event, ih]

end HistoryTransport
end KUOS.DependentOriginationFreeHistoryFunctorV0_6

/-! Preserve receiver notation for finite-history APIs added in v0.6. -/
namespace KUOS.DependentOriginationHistorySensitiveTransportV0_5.HistoryTransport
export KUOS.DependentOriginationFreeHistoryFunctorV0_6.HistoryTransport
  (toFreeHistoryFunctor toFunctorialTransportSystem singleEventTransport
    eval_cons eval_eq_foldr_singleEvent ofSingleEventTransport
    ofSingleEventTransport_eval_eq eval_eq_of_singleEventTransport_eq)
end KUOS.DependentOriginationHistorySensitiveTransportV0_5.HistoryTransport