import KUOS.DependentOriginationStandardTypeABoundaryPrismRawTransfiniteV1_76

namespace KUOS.DependentOriginationStandardTypeAEndpointOppositeCellCertificateV1_77

open CategoryTheory
open CategoryTheory.Category
open CategoryTheory.Limits
open MonoidalCategory
open Opposite
open Simplicial
open KUOS.DependentOriginationScaledTerminalRLPV1_41
open KUOS.DependentOriginationScaledAnodyneAttachmentFactorizationV1_48
open KUOS.DependentOriginationStandardTypeAScaledHornFamilyV1_49
open KUOS.DependentOriginationStandardTypeAEndpointPushoutProductV1_50
open KUOS.DependentOriginationScaledCartesianIntervalCylinderV1_52
open KUOS.DependentOriginationStandardTypeAScaledPushoutSourceEnrichmentV1_53
open KUOS.DependentOriginationStandardTypeAScaledLeibnizPushoutV1_55
open KUOS.DependentOriginationStandardABCLeibnizCellularComparisonV1_59
open KUOS.DependentOriginationStandardTypeAEndpointPrismPairingV1_60
open KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseABCellularityV1_72
open KUOS.DependentOriginationStandardTypeABoundaryPrismRankwiseScaledPushoutV1_73
open KUOS.DependentOriginationStandardTypeABoundaryPrismRawTransfiniteV1_76

universe u

noncomputable section

/-!
# The missing opposite endpoint A-cell and the final standard A/B/C certificate v1.77

Version v1.76 finished the boundary-prism inclusion

```text
A_boundary -> Delta[n] x Delta[1]
```

as one natural-number transfinite composition of raw standard type-(A)/(B)
cellular steps.  The only remaining map in the v1.60 factorization is

```text
A_epsilon -> A_boundary.
```

This file closes that last geometric gap and then instantiates the exact v1.59
`StandardABCTypeAEndpointLeibnizCellularCertificate`.

There are two points which must not be hidden.

First, the v1.55 categorical endpoint source carries the *least generated*
scaling, while v1.60's boundary prism carries the ambient cylinder pullback
scaling.  We prove that the source distinction disappears: every simplex of a
`unionProd` belongs to one of its two defining legs, so every ambient-thin
source triangle is generated by the corresponding leg.  Hence

```text
T_generated = T_induced = T_ambient|A_epsilon.
```

Second, the missing cell is not declared to be literally a standard A horn.
On carriers it is the opposite endpoint product

```text
Lambda_i^n x {1-epsilon} -> Delta[n] x {1-epsilon}.
```

The endpoint subcomplex is a copy of `Delta[0]`, hence terminal.  Projection
onto the first coordinate gives explicit scaled isomorphisms of this product
arrow with the literal standard type-(A) horn generator.  The subcomplex
lattice square is bicartesian because

```text
partial Delta[1] = {epsilon} union {1-epsilon},
{epsilon} intersection {1-epsilon} = empty.
```

Mathlib's `Subcomplex.BicartSq.isPushout`, upgraded with the generated-scaled
pushout theorem of v1.73, therefore makes `A_epsilon -> A_boundary` one raw
standard A cellular step.

Composing that step with the v1.76 boundary-prism transfinite composition gives
the full genuine scaled endpoint Leibniz map in `standardABCCellularClosure`.
No type-(C) cell is used, and no identification of the arbitrary-scaling
canonical KuuOS family with the standard A/B/C family is asserted.
-/

/-! ## The least-generated endpoint source already has the full induced scaling -/

/-- Reverse inclusion to v1.53's `generated <= induced` theorem.

A source triangle belongs setwise either to the simplex-endpoint leg or to the
horn-interval leg.  In the first case it lifts to a thin triangle of the first
leg; in the second case it lifts to a thin triangle of the second leg. -/
theorem standardTypeAEndpointInducedProductPullbackScaling_le_generated
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScalingLE
      (standardTypeAEndpointInducedProductPullbackScaling g)
      (standardTypeAEndpointGeneratedPushoutScaling g) := by
  intro t ht
  have htmem :
      t.val ∈
        ((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint)).obj (op ⦋2⦌) :=
    t.property
  rw [SSet.Subcomplex.mem_unionProd_iff] at htmem
  rcases htmem with hendpoint | hhorn
  · let x :
        ((Δ[g.n] : SSet.{u}) ⊗
          (intervalEndpoint g.endpoint : SSet.{u})).obj (op ⦋2⦌) :=
      ⟨t.val.1, ⟨t.val.2, hendpoint⟩⟩
    have hxmap :
        (SSet.Subcomplex.unionProd.ι₁
          (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)).app
            (op ⦋2⦌) x = t := by
      apply Subtype.ext
      rfl
    refine Or.inr (Or.inr (Or.inl ⟨x, ?_, hxmap⟩))
    change
      (standardTypeAEndpointInducedProductPullbackScaling g).thin
        ((SSet.Subcomplex.unionProd.ι₁
          (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)).app
            (op ⦋2⦌) x)
    rw [hxmap]
    exact ht
  · let x :
        ((SSet.horn g.n g.i : SSet.{u}) ⊗ Δ[1]).obj (op ⦋2⦌) :=
      ⟨⟨t.val.1, hhorn⟩, t.val.2⟩
    have hxmap :
        (SSet.Subcomplex.unionProd.ι₂
          (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)).app
            (op ⦋2⦌) x = t := by
      apply Subtype.ext
      rfl
    refine Or.inr (Or.inr (Or.inr ⟨x, ?_, hxmap⟩))
    change
      (standardTypeAEndpointInducedProductPullbackScaling g).thin
        ((SSet.Subcomplex.unionProd.ι₂
          (SSet.horn g.n g.i) (intervalEndpoint g.endpoint)).app
            (op ⦋2⦌) x)
    rw [hxmap]
    exact ht

/-- The categorical least-generated endpoint source scaling is exactly the
full induced pullback scaling. -/
theorem standardTypeAEndpointGeneratedPushoutScaling_eq_induced
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointGeneratedPushoutScaling g =
      standardTypeAEndpointInducedProductPullbackScaling g :=
  scaling_eq_of_le_antisymm
    (standardTypeAEndpointGeneratedPushoutScaling_le_induced g)
    (standardTypeAEndpointInducedProductPullbackScaling_le_generated g)

/-- Ambient cylinder pullback scaling on the endpoint source carrier. -/
def standardTypeAEndpointAmbientSourceScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScaledSimplicialSet
      ((SSet.horn g.n g.i).unionProd
        (intervalEndpoint g.endpoint) : SSet.{u}) :=
  pullbackScaling
    (scaledSimplexCylinder (standardTypeASimplexScaling g.i)).scaling
    ((SSet.horn g.n g.i).unionProd
      (intervalEndpoint g.endpoint)).ι

/-- The least-generated source is in fact exactly the ambient-pullback-scaled
source used by the prism factorization. -/
theorem standardTypeAEndpointGeneratedPushoutScaling_eq_ambient
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointGeneratedPushoutScaling g =
      standardTypeAEndpointAmbientSourceScaling g := by
  rw [standardTypeAEndpointGeneratedPushoutScaling_eq_induced g]
  unfold standardTypeAEndpointInducedProductPullbackScaling
  unfold standardTypeAEndpointCylinderProductScaling
  unfold standardTypeAEndpointAmbientSourceScaling
  rw [cartesianProductScaling_interval_eq_simplexCylinderScaling
    (standardTypeASimplexScaling g.i)
    (ScaledSimplicialSet.maximal (Δ[1] : SSet.{u}))]
  rfl

/-- Endpoint source with its now-canonical ambient pullback scaling. -/
def standardTypeAEndpointAmbientSource
    (g : StandardTypeAHornAttachmentGeneratorIndex) : ScaledSSet.{u} :=
  ScaledSSet.of
    ((SSet.horn g.n g.i).unionProd
      (intervalEndpoint g.endpoint) : SSet.{u})
    (standardTypeAEndpointAmbientSourceScaling g)

/-- Identity-underlying scaled isomorphism from the v1.55 categorical source
to the ambient-pullback presentation. -/
def standardTypeAEndpointGeneratedSourceIsoAmbient
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointGeneratedPushoutSource g ≅
      standardTypeAEndpointAmbientSource g :=
  scalingEqualityIso
    (standardTypeAEndpointGeneratedPushoutScaling g)
    (standardTypeAEndpointAmbientSourceScaling g)
    (standardTypeAEndpointGeneratedPushoutScaling_eq_ambient g)

/-! ## The interval boundary is exactly its two endpoint subcomplexes -/

/-- Endpoint zero is the face opposite vertex one. -/
theorem intervalEndpoint_zero_eq_face_one :
    intervalEndpoint (0 : Fin 2) =
      SSet.stdSimplex.face ({(1 : Fin 2)}ᶜ) := by
  unfold intervalEndpoint
  rw [SSet.stdSimplex.face_singleton_compl]
  rfl

/-- Endpoint one is the face opposite vertex zero. -/
theorem intervalEndpoint_one_eq_face_zero :
    intervalEndpoint (1 : Fin 2) =
      SSet.stdSimplex.face ({(0 : Fin 2)}ᶜ) := by
  unfold intervalEndpoint
  rw [SSet.stdSimplex.face_singleton_compl]
  rfl

/-- Uniform face presentation of an interval endpoint. -/
theorem intervalEndpoint_eq_face_rev (ε : Fin 2) :
    intervalEndpoint ε =
      SSet.stdSimplex.face ({ε.rev}ᶜ) := by
  fin_cases ε
  · simpa using intervalEndpoint_zero_eq_face_one
  · simpa using intervalEndpoint_one_eq_face_zero

/-- The two distinct endpoint subcomplexes are disjoint. -/
theorem intervalEndpoint_inf_rev_eq_bot (ε : Fin 2) :
    intervalEndpoint ε ⊓ intervalEndpoint ε.rev =
      (⊥ : (Δ[1] : SSet.{u}).Subcomplex) := by
  fin_cases ε
  · rw [intervalEndpoint_zero_eq_face_one,
      intervalEndpoint_one_eq_face_zero,
      SSet.stdSimplex.face_inter_face]
    simp
  · rw [intervalEndpoint_one_eq_face_zero,
      intervalEndpoint_zero_eq_face_one,
      SSet.stdSimplex.face_inter_face]
    simp

/-- The boundary of the interval is the union of endpoint zero and endpoint
one. -/
theorem intervalBoundary_eq_endpoint_zero_sup_one :
    (∂Δ[1] : (Δ[1] : SSet.{u}).Subcomplex) =
      intervalEndpoint 0 ⊔ intervalEndpoint 1 := by
  rw [SSet.boundary_eq_iSup]
  apply le_antisymm
  · refine iSup_le ?_
    intro i
    fin_cases i
    · rw [← intervalEndpoint_one_eq_face_zero]
      exact le_sup_right
    · rw [← intervalEndpoint_zero_eq_face_one]
      exact le_sup_left
  · exact sup_le
      (intervalEndpoint_le_boundary 0)
      (intervalEndpoint_le_boundary 1)

/-- Endpoint-symmetric form used by the missing-cell square. -/
theorem intervalBoundary_eq_endpoint_sup_rev (ε : Fin 2) :
    (∂Δ[1] : (Δ[1] : SSet.{u}).Subcomplex) =
      intervalEndpoint ε ⊔ intervalEndpoint ε.rev := by
  fin_cases ε
  · simpa using intervalBoundary_eq_endpoint_zero_sup_one
  · simpa [sup_comm] using intervalBoundary_eq_endpoint_zero_sup_one

/-! ## The ordinary missing-endpoint square is bicartesian -/

/-- Corner subcomplex for attaching the opposite endpoint copy of the horn. -/
def standardTypeAEndpointOppositeCornerSubcomplex
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ((Δ[g.n] : SSet.{u}) ⊗ Δ[1]).Subcomplex :=
  (SSet.horn g.n g.i).prod (intervalEndpoint g.endpoint.rev)

/-- Opposite endpoint copy of the whole simplex. -/
def standardTypeAEndpointOppositeSimplexSubcomplex
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ((Δ[g.n] : SSet.{u}) ⊗ Δ[1]).Subcomplex :=
  (⊤ : (Δ[g.n] : SSet.{u}).Subcomplex).prod
    (intervalEndpoint g.endpoint.rev)

/-- The four subcomplexes form the exact lattice pushout square. -/
def standardTypeAEndpointOppositeCarrierBicartSq
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    SSet.Subcomplex.BicartSq
      (standardTypeAEndpointOppositeCornerSubcomplex g)
      (standardTypeAEndpointOppositeSimplexSubcomplex g)
      ((SSet.horn g.n g.i).unionProd (intervalEndpoint g.endpoint))
      (standardTypeABoundaryPrismSubcomplex g) where
  sup_eq := by
    rw [standardTypeABoundaryPrismSubcomplex,
      intervalBoundary_eq_endpoint_sup_rev g.endpoint]
    ext d ⟨x, y⟩
    change
      ((x ∈ Set.univ ∧
          y ∈ (intervalEndpoint g.endpoint.rev).obj d) ∨
        (y ∈ (intervalEndpoint g.endpoint).obj d ∨
          x ∈ (SSet.horn g.n g.i).obj d)) ↔
        ((y ∈ (intervalEndpoint g.endpoint).obj d ∨
          y ∈ (intervalEndpoint g.endpoint.rev).obj d) ∨
          x ∈ (SSet.horn g.n g.i).obj d)
    simp only [Set.mem_univ, true_and]
    tauto
  inf_eq := by
    ext d ⟨x, y⟩
    change
      ((x ∈ Set.univ ∧
          y ∈ (intervalEndpoint g.endpoint.rev).obj d) ∧
        (y ∈ (intervalEndpoint g.endpoint).obj d ∨
          x ∈ (SSet.horn g.n g.i).obj d)) ↔
        (x ∈ (SSet.horn g.n g.i).obj d ∧
          y ∈ (intervalEndpoint g.endpoint.rev).obj d)
    have hdis :
        ¬ (y ∈ (intervalEndpoint g.endpoint).obj d ∧
          y ∈ (intervalEndpoint g.endpoint.rev).obj d) := by
      intro h
      have hm :
          y ∈
            (intervalEndpoint g.endpoint ⊓
              intervalEndpoint g.endpoint.rev).obj d := h
      rw [intervalEndpoint_inf_rev_eq_bot g.endpoint] at hm
      simpa using hm
    simp only [Set.mem_univ, true_and]
    tauto

/-- The preceding lattice square is therefore a genuine ordinary simplicial
pushout.  We immediately flip it so that the standard A cell is the second
map and the endpoint-source inclusion is the cobase-change output, matching
`MorphismProperty.pushouts_mk`. -/
noncomputable def standardTypeAEndpointOppositeCarrier_isPushout
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    IsPushout
      (SSet.Subcomplex.homOfLE
        (standardTypeAEndpointOppositeCarrierBicartSq g).le₁₃)
      (SSet.Subcomplex.homOfLE
        (standardTypeAEndpointOppositeCarrierBicartSq g).le₁₂)
      (SSet.Subcomplex.homOfLE
        (standardTypeAEndpointOppositeCarrierBicartSq g).le₃₄)
      (SSet.Subcomplex.homOfLE
        (standardTypeAEndpointOppositeCarrierBicartSq g).le₂₄) :=
  (standardTypeAEndpointOppositeCarrierBicartSq g).isPushout.flip

/-! ## Product with an interval endpoint is the same standard A cell -/

/-- Each endpoint subcomplex is canonically a copy of `Delta[0]`. -/
noncomputable def intervalEndpointIsoStdZero (ε : Fin 2) :
    (Δ[0] : SSet.{u}) ≅ (intervalEndpoint ε : SSet.{u}) :=
  SSet.stdSimplex.faceSingletonComplIso ε.rev ≪≫
    SSet.Subcomplex.eqToIso (intervalEndpoint_eq_face_rev ε).symm

/-- Hence each endpoint subcomplex is terminal. -/
noncomputable def intervalEndpointIsTerminal (ε : Fin 2) :
    IsTerminal (intervalEndpoint ε : SSet.{u}) :=
  IsTerminal.ofIso SSet.stdSimplex.isTerminalObj₀
    (intervalEndpointIsoStdZero ε)

/-- Product of an arbitrary subcomplex with a fixed interval endpoint projects
isomorphically back to that subcomplex. -/
noncomputable def subcomplexProdIntervalEndpointIso
    {X : SSet.{u}}
    (A : X.Subcomplex)
    (ε : Fin 2) :
    (A.prod (intervalEndpoint ε) : SSet.{u}) ≅ (A : SSet.{u}) :=
  SSet.Subcomplex.prodIso A (intervalEndpoint ε) ≪≫
    whiskerLeftIso (A : SSet.{u})
      ((intervalEndpointIsTerminal ε).uniqueUpToIso
        CartesianMonoidalCategory.isTerminalTensorUnit) ≪≫
    ρ_ (A : SSet.{u})

/-- Carrier isomorphism from the opposite horn product to the literal horn. -/
noncomputable def standardTypeAEndpointOppositeCornerCarrierIso
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointOppositeCornerSubcomplex g : SSet.{u}) ≅
      (SSet.horn g.n g.i : SSet.{u}) :=
  subcomplexProdIntervalEndpointIso
    (SSet.horn g.n g.i) g.endpoint.rev

/-- Carrier isomorphism from the opposite simplex product to the literal
standard simplex. -/
noncomputable def standardTypeAEndpointOppositeSimplexCarrierIso
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (standardTypeAEndpointOppositeSimplexSubcomplex g : SSet.{u}) ≅
      (Δ[g.n] : SSet.{u}) :=
  subcomplexProdIntervalEndpointIso
      (⊤ : (Δ[g.n] : SSet.{u}).Subcomplex) g.endpoint.rev ≪≫
    SSet.Subcomplex.topIso (Δ[g.n] : SSet.{u})

@[simp]
theorem standardTypeAEndpointOppositeCornerCarrierIso_hom_app_val
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (d : SimplexCategoryᵒᵖ)
    (z : (standardTypeAEndpointOppositeCornerSubcomplex g : SSet.{u}).obj d) :
    ((standardTypeAEndpointOppositeCornerCarrierIso g).hom.app d z).val =
      z.val.1 := by
  simp [standardTypeAEndpointOppositeCornerCarrierIso,
    subcomplexProdIntervalEndpointIso]

@[simp]
theorem standardTypeAEndpointOppositeSimplexCarrierIso_hom_app
    (g : StandardTypeAHornAttachmentGeneratorIndex)
    (d : SimplexCategoryᵒᵖ)
    (z : (standardTypeAEndpointOppositeSimplexSubcomplex g : SSet.{u}).obj d) :
    (standardTypeAEndpointOppositeSimplexCarrierIso g).hom.app d z =
      z.val.1 := by
  simp [standardTypeAEndpointOppositeSimplexCarrierIso,
    subcomplexProdIntervalEndpointIso]

/-- Generic upgrade of a carrier isomorphism to an isomorphism of scaled
objects by putting the pullback scaling on its source. -/
def pullbackScalingIso
    {X Y : SSet.{u}}
    (e : X ≅ Y)
    (sY : ScaledSimplicialSet Y) :
    ScaledSSet.of X (pullbackScaling sY e.hom) ≅
      ScaledSSet.of Y sY where
  hom :=
    { map := e.hom
      scaled := pullbackScaling_map _ _ }
  inv :=
    { map := e.inv
      scaled := by
        intro t ht
        change sY.thin (e.hom.app (op ⦋2⦌) (e.inv.app (op ⦋2⦌) t))
        rw [← NatTrans.comp_app_apply, e.hom_inv_id]
        exact ht }
  hom_inv_id := by
    apply ScaledSSet.ScaledMap.ext
    exact e.hom_inv_id
  inv_hom_id := by
    apply ScaledSSet.ScaledMap.ext
    exact e.inv_hom_id

/-- Scaling on the opposite horn product transported from the literal standard
A horn scaling. -/
def standardTypeAEndpointOppositeCornerScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScaledSimplicialSet
      (standardTypeAEndpointOppositeCornerSubcomplex g : SSet.{u}) :=
  pullbackScaling (standardTypeAHornScaling g.i)
    (standardTypeAEndpointOppositeCornerCarrierIso g).hom

/-- Scaling on the opposite simplex product transported from the literal
standard A simplex scaling. -/
def standardTypeAEndpointOppositeSimplexScaling
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    ScaledSimplicialSet
      (standardTypeAEndpointOppositeSimplexSubcomplex g : SSet.{u}) :=
  pullbackScaling (standardTypeASimplexScaling g.i)
    (standardTypeAEndpointOppositeSimplexCarrierIso g).hom

/-- Scaled opposite horn-product object. -/
def standardTypeAEndpointOppositeCorner
    (g : StandardTypeAHornAttachmentGeneratorIndex) : ScaledSSet.{u} :=
  ScaledSSet.of
    (standardTypeAEndpointOppositeCornerSubcomplex g : SSet.{u})
    (standardTypeAEndpointOppositeCornerScaling g)

/-- Scaled opposite simplex-product object. -/
def standardTypeAEndpointOppositeSimplex
    (g : StandardTypeAHornAttachmentGeneratorIndex) : ScaledSSet.{u} :=
  ScaledSSet.of
    (standardTypeAEndpointOppositeSimplexSubcomplex g : SSet.{u})
    (standardTypeAEndpointOppositeSimplexScaling g)

/-- These transported objects are literally scaled-isomorphic to the standard
A horn. -/
def standardTypeAEndpointOppositeCornerIso
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointOppositeCorner g ≅
      standardTypeAScaledHorn g.toHornGenerator :=
  pullbackScalingIso
    (standardTypeAEndpointOppositeCornerCarrierIso g)
    (standardTypeAHornScaling g.i)

/-- And likewise to the standard A simplex target. -/
def standardTypeAEndpointOppositeSimplexIso
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointOppositeSimplex g ≅
      standardTypeAScaledSimplex g.toHornGenerator :=
  pullbackScalingIso
    (standardTypeAEndpointOppositeSimplexCarrierIso g)
    (standardTypeASimplexScaling g.i)

/-! ## The flipped carrier pushout lifts to a scaled pushout -/

/-- The opposite horn inclusion, before identifying it with the literal
standard A generator. -/
def standardTypeAEndpointOppositeCellHom
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointOppositeCorner g ⟶
      standardTypeAEndpointOppositeSimplex g where
  map := SSet.Subcomplex.homOfLE
    (standardTypeAEndpointOppositeCarrierBicartSq g).le₁₂
  scaled := by
    intro t ht
    have hA := standardTypeAHornInclusion_scaled g.i
      ((standardTypeAEndpointOppositeCornerCarrierIso g).hom.app
        (op ⦋2⦌) t) ht
    change
      (standardTypeASimplexScaling g.i).thin
        ((standardTypeAEndpointOppositeSimplexCarrierIso g).hom.app
          (op ⦋2⦌)
          ((SSet.Subcomplex.homOfLE
            (standardTypeAEndpointOppositeCarrierBicartSq g).le₁₂).app
              (op ⦋2⦌) t))
    simpa using hA

/-- The product cell and the literal standard type-(A) horn generator are
isomorphic as arrows in `ScaledSSet`. -/
noncomputable def standardTypeAEndpointOppositeCellArrowIso
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    Arrow.mk (standardTypeAEndpointOppositeCellHom g) ≅
      Arrow.mk (standardTypeAScaledHornGeneratorHom g.toHornGenerator) := by
  refine Arrow.isoMk
    (standardTypeAEndpointOppositeCornerIso g)
    (standardTypeAEndpointOppositeSimplexIso g) ?_
  apply ScaledSSet.ScaledMap.ext
  ext d t
  apply Subtype.ext
  rfl

/-- The opposite product cell is therefore in `coproducts E_std` already. -/
theorem standardTypeAEndpointOppositeCellHom_mem_coproductsABC
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    (MorphismProperty.coproducts.{u}
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})))
      (standardTypeAEndpointOppositeCellHom g) := by
  have hA :
      (MorphismProperty.coproducts.{u}
        (standardScaledAnodyneGeneratorsABC :
          MorphismProperty (ScaledSSet.{u})))
        (standardTypeAScaledHornGeneratorHom g.toHornGenerator) :=
    MorphismProperty.le_coproducts
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u})) _
      (standardTypeAGenerator_mem_ABC g.toHornGenerator)
  exact
    ((MorphismProperty.coproducts.{u}
      (standardScaledAnodyneGeneratorsABC :
        MorphismProperty (ScaledSSet.{u}))).arrow_mk_iso_iff
      (standardTypeAEndpointOppositeCellArrowIso g)).2 hA

/-- Corner map into the ambient-pullback-scaled endpoint source. -/
def standardTypeAEndpointOppositeCornerToAmbientSource
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointOppositeCorner g ⟶
      standardTypeAEndpointAmbientSource g where
  map := SSet.Subcomplex.homOfLE
    (standardTypeAEndpointOppositeCarrierBicartSq g).le₁₃
  scaled := by
    intro t ht
    have hA := standardTypeAHornInclusion_scaled g.i
      ((standardTypeAEndpointOppositeCornerCarrierIso g).hom.app
        (op ⦋2⦌) t) ht
    change
      (standardTypeASimplexScaling g.i).thin
        (((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint)).ι.app (op ⦋2⦌)
          ((SSet.Subcomplex.homOfLE
            (standardTypeAEndpointOppositeCarrierBicartSq g).le₁₃).app
              (op ⦋2⦌) t)).1
    simpa using hA

/-- Opposite simplex endpoint copy maps into the boundary prism. -/
def standardTypeAEndpointOppositeSimplexToBoundary
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointOppositeSimplex g ⟶
      standardTypeABoundaryPrism g where
  map := SSet.Subcomplex.homOfLE
    (standardTypeAEndpointOppositeCarrierBicartSq g).le₂₄
  scaled := by
    intro t ht
    change
      (standardTypeASimplexScaling g.i).thin
        ((standardTypeAEndpointOppositeSimplexCarrierIso g).hom.app
          (op ⦋2⦌) t) at ht
    change
      (standardTypeASimplexScaling g.i).thin
        ((standardTypeABoundaryPrismSubcomplex g).ι.app (op ⦋2⦌)
          ((SSet.Subcomplex.homOfLE
            (standardTypeAEndpointOppositeCarrierBicartSq g).le₂₄).app
              (op ⦋2⦌) t)).1
    simpa using ht

/-- Ambient presentation of the endpoint-source inclusion into the boundary
prism. -/
def standardTypeAEndpointAmbientSourceToBoundary
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardTypeAEndpointAmbientSource g ⟶
      standardTypeABoundaryPrism g where
  map := SSet.Subcomplex.homOfLE
    (standardTypeAEndpointOppositeCarrierBicartSq g).le₃₄
  scaled := by
    intro t ht
    change
      (scaledSimplexCylinder
        (standardTypeASimplexScaling g.i)).scaling.thin
        ((standardTypeABoundaryPrismSubcomplex g).ι.app (op ⦋2⦌)
          ((SSet.Subcomplex.homOfLE
            (standardTypeAEndpointOppositeCarrierBicartSq g).le₃₄).app
              (op ⦋2⦌) t))
    change
      (scaledSimplexCylinder
        (standardTypeASimplexScaling g.i)).scaling.thin
        (((SSet.horn g.n g.i).unionProd
          (intervalEndpoint g.endpoint)).ι.app (op ⦋2⦌) t) at ht
    rw [← NatTrans.comp_app_apply,
      SSet.Subcomplex.homOfLE_ι]
    exact ht

/-- The scaling generated on the boundary carrier by the ambient source and
the opposite standard-A simplex is exactly the existing boundary-prism
pullback scaling. -/
theorem standardTypeAEndpointOppositeGeneratedScaling_eq_boundary
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    generatedPushoutScaling
      (standardTypeAEndpointAmbientSourceScaling g)
      (standardTypeAEndpointOppositeSimplexScaling g)
      (standardTypeAEndpointAmbientSourceToBoundary g).map
      (standardTypeAEndpointOppositeSimplexToBoundary g).map =
        standardTypeABoundaryPrismScaling g := by
  apply scaling_eq_of_le_antisymm
  · intro t ht
    rcases ht with hmin | ⟨x, hx, rfl⟩ | ⟨y, hy, rfl⟩
    · exact
        (minimalScaling_map
          (standardTypeABoundaryPrismScaling g) (𝟙 _)) t hmin
    · exact (standardTypeAEndpointAmbientSourceToBoundary g).scaled x hx
    · exact (standardTypeAEndpointOppositeSimplexToBoundary g).scaled y hy
  · intro t ht
    have hmem :
        t.val ∈
          (((SSet.horn g.n g.i).unionProd (intervalEndpoint g.endpoint)) ⊔
            standardTypeAEndpointOppositeSimplexSubcomplex g).obj
              (op ⦋2⦌) := by
      rw [(standardTypeAEndpointOppositeCarrierBicartSq g).sup_eq]
      exact t.property
    change
      t.val ∈
          ((SSet.horn g.n g.i).unionProd (intervalEndpoint g.endpoint)).obj
            (op ⦋2⦌) ∨
        t.val ∈
          (standardTypeAEndpointOppositeSimplexSubcomplex g).obj
            (op ⦋2⦌) at hmem
    rcases hmem with hsource | hopposite
    · let x :
          ((SSet.horn g.n g.i).unionProd
            (intervalEndpoint g.endpoint) : SSet.{u}).obj (op ⦋2⦌) :=
        ⟨t.val, hsource⟩
      have hxmap :
          (standardTypeAEndpointAmbientSourceToBoundary g).map.app
            (op ⦋2⦌) x = t := by
        apply Subtype.ext
        rfl
      refine Or.inr (Or.inl ⟨x, ?_, hxmap⟩)
      change
        (scaledSimplexCylinder
          (standardTypeASimplexScaling g.i)).scaling.thin
          (((SSet.horn g.n g.i).unionProd
            (intervalEndpoint g.endpoint)).ι.app (op ⦋2⦌) x)
      change
        (scaledSimplexCylinder
          (standardTypeASimplexScaling g.i)).scaling.thin
          ((standardTypeABoundaryPrismSubcomplex g).ι.app
            (op ⦋2⦌) t) at ht
      rw [hxmap]
      exact ht
    · let x :
          (standardTypeAEndpointOppositeSimplexSubcomplex g : SSet.{u}).obj
            (op ⦋2⦌) :=
        ⟨t.val, hopposite⟩
      have hxmap :
          (standardTypeAEndpointOppositeSimplexToBoundary g).map.app
            (op ⦋2⦌) x = t := by
        apply Subtype.ext
        rfl
      refine Or.inr (Or.inr ⟨x, ?_, hxmap⟩)
      change
        (standardTypeASimplexScaling g.i).thin
          ((standardTypeAEndpointOppositeSimplexCarrierIso g).hom.app
            (op ⦋2⦌) x)
      change
        (standardTypeASimplexScaling g.i).thin
          (((standardTypeABoundaryPrismSubcomplex g).ι.app
            (op ⦋2⦌) t).1) at ht
      simpa using ht

/-- Genuine scaled pushout for the missing opposite endpoint A-cell. -/
noncomputable def standardTypeAEndpointOpposite_scaled_isPushout
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    IsPushout
      (standardTypeAEndpointOppositeCornerToAmbientSource g)
      (standardTypeAEndpointOppositeCellHom g)
      (standardTypeAEndpointAmbientSourceToBoundary g)
      (standardTypeAEndpointOppositeSimplexToBoundary g) := by
  have h := generatedPushout_isPushout
    (standardTypeAEndpointOppositeCornerToAmbientSource g)
    (standardTypeAEndpointOppositeCellHom g)
    (standardTypeAEndpointAmbientSourceToBoundary g).map
    (standardTypeAEndpointOppositeSimplexToBoundary g).map
    (standardTypeAEndpointOppositeCarrier_isPushout g)
  rw [standardTypeAEndpointOppositeGeneratedScaling_eq_boundary g] at h
  simpa [generatedPushoutInl, generatedPushoutInr, generatedPushoutTarget,
    standardTypeAEndpointAmbientSourceToBoundary,
    standardTypeAEndpointOppositeSimplexToBoundary] using h

/-- The ambient endpoint-source inclusion is one raw standard A cellular step. -/
theorem standardTypeAEndpointAmbientSourceToBoundary_mem_rawCellular
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardABCRawCellularStep
      (standardTypeAEndpointAmbientSourceToBoundary g) := by
  exact MorphismProperty.pushouts_mk
    (standardTypeAEndpointOpposite_scaled_isPushout g)
    (standardTypeAEndpointOppositeCellHom_mem_coproductsABC g)

/-! ## Return to the actual v1.55 source and close the certificate -/

/-- The actual v1.60 endpoint-to-boundary map is arrow-isomorphic to the
ambient presentation just proved raw-cellular. -/
noncomputable def standardTypeAEndpointToBoundaryPrismArrowIsoAmbient
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    Arrow.mk (standardTypeAEndpointToBoundaryPrism g) ≅
      Arrow.mk (standardTypeAEndpointAmbientSourceToBoundary g) := by
  refine Arrow.isoMk
    (standardTypeAEndpointGeneratedSourceIsoAmbient g)
    (Iso.refl _) ?_
  apply ScaledSSet.ScaledMap.ext
  rfl

/-- Therefore the genuine v1.55/v1.60 endpoint-to-boundary map itself is one
raw standard type-(A) cellular step. -/
theorem standardTypeAEndpointToBoundaryPrism_mem_rawCellular
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardABCRawCellularStep
      (standardTypeAEndpointToBoundaryPrism g) := by
  exact
    ((standardABCRawCellularStep : MorphismProperty (ScaledSSet.{u})).arrow_mk_iso_iff
      (standardTypeAEndpointToBoundaryPrismArrowIsoAmbient g)).2
      (standardTypeAEndpointAmbientSourceToBoundary_mem_rawCellular g)

/-- Endpoint-to-boundary already lies in the strong unretracted standard
cellular closure. -/
theorem standardTypeAEndpointToBoundaryPrism_mem_strongCellular
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardABCStrongCellularClosure
      (standardTypeAEndpointToBoundaryPrism g) :=
  MorphismProperty.le_transfiniteCompositions
    (standardABCRawCellularStep : MorphismProperty (ScaledSSet.{u})) _
    (standardTypeAEndpointToBoundaryPrism_mem_rawCellular g)

/-- The complete genuine scaled endpoint Leibniz map is in the strong
unretracted standard A/B cellular closure. -/
theorem standardTypeAEndpointScaledLeibnizPushoutProductHom_mem_strongCellular
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardABCStrongCellularClosure
      (standardTypeAEndpointScaledLeibnizPushoutProductHom g) := by
  have hcomp :=
    (standardABCStrongCellularClosure : MorphismProperty (ScaledSSet.{u})).comp_mem
      (standardTypeAEndpointToBoundaryPrism g)
      (standardTypeABoundaryPrismToCylinder g)
      (standardTypeAEndpointToBoundaryPrism_mem_strongCellular g)
      (standardTypeABoundaryPrismToCylinder_mem_strongCellular g)
  simpa only [standardTypeAEndpointLeibniz_factor_boundaryPrism] using hcomp

/-- Hence every genuine scaled type-(A) endpoint Leibniz generator lies in the
exact v1.59 standard A/B/C cellular closure. -/
theorem standardTypeAEndpointScaledLeibnizPushoutProductHom_mem_cellular
    (g : StandardTypeAHornAttachmentGeneratorIndex) :
    standardABCCellularClosure
      (standardTypeAEndpointScaledLeibnizPushoutProductHom g) :=
  standardABCStrongCellularClosure_le_standardABCCellularClosure _
    (standardTypeAEndpointScaledLeibnizPushoutProductHom_mem_strongCellular g)

/-- Final geometric certificate requested by v1.59. -/
def standardABCTypeAEndpointLeibnizCellularCertificateConstructed :
    StandardABCTypeAEndpointLeibnizCellularCertificate.{u} where
  generators_le_cellular := by
    intro A B f hf
    dsimp [standardTypeAScaledLeibnizPushoutProductGenerators] at hf
    cases hf with
    | mk g =>
        exact
          standardTypeAEndpointScaledLeibnizPushoutProductHom_mem_cellular g

/-- The explicit certificate immediately yields the standard endpoint Leibniz
stability theorem. -/
theorem standardABCTypeAEndpointLeibnizStability_proved :
    StandardABCTypeAEndpointLeibnizStability.{u} :=
  standardABCTypeAEndpointLeibnizCellularCertificateConstructed.toLeibnizStability

/-- And therefore the right-lifting formulation is now unconditional for the
standard A/B/C presentation. -/
theorem standardABCTypeAEndpointLeibnizLifting_proved :
    StandardABCTypeAEndpointLeibnizLifting.{u} :=
  standardABCTypeAEndpointLeibnizCellularCertificateConstructed.lifting

/-!
The standard type-(A) endpoint frontier is now closed:

```text
A_epsilon
  -- one opposite-endpoint raw A pushout --> A_boundary
  -- one raw A/B transfinite composition --> Delta[n] x Delta[1].
```

Consequently every genuine scaled type-(A) endpoint Leibniz generator belongs
to `standardABCCellularClosure`, and the exact v1.59 cellular certificate,
Leibniz stability theorem, and right-lifting theorem are all inhabited.

This conclusion concerns the explicit standard A/B/C presentation only.  The
separate v1.59 residual comparison for the arbitrary-scaling canonical KuuOS
family remains exactly as stated there and is not weakened or identified with
this theorem.
-/

end

end KUOS.DependentOriginationStandardTypeAEndpointOppositeCellCertificateV1_77
