#!/usr/bin/env python3
from __future__ import annotations
from typing import Any, Mapping
from runtime.kuuos_learnos_future_only_learning_common_v0_1 import *
from runtime.kuuos_learnos_future_only_learning_route_v0_1 import route_learning

def build_learnos_dukkha_preserving_future_only_learning_maintenance_disposition_intake(
    *, source_realized_dukkha_verification_receipt: Mapping[str, Any],
    expected_source_realized_dukkha_verification_receipt_digest: str,
    future_only_learning_evidence_packet: Mapping[str, Any],
    expected_future_only_learning_evidence_packet_digest: str,
    future_only_learning_review_certificate: Mapping[str, Any],
    expected_future_only_learning_review_certificate_digest: str,
    future_only_learning_intake_context: Mapping[str, Any],
    expected_future_only_learning_intake_context_digest: str,
    future_only_learning_policy_digest: str,
    future_only_learning_responsibility_digest: str,
    future_only_learning_request_id: str,
    future_only_learning_bundle_digest: str,
) -> LearnOSFutureOnlyLearningMaintenanceDispositionResult:
    source=as_map(source_realized_dukkha_verification_receipt); evidence=as_map(future_only_learning_evidence_packet); review=as_map(future_only_learning_review_certificate); context=as_map(future_only_learning_intake_context); blockers=[]
    source_digest, source_epoch, source_lineage, source_responsibility = verify_source(source, expected_source_realized_dukkha_verification_receipt_digest, blockers)
    evidence_digest=evidence.get(EVIDENCE_DIGEST_FIELD,""); review_digest=review.get(REVIEW_DIGEST_FIELD,""); context_digest=context.get(CONTEXT_DIGEST_FIELD,"")
    if evidence_digest != compute_future_only_learning_evidence_packet_digest(evidence) or evidence_digest != expected_future_only_learning_evidence_packet_digest: blockers.append("future_only_learning_evidence_digest_mismatch")
    if review_digest != compute_future_only_learning_review_certificate_digest(review) or review_digest != expected_future_only_learning_review_certificate_digest: blockers.append("future_only_learning_review_digest_mismatch")
    if context_digest != compute_future_only_learning_intake_context_digest(context) or context_digest != expected_future_only_learning_intake_context_digest: blockers.append("future_only_learning_context_digest_mismatch")
    if context.get("requested_future_only_learning_operation_digest") != compute_requested_future_only_learning_operation_digest(source,evidence,review): blockers.append("requested_future_only_learning_operation_digest_mismatch")
    if context.get("exact_future_only_learning_cycle_digest") != compute_exact_future_only_learning_cycle_digest(source,evidence,review,context): blockers.append("exact_future_only_learning_cycle_digest_mismatch")
    bundle_fields=dict(source_realized_dukkha_verification_receipt_digest=source_digest,expected_source_realized_dukkha_verification_receipt_digest=expected_source_realized_dukkha_verification_receipt_digest,future_only_learning_evidence_packet_digest=evidence_digest,expected_future_only_learning_evidence_packet_digest=expected_future_only_learning_evidence_packet_digest,future_only_learning_review_certificate_digest=review_digest,expected_future_only_learning_review_certificate_digest=expected_future_only_learning_review_certificate_digest,future_only_learning_intake_context_digest=context_digest,expected_future_only_learning_intake_context_digest=expected_future_only_learning_intake_context_digest,requested_future_only_learning_operation_digest=context.get("requested_future_only_learning_operation_digest"),exact_future_only_learning_cycle_digest=context.get("exact_future_only_learning_cycle_digest"),future_only_learning_policy_digest=future_only_learning_policy_digest,future_only_learning_responsibility_digest=future_only_learning_responsibility_digest,future_only_learning_request_id=future_only_learning_request_id)
    if compute_future_only_learning_bundle_digest(**bundle_fields) != future_only_learning_bundle_digest: blockers.append("future_only_learning_bundle_digest_mismatch")
    if blockers: return LearnOSFutureOnlyLearningMaintenanceDispositionResult(STATUS_BLOCKED,sorted(set(blockers)),None)
    routed_context=dict(context); routed_context.update(source_world_binding_digest=source.get("source_world_binding_digest"),source_world_model_state_digest=source.get("source_world_model_state_digest"),source_world_model_revision=source.get("source_world_model_revision"),source_persistent_world_storage_target_digest=source.get("source_persistent_world_storage_target_digest"))
    disposition=route_learning(evidence,review,routed_context,source_epoch); supported=disposition==DISPOSITION_SUPPORTED; state_after=STATE_AFTER_SUPPORTED if supported else STATE_BEFORE
    record={"source":source_digest,"evidence":evidence_digest,"review":review_digest,"fact":evidence["world_candidate_fact_digest"],"relation":evidence["world_candidate_relation_digest"],"revision":evidence["resulting_world_revision"],"target":evidence["learning_target_digest"],"delta":evidence["future_only_learning_delta_digest"],"maintenance":evidence["maintenance_policy_candidate_digest"],"session":context["future_only_learning_intake_session_id"],"nonce":context["future_only_learning_intake_nonce_digest"],"epoch":context["future_only_learning_intake_epoch"],"disposition":disposition,"state_before":STATE_BEFORE,"state_after":state_after}
    record_digest=canonical_digest(record); debt={"source":source_digest,"record":record_digest,"consumed":supported,"double":False}; debt_digest=canonical_digest(debt)
    delta=handoff=None; delta_digest=handoff_digest=""
    if supported:
        delta={"source":source_digest,"record":record_digest,"debt":debt_digest,"binding":source["bounded_realized_dukkha_confirmation_binding_digest"],"target":evidence["learning_target_digest"],"delta":evidence["future_only_learning_delta_digest"],"maintenance":evidence["maintenance_policy_candidate_digest"],"future_only":True,"active_now":False,"world_changed":False,"plan_changed":False,"policy_activated":False}; delta_digest=canonical_digest(delta)
        handoff={"source":source_digest,"delta_binding":delta_digest,"maintenance_window":evidence["maintenance_window_digest"],"durability":evidence["durability_monitoring_specification_digest"],"adverse":evidence["adverse_effect_monitoring_specification_digest"],"distributional":evidence["distributional_monitoring_specification_digest"],"reobservation":evidence["reobservation_trigger_digest"],"retention":evidence["retention_window_digest"],"state":"prepared_not_activated","automatic_action":False}; handoff_digest=canonical_digest(handoff)
    lineage=sorted(set(source_lineage)|{x for x in (source_digest,evidence_digest,review_digest,context_digest,record_digest,debt_digest,delta_digest,handoff_digest,future_only_learning_bundle_digest) if x}); responsibility=sorted(set(source_responsibility)|{review["reviewer_id"],future_only_learning_responsibility_digest})
    receipt={
        "kernel":"LearnOS Dukkha-Preserving Future-Only Learning Maintenance Disposition Intake Kernel","kernel_version":"v0.1","learnos_version":"v0.4","status":"LEARNOS_DUKKHA_PRESERVING_FUTURE_ONLY_LEARNING_MAINTENANCE_DISPOSITION_ROUTED",
        "source_realized_dukkha_verification_receipt_digest":source_digest,"source_realized_dukkha_verification_evidence_packet_digest":source[SOURCE_EVIDENCE_DIGEST_FIELD],"source_realized_dukkha_verification_review_certificate_digest":source[SOURCE_REVIEW_DIGEST_FIELD],"source_realized_dukkha_verification_record_digest":source["realized_dukkha_verification_record_digest"],"source_realized_dukkha_verification_debt_consumption_record_digest":source["realized_dukkha_verification_debt_consumption_record_digest"],"source_bounded_realized_dukkha_confirmation_binding_digest":source["bounded_realized_dukkha_confirmation_binding_digest"],"source_future_learning_handoff_envelope_digest":source["future_learning_handoff_envelope_digest"],
        "future_only_learning_evidence_packet":evidence,EVIDENCE_DIGEST_FIELD:evidence_digest,"future_only_learning_review_certificate":review,REVIEW_DIGEST_FIELD:review_digest,CONTEXT_DIGEST_FIELD:context_digest,
        "future_only_learning_disposition":disposition,"future_only_learning_state_before":STATE_BEFORE,"future_only_learning_state_after":state_after,"future_only_learning_record":record,"future_only_learning_record_digest":record_digest,"future_only_learning_debt_consumption_record":debt,"future_only_learning_debt_consumption_record_digest":debt_digest,"future_only_learning_delta_binding":delta,"future_only_learning_delta_binding_digest":delta_digest,"maintenance_monitoring_handoff_envelope":handoff,"maintenance_monitoring_handoff_envelope_digest":handoff_digest,
        "world_fact_confirmed":True,"causal_attribution_confirmed":True,"dukkha_reduction_realized_confirmed":True,"future_only_learning_supported":supported,"future_only_learning_debt_consumed":supported,"future_only_learning_debt_open":not supported,"future_only_learning_delta_recorded":supported,"future_only_learning_delta_scope_exactly_bounded":supported,"future_only_learning_delta_activated":False,"maintenance_monitoring_handoff_prepared":supported,"maintenance_monitoring_activated":False,
        "persistent_world_state_changed_by_learning":False,"world_model_revision_incremented_by_learning":False,"current_plan_revised_by_learning":False,"current_policy_activated_by_learning":False,"tool_invocation_performed":False,"external_side_effect_performed":False,"selection_authority_granted_to_learnos":False,"plan_revision_authority_granted_to_learnos":False,"dukkha_minimization_authority_granted_to_learnos":False,"general_execution_authority_granted":False,"world_mutation_authority_granted":False,"current_policy_activation_authority_granted":False,"history_read_only":True,"future_only":True,"active_now":False,"resulting_lineage_digests":lineage,"resulting_responsibility_lineage_digests":responsibility,
    }
    receipt[RECEIPT_DIGEST_FIELD]=canonical_digest(receipt)
    return LearnOSFutureOnlyLearningMaintenanceDispositionResult(STATUS_READY,[],receipt)
