#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import asdict, dataclass
from html import escape
import hashlib
import json
from typing import Any, Mapping


@dataclass(frozen=True)
class QiCatalogStaticIndex:
    index_version: str
    index_status: str
    index_artifact_id: str
    source_catalog_id: str | None
    catalog_key: str | None
    navigation_index_key: str | None
    navigation_index_hash: str | None
    html_artifact_name: str
    html_sha256: str
    html_bytes: int
    entry_count: int
    latest_publication_uri: str | None
    static_catalog_index_rendered: bool
    multi_dashboard_index_ready: bool
    js_enabled: bool
    external_network_required: bool
    read_only_surface: bool
    daemon_control_performed: bool
    daemon_restart_performed: bool
    daemon_stop_performed: bool
    daemon_resume_performed: bool
    memory_write_performed: bool
    memory_append_performed: bool
    memory_overwrite_performed: bool
    world_update_performed: bool
    control_packet_mutation_performed: bool
    probe_execution_performed: bool
    auto_remediation_performed: bool
    grants_daemon_control_authority: bool
    grants_probe_execution_authority: bool
    grants_world_update_authority: bool
    grants_memory_overwrite_authority: bool
    index_blockers: list[str]
    index_warnings: list[str]
    html: str
    authority: str = "catalog_static_index"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _render_entry(entry: Mapping[str, Any]) -> str:
    uri = escape(str(entry.get("publication_uri", "")))
    name = escape(str(entry.get("html_artifact_name", "dashboard")))
    receipt = escape(str(entry.get("publication_receipt_id", "")))
    digest = escape(str(entry.get("index_entry_hash", "")))
    return (
        "<li>"
        f"<a href='{uri}'>{name}</a>"
        f"<br><small>receipt=<code>{receipt}</code></small>"
        f"<br><small>index_entry_hash=<code>{digest}</code></small>"
        "</li>"
    )


def render_catalog_static_index_html(catalog: Mapping[str, Any], *, generated_by: str) -> str:
    catalog_id = str(catalog.get("catalog_id", "unknown"))
    catalog_key = str(catalog.get("catalog_key", "unknown"))
    navigation_key = str(catalog.get("navigation_index_key", "unknown"))
    navigation_hash = str(catalog.get("navigation_index_hash", "unknown"))
    entries = [_render_entry(_mapping(item)) for item in _list(catalog.get("entries"))]
    entry_html = "\n".join(entries) if entries else "<li>No published dashboard entries.</li>"
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Qi Published Dashboard Catalog</title>
  <style>
    body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; line-height: 1.5; }}
    header {{ border-bottom: 1px solid #ccc; margin-bottom: 1.5rem; }}
    section {{ border: 1px solid #ddd; border-radius: 0.75rem; padding: 1rem; margin: 1rem 0; }}
    li {{ margin: 0.75rem 0; }}
    code {{ white-space: pre-wrap; word-break: break-word; }}
    footer {{ margin-top: 2rem; color: #666; font-size: 0.9rem; }}
  </style>
</head>
<body>
  <header>
    <h1>Qi Published Dashboard Catalog</h1>
    <p>Read-only multi-dashboard navigation index.</p>
  </header>
  <section>
    <h2>Catalog metadata</h2>
    <p>catalog_id: <code>{escape(catalog_id)}</code></p>
    <p>catalog_key: <code>{escape(catalog_key)}</code></p>
    <p>navigation_index_key: <code>{escape(navigation_key)}</code></p>
    <p>navigation_index_hash: <code>{escape(navigation_hash)}</code></p>
  </section>
  <section>
    <h2>Published dashboards</h2>
    <ol>{entry_html}</ol>
  </section>
  <footer>Generated by {escape(generated_by)}. No JavaScript. No external network dependency.</footer>
</body>
</html>
"""


def build_qi_catalog_static_index(*, published_catalog: Mapping[str, Any], render_context: Mapping[str, Any] | None = None) -> QiCatalogStaticIndex:
    catalog = _mapping(published_catalog)
    ctx = _mapping(render_context)
    blockers: list[str] = []
    warnings: list[str] = []

    if ctx.get("catalog_static_index_enabled") is not True:
        blockers.append("catalog_static_index_enabled_not_true")
    if ctx.get("read_only_surface_required") is not True:
        blockers.append("read_only_surface_required_not_true")
    if catalog.get("catalog_status") != "QI_PUBLISHED_DASHBOARD_CATALOG_READY":
        blockers.append("published_catalog_not_ready")
    if catalog.get("published_dashboard_catalog_rendered") is not True:
        blockers.append("published_dashboard_catalog_not_rendered")
    if catalog.get("operator_navigation_index_rendered") is not True:
        blockers.append("operator_navigation_index_not_rendered")

    entries = _list(catalog.get("entries"))
    if not entries:
        blockers.append("catalog_entries_missing")
    for key in ("catalog_id", "catalog_key", "navigation_index_key", "navigation_index_hash"):
        if not catalog.get(key):
            blockers.append(f"{key}_missing")

    forbidden_flags = [
        "daemon_control_performed", "daemon_restart_performed", "daemon_stop_performed", "daemon_resume_performed",
        "memory_write_performed", "memory_append_performed", "memory_overwrite_performed", "world_update_performed",
        "control_packet_mutation_performed", "probe_execution_performed", "auto_remediation_performed",
        "grants_daemon_control_authority", "grants_probe_execution_authority", "grants_world_update_authority", "grants_memory_overwrite_authority",
    ]
    for flag in forbidden_flags:
        if catalog.get(flag) is True or ctx.get(flag) is True:
            blockers.append(f"forbidden_flag_true:{flag}")

    html = render_catalog_static_index_html(catalog, generated_by=str(ctx.get("generated_by", "kuuos_catalog_static_index_v0_1")))
    html_sha = _sha256(html)
    artifact_name = str(ctx.get("html_artifact_name") or f"qi-catalog-index-{html_sha[:12]}.html")
    index_artifact_id = "qi-catalog-index-" + _sha256(json.dumps({"catalog_id": catalog.get("catalog_id"), "html_sha256": html_sha, "artifact_name": artifact_name}, sort_keys=True))[:16]
    ready = not blockers
    if "<script" in html.lower():
        blockers.append("script_tag_present")
        ready = False
    if ready and len(entries) == 1:
        warnings.append("single_entry_static_index")

    return QiCatalogStaticIndex(
        index_version="kuuos_runtime_daemon_qi_catalog_static_index_v0_1",
        index_status="QI_CATALOG_STATIC_INDEX_READY" if ready else "QI_CATALOG_STATIC_INDEX_BLOCKED",
        index_artifact_id=index_artifact_id,
        source_catalog_id=str(catalog.get("catalog_id")) if catalog.get("catalog_id") else None,
        catalog_key=str(catalog.get("catalog_key")) if catalog.get("catalog_key") else None,
        navigation_index_key=str(catalog.get("navigation_index_key")) if catalog.get("navigation_index_key") else None,
        navigation_index_hash=str(catalog.get("navigation_index_hash")) if catalog.get("navigation_index_hash") else None,
        html_artifact_name=artifact_name,
        html_sha256=html_sha,
        html_bytes=len(html.encode("utf-8")),
        entry_count=len(entries),
        latest_publication_uri=str(catalog.get("latest_publication_uri")) if catalog.get("latest_publication_uri") else None,
        static_catalog_index_rendered=True,
        multi_dashboard_index_ready=ready,
        js_enabled=False,
        external_network_required=False,
        read_only_surface=ctx.get("read_only_surface_required") is True,
        daemon_control_performed=False,
        daemon_restart_performed=False,
        daemon_stop_performed=False,
        daemon_resume_performed=False,
        memory_write_performed=False,
        memory_append_performed=False,
        memory_overwrite_performed=False,
        world_update_performed=False,
        control_packet_mutation_performed=False,
        probe_execution_performed=False,
        auto_remediation_performed=False,
        grants_daemon_control_authority=False,
        grants_probe_execution_authority=False,
        grants_world_update_authority=False,
        grants_memory_overwrite_authority=False,
        index_blockers=blockers,
        index_warnings=warnings,
        html=html,
    )
