#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import asdict, dataclass
from html import escape
import hashlib
import json
from typing import Any, Mapping


@dataclass(frozen=True)
class QiStaticDashboardSurface:
    surface_version: str
    surface_status: str
    surface_id: str
    source_dashboard_packet_id: str | None
    dashboard_title: str
    replay_index_key: str | None
    replay_index_hash: str | None
    html_artifact_name: str
    html_sha256: str
    html_bytes: int
    static_html_rendered: bool
    dashboard_artifact_ready: bool
    js_enabled: bool
    external_network_required: bool
    read_only_surface: bool
    daemon_control_performed: bool
    daemon_restart_performed: bool
    daemon_stop_performed: bool
    daemon_resume_performed: bool
    memory_write_performed: bool
    memory_append_performed: bool
    memory_overwrite_performed: bool
    world_update_performed: bool
    control_packet_mutation_performed: bool
    probe_execution_performed: bool
    auto_remediation_performed: bool
    grants_daemon_control_authority: bool
    grants_probe_execution_authority: bool
    grants_world_update_authority: bool
    grants_memory_overwrite_authority: bool
    surface_blockers: list[str]
    surface_warnings: list[str]
    html: str
    authority: str = "static_dashboard_surface"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _render_card(card: Mapping[str, Any]) -> str:
    title = escape(str(card.get("card", "card")))
    rows = []
    for key, value in card.items():
        rows.append(f"<tr><th>{escape(str(key))}</th><td><code>{escape(str(value))}</code></td></tr>")
    return f"<section class='card'><h2>{title}</h2><table>{''.join(rows)}</table></section>"


def render_static_dashboard_html(dashboard_packet: Mapping[str, Any], *, generated_by: str) -> str:
    title = str(dashboard_packet.get("dashboard_title", "Qi Operator Dashboard"))
    packet_id = str(dashboard_packet.get("dashboard_packet_id", "unknown"))
    replay_key = str(dashboard_packet.get("replay_index_key", "unknown"))
    replay_hash = str(dashboard_packet.get("replay_index_hash", "unknown"))
    cards = "\n".join(_render_card(_mapping(card)) for card in _list(dashboard_packet.get("dashboard_cards")))
    if not cards:
        cards = "<section class='card'><h2>No cards</h2><p>No dashboard cards provided.</p></section>"
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; line-height: 1.5; }}
    header {{ border-bottom: 1px solid #ccc; margin-bottom: 1.5rem; }}
    .meta, .card {{ border: 1px solid #ddd; border-radius: 0.75rem; padding: 1rem; margin: 1rem 0; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th {{ text-align: left; width: 30%; background: #f7f7f7; }}
    th, td {{ border-top: 1px solid #eee; padding: 0.5rem; vertical-align: top; }}
    code {{ white-space: pre-wrap; word-break: break-word; }}
    footer {{ margin-top: 2rem; color: #666; font-size: 0.9rem; }}
  </style>
</head>
<body>
  <header>
    <h1>{escape(title)}</h1>
    <p>Read-only static dashboard surface.</p>
  </header>
  <section class="meta">
    <h2>Replay index</h2>
    <table>
      <tr><th>dashboard_packet_id</th><td><code>{escape(packet_id)}</code></td></tr>
      <tr><th>replay_index_key</th><td><code>{escape(replay_key)}</code></td></tr>
      <tr><th>replay_index_hash</th><td><code>{escape(replay_hash)}</code></td></tr>
    </table>
  </section>
  {cards}
  <footer>
    Generated by {escape(generated_by)}. No JavaScript. No external network dependency.
  </footer>
</body>
</html>
"""


def build_qi_static_dashboard_surface(
    *,
    dashboard_packet: Mapping[str, Any],
    render_context: Mapping[str, Any] | None = None,
) -> QiStaticDashboardSurface:
    packet = _mapping(dashboard_packet)
    ctx = _mapping(render_context)
    blockers: list[str] = []
    warnings: list[str] = []

    if ctx.get("static_dashboard_surface_enabled") is not True:
        blockers.append("static_dashboard_surface_enabled_not_true")
    if ctx.get("read_only_surface_required") is not True:
        blockers.append("read_only_surface_required_not_true")
    if packet.get("index_status") != "QI_OPERATOR_DASHBOARD_REPLAY_INDEX_READY":
        blockers.append("dashboard_packet_not_ready")
    if packet.get("operator_dashboard_ready") is not True:
        blockers.append("operator_dashboard_not_ready")
    if packet.get("read_only_surface") is not True:
        blockers.append("source_not_read_only")

    required = ["dashboard_packet_id", "replay_index_key", "replay_index_hash", "dashboard_cards"]
    for key in required:
        if packet.get(key) in (None, "", []):
            blockers.append(f"{key}_missing")

    forbidden_flags = [
        "daemon_control_performed",
        "daemon_restart_performed",
        "daemon_stop_performed",
        "daemon_resume_performed",
        "memory_write_performed",
        "memory_append_performed",
        "memory_overwrite_performed",
        "world_update_performed",
        "control_packet_mutation_performed",
        "probe_execution_performed",
        "auto_remediation_performed",
        "grants_daemon_control_authority",
        "grants_probe_execution_authority",
        "grants_world_update_authority",
        "grants_memory_overwrite_authority",
    ]
    for flag in forbidden_flags:
        if packet.get(flag) is True or ctx.get(flag) is True:
            blockers.append(f"forbidden_flag_true:{flag}")

    generated_by = str(ctx.get("generated_by", "kuuos_static_dashboard_surface_v0_1"))
    html = render_static_dashboard_html(packet, generated_by=generated_by)
    html_sha = _sha256(html)
    artifact_name = str(ctx.get("html_artifact_name") or f"qi-dashboard-{html_sha[:12]}.html")
    surface_material = {
        "dashboard_packet_id": packet.get("dashboard_packet_id"),
        "replay_index_hash": packet.get("replay_index_hash"),
        "html_sha256": html_sha,
        "artifact_name": artifact_name,
    }
    surface_id = "qi-static-dashboard-" + _sha256(json.dumps(surface_material, sort_keys=True))[:16]
    ready = not blockers
    if ready and "<script" in html.lower():
        blockers.append("script_tag_present")
        ready = False

    return QiStaticDashboardSurface(
        surface_version="kuuos_runtime_daemon_qi_static_dashboard_surface_v0_1",
        surface_status="QI_STATIC_DASHBOARD_SURFACE_READY" if ready else "QI_STATIC_DASHBOARD_SURFACE_BLOCKED",
        surface_id=surface_id,
        source_dashboard_packet_id=str(packet.get("dashboard_packet_id")) if packet.get("dashboard_packet_id") else None,
        dashboard_title=str(packet.get("dashboard_title", "Qi Operator Dashboard")),
        replay_index_key=str(packet.get("replay_index_key")) if packet.get("replay_index_key") else None,
        replay_index_hash=str(packet.get("replay_index_hash")) if packet.get("replay_index_hash") else None,
        html_artifact_name=artifact_name,
        html_sha256=html_sha,
        html_bytes=len(html.encode("utf-8")),
        static_html_rendered=True,
        dashboard_artifact_ready=ready,
        js_enabled=False,
        external_network_required=False,
        read_only_surface=ctx.get("read_only_surface_required") is True,
        daemon_control_performed=False,
        daemon_restart_performed=False,
        daemon_stop_performed=False,
        daemon_resume_performed=False,
        memory_write_performed=False,
        memory_append_performed=False,
        memory_overwrite_performed=False,
        world_update_performed=False,
        control_packet_mutation_performed=False,
        probe_execution_performed=False,
        auto_remediation_performed=False,
        grants_daemon_control_authority=False,
        grants_probe_execution_authority=False,
        grants_world_update_authority=False,
        grants_memory_overwrite_authority=False,
        surface_blockers=blockers,
        surface_warnings=warnings,
        html=html,
    )
