#!/usr/bin/env python3
from __future__ import annotations
from typing import Any
from runtime.kuuos_codeai_candidate_static_admissibility_preflight_schema_v0_1 import *
from runtime.kuuos_codeai_candidate_static_admissibility_preflight_checks_v0_1 import collision_findings,apply_operations,static_findings,test_findings,disposition

def _report(ir,rr,req,pol,inv,cat,source,result,fs):
 paths=sorted(p for p in set(source)|set(result) if source.get(p)!=result.get(p)); d=disposition(fs); counts={s:sum(x['severity']==s for x in fs) for s in (SEVERITY_REPAIRABLE,SEVERITY_HOLD,SEVERITY_REJECT)}
 v={'schema_version':SCHEMA_VERSION,'profile_version':PROFILE_VERSION,'typed_edit_ir_digest':ir[IR_DIGEST_FIELD],'typed_edit_ir_receipt_digest':rr[TYPED_IR_RECEIPT_DIGEST_FIELD],'preflight_request_digest':req[REQUEST_DIGEST_FIELD],'preflight_policy_digest':pol[POLICY_DIGEST_FIELD],'dependency_inventory_digest':inv[DEPENDENCY_INVENTORY_DIGEST_FIELD],'test_plan_catalog_digest':cat[TEST_PLAN_CATALOG_DIGEST_FIELD],'repository_full_name':ir['repository_full_name'],'source_commit_sha':ir['source_commit_sha'],'source_repository_snapshot_digest':ir['repository_snapshot_digest'],'result_repository_snapshot_digest':canonical_digest(result),'source_path_count':len(source),'result_path_count':len(result),'source_snapshot_bytes':snapshot_size(source),'result_snapshot_bytes':snapshot_size(result),'operation_count':ir['operation_count'],'changed_path_count':len(paths),'changed_paths':paths,'findings':fs,'finding_counts':counts,'codeai_disposition':d,'operating_mode':MODE_PREFLIGHT_ONLY,'static_admissibility_preflight_completed':True,'typed_ir_lineage_verified':True,'operation_collision_check_completed':True,'in_memory_materialization_completed':True,'materialized_parse_checks_completed':True,'dependency_correspondence_checked':True,'test_plan_correspondence_checked':True,'admissible':d==DISPOSITION_ADMISSIBLE,'repair_required':d==DISPOSITION_REPAIRABLE,'held':d==DISPOSITION_HOLD,'rejected':d==DISPOSITION_REJECTED,'repository_snapshot_read_only':True,'result_snapshot_ephemeral':True,'provider_invoked':False,'verification_runner_invoked':False,'repository_mutation_performed':False,'git_effect_performed':False,'network_access_performed':False,'secret_access_performed':False,'candidate_selected':False,'candidate_selection_authority_granted':False,'execution_authority_granted':False,'merge_authority_granted':False,'deployment_authority_granted':False,'static_preflight_treated_as_correctness_proof':False,'parse_success_treated_as_type_correctness':False,'dependency_correspondence_treated_as_runtime_success':False,'test_plan_correspondence_treated_as_test_success':False,'history_read_only':True,'future_only':True,'active_now':False}
 return seal(v,REPORT_DIGEST_FIELD)
def _receipt(r):
 keys=('typed_edit_ir_digest','typed_edit_ir_receipt_digest','preflight_request_digest','preflight_policy_digest','dependency_inventory_digest','test_plan_catalog_digest','repository_full_name','source_commit_sha','source_repository_snapshot_digest','result_repository_snapshot_digest','operation_count','changed_paths','finding_counts','codeai_disposition','admissible','repair_required','held','rejected'); v={k:r[k] for k in keys}; v.update({'schema_version':SCHEMA_VERSION,'profile_version':PROFILE_VERSION,'static_admissibility_report_digest':r[REPORT_DIGEST_FIELD],'operating_mode':MODE_PREFLIGHT_ONLY,'route_receipt_recorded':True,'static_admissibility_report_emitted':True,'repository_snapshot_read_only':True,'result_snapshot_ephemeral':True,'provider_invoked':False,'verification_runner_invoked':False,'repository_mutation_performed':False,'git_effect_performed':False,'network_access_performed':False,'secret_access_performed':False,'candidate_selected':False,'candidate_selection_authority_granted':False,'execution_authority_granted':False,'merge_authority_granted':False,'deployment_authority_granted':False,'static_preflight_treated_as_correctness_proof':False,'history_read_only':True,'future_only':True,'active_now':False}); return seal(v,RECEIPT_DIGEST_FIELD)
def build_codeai_candidate_static_admissibility_preflight(*,typed_edit_ir:Any,typed_edit_ir_receipt:Any,repository_files:Any,preflight_request:Any,preflight_policy:Any,dependency_inventory:Any,test_plan_catalog:Any):
 vals=[mapping(x) for x in (typed_edit_ir,typed_edit_ir_receipt,repository_files,preflight_request,preflight_policy,dependency_inventory,test_plan_catalog)]
 if any(x is None for x in vals):return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,('input_not_mapping',),None,None)
 ir,rr,repo,req,pol,inv,cat=vals; issues=validate_inputs(ir,rr,repo,req,pol,inv,cat)
 if issues:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,tuple(issues),None,None)
 if any(pol[x] for x in ('allow_repository_mutation','allow_provider_invocation','allow_verification_runner_invocation','allow_candidate_selection_authority','allow_execution_authority')):return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,('preflight_policy_effect_or_authority_enabled',),None,None)
 if req['claims_authority'] or req['unresolved_preflight_questions']:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,('preflight_request_claims_authority' if req['claims_authority'] else 'preflight_unresolved_questions_present',),None,None)
 rd=canonical_digest(repo); corr=((req['expected_typed_edit_ir_digest'],ir[IR_DIGEST_FIELD],'typed_ir_digest_mismatch'),(req['expected_typed_edit_ir_receipt_digest'],rr[TYPED_IR_RECEIPT_DIGEST_FIELD],'typed_ir_receipt_digest_mismatch'),(rr['typed_edit_ir_digest'],ir[IR_DIGEST_FIELD],'typed_ir_receipt_ir_digest_mismatch'),(req['expected_repository_snapshot_digest'],rd,'repository_snapshot_digest_mismatch'),(ir['repository_snapshot_digest'],rd,'typed_ir_repository_snapshot_digest_mismatch'),(rr['repository_snapshot_digest'],rd,'typed_ir_receipt_repository_snapshot_digest_mismatch'),(inv['repository_snapshot_digest'],rd,'dependency_inventory_repository_snapshot_digest_mismatch'),(cat['repository_snapshot_digest'],rd,'test_plan_catalog_repository_snapshot_digest_mismatch'),(req['dependency_inventory_digest'],inv[DEPENDENCY_INVENTORY_DIGEST_FIELD],'dependency_inventory_digest_mismatch'),(req['test_plan_catalog_digest'],cat[TEST_PLAN_CATALOG_DIGEST_FIELD],'test_plan_catalog_digest_mismatch'),(pol['expected_repository_full_name'],ir['repository_full_name'],'repository_full_name_mismatch'),(req['source_commit_sha'],ir['source_commit_sha'],'source_commit_sha_mismatch'),(pol['expected_source_commit_sha'],ir['source_commit_sha'],'policy_source_commit_sha_mismatch'),(rr['repository_full_name'],ir['repository_full_name'],'typed_ir_receipt_repository_mismatch'),(rr['source_commit_sha'],ir['source_commit_sha'],'typed_ir_receipt_source_commit_mismatch'))
 bad=tuple(c for a,b,c in corr if a!=b)
 if bad:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,bad,None,None)
 if not pol['evaluation_epoch']-pol['maximum_request_age']<=req['request_created_epoch']<=pol['evaluation_epoch']:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,('preflight_request_window_invalid',),None,None)
 if ir['operation_count']>pol['maximum_operations'] or snapshot_size(repo)>pol['maximum_source_snapshot_bytes']:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,('preflight_operation_budget_exceeded' if ir['operation_count']>pol['maximum_operations'] else 'preflight_source_snapshot_budget_exceeded',),None,None)
 paths=sorted({o['path'] for o in ir['operations']})
 if len(paths)>pol['maximum_changed_paths']:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,('preflight_changed_path_budget_exceeded',),None,None)
 pbad=tuple(sorted({('preflight_target_path_not_allowed:'+p) for p in paths if not path_allowed(p,pol)}|{('preflight_operation_language_not_allowed:'+o['operation_id']) for o in ir['operations'] if o['language'] not in pol['allowed_languages']}))
 if pbad:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,pbad,None,None)
 rb=[]
 if rr['operation_count']!=ir['operation_count']:rb.append('typed_ir_receipt_operation_count_mismatch')
 if rr['operation_ids']!=[o['operation_id'] for o in ir['operations']]:rb.append('typed_ir_receipt_operation_ids_mismatch')
 if rr['target_paths']!=paths:rb.append('typed_ir_receipt_target_paths_mismatch')
 if pol['require_exact_ir_lineage'] and rb:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,tuple(rb),None,None)
 fs=collision_findings(ir['operations']); result,more=apply_operations(repo,ir['operations']); fs+=more
 if snapshot_size(result)>pol['maximum_result_snapshot_bytes']:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,('preflight_result_snapshot_budget_exceeded',),None,None)
 fs+=static_findings(repo,result,ir['operations'],pol,inv); changed=sorted(p for p in set(repo)|set(result) if repo.get(p)!=result.get(p)); fs+=test_findings(changed,ir,req,cat,pol['require_test_plan_correspondence']); fs=sorted(fs,key=lambda x:(x['severity'],x['code'],x['path'],x['operation_id'],x['detail']))
 if len(fs)>pol['maximum_findings']:return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_BLOCKED,('preflight_finding_budget_exceeded',),None,None)
 report=_report(ir,rr,req,pol,inv,cat,repo,result,fs); return CodeAICandidateStaticAdmissibilityPreflightResult(STATUS_READY,(),report,_receipt(report))
__all__=[n for n in globals() if n.isupper()]+['CodeAICandidateStaticAdmissibilityPreflightResult','build_codeai_candidate_static_admissibility_preflight','canonical_digest','canonical_json','digest_without','seal']
