#!/usr/bin/env python3
from __future__ import annotations

from typing import Any, Mapping

from runtime.kuuos_event_adapter_federation_types_v0_5 import batch_digest
from runtime.kuuos_policy_regret_cadence_types_v0_10 import (
    LICENSE_VERSION as REGRET_LICENSE_VERSION,
    PLAN_VERSION as REGRET_PLAN_VERSION,
    REQUIRED_BOUNDARY as REGRET_REQUIRED_BOUNDARY,
    plan_digest as regret_plan_digest,
)
from runtime.kuuos_delayed_credit_multihorizon_types_v0_11 import (
    clamp,
    integer,
    mapping,
    nonnegative,
    signed,
)


def build_child_regret_plan(
    *,
    horizon_plan: Mapping[str, Any],
    horizon_decision: Mapping[str, Any],
    source_packets: list[Mapping[str, Any]],
    root_packet: Mapping[str, Any],
    adapter_registry: Mapping[str, Any],
    previous_capability_state: Mapping[str, Any],
    previous_capability_bundle: Mapping[str, Any],
    source_portfolio_bundle: Mapping[str, Any],
    previous_experiment_state: Mapping[str, Any],
    previous_experiment_bundle: Mapping[str, Any],
    previous_policy_state: Mapping[str, Any],
    previous_policy_bundle: Mapping[str, Any],
    previous_regret_state: Mapping[str, Any],
    previous_regret_bundle: Mapping[str, Any],
) -> dict[str, Any]:
    packet = {
        "version": REGRET_PLAN_VERSION,
        "regret_run_id": str(horizon_plan.get("horizon_run_id", "")) + ":regret",
        "agent_id": str(horizon_plan.get("agent_id", "")),
        "expected_source_batch_digest": batch_digest(source_packets),
        "expected_root_principles_digest": root_packet.get("root_principles_digest", ""),
        "expected_adapter_registry_digest": adapter_registry.get("adapter_registry_digest", ""),
        "expected_previous_capability_state_digest": previous_capability_state.get("capability_state_digest", ""),
        "expected_previous_capability_bundle_digest": previous_capability_bundle.get("capability_bundle_digest", ""),
        "expected_source_portfolio_bundle_digest": source_portfolio_bundle.get("portfolio_bundle_digest", ""),
        "expected_previous_experiment_state_digest": previous_experiment_state.get("experiment_state_digest", ""),
        "expected_previous_experiment_bundle_digest": previous_experiment_bundle.get("experiment_bundle_digest", ""),
        "expected_previous_policy_state_digest": previous_policy_state.get("policy_state_digest", ""),
        "expected_previous_policy_bundle_digest": previous_policy_bundle.get("policy_bundle_digest", ""),
        "expected_previous_regret_state_digest": previous_regret_state.get("regret_state_digest", ""),
        "expected_previous_regret_bundle_digest": previous_regret_bundle.get("regret_bundle_digest", ""),
        "learning_rate": clamp(horizon_plan.get("learning_rate")),
        "exploration_weight": clamp(horizon_plan.get("exploration_weight")),
        "max_exploration_bonus": clamp(horizon_plan.get("max_exploration_bonus")),
        "curvature_penalty": clamp(horizon_plan.get("curvature_penalty")),
        "resolved_evidence_weight": clamp(horizon_plan.get("resolved_evidence_weight")),
        "max_portfolio_adjustment": clamp(horizon_plan.get("max_portfolio_adjustment")),
        "shadow_model_weight": clamp(horizon_plan.get("shadow_model_weight")),
        "shadow_learning_rate": clamp(horizon_plan.get("shadow_learning_rate")),
        "reliability_prior_mass": nonnegative(horizon_plan.get("reliability_prior_mass"), 2.0),
        "default_prediction_confidence": clamp(horizon_plan.get("default_prediction_confidence")),
        "shadow_action_utility": dict(mapping(horizon_plan.get("shadow_action_utility"))),
        "uncertainty_weight": clamp(horizon_plan.get("uncertainty_weight")),
        "unresolved_shadow_weight": clamp(horizon_plan.get("unresolved_shadow_weight")),
        "trial_novelty_weight": clamp(horizon_plan.get("trial_novelty_weight")),
        "opportunity_cost_weight": clamp(horizon_plan.get("opportunity_cost_weight")),
        "base_minimum_information_gain": clamp(horizon_plan.get("base_minimum_information_gain")),
        "hard_minimum_information_gain": clamp(horizon_plan.get("hard_minimum_information_gain")),
        "information_gain_threshold_adaptation_rate": clamp(horizon_plan.get("information_gain_threshold_adaptation_rate")),
        "maximum_trial_risk": clamp(horizon_plan.get("maximum_trial_risk")),
        "minimum_trial_recoverability": clamp(horizon_plan.get("minimum_trial_recoverability")),
        "total_trial_budget": nonnegative(horizon_plan.get("total_trial_budget")),
        "maximum_trial_cost": nonnegative(horizon_plan.get("maximum_trial_cost")),
        "default_trial_cost": nonnegative(horizon_plan.get("default_trial_cost")),
        "default_trial_risk": clamp(horizon_plan.get("default_trial_risk")),
        "default_trial_recoverability": clamp(horizon_plan.get("default_trial_recoverability"), 1.0),
        "max_live_trials_total": integer(horizon_plan.get("max_live_trials_total"), 0),
        "max_live_trials_per_adapter_context": integer(horizon_plan.get("max_live_trials_per_adapter_context"), 0),
        "base_trial_cooldown_cycles": integer(horizon_plan.get("base_trial_cooldown_cycles"), 0),
        "hard_minimum_trial_cooldown_cycles": integer(horizon_plan.get("hard_minimum_trial_cooldown_cycles"), 0),
        "maximum_cooldown_reduction_cycles": integer(horizon_plan.get("maximum_cooldown_reduction_cycles"), 0),
        "policy_information_gain_weight": clamp(horizon_plan.get("policy_information_gain_weight")),
        "policy_posterior_weight": clamp(horizon_plan.get("policy_posterior_weight")),
        "policy_net_value_weight": clamp(horizon_plan.get("policy_net_value_weight")),
        "policy_pending_weight": clamp(horizon_plan.get("policy_pending_weight")),
        "policy_recoverability_weight": clamp(horizon_plan.get("policy_recoverability_weight")),
        "policy_cost_penalty_weight": clamp(horizon_plan.get("policy_cost_penalty_weight")),
        "policy_risk_penalty_weight": clamp(horizon_plan.get("policy_risk_penalty_weight")),
        "prior_experiment_value": clamp(horizon_plan.get("prior_experiment_value")),
        "posterior_confidence_mass": nonnegative(horizon_plan.get("posterior_confidence_mass"), 6.0),
        "base_experiment_pressure_threshold": clamp(horizon_decision.get("adapted_base_experiment_threshold")),
        "minimum_experiment_pressure_threshold": clamp(horizon_plan.get("minimum_experiment_pressure_threshold")),
        "maximum_experiment_pressure_threshold": clamp(horizon_plan.get("maximum_experiment_pressure_threshold"), 1.0),
        "base_policy_cycles_between_experiments": integer(horizon_decision.get("adapted_base_experiment_interval"), 0),
        "minimum_policy_cycles_between_experiments": integer(horizon_plan.get("minimum_policy_cycles_between_experiments"), 0),
        "maximum_policy_cycles_between_experiments": integer(horizon_plan.get("maximum_policy_cycles_between_experiments"), 100000),
        "reobserve_pending_weight": clamp(horizon_plan.get("reobserve_pending_weight")),
        "reobserve_resolution_debt_weight": clamp(horizon_plan.get("reobserve_resolution_debt_weight")),
        "reobserve_low_confidence_weight": clamp(horizon_plan.get("reobserve_low_confidence_weight")),
        "post_experiment_reobserve_bonus": clamp(horizon_plan.get("post_experiment_reobserve_bonus")),
        "base_reobserve_pressure_threshold": clamp(horizon_decision.get("adapted_base_reobserve_threshold")),
        "minimum_reobserve_pressure_threshold": clamp(horizon_plan.get("minimum_reobserve_pressure_threshold")),
        "maximum_reobserve_pressure_threshold": clamp(horizon_plan.get("maximum_reobserve_pressure_threshold"), 1.0),
        "base_policy_cycles_between_reobservations": integer(horizon_decision.get("adapted_base_reobserve_interval"), 0),
        "minimum_policy_cycles_between_reobservations": integer(horizon_plan.get("minimum_policy_cycles_between_reobservations"), 0),
        "maximum_policy_cycles_between_reobservations": integer(horizon_plan.get("maximum_policy_cycles_between_reobservations"), 100000),
        "outcome_cost_weight": clamp(horizon_plan.get("outcome_cost_weight")),
        "outcome_risk_weight": clamp(horizon_plan.get("outcome_risk_weight")),
        "outcome_recoverability_weight": clamp(horizon_plan.get("outcome_recoverability_weight")),
        "experiment_success_net_value_floor": signed(horizon_plan.get("experiment_success_net_value_floor"), 0.0),
        "regret_threshold_gain": clamp(horizon_plan.get("regret_threshold_gain")),
        "exploit_resistance_gain": clamp(horizon_plan.get("exploit_resistance_gain")),
        "regret_interval_gain_cycles": integer(horizon_plan.get("regret_interval_gain_cycles"), 0),
        "exploit_interval_gain_cycles": integer(horizon_plan.get("exploit_interval_gain_cycles"), 0),
        "minimum_counterfactual_confidence": clamp(horizon_plan.get("minimum_counterfactual_confidence")),
        "regret_tolerance": clamp(horizon_plan.get("regret_tolerance")),
        "maximum_regret_per_cycle": clamp(horizon_plan.get("maximum_regret_per_cycle"), 1.0),
        "regret_credit_decay": clamp(horizon_plan.get("regret_credit_decay"), 1.0),
        "regret_credit_learning_rate": clamp(horizon_plan.get("regret_credit_learning_rate")),
        "chosen_mode_credit_penalty": clamp(horizon_plan.get("chosen_mode_credit_penalty")),
        "counterfactual_credibility_mass": nonnegative(horizon_plan.get("counterfactual_credibility_mass"), 2.0),
        "prior_mode_confidence": clamp(horizon_plan.get("prior_mode_confidence")),
        "pending_shadow_discount": clamp(horizon_plan.get("pending_shadow_discount")),
        "delayed_compatible_weight": clamp(horizon_plan.get("delayed_compatible_weight"), 1.0),
        "prior_experiment_counterfactual_value": clamp(horizon_plan.get("prior_experiment_counterfactual_value")),
        "prior_reobserve_counterfactual_value": clamp(horizon_plan.get("prior_reobserve_counterfactual_value")),
        "prior_exploit_counterfactual_value": clamp(horizon_plan.get("prior_exploit_counterfactual_value")),
        "max_shadow_candidates": integer(horizon_plan.get("max_shadow_candidates"), 8),
        "max_pending_predictions": integer(horizon_plan.get("max_pending_predictions"), 256),
        "max_resolved_predictions": integer(horizon_plan.get("max_resolved_predictions"), 256),
        "max_portfolio_holonomy": integer(horizon_plan.get("max_portfolio_holonomy"), 256),
        "max_trial_records": integer(horizon_plan.get("max_trial_records"), 256),
        "max_decision_holonomy": integer(horizon_plan.get("max_decision_holonomy"), 256),
        "max_policy_outcomes": integer(horizon_plan.get("max_policy_outcomes"), 256),
        "max_policy_holonomy": integer(horizon_plan.get("max_policy_holonomy"), 256),
        "max_regret_outcomes": integer(horizon_plan.get("max_regret_outcomes"), 256),
        "max_regret_holonomy": integer(horizon_plan.get("max_regret_holonomy"), 256),
        "max_sources_per_cycle": integer(horizon_plan.get("max_sources_per_cycle"), 8),
        "max_signals_per_source": integer(horizon_plan.get("max_signals_per_source"), 8),
        "max_total_signals": integer(horizon_plan.get("max_total_signals"), 32),
        "max_generated_goals": integer(horizon_plan.get("max_generated_goals"), 8),
        "max_selected_goals": integer(horizon_plan.get("max_selected_goals"), 4),
        "min_goal_score": clamp(horizon_plan.get("min_goal_score")),
        "min_action_scale": clamp(horizon_plan.get("min_action_scale")),
        "renewal_window_steps": integer(horizon_plan.get("renewal_window_steps"), 3),
        "max_bundle_sections": integer(horizon_plan.get("max_bundle_sections"), 256),
        "max_new_sections_per_run": integer(horizon_plan.get("max_new_sections_per_run"), 8),
        "max_transports_per_section": integer(horizon_plan.get("max_transports_per_section"), 4),
        "boundary": dict(REGRET_REQUIRED_BOUNDARY),
    }
    packet["regret_plan_digest"] = regret_plan_digest(packet)
    return packet


def build_child_regret_license(
    *,
    child_plan: Mapping[str, Any],
    source_packets: list[Mapping[str, Any]],
    root_packet: Mapping[str, Any],
    adapter_registry: Mapping[str, Any],
    previous_capability_bundle: Mapping[str, Any],
    source_portfolio_bundle: Mapping[str, Any],
    previous_experiment_bundle: Mapping[str, Any],
    previous_policy_bundle: Mapping[str, Any],
    previous_regret_bundle: Mapping[str, Any],
) -> dict[str, Any]:
    packet = {
        "version": REGRET_LICENSE_VERSION,
        "bound_regret_plan_digest": child_plan.get("regret_plan_digest", ""),
        "bound_source_batch_digest": batch_digest(source_packets),
        "bound_root_principles_digest": root_packet.get("root_principles_digest", ""),
        "bound_adapter_registry_digest": adapter_registry.get("adapter_registry_digest", ""),
        "bound_previous_capability_bundle_digest": previous_capability_bundle.get("capability_bundle_digest", ""),
        "bound_source_portfolio_bundle_digest": source_portfolio_bundle.get("portfolio_bundle_digest", ""),
        "bound_previous_experiment_bundle_digest": previous_experiment_bundle.get("experiment_bundle_digest", ""),
        "bound_previous_policy_bundle_digest": previous_policy_bundle.get("policy_bundle_digest", ""),
        "bound_previous_regret_bundle_digest": previous_regret_bundle.get("regret_bundle_digest", ""),
        "multiple_child_policy_cycles_allowed": False,
        "counterfactual_truth_promotion_allowed": False,
        "unexecuted_alternative_outcome_allowed": False,
        "v0_9_authority_bypass_allowed": False,
        "v0_8_hard_gate_bypass_allowed": False,
        "unbudgeted_trial_allowed": False,
        "shadow_execution_allowed": False,
        "external_network_effect_allowed": False,
        "world_update_allowed": False,
        "memory_overwrite_allowed": False,
        "source_authority_transfer_allowed": False,
        "adapter_authority_inheritance_allowed": False,
    }
    for field in (
        "source_read_allowed",
        "upstream_state_read_allowed",
        "counterfactual_estimation_allowed",
        "regret_update_allowed",
        "cadence_adaptation_allowed",
        "one_child_policy_cycle_allowed",
        "regret_bundle_write_allowed",
        "regret_state_write_allowed",
        "decision_write_allowed",
        "outcome_write_allowed",
        "child_packet_write_allowed",
        "ledger_append_allowed",
        "receipt_write_allowed",
        "audit_append_allowed",
    ):
        packet[field] = True
    return packet
