#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import asdict, dataclass
from html import escape
import hashlib
import json
from typing import Any, Mapping


@dataclass(frozen=True)
class QiCatalogStaticRenderer:
    renderer_version: str
    renderer_status: str
    renderer_receipt_id: str
    source_catalog_id: str | None
    catalog_key: str | None
    navigation_index_key: str | None
    navigation_index_hash: str | None
    catalog_entry_count: int
    html_artifact_name: str
    html_sha256: str
    html_bytes: int
    catalog_static_html_rendered: bool
    multi_dashboard_index_ready: bool
    js_enabled: bool
    external_network_required: bool
    read_only_surface: bool
    daemon_control_performed: bool
    daemon_restart_performed: bool
    daemon_stop_performed: bool
    daemon_resume_performed: bool
    memory_write_performed: bool
    memory_append_performed: bool
    memory_overwrite_performed: bool
    world_update_performed: bool
    control_packet_mutation_performed: bool
    probe_execution_performed: bool
    auto_remediation_performed: bool
    grants_daemon_control_authority: bool
    grants_probe_execution_authority: bool
    grants_world_update_authority: bool
    grants_memory_overwrite_authority: bool
    renderer_blockers: list[str]
    renderer_warnings: list[str]
    html: str
    authority: str = "catalog_static_renderer"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _entry_row(entry: Mapping[str, Any]) -> str:
    receipt = escape(str(entry.get("publication_receipt_id", "unknown")))
    uri = escape(str(entry.get("publication_uri", "")))
    artifact = escape(str(entry.get("html_artifact_name", "")))
    sha = escape(str(entry.get("html_sha256", "")))
    idx_hash = escape(str(entry.get("index_entry_hash", "")))
    link = f"<a href=\"{uri}\">{artifact}</a>" if uri else artifact
    return (
        "<tr>"
        f"<td><code>{receipt}</code></td>"
        f"<td>{link}</td>"
        f"<td><code>{sha}</code></td>"
        f"<td><code>{idx_hash}</code></td>"
        "</tr>"
    )


def render_catalog_html(catalog: Mapping[str, Any], *, generated_by: str) -> str:
    title = str(catalog.get("dashboard_title", "Qi Published Dashboard Catalog"))
    catalog_id = str(catalog.get("catalog_id", "unknown"))
    catalog_key = str(catalog.get("catalog_key", "unknown"))
    nav_key = str(catalog.get("navigation_index_key", "unknown"))
    nav_hash = str(catalog.get("navigation_index_hash", "unknown"))
    rows = "\n".join(_entry_row(_mapping(item)) for item in _list(catalog.get("entries")))
    if not rows:
        rows = "<tr><td colspan='4'>No entries</td></tr>"
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; line-height: 1.5; }}
    header {{ border-bottom: 1px solid #ccc; margin-bottom: 1.5rem; }}
    .meta {{ border: 1px solid #ddd; border-radius: 0.75rem; padding: 1rem; margin: 1rem 0; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border-top: 1px solid #eee; padding: 0.5rem; vertical-align: top; text-align: left; }}
    th {{ background: #f7f7f7; }}
    code {{ white-space: pre-wrap; word-break: break-word; }}
    footer {{ margin-top: 2rem; color: #666; font-size: 0.9rem; }}
  </style>
</head>
<body>
  <header>
    <h1>{escape(title)}</h1>
    <p>Read-only multi-dashboard HTML index.</p>
  </header>
  <section class="meta">
    <h2>Catalog metadata</h2>
    <table>
      <tr><th>catalog_id</th><td><code>{escape(catalog_id)}</code></td></tr>
      <tr><th>catalog_key</th><td><code>{escape(catalog_key)}</code></td></tr>
      <tr><th>navigation_index_key</th><td><code>{escape(nav_key)}</code></td></tr>
      <tr><th>navigation_index_hash</th><td><code>{escape(nav_hash)}</code></td></tr>
    </table>
  </section>
  <section class="meta">
    <h2>Published dashboards</h2>
    <table>
      <thead><tr><th>Receipt</th><th>Artifact</th><th>HTML SHA-256</th><th>Index entry hash</th></tr></thead>
      <tbody>{rows}</tbody>
    </table>
  </section>
  <footer>Generated by {escape(generated_by)}. No JavaScript. No external network dependency.</footer>
</body>
</html>
"""


def build_qi_catalog_static_renderer(
    *,
    published_catalog: Mapping[str, Any],
    render_context: Mapping[str, Any] | None = None,
) -> QiCatalogStaticRenderer:
    catalog = _mapping(published_catalog)
    ctx = _mapping(render_context)
    blockers: list[str] = []
    warnings: list[str] = []

    if ctx.get("catalog_static_renderer_enabled") is not True:
        blockers.append("catalog_static_renderer_enabled_not_true")
    if ctx.get("read_only_surface_required") is not True:
        blockers.append("read_only_surface_required_not_true")
    if catalog.get("catalog_status") != "QI_PUBLISHED_DASHBOARD_CATALOG_READY":
        blockers.append("published_catalog_not_ready")
    if catalog.get("published_dashboard_catalog_rendered") is not True:
        blockers.append("published_catalog_not_rendered")
    if catalog.get("operator_navigation_index_rendered") is not True:
        blockers.append("navigation_index_not_rendered")
    if catalog.get("read_only_surface") is not True:
        blockers.append("catalog_not_read_only")

    entries = _list(catalog.get("entries"))
    if not entries:
        blockers.append("catalog_entries_missing")
    for idx, entry in enumerate(entries):
        e = _mapping(entry)
        for required in ("publication_receipt_id", "publication_uri", "html_sha256", "index_entry_hash"):
            if not e.get(required):
                blockers.append(f"entry_{idx}_{required}_missing")

    required_catalog_fields = ("catalog_id", "catalog_key", "navigation_index_key", "navigation_index_hash")
    for key in required_catalog_fields:
        if not catalog.get(key):
            blockers.append(f"{key}_missing")

    forbidden_flags = [
        "daemon_control_performed",
        "daemon_restart_performed",
        "daemon_stop_performed",
        "daemon_resume_performed",
        "memory_write_performed",
        "memory_append_performed",
        "memory_overwrite_performed",
        "world_update_performed",
        "control_packet_mutation_performed",
        "probe_execution_performed",
        "auto_remediation_performed",
        "grants_daemon_control_authority",
        "grants_probe_execution_authority",
        "grants_world_update_authority",
        "grants_memory_overwrite_authority",
    ]
    for flag in forbidden_flags:
        if catalog.get(flag) is True or ctx.get(flag) is True:
            blockers.append(f"forbidden_flag_true:{flag}")

    generated_by = str(ctx.get("generated_by", "kuuos_catalog_static_renderer_v0_1"))
    html = render_catalog_html(catalog, generated_by=generated_by)
    if "<script" in html.lower():
        blockers.append("script_tag_present")
    html_sha = _sha256(html)
    artifact_name = str(ctx.get("html_artifact_name") or f"qi-dashboard-catalog-{html_sha[:12]}.html")
    ready = not blockers
    if ready and len(entries) == 1:
        warnings.append("single_entry_index")
    receipt_material = {
        "catalog_id": catalog.get("catalog_id"),
        "navigation_index_hash": catalog.get("navigation_index_hash"),
        "html_sha256": html_sha,
        "artifact_name": artifact_name,
    }
    renderer_receipt_id = "qi-catalog-html-" + _sha256(json.dumps(receipt_material, sort_keys=True))[:16]

    return QiCatalogStaticRenderer(
        renderer_version="kuuos_runtime_daemon_qi_catalog_static_renderer_v0_1",
        renderer_status="QI_CATALOG_STATIC_RENDERER_READY" if ready else "QI_CATALOG_STATIC_RENDERER_BLOCKED",
        renderer_receipt_id=renderer_receipt_id,
        source_catalog_id=str(catalog.get("catalog_id")) if catalog.get("catalog_id") else None,
        catalog_key=str(catalog.get("catalog_key")) if catalog.get("catalog_key") else None,
        navigation_index_key=str(catalog.get("navigation_index_key")) if catalog.get("navigation_index_key") else None,
        navigation_index_hash=str(catalog.get("navigation_index_hash")) if catalog.get("navigation_index_hash") else None,
        catalog_entry_count=len(entries),
        html_artifact_name=artifact_name,
        html_sha256=html_sha,
        html_bytes=len(html.encode("utf-8")),
        catalog_static_html_rendered=True,
        multi_dashboard_index_ready=ready,
        js_enabled=False,
        external_network_required=False,
        read_only_surface=ctx.get("read_only_surface_required") is True,
        daemon_control_performed=False,
        daemon_restart_performed=False,
        daemon_stop_performed=False,
        daemon_resume_performed=False,
        memory_write_performed=False,
        memory_append_performed=False,
        memory_overwrite_performed=False,
        world_update_performed=False,
        control_packet_mutation_performed=False,
        probe_execution_performed=False,
        auto_remediation_performed=False,
        grants_daemon_control_authority=False,
        grants_probe_execution_authority=False,
        grants_world_update_authority=False,
        grants_memory_overwrite_authority=False,
        renderer_blockers=blockers,
        renderer_warnings=warnings,
        html=html,
    )
