import Mathlib
import KUOS.WORLD.KuuVacuumInformationGeometryBridgeV0_55

/-!
WORLD v0.56: bounded-generator infinite-dimensional Araki Hessian and
Osterwalder-Schrader physical realization.

The calculus kernel below contains no Hessian-identification receipt.  Starting
from the exact first-variation response along bounded self-adjoint exponential
arcs, Lean differentiates once more and proves that the negative mixed Hessian
is the Bogoliubov-Kubo-Mori pairing.

The WORLD layer then transports that proved pairing to the existing vacuum
quantum Fisher metric, Hilbert excitation Gram form, Araki Hessian shadow, and
an Osterwalder-Schrader reflection form representative.

The analytic construction of general relative modular logarithms and unbounded
generator exponential arcs is not silently assumed.  This version states the
literature-supported bounded-generator scope explicitly.
-/

namespace KUOS
namespace WORLD

noncomputable section

/--
The one-dimensional response kernel extracted from an Araki exponential arc.

For generators `k` and `h`, `expectationAlong k h s` is the expectation of `h`
in the exponential arc generated by `k`.  Its derivative at the reference point
is the BKM pairing.  This is the exact analytic input needed after the Araki
first-variation formula has been established.
-/
structure ArakiBoundedExponentialArcKernel where
  Generator : Type
  referenceExpectation : Generator → ℝ
  expectationAlong : Generator → Generator → ℝ → ℝ
  bkmPairing : Generator → Generator → ℝ
  expectationDerivativeAtReference : ∀ k h,
    HasDerivAt (expectationAlong k h) (bkmPairing k h) 0
  bkmSymmetric : ∀ k h, bkmPairing k h = bkmPairing h k
  bkmNonnegative : ∀ h, 0 ≤ bkmPairing h h

namespace ArakiBoundedExponentialArcKernel

variable (A : ArakiBoundedExponentialArcKernel)

/-- The Araki first variation in the second exponential-arc argument. -/
def arakiFirstVariation (k h : A.Generator) (s : ℝ) : ℝ :=
  A.referenceExpectation h - A.expectationAlong k h s

/-- The negative mixed Hessian prescribed by divergence information geometry. -/
def arakiMixedHessian (k h : A.Generator) : ℝ :=
  -deriv (A.arakiFirstVariation k h) 0

/-- The first variation has derivative `-BKM` in the comparison arc. -/
theorem araki_first_variation_hasDerivAt (k h : A.Generator) :
    HasDerivAt (A.arakiFirstVariation k h) (-A.bkmPairing k h) 0 := by
  simpa [arakiFirstVariation] using
    (A.expectationDerivativeAtReference k h).const_sub
      (A.referenceExpectation h)

/--
The infinite-dimensional bounded-generator Araki Hessian equals the BKM metric.
This is a genuine Lean calculus proof from the response derivative, not a stored
claim/proof receipt.
-/
theorem araki_mixed_hessian_eq_bkm (k h : A.Generator) :
    A.arakiMixedHessian k h = A.bkmPairing k h := by
  have hderiv := A.araki_first_variation_hasDerivAt k h
  unfold arakiMixedHessian
  rw [hderiv.deriv]
  simp

theorem araki_mixed_hessian_symmetric (k h : A.Generator) :
    A.arakiMixedHessian k h = A.arakiMixedHessian h k := by
  rw [A.araki_mixed_hessian_eq_bkm, A.araki_mixed_hessian_eq_bkm]
  exact A.bkmSymmetric k h

theorem araki_mixed_hessian_nonnegative (h : A.Generator) :
    0 ≤ A.arakiMixedHessian h h := by
  rw [A.araki_mixed_hessian_eq_bkm]
  exact A.bkmNonnegative h

end ArakiBoundedExponentialArcKernel

structure WorldKuuVacuumArakiHessianPhysicalRealization
    {C : RealHilbertL2Carrier}
    {W : WorldNoncommutativeOperatorAlgebra C}
    [PartialOrder W.Region]
    {B : WorldCStarLocalNetBridge C W}
    {V : WorldVonNeumannBicommutantBridge B}
    {M : WorldStandardFormModularFlowBridge V}
    {R : WorldModularStateKMSRelativeFlowBridge M}
    {E : WorldArakiRelativeEntropyBridge R}
    {P : WorldPetzRecoverySufficiencyBridge E}
    {T : WorldConditionalExpectationTakesakiBridge P}
    {J : WorldJonesBasicConstructionIndexBridge T}
    {S : WorldJonesTowerStandardInvariantBridge J}
    {Q : WorldCanonicalEndomorphismQSystemFrobeniusBridge S}
    {F : WorldBimoduleSectorFusionCategoryBridge Q}
    {Z : WorldModuleCategoryNimrepTubeCenterBridge F}
    {G : WorldGaugeCategoricalIndraNetBridge Z}
    {I : WorldInformationGeometricHigherGaugeBridge G}
    {H : WorldArakiPetzQuantumInformationGeometryBridge I}
    {D : WorldQuantumExponentialDualAffineProjectionBridge H}
    {Vary : WorldQuantumGeodesicMirrorDescentFreeEnergyBridge D}
    {Flow : WorldQuantumGradientJKOEntropyProductionBridge Vary}
    {Mix : WorldQuantumLogSobolevContractivityMixingBridge Flow}
    {K : WorldKuuVacuumOSHilbertCompletionBridge Mix}
    {Central : WorldKuuVacuumCentralReferenceStateBridge K}
    (Geom : WorldKuuVacuumInformationGeometryBridge Central) where
  analyticKernel : ArakiBoundedExponentialArcKernel
  boundedSelfAdjoint : analyticKernel.Generator → Prop
  generatorScope : ∀ h, boundedSelfAdjoint h

  tangentOfGenerator : analyticKernel.Generator → I.Tangent
  physicalObservable : analyticKernel.Generator → B.A
  tangentObservable_eq_physicalObservable : ∀ h,
    H.tangentObservable (tangentOfGenerator h) = physicalObservable h

  bkm_eq_quantumFisher : ∀ i k h,
    analyticKernel.bkmPairing k h =
      H.quantumFisherMetric i (Geom.vacuumParameter i)
        (tangentOfGenerator k) (tangentOfGenerator h)

  positiveTimeRepresentative : analyticKernel.Generator → K.PositiveTimeObservable
  osImage_eq_excitation : ∀ h,
    K.osHilbertIdentification (K.osClass (positiveTimeRepresentative h)) =
      Central.excitationVector (physicalObservable h)

  infiniteDimensionalPhysicalCarrier : InfiniteDimensional ℂ M.H

  sigmaFiniteStandardFormScope : Prop
  sigmaFiniteStandardFormScopeProof : sigmaFiniteStandardFormScope
  faithfulNormalVacuumScope : Prop
  faithfulNormalVacuumScopeProof : faithfulNormalVacuumScope
  boundedArakiExponentialArcScope : Prop
  boundedArakiExponentialArcScopeProof : boundedArakiExponentialArcScope

  noUnboundedGeneratorClaim : Prop
  noUnboundedGeneratorClaimProof : noUnboundedGeneratorClaim
  physicalRealizationNotWorldIdentity : Prop
  physicalRealizationNotWorldIdentityProof : physicalRealizationNotWorldIdentity
  hessianNotTruthAuthority : Prop
  hessianNotTruthAuthorityProof : hessianNotTruthAuthority
  readOnlyAnalyticSidecar : Prop
  readOnlyAnalyticSidecarProof : readOnlyAnalyticSidecar

namespace WorldKuuVacuumArakiHessianPhysicalRealization

variable {C : RealHilbertL2Carrier}
variable {W : WorldNoncommutativeOperatorAlgebra C}
variable [PartialOrder W.Region]
variable {B : WorldCStarLocalNetBridge C W}
variable {V : WorldVonNeumannBicommutantBridge B}
variable {M : WorldStandardFormModularFlowBridge V}
variable {R : WorldModularStateKMSRelativeFlowBridge M}
variable {E : WorldArakiRelativeEntropyBridge R}
variable {P : WorldPetzRecoverySufficiencyBridge E}
variable {T : WorldConditionalExpectationTakesakiBridge P}
variable {J : WorldJonesBasicConstructionIndexBridge T}
variable {S : WorldJonesTowerStandardInvariantBridge J}
variable {Q : WorldCanonicalEndomorphismQSystemFrobeniusBridge S}
variable {F : WorldBimoduleSectorFusionCategoryBridge Q}
variable {Z : WorldModuleCategoryNimrepTubeCenterBridge F}
variable {G : WorldGaugeCategoricalIndraNetBridge Z}
variable {I : WorldInformationGeometricHigherGaugeBridge G}
variable {H : WorldArakiPetzQuantumInformationGeometryBridge I}
variable {D : WorldQuantumExponentialDualAffineProjectionBridge H}
variable {Vary : WorldQuantumGeodesicMirrorDescentFreeEnergyBridge D}
variable {Flow : WorldQuantumGradientJKOEntropyProductionBridge Vary}
variable {Mix : WorldQuantumLogSobolevContractivityMixingBridge Flow}
variable {K : WorldKuuVacuumOSHilbertCompletionBridge Mix}
variable {Central : WorldKuuVacuumCentralReferenceStateBridge K}
variable {Geom : WorldKuuVacuumInformationGeometryBridge Central}

variable (Realization :
  WorldKuuVacuumArakiHessianPhysicalRealization Geom)

/-- Physical excitation generated from the information-geometric tangent. -/
def physicalGeneratorExcitation
    (h : Realization.analyticKernel.Generator) : M.H :=
  Geom.vacuumTangentExcitation (Realization.tangentOfGenerator h)

theorem physical_generator_excitation_eq_observable_excitation
    (h : Realization.analyticKernel.Generator) :
    Realization.physicalGeneratorExcitation h =
      Central.excitationVector (Realization.physicalObservable h) := by
  unfold physicalGeneratorExcitation
  unfold WorldKuuVacuumInformationGeometryBridge.vacuumTangentExcitation
  rw [Realization.tangentObservable_eq_physicalObservable h]

theorem physical_generator_excitation_eq_os_image
    (h : Realization.analyticKernel.Generator) :
    Realization.physicalGeneratorExcitation h =
      K.osHilbertIdentification
        (K.osClass (Realization.positiveTimeRepresentative h)) := by
  rw [Realization.physical_generator_excitation_eq_observable_excitation h]
  exact (Realization.osImage_eq_excitation h).symm

theorem araki_hessian_eq_quantum_fisher
    (i : G.Patch) (k h : Realization.analyticKernel.Generator) :
    Realization.analyticKernel.arakiMixedHessian k h =
      H.quantumFisherMetric i (Geom.vacuumParameter i)
        (Realization.tangentOfGenerator k)
        (Realization.tangentOfGenerator h) := by
  rw [Realization.analyticKernel.araki_mixed_hessian_eq_bkm]
  exact Realization.bkm_eq_quantumFisher i k h

theorem araki_hessian_eq_araki_hessian_shadow
    (i : G.Patch) (k h : Realization.analyticKernel.Generator) :
    Realization.analyticKernel.arakiMixedHessian k h =
      H.arakiHessianShadow i (Geom.vacuumParameter i)
        (Realization.tangentOfGenerator k)
        (Realization.tangentOfGenerator h) := by
  calc
    Realization.analyticKernel.arakiMixedHessian k h =
        H.quantumFisherMetric i (Geom.vacuumParameter i)
          (Realization.tangentOfGenerator k)
          (Realization.tangentOfGenerator h) :=
      Realization.araki_hessian_eq_quantum_fisher i k h
    _ = H.arakiHessianShadow i (Geom.vacuumParameter i)
          (Realization.tangentOfGenerator k)
          (Realization.tangentOfGenerator h) :=
      H.quantumFisher_eq_arakiHessian i (Geom.vacuumParameter i)
        (Realization.tangentOfGenerator k)
        (Realization.tangentOfGenerator h)

theorem araki_hessian_eq_physical_excitation_gram
    (i : G.Patch) (k h : Realization.analyticKernel.Generator) :
    Realization.analyticKernel.arakiMixedHessian k h =
      (inner ℂ
        (Realization.physicalGeneratorExcitation k)
        (Realization.physicalGeneratorExcitation h)).re := by
  calc
    Realization.analyticKernel.arakiMixedHessian k h =
        H.quantumFisherMetric i (Geom.vacuumParameter i)
          (Realization.tangentOfGenerator k)
          (Realization.tangentOfGenerator h) :=
      Realization.araki_hessian_eq_quantum_fisher i k h
    _ = (inner ℂ
          (Geom.vacuumTangentExcitation (Realization.tangentOfGenerator k))
          (Geom.vacuumTangentExcitation (Realization.tangentOfGenerator h))).re :=
      (Geom.vacuum_excitation_gram_eq_quantum_fisher i
        (Realization.tangentOfGenerator k)
        (Realization.tangentOfGenerator h)).symm
    _ = (inner ℂ
          (Realization.physicalGeneratorExcitation k)
          (Realization.physicalGeneratorExcitation h)).re := rfl

theorem araki_hessian_eq_os_reflection_form_re
    (i : G.Patch) (k h : Realization.analyticKernel.Generator) :
    Realization.analyticKernel.arakiMixedHessian k h =
      (K.osReflectionForm
        (Realization.positiveTimeRepresentative k)
        (Realization.positiveTimeRepresentative h)).re := by
  rw [Realization.araki_hessian_eq_physical_excitation_gram i k h]
  rw [Realization.physical_generator_excitation_eq_os_image k]
  rw [Realization.physical_generator_excitation_eq_os_image h]
  simpa using congrArg Complex.re
    (K.osClassInner
      (Realization.positiveTimeRepresentative k)
      (Realization.positiveTimeRepresentative h))

theorem araki_hessian_nonnegative
    (h : Realization.analyticKernel.Generator) :
    0 ≤ Realization.analyticKernel.arakiMixedHessian h h :=
  Realization.analyticKernel.araki_mixed_hessian_nonnegative h

theorem physical_carrier_is_infinite_dimensional :
    InfiniteDimensional ℂ M.H :=
  Realization.infiniteDimensionalPhysicalCarrier

theorem exact_scope_package :
    Realization.sigmaFiniteStandardFormScope ∧
    Realization.faithfulNormalVacuumScope ∧
    Realization.boundedArakiExponentialArcScope :=
  ⟨Realization.sigmaFiniteStandardFormScopeProof,
    Realization.faithfulNormalVacuumScopeProof,
    Realization.boundedArakiExponentialArcScopeProof⟩

theorem analytic_boundary_package :
    Realization.noUnboundedGeneratorClaim ∧
    Realization.physicalRealizationNotWorldIdentity ∧
    Realization.hessianNotTruthAuthority ∧
    Realization.readOnlyAnalyticSidecar :=
  ⟨Realization.noUnboundedGeneratorClaimProof,
    Realization.physicalRealizationNotWorldIdentityProof,
    Realization.hessianNotTruthAuthorityProof,
    Realization.readOnlyAnalyticSidecarProof⟩

end WorldKuuVacuumArakiHessianPhysicalRealization
end
end WORLD
end KUOS
