import Mathlib
import KUOS.WORLD.CStarLocalNetBridgeV0_30

/-!
Kū–Indra WORLD von Neumann bicommutant bridge v0.31.

This module constructs algebraic commutants and bicommutants for the v0.30 local
C⋆-net. The algebraic consequences are proved in Lean. Identification with a
weak-operator closure is deliberately isolated as an external analytic proof
receipt; runtime does not manufacture that theorem or a weak operator topology.
-/

namespace KUOS
namespace WORLD

namespace WorldCStarLocalNetBridge

variable {C : RealHilbertL2Carrier}
variable {W : WorldNoncommutativeOperatorAlgebra C}
variable [PartialOrder W.Region]
variable (B : WorldCStarLocalNetBridge C W)

/-- The multiplicative commutant of a set of observables. -/
def commutant (S : Set B.A) : Set B.A :=
  S.centralizer

/-- The algebraic double commutant generated by a set of observables. -/
def bicommutant (S : Set B.A) : Set B.A :=
  S.centralizer.centralizer

theorem subset_bicommutant (S : Set B.A) :
    S ⊆ B.bicommutant S :=
  Set.subset_centralizer_centralizer

theorem commutant_antitone {S T : Set B.A} (h : S ⊆ T) :
    B.commutant T ⊆ B.commutant S :=
  Set.centralizer_subset h

theorem bicommutant_monotone {S T : Set B.A} (h : S ⊆ T) :
    B.bicommutant S ⊆ B.bicommutant T := by
  exact Set.centralizer_subset (Set.centralizer_subset h)

theorem triple_commutant_eq_commutant (S : Set B.A) :
    (B.bicommutant S).centralizer = B.commutant S := by
  exact Set.centralizer_centralizer_centralizer S

theorem bicommutant_idempotent (S : Set B.A) :
    B.bicommutant (B.bicommutant S) = B.bicommutant S := by
  exact Set.centralizer_centralizer_centralizer S.centralizer

/-- The underlying set of the local C⋆-algebra at a WORLD region. -/
def localCarrier (i : W.Region) : Set B.A :=
  B.localAlgebra i

/-- The commutant of the local algebra at a WORLD region. -/
def localCommutant (i : W.Region) : Set B.A :=
  B.commutant (B.localCarrier i)

/-- The algebraic von Neumann candidate generated by a local algebra. -/
def localBicommutant (i : W.Region) : Set B.A :=
  B.bicommutant (B.localCarrier i)

theorem local_subset_localBicommutant (i : W.Region) :
    B.localCarrier i ⊆ B.localBicommutant i :=
  B.subset_bicommutant (B.localCarrier i)

theorem localBicommutant_isotony {i j : W.Region} (h : i ≤ j) :
    B.localBicommutant i ⊆ B.localBicommutant j := by
  apply B.bicommutant_monotone
  exact B.isotony h

theorem localBicommutant_idempotent (i : W.Region) :
    B.bicommutant (B.localBicommutant i) = B.localBicommutant i :=
  B.bicommutant_idempotent (B.localCarrier i)

theorem local_subset_spacelike_commutant
    {i j : W.Region}
    (h : B.spacelike i j) :
    B.localCarrier i ⊆ B.localCommutant j := by
  intro a ha
  rw [Set.mem_centralizer_iff]
  intro b hb
  exact (B.locality h ⟨a, ha⟩ ⟨b, hb⟩).eq.symm

theorem localBicommutant_subset_spacelike_commutant
    {i j : W.Region}
    (h : B.spacelike i j) :
    B.localBicommutant i ⊆ B.localCommutant j := by
  have hji : B.localCarrier j ⊆ B.localCommutant i :=
    B.local_subset_spacelike_commutant (B.spacelikeSymmetric h)
  exact Set.centralizer_subset hji

theorem localBicommutants_commute
    {i j : W.Region}
    (h : B.spacelike i j)
    {a b : B.A}
    (ha : a ∈ B.localBicommutant i)
    (hb : b ∈ B.localBicommutant j) :
    Commute a b := by
  have ha' : a ∈ B.localCommutant j :=
    B.localBicommutant_subset_spacelike_commutant h ha
  change a * b = b * a
  exact (Set.mem_centralizer_iff.mp hb) a ha'

end WorldCStarLocalNetBridge

structure WorldVonNeumannBicommutantBridge
    {C : RealHilbertL2Carrier}
    {W : WorldNoncommutativeOperatorAlgebra C}
    [PartialOrder W.Region]
    (B : WorldCStarLocalNetBridge C W) where
  weakOperatorClosure : W.Region → Set B.A
  weakOperatorClosedClaim : W.Region → Prop
  weakOperatorClosedProof : ∀ i, weakOperatorClosedClaim i
  weakClosureEqBicommutant : ∀ i,
    weakOperatorClosure i = B.localBicommutant i
  bicommutantTheoremExternallyProved : Prop
  bicommutantTheoremExternalProof : bicommutantTheoremExternallyProved
  runtimeModelsWeakOperatorTopology : Bool
  runtimeConstructsWeakClosure : Bool
  runtimeClaimsBicommutantTheorem : Bool
  runtimeExecutesUnboundedOperator : Bool
  worldUpdated : Bool
  noRuntimeWeakTopology : runtimeModelsWeakOperatorTopology = false
  noRuntimeWeakClosureConstruction : runtimeConstructsWeakClosure = false
  noRuntimeBicommutantTheoremClaim : runtimeClaimsBicommutantTheorem = false
  noRuntimeUnboundedExecution : runtimeExecutesUnboundedOperator = false
  noWorldUpdate : worldUpdated = false
  worldNotIdentifiedWithVonNeumannCarrier : Prop
  worldNotIdentifiedProof : worldNotIdentifiedWithVonNeumannCarrier
  multiWorldNoncollapsePreserved : Prop
  multiWorldNoncollapseProof : multiWorldNoncollapsePreserved
  twoTruthsGapPreserved : Prop
  twoTruthsGapProof : twoTruthsGapPreserved

namespace WorldVonNeumannBicommutantBridge

variable {C : RealHilbertL2Carrier}
variable {W : WorldNoncommutativeOperatorAlgebra C}
variable [PartialOrder W.Region]
variable {B : WorldCStarLocalNetBridge C W}
variable (V : WorldVonNeumannBicommutantBridge B)

theorem weakOperatorClosedCertified (i : W.Region) :
    V.weakOperatorClosedClaim i :=
  V.weakOperatorClosedProof i

theorem weakClosure_eq_localBicommutant (i : W.Region) :
    V.weakOperatorClosure i = B.localBicommutant i :=
  V.weakClosureEqBicommutant i

theorem local_subset_weakClosure (i : W.Region) :
    B.localCarrier i ⊆ V.weakOperatorClosure i := by
  rw [V.weakClosureEqBicommutant]
  exact B.local_subset_localBicommutant i

theorem weakClosure_isotony {i j : W.Region} (h : i ≤ j) :
    V.weakOperatorClosure i ⊆ V.weakOperatorClosure j := by
  rw [V.weakClosureEqBicommutant, V.weakClosureEqBicommutant]
  exact B.localBicommutant_isotony h

theorem weakClosures_spacelike_commute
    {i j : W.Region}
    (h : B.spacelike i j)
    {a b : B.A}
    (ha : a ∈ V.weakOperatorClosure i)
    (hb : b ∈ V.weakOperatorClosure j) :
    Commute a b := by
  rw [V.weakClosureEqBicommutant] at ha
  rw [V.weakClosureEqBicommutant] at hb
  exact B.localBicommutants_commute h ha hb

theorem external_bicommutant_theorem_receipt :
    V.bicommutantTheoremExternallyProved :=
  V.bicommutantTheoremExternalProof

theorem runtime_grants_no_von_neumann_authority :
    V.runtimeModelsWeakOperatorTopology = false ∧
    V.runtimeConstructsWeakClosure = false ∧
    V.runtimeClaimsBicommutantTheorem = false ∧
    V.runtimeExecutesUnboundedOperator = false ∧
    V.worldUpdated = false :=
  ⟨V.noRuntimeWeakTopology, V.noRuntimeWeakClosureConstruction,
    V.noRuntimeBicommutantTheoremClaim, V.noRuntimeUnboundedExecution,
    V.noWorldUpdate⟩

theorem representation_boundary_preserved :
    V.worldNotIdentifiedWithVonNeumannCarrier ∧
    V.multiWorldNoncollapsePreserved ∧
    V.twoTruthsGapPreserved :=
  ⟨V.worldNotIdentifiedProof, V.multiWorldNoncollapseProof,
    V.twoTruthsGapProof⟩

end WorldVonNeumannBicommutantBridge
end WORLD
end KUOS
