import Mathlib
import KUOS.OpenHorizon.MemoryOSFiniteFamilySignatureLatticeV0_97

namespace KUOS.OpenHorizon.MemoryOSSensorKernelPolarityV0_98

open KUOS.OpenHorizon.MemoryOSNonAbelianWilsonLoopV0_72
open KUOS.OpenHorizon.MemoryOSRootedRouteAtlasNielsenChangeV0_78
open KUOS.OpenHorizon.MemoryOSAllRootChartDefectAwareWordTransportV0_80
open KUOS.OpenHorizon.MemoryOSNormalizedRootWordGroupoidDescentV0_81
open KUOS.OpenHorizon.MemoryOSGlobalWordCechDescentV0_82
open KUOS.OpenHorizon.MemoryOSGlobalSectionGroupAnchorCoherenceV0_83
open KUOS.OpenHorizon.MemoryOSGlobalObservableKernelQuotientV0_84
open KUOS.OpenHorizon.MemoryOSObservableSensorCoarseningV0_85
open KUOS.OpenHorizon.MemoryOSJointSensorProductRefinementV0_86
open KUOS.OpenHorizon.MemoryOSFiniteSensorFamilyRefinementV0_87
open KUOS.OpenHorizon.MemoryOSExactSensorCoreV0_88
open KUOS.OpenHorizon.MemoryOSSensorSupportClosureV0_89
open KUOS.OpenHorizon.MemoryOSFullClosedSupportRepresentationV0_90
open KUOS.OpenHorizon.MemoryOSCounterexampleGuidedContextRefinementV0_91
open KUOS.OpenHorizon.MemoryOSFiniteBatchContextSaturationV0_92
open KUOS.OpenHorizon.MemoryOSMinimalGeneratorClosureQuotientV0_93
open KUOS.OpenHorizon.MemoryOSChoiceFreeGeneratorAntichainSignaturesV0_94
open KUOS.OpenHorizon.MemoryOSChoiceFreeSignatureHullKernelOrderDualityV0_95
open KUOS.OpenHorizon.MemoryOSPointedSignatureLatticeV0_96
open KUOS.OpenHorizon.MemoryOSFiniteFamilySignatureLatticeV0_97

/-- Sensors whose individual invisible kernel dominates the supplied subgroup. -/
noncomputable def kernelDominatedSensorSupport
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) : Finset ι := by
  classical
  exact Finset.univ.filter fun i =>
    kernel ≤ sensorObservableKernel (sensors i) atlas targetDefect root

/-- Kernel-side closure generated by all sensors dominated by a subgroup. -/
noncomputable def sensorKernelEnvelope
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) : Subgroup GlobalNormalizedWordSection :=
  finiteSensorSupportKernel sensors
    (kernelDominatedSensorSupport sensors kernel atlas targetDefect root)
    atlas targetDefect root

/-- Fixed points of the kernel envelope are exactly the kernels representable by
some finite sensor support. -/
def SensorKernelRepresentable
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) : Prop :=
  sensorKernelEnvelope sensors kernel atlas targetDefect root = kernel

@[simp] theorem mem_kernel_dominated_sensor_support_iff
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection) (i : ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    i ∈ kernelDominatedSensorSupport sensors kernel atlas targetDefect root ↔
      kernel ≤ sensorObservableKernel (sensors i) atlas targetDefect root := by
  classical
  simp [kernelDominatedSensorSupport]

/-- Exact antitone polarity between sensor supports and invisible kernels. -/
theorem kernel_le_support_kernel_iff_subset_dominated_support
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (support : Finset ι)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    kernel ≤ finiteSensorSupportKernel sensors support atlas targetDefect root ↔
      support ⊆
        kernelDominatedSensorSupport sensors kernel atlas targetDefect root := by
  constructor
  · intro hkernel i hi
    rw [mem_kernel_dominated_sensor_support_iff]
    intro section hsection
    have hsupport :
        section ∈ finiteSensorSupportKernel sensors support
          atlas targetDefect root := hkernel hsection
    rw [mem_finite_sensor_support_kernel_iff] at hsupport
    exact hsupport i hi
  · intro hsupport section hsection
    rw [mem_finite_sensor_support_kernel_iff]
    intro i hi
    have hiDominated := hsupport hi
    rw [mem_kernel_dominated_sensor_support_iff] at hiDominated
    exact hiDominated hsection

/-- The v0.89 support closure is exactly the support-side composite of the
kernel polarity. -/
theorem sensor_support_closure_eq_kernel_dominated_support
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (support : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    sensorSupportClosure sensors support atlas targetDefect root =
      kernelDominatedSensorSupport sensors
        (finiteSensorSupportKernel sensors support atlas targetDefect root)
        atlas targetDefect root := by
  classical
  ext i
  rw [mem_sensor_support_closure_iff,
    mem_kernel_dominated_sensor_support_iff]

/-- Every subgroup is contained in its sensor-representable kernel envelope. -/
theorem kernel_le_sensor_kernel_envelope
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    kernel ≤ sensorKernelEnvelope sensors kernel atlas targetDefect root := by
  unfold sensorKernelEnvelope
  exact
    (kernel_le_support_kernel_iff_subset_dominated_support sensors
      (kernelDominatedSensorSupport sensors kernel atlas targetDefect root)
      kernel atlas targetDefect root).2 (fun _ hi => hi)

/-- Kernel envelope is monotone. -/
theorem sensor_kernel_envelope_mono
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    {left right : Subgroup GlobalNormalizedWordSection}
    (hkernel : left ≤ right)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    sensorKernelEnvelope sensors left atlas targetDefect root ≤
      sensorKernelEnvelope sensors right atlas targetDefect root := by
  unfold sensorKernelEnvelope
  apply finite_sensor_support_kernel_antitone sensors
  intro i hi
  rw [mem_kernel_dominated_sensor_support_iff] at hi ⊢
  exact hkernel.trans hi

/-- Every finite support kernel is already a fixed point of the kernel envelope. -/
theorem support_kernel_envelope_eq
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (support : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    sensorKernelEnvelope sensors
        (finiteSensorSupportKernel sensors support atlas targetDefect root)
        atlas targetDefect root =
      finiteSensorSupportKernel sensors support atlas targetDefect root := by
  unfold sensorKernelEnvelope
  rw [← sensor_support_closure_eq_kernel_dominated_support]
  exact sensor_support_closure_kernel_eq sensors support
    atlas targetDefect root

/-- Kernel envelope is idempotent. -/
theorem sensor_kernel_envelope_idempotent
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    sensorKernelEnvelope sensors
        (sensorKernelEnvelope sensors kernel atlas targetDefect root)
        atlas targetDefect root =
      sensorKernelEnvelope sensors kernel atlas targetDefect root := by
  unfold sensorKernelEnvelope
  exact support_kernel_envelope_eq sensors
    (kernelDominatedSensorSupport sensors kernel atlas targetDefect root)
    atlas targetDefect root

/-- The support selected by any subgroup is closed under exact kernel
implication. -/
theorem kernel_dominated_sensor_support_closed
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    SensorSupportClosed sensors
      (kernelDominatedSensorSupport sensors kernel atlas targetDefect root)
      atlas targetDefect root := by
  unfold SensorSupportClosed
  rw [sensor_support_closure_eq_kernel_dominated_support]
  apply Finset.Subset.antisymm
  · intro i hi
    rw [mem_kernel_dominated_sensor_support_iff] at hi ⊢
    exact (kernel_le_sensor_kernel_envelope sensors kernel
      atlas targetDefect root).trans hi
  · have hsubset := sensor_support_subset_closure sensors
      (kernelDominatedSensorSupport sensors kernel atlas targetDefect root)
      atlas targetDefect root
    rw [sensor_support_closure_eq_kernel_dominated_support] at hsubset
    exact hsubset

/-- Closed supports are recovered exactly from their kernels. -/
theorem kernel_dominated_support_of_closed_eq
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (support : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (hclosed : SensorSupportClosed sensors support atlas targetDefect root) :
    kernelDominatedSensorSupport sensors
        (finiteSensorSupportKernel sensors support atlas targetDefect root)
        atlas targetDefect root =
      support := by
  rw [← sensor_support_closure_eq_kernel_dominated_support, hclosed]

/-- Support kernels are representable fixed points. -/
theorem support_kernel_representable
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (support : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    SensorKernelRepresentable sensors
      (finiteSensorSupportKernel sensors support atlas targetDefect root)
      atlas targetDefect root := by
  exact support_kernel_envelope_eq sensors support atlas targetDefect root

/-- Kernel fixed points are exactly kernels of closed sensor supports. -/
theorem sensor_kernel_representable_iff_exists_closed_support
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    SensorKernelRepresentable sensors kernel atlas targetDefect root ↔
      ∃ support : Finset ι,
        SensorSupportClosed sensors support atlas targetDefect root ∧
        finiteSensorSupportKernel sensors support atlas targetDefect root = kernel := by
  constructor
  · intro hrepresentable
    refine ⟨kernelDominatedSensorSupport sensors kernel atlas targetDefect root,
      kernel_dominated_sensor_support_closed sensors kernel atlas targetDefect root,
      ?_⟩
    exact hrepresentable
  · rintro ⟨support, hclosed, hkernel⟩
    unfold SensorKernelRepresentable
    rw [← hkernel]
    exact support_kernel_envelope_eq sensors support atlas targetDefect root

/-- Closed-support inclusion is the reverse order of representable kernels. -/
theorem closed_support_order_anti_equivalence
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (left right : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (hleftClosed : SensorSupportClosed sensors left atlas targetDefect root)
    (hrightClosed : SensorSupportClosed sensors right atlas targetDefect root) :
    left ⊆ right ↔
      finiteSensorSupportKernel sensors right atlas targetDefect root ≤
        finiteSensorSupportKernel sensors left atlas targetDefect root := by
  exact closed_context_subset_iff_kernel_reverse sensors left right
    atlas targetDefect root hleftClosed hrightClosed

/-- Finite infimum of support kernels in the ambient subgroup lattice. -/
noncomputable def finiteSupportKernelInf
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) : Subgroup GlobalNormalizedWordSection :=
  ⨅ support, ⨅ (_ : support ∈ family),
    finiteSensorSupportKernel sensors support atlas targetDefect root

/-- Finite supremum of support kernels before representable closure. -/
noncomputable def finiteSupportKernelSup
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) : Subgroup GlobalNormalizedWordSection :=
  ⨆ support, ⨆ (_ : support ∈ family),
    finiteSensorSupportKernel sensors support atlas targetDefect root

@[simp] theorem mem_finite_support_kernel_inf_iff
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) (section : GlobalNormalizedWordSection) :
    section ∈ finiteSupportKernelInf sensors family atlas targetDefect root ↔
      ∀ support ∈ family,
        section ∈ finiteSensorSupportKernel sensors support
          atlas targetDefect root := by
  simp [finiteSupportKernelInf]

@[simp] theorem finite_support_kernel_sup_le_iff
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    finiteSupportKernelSup sensors family atlas targetDefect root ≤ kernel ↔
      ∀ support ∈ family,
        finiteSensorSupportKernel sensors support atlas targetDefect root ≤ kernel := by
  simp [finiteSupportKernelSup]

/-- Finite support join transports to ambient kernel infimum. -/
theorem finite_join_support_kernel_eq_inf
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    finiteSensorSupportKernel sensors
        (closedContextFiniteJoin sensors family atlas targetDefect root)
        atlas targetDefect root =
      finiteSupportKernelInf sensors family atlas targetDefect root := by
  unfold closedContextFiniteJoin
  rw [sensor_support_closure_kernel_eq]
  ext section
  rw [mem_finite_sensor_support_kernel_iff,
    mem_finite_support_kernel_inf_iff]
  constructor
  · intro h support hsupport
    rw [mem_finite_sensor_support_kernel_iff]
    intro i hi
    exact h i ((mem_closed_context_finite_union_iff family i).2
      ⟨support, hsupport, hi⟩)
  · intro h i hi
    obtain ⟨support, hsupport, hiSupport⟩ :=
      (mem_closed_context_finite_union_iff family i).1 hi
    have hkernel := h support hsupport
    rw [mem_finite_sensor_support_kernel_iff] at hkernel
    exact hkernel i hiSupport

/-- For a closed family, the support selected by the ambient kernel supremum is
exactly the finite support meet. -/
theorem kernel_dominated_support_finite_sup_eq_meet
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (hclosed : ∀ support ∈ family,
      SensorSupportClosed sensors support atlas targetDefect root) :
    kernelDominatedSensorSupport sensors
        (finiteSupportKernelSup sensors family atlas targetDefect root)
        atlas targetDefect root =
      closedContextFiniteMeet family := by
  classical
  ext i
  rw [mem_kernel_dominated_sensor_support_iff,
    mem_closed_context_finite_meet_iff]
  constructor
  · intro hsup support hsupport
    have hcomponent :=
      (finite_support_kernel_sup_le_iff sensors family
        (sensorObservableKernel (sensors i) atlas targetDefect root)
        atlas targetDefect root).1 hsup support hsupport
    have hiClosure :=
      (mem_sensor_support_closure_iff sensors support i
        atlas targetDefect root).2 hcomponent
    rw [hclosed support hsupport] at hiClosure
    exact hiClosure
  · intro hall
    apply
      (finite_support_kernel_sup_le_iff sensors family
        (sensorObservableKernel (sensors i) atlas targetDefect root)
        atlas targetDefect root).2
    intro support hsupport
    have hiClosure :
        i ∈ sensorSupportClosure sensors support atlas targetDefect root := by
      rw [hclosed support hsupport]
      exact hall support hsupport
    exact
      (mem_sensor_support_closure_iff sensors support i
        atlas targetDefect root).1 hiClosure

/-- Finite meet of closed supports transports to the representable closure of
ambient kernel supremum. -/
theorem finite_meet_support_kernel_eq_envelope_sup
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (hclosed : ∀ support ∈ family,
      SensorSupportClosed sensors support atlas targetDefect root) :
    finiteSensorSupportKernel sensors (closedContextFiniteMeet family)
        atlas targetDefect root =
      sensorKernelEnvelope sensors
        (finiteSupportKernelSup sensors family atlas targetDefect root)
        atlas targetDefect root := by
  unfold sensorKernelEnvelope
  rw [kernel_dominated_support_finite_sup_eq_meet sensors family
    atlas targetDefect root hclosed]

/-- Kernel infimum obtained from finite support join is representable. -/
theorem finite_support_kernel_inf_representable
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    SensorKernelRepresentable sensors
      (finiteSupportKernelInf sensors family atlas targetDefect root)
      atlas targetDefect root := by
  rw [← finite_join_support_kernel_eq_inf sensors family
    atlas targetDefect root]
  exact support_kernel_representable sensors
    (closedContextFiniteJoin sensors family atlas targetDefect root)
    atlas targetDefect root

/-- Kernel envelope of a finite supremum is representable. -/
theorem finite_support_kernel_envelope_sup_representable
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (family : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    SensorKernelRepresentable sensors
      (sensorKernelEnvelope sensors
        (finiteSupportKernelSup sensors family atlas targetDefect root)
        atlas targetDefect root)
      atlas targetDefect root := by
  exact sensor_kernel_envelope_idempotent sensors
    (finiteSupportKernelSup sensors family atlas targetDefect root)
    atlas targetDefect root

/-- Dominated support is independent of the selected route root. -/
theorem kernel_dominated_sensor_support_root_independent
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (sourceRoot targetRoot : RouteLabel) :
    kernelDominatedSensorSupport sensors kernel atlas targetDefect sourceRoot =
      kernelDominatedSensorSupport sensors kernel atlas targetDefect targetRoot := by
  classical
  ext i
  rw [mem_kernel_dominated_sensor_support_iff,
    mem_kernel_dominated_sensor_support_iff,
    sensor_observable_kernel_root_independent
      (sensors i) atlas targetDefect sourceRoot targetRoot]

/-- Kernel envelope is independent of the selected route root. -/
theorem sensor_kernel_envelope_root_independent
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (kernel : Subgroup GlobalNormalizedWordSection)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (sourceRoot targetRoot : RouteLabel) :
    sensorKernelEnvelope sensors kernel atlas targetDefect sourceRoot =
      sensorKernelEnvelope sensors kernel atlas targetDefect targetRoot := by
  unfold sensorKernelEnvelope
  calc
    finiteSensorSupportKernel sensors
        (kernelDominatedSensorSupport sensors kernel atlas targetDefect sourceRoot)
        atlas targetDefect sourceRoot =
      finiteSensorSupportKernel sensors
        (kernelDominatedSensorSupport sensors kernel atlas targetDefect sourceRoot)
        atlas targetDefect targetRoot :=
      finite_sensor_support_kernel_root_independent sensors
        (kernelDominatedSensorSupport sensors kernel atlas targetDefect sourceRoot)
        atlas targetDefect sourceRoot targetRoot
    _ = finiteSensorSupportKernel sensors
        (kernelDominatedSensorSupport sensors kernel atlas targetDefect targetRoot)
        atlas targetDefect targetRoot := by
      rw [kernel_dominated_sensor_support_root_independent sensors kernel
        atlas targetDefect sourceRoot targetRoot]

structure SensorKernelPolarityCertificate where
  sourceMemoryOSV097Bound : Bool
  supportKernelPolarityExact : Bool
  supportClosureCompositeExact : Bool
  kernelEnvelopeClosureExact : Bool
  closedSupportFixedKernelCorrespondenceExact : Bool
  closedSupportKernelOrderDualityExact : Bool
  finiteJoinKernelInfTransportExact : Bool
  finiteMeetKernelEnvelopeSupTransportExact : Bool
  routeRootIndependenceExact : Bool
  completeLatticeTypeclassClaimed : Bool
  infiniteFamilySupInfClaimed : Bool
  distributivityClaimed : Bool
  modularityClaimed : Bool
  externalOracleAuthorityGranted : Bool
  candidateRankingPerformed : Bool
  executionPermission : Bool
  persistentWorldStateMutated : Bool
  truthAuthorityGranted : Bool

end KUOS.OpenHorizon.MemoryOSSensorKernelPolarityV0_98
