import Mathlib
import KUOS.OpenHorizon.MemoryOSCounterexampleGuidedContextRefinementV0_91

namespace KUOS.OpenHorizon.MemoryOSFiniteBatchContextSaturationV0_92

open KUOS.OpenHorizon.MemoryOSNonAbelianWilsonLoopV0_72
open KUOS.OpenHorizon.MemoryOSRootedRouteAtlasNielsenChangeV0_78
open KUOS.OpenHorizon.MemoryOSAllRootChartDefectAwareWordTransportV0_80
open KUOS.OpenHorizon.MemoryOSNormalizedRootWordGroupoidDescentV0_81
open KUOS.OpenHorizon.MemoryOSGlobalWordCechDescentV0_82
open KUOS.OpenHorizon.MemoryOSGlobalSectionGroupAnchorCoherenceV0_83
open KUOS.OpenHorizon.MemoryOSGlobalObservableKernelQuotientV0_84
open KUOS.OpenHorizon.MemoryOSObservableSensorCoarseningV0_85
open KUOS.OpenHorizon.MemoryOSJointSensorProductRefinementV0_86
open KUOS.OpenHorizon.MemoryOSFiniteSensorFamilyRefinementV0_87
open KUOS.OpenHorizon.MemoryOSExactSensorCoreV0_88
open KUOS.OpenHorizon.MemoryOSSensorSupportClosureV0_89
open KUOS.OpenHorizon.MemoryOSFullClosedSupportRepresentationV0_90
open KUOS.OpenHorizon.MemoryOSCounterexampleGuidedContextRefinementV0_91

/-- The distinct proper closure contexts generated by a finite batch of premises. -/
noncomputable def canonicalProperClosureContexts
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (premises : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) : Finset (Finset ι) := by
  classical
  exact
    (premises.image (fun premise =>
      sensorSupportClosure sensors premise atlas targetDefect root)).filter fun context =>
        context ≠ Finset.univ

/-- Add every distinct proper canonical closure generated by a finite premise batch. -/
noncomputable def batchRefineClosedContexts
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts premises : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) : Finset (Finset ι) :=
  contexts ∪ canonicalProperClosureContexts sensors premises atlas targetDefect root

theorem mem_canonical_proper_closure_contexts_iff
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (premises : Finset (Finset ι))
    (context : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    context ∈ canonicalProperClosureContexts sensors premises atlas targetDefect root ↔
      (∃ premise ∈ premises,
        sensorSupportClosure sensors premise atlas targetDefect root = context) ∧
        context ≠ Finset.univ := by
  classical
  simp [canonicalProperClosureContexts]

theorem mem_batch_refine_closed_contexts_iff
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts premises : Finset (Finset ι))
    (context : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    context ∈ batchRefineClosedContexts sensors contexts premises atlas targetDefect root ↔
      context ∈ contexts ∨
        context ∈ canonicalProperClosureContexts sensors premises atlas targetDefect root := by
  classical
  simp [batchRefineClosedContexts]

/-- Every canonical batch context is closed and proper. -/
theorem canonical_proper_closure_contexts_are_proper_closed
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (premises : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    ∀ context ∈ canonicalProperClosureContexts sensors premises atlas targetDefect root,
      SensorSupportClosed sensors context atlas targetDefect root ∧
        context ≠ Finset.univ := by
  intro context hcontext
  rw [mem_canonical_proper_closure_contexts_iff] at hcontext
  rcases hcontext with ⟨⟨premise, hpremise, hclosure⟩, hproper⟩
  subst context
  exact ⟨sensor_support_closure_closed sensors premise atlas targetDefect root, hproper⟩

/-- Finite batch refinement preserves a selected family of proper closed contexts. -/
theorem batch_refine_contexts_are_proper_closed
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts premises : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (hproper : ∀ context ∈ contexts,
      SensorSupportClosed sensors context atlas targetDefect root ∧
        context ≠ Finset.univ) :
    ∀ context ∈ batchRefineClosedContexts sensors contexts premises atlas targetDefect root,
      SensorSupportClosed sensors context atlas targetDefect root ∧
        context ≠ Finset.univ := by
  intro context hcontext
  rw [mem_batch_refine_closed_contexts_iff] at hcontext
  rcases hcontext with hbase | hbatch
  · exact hproper context hbase
  · exact canonical_proper_closure_contexts_are_proper_closed
      sensors premises atlas targetDefect root context hbatch

theorem contexts_subset_batch_refinement
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts premises : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    contexts ⊆
      batchRefineClosedContexts sensors contexts premises atlas targetDefect root := by
  intro context hcontext
  rw [mem_batch_refine_closed_contexts_iff]
  exact Or.inl hcontext

theorem premise_closure_mem_batch_refinement
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts premises : Finset (Finset ι))
    (premise : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (hpremise : premise ∈ premises)
    (hproper :
      sensorSupportClosure sensors premise atlas targetDefect root ≠ Finset.univ) :
    sensorSupportClosure sensors premise atlas targetDefect root ∈
      batchRefineClosedContexts sensors contexts premises atlas targetDefect root := by
  rw [mem_batch_refine_closed_contexts_iff]
  apply Or.inr
  rw [mem_canonical_proper_closure_contexts_iff]
  exact ⟨⟨premise, hpremise, rfl⟩, hproper⟩

/-- Every premise in the batch becomes exact for every singleton sensor query. -/
theorem batch_refinement_exact_for_included_premise
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts premises : Finset (Finset ι))
    (premise : Finset ι) (i : ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (hproper : ∀ context ∈ contexts,
      SensorSupportClosed sensors context atlas targetDefect root ∧
        context ≠ Finset.univ)
    (hpremise : premise ∈ premises) :
    i ∈ sensorSupportClosure sensors premise atlas targetDefect root ↔
      supportTruthRegion
          (batchRefineClosedContexts sensors contexts premises atlas targetDefect root)
          premise ⊆
        sensorTruthRegion
          (batchRefineClosedContexts sensors contexts premises atlas targetDefect root) i := by
  constructor
  · intro hi
    exact selected_closed_context_truth_region_sound sensors
      (batchRefineClosedContexts sensors contexts premises atlas targetDefect root)
      premise i atlas targetDefect root
      (fun context hcontext =>
        (batch_refine_contexts_are_proper_closed sensors contexts premises
          atlas targetDefect root hproper context hcontext).1) hi
  · intro hconsequence
    let closure := sensorSupportClosure sensors premise atlas targetDefect root
    by_cases htop : closure = Finset.univ
    · rw [htop]
      exact Finset.mem_univ i
    · have hcontext :
          closure ∈
            batchRefineClosedContexts sensors contexts premises atlas targetDefect root := by
        exact premise_closure_mem_batch_refinement sensors contexts premises premise
          atlas targetDefect root hpremise htop
      have hpremise_mem :
          closure ∈ supportTruthRegion
            (batchRefineClosedContexts sensors contexts premises atlas targetDefect root)
            premise := by
        rw [mem_support_truth_region_iff]
        exact ⟨hcontext,
          sensor_support_subset_closure sensors premise atlas targetDefect root⟩
      have hsensor := hconsequence hpremise_mem
      exact ((mem_sensor_truth_region_iff
        (batchRefineClosedContexts sensors contexts premises atlas targetDefect root)
        closure i).mp hsensor).2

/-- Applying the same finite batch twice changes nothing. -/
theorem batch_refine_closed_contexts_idempotent
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts premises : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    batchRefineClosedContexts sensors
        (batchRefineClosedContexts sensors contexts premises atlas targetDefect root)
        premises atlas targetDefect root =
      batchRefineClosedContexts sensors contexts premises atlas targetDefect root := by
  classical
  simp [batchRefineClosedContexts, Finset.union_assoc]

/-- Refining by a union of premise batches equals sequential refinement. -/
theorem batch_refine_closed_contexts_union
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts left right : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    batchRefineClosedContexts sensors contexts (left ∪ right)
        atlas targetDefect root =
      batchRefineClosedContexts sensors
        (batchRefineClosedContexts sensors contexts left atlas targetDefect root)
        right atlas targetDefect root := by
  classical
  simp [batchRefineClosedContexts, canonicalProperClosureContexts,
    Finset.union_assoc, Finset.union_left_comm, Finset.union_comm]

/-- The order of two finite refinement batches is irrelevant. -/
theorem batch_refine_closed_contexts_commute
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts left right : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    batchRefineClosedContexts sensors
        (batchRefineClosedContexts sensors contexts left atlas targetDefect root)
        right atlas targetDefect root =
      batchRefineClosedContexts sensors
        (batchRefineClosedContexts sensors contexts right atlas targetDefect root)
        left atlas targetDefect root := by
  classical
  simp [batchRefineClosedContexts, canonicalProperClosureContexts,
    Finset.union_assoc, Finset.union_left_comm, Finset.union_comm]

/-- Adding premise queries can only add canonical proper closure contexts. -/
theorem batch_refinement_monotone_in_premises
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts smaller larger : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (hsubset : smaller ⊆ larger) :
    batchRefineClosedContexts sensors contexts smaller atlas targetDefect root ⊆
      batchRefineClosedContexts sensors contexts larger atlas targetDefect root := by
  intro context hcontext
  rw [mem_batch_refine_closed_contexts_iff] at hcontext ⊢
  rcases hcontext with hbase | hcanonical
  · exact Or.inl hbase
  · apply Or.inr
    rw [mem_canonical_proper_closure_contexts_iff] at hcanonical ⊢
    rcases hcanonical with ⟨⟨premise, hpremise, hclosure⟩, hproper⟩
    exact ⟨⟨premise, hsubset hpremise, hclosure⟩, hproper⟩

/-- Only the set of distinct proper closure images matters, not premise multiplicity. -/
theorem batch_refinement_closure_image_invariant
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts left right : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel)
    (himages :
      canonicalProperClosureContexts sensors left atlas targetDefect root =
        canonicalProperClosureContexts sensors right atlas targetDefect root) :
    batchRefineClosedContexts sensors contexts left atlas targetDefect root =
      batchRefineClosedContexts sensors contexts right atlas targetDefect root := by
  unfold batchRefineClosedContexts
  rw [himages]

/-- Finite batch refinement is independent of the chosen route root. -/
theorem batch_refine_closed_contexts_root_independent
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (contexts premises : Finset (Finset ι))
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (sourceRoot targetRoot : RouteLabel) :
    batchRefineClosedContexts sensors contexts premises atlas targetDefect sourceRoot =
      batchRefineClosedContexts sensors contexts premises atlas targetDefect targetRoot := by
  classical
  have himage :
      premises.image (fun premise =>
          sensorSupportClosure sensors premise atlas targetDefect sourceRoot) =
        premises.image (fun premise =>
          sensorSupportClosure sensors premise atlas targetDefect targetRoot) := by
    apply Finset.image_congr
    intro premise hpremise
    exact sensor_support_closure_root_independent sensors premise atlas targetDefect
      sourceRoot targetRoot
  unfold batchRefineClosedContexts canonicalProperClosureContexts
  rw [himage]

/-- Refining the empty family by every finite support recovers all proper closed contexts. -/
theorem batch_refine_all_supports_eq_proper_closed
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    batchRefineClosedContexts sensors ∅ Finset.univ atlas targetDefect root =
      properClosedSensorSupports sensors atlas targetDefect root := by
  classical
  apply Finset.ext
  intro context
  rw [mem_batch_refine_closed_contexts_iff,
    mem_proper_closed_sensor_supports_iff]
  constructor
  · intro hcontext
    rcases hcontext with himpossible | hcanonical
    · simp at himpossible
    · rw [mem_canonical_proper_closure_contexts_iff] at hcanonical
      rcases hcanonical with ⟨⟨premise, hpremise, hclosure⟩, hproper⟩
      subst context
      exact ⟨sensor_support_closure_closed sensors premise atlas targetDefect root,
        hproper⟩
  · rintro ⟨hclosed, hproper⟩
    apply Or.inr
    rw [mem_canonical_proper_closure_contexts_iff]
    exact ⟨⟨context, Finset.mem_univ context, hclosed⟩, hproper⟩

/-- The saturated finite batch family is complete for every singleton consequence query. -/
theorem saturated_batch_singleton_consequence_complete
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (premise : Finset ι) (i : ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    i ∈ sensorSupportClosure sensors premise atlas targetDefect root ↔
      supportTruthRegion
          (batchRefineClosedContexts sensors ∅ Finset.univ atlas targetDefect root)
          premise ⊆
        sensorTruthRegion
          (batchRefineClosedContexts sensors ∅ Finset.univ atlas targetDefect root) i := by
  rw [batch_refine_all_supports_eq_proper_closed]
  exact mem_sensor_support_closure_iff_proper_truth_region_subset
    sensors premise i atlas targetDefect root

/-- Saturation is also complete for every finite-support conclusion. -/
theorem saturated_batch_finite_support_consequence_complete
    {ι G H : Type*}
    [Fintype ι] [DecidableEq ι] [Group G] [Group H]
    (sensors : ι → G →* H) (premise target : Finset ι)
    (atlas : DualFourRouteAtlas G) (targetDefect : G)
    (root : RouteLabel) :
    target ⊆ sensorSupportClosure sensors premise atlas targetDefect root ↔
      supportTruthRegion
          (batchRefineClosedContexts sensors ∅ Finset.univ atlas targetDefect root)
          premise ⊆
        supportTruthRegion
          (batchRefineClosedContexts sensors ∅ Finset.univ atlas targetDefect root)
          target := by
  rw [batch_refine_all_supports_eq_proper_closed]
  exact support_subset_closure_iff_proper_truth_region_subset
    sensors premise target atlas targetDefect root

/-- Finite formal authority boundary of the v0.92 certificate. -/
structure FiniteBatchContextSaturationCertificate where
  sourceMemoryOSV091Bound : Bool
  canonicalProperClosureImageExact : Bool
  batchExactForIncludedPremises : Bool
  batchUnionCompositionExact : Bool
  batchOrderIndependentExact : Bool
  batchDuplicateInvariantExact : Bool
  batchIdempotentExact : Bool
  batchPremiseMonotoneExact : Bool
  allSupportSaturationExact : Bool
  saturatedAllQueryCompletenessExact : Bool
  rootIndependenceExact : Bool
  globalMinimumContextBasisClaimed : Bool
  canonicalImplicationBasisClaimed : Bool
  optimalQueryOrderClaimed : Bool
  externalOracleAuthorityGranted : Bool
  candidateRankingPerformed : Bool
  executionPermission : Bool
  persistentWorldStateMutated : Bool
  truthAuthorityGranted : Bool

end KUOS.OpenHorizon.MemoryOSFiniteBatchContextSaturationV0_92
