import KUOS.CodeAI.ExternalCorpusAcquisitionFreezeReceiptV0_1

namespace KuuOSCodeAIExternalCorpusAcquisitionFreezeReceiptV0_1

open KUOS.CodeAI.ExternalCorpusAcquisitionFreezeReceiptV0_1

export KUOS.CodeAI.ExternalCorpusAcquisitionFreezeReceiptV0_1 (
  Binding CorpusContract AcquisitionEvidence ContractExact AcquisitionVerified
  FieldIsolationPreserved BoundaryPreserved FreezeAdmitted
  admitted_exact_binding admitted_acquisition_verified admitted_field_isolation
  admitted_boundary_preserved revision_mismatch_forbids_admission
  row_count_mismatch_forbids_admission gold_patch_exposure_forbids_admission
  label_exposure_forbids_admission kernel_fetch_forbids_admission
  harness_execution_forbids_admission repository_mutation_forbids_admission
  referenceBinding referenceContract referenceEvidence reference_admitted
  reference_gold_exposed_not_admitted reference_wrong_rows_not_admitted
  reference_harness_executed_not_admitted
)

end KuuOSCodeAIExternalCorpusAcquisitionFreezeReceiptV0_1
