/-
# KuuOS aggregate formal root

This is the strict aggregate build surface for the formal artifacts integrated on
`main` through KuuOS Repository Checkpoint Reflog v1.24, together with the
independent read-only KuuOS Checkpoint Recovery Proposal v0.1 and lifecycle
governance lines.

The root preserves the distinction between a Lean-derived theorem, a structure
supplied by hypotheses, an external analytic or institutional receipt, and an
empirical claim.

Version-specific roots remain available for local validation.  This aggregate
root exists to detect missing imports and cross-version regressions.
-/

import KUOS

-- Vacuum-expectation OS receipt and execution chain.
import KUOS.WORLD.BimoduleSectorFusionCategoryBridgeV0_40
import KUOS.VerifyOS.VacuumExpectationCommitVerificationReceiptV0_3
import KUOS.LearnOS.VacuumExpectationVerificationFutureOnlyDeltaV0_3
import KUOS.PlanOS.VacuumExpectationLearningReplanIntakeV0_18
import KUOS.PlanOS.VacuumExpectationHistoryQiCandidateGenerationV0_19
import KUOS.PlanOS.VacuumExpectationHysteresisConstraintDecisionHandoffV0_20
import KUOS.PlanOS.VacuumExpectationSelectedCandidateNextCycleSynthesisV0_21
import KUOS.PlanOS.VacuumExpectationCompilerMaterializationV0_22
import KUOS.PlanOS.«VacuumExpectationActivationAdmissionActOSHandoffV0_23»
import KUOS.ActOS.«VacuumExpectationActivationAuthorizationIntakeV0_3»
import KUOS.ActOS.VacuumExpectationBoundedAdapterInvocationV0_4
import KUOS.WORLD.VacuumExpectationHostEffectAtomicCommitIntakeV0_52
import KUOS.ObserveOS.WorldHostEffectObservationReceiptV0_4
import KUOS.WORLD.VacuumExpectationObserveOSCommitVerifyHandoffBridgeV0_53

-- WORLD operator-algebraic and four-great continuation.
import KUOS.WORLD.KuuVacuumCentralReferenceStateBridgeV0_54
import KUOS.WORLD.KuuVacuumInformationGeometryBridgeV0_55
import KUOS.WORLD.KuuVacuumArakiHessianOSTransportV0_56
import KUOS.WORLD.TomitaClosedGraphIsometryV0_57
import KUOS.WORLD.TomitaConjugateAdjointClosedV0_58
import KUOS.WORLD.FourGreatPhaseDynamicsCoreBridgeV0_59

-- Gauge-field self-organization and legacy approval boundary.
import KUOS.WORLD.KuuOSGaugeFieldSelfOrganizationV0_60
import KUOS.WORLD.KuuOSOSAssociatedGaugeFieldsV0_61
import KUOS.WORLD.KuuOSConnectionCandidateCoreV0_62
import KUOS.WORLD.KuuOSConnectionCandidateGaugeInvarianceV0_62
import KUOS.WORLD.KuuOSConnectionReviewCoreV0_63
import KUOS.WORLD.KuuOSConnectionEvaluationCoreV0_64
import KUOS.WORLD.KuuOSConnectionStagingV0_65
import KUOS.WORLD.KuuOSConnectionShadowV0_66
import KUOS.WORLD.KuuOSFiniteGaugeValidationV0_67
import KUOS.WORLD.KuuOSConnectionEvidenceV0_68
import KUOS.WORLD.KuuOSConnectionEvidenceReviewV0_69

-- Module-bundle, noncommutative connection, and MemoryOS production chain.
import KUOS.WORLD.KuuOSModuleBundleSelfOrganizationV0_70
import KUOS.WORLD.KuuOSNoncommutativeLeibnizConnectionV0_71
import KUOS.WORLD.KuuOSNonMarkovMemoryConnectionV0_72
import KUOS.WORLD.KuuOSFiniteMemoryEvaluationV0_73
import KUOS.WORLD.KuuOSMemorySelectionReviewV0_74
import KUOS.WORLD.KuuOSAuthorizedMemoryApplicationV0_75
import KUOS.WORLD.KuuOSMemoryRollbackV0_76

-- v0.77 authority-topology and post-transition-verification proposals were not
-- integrated on main.  The aggregate root therefore advances directly to v0.78.

-- Primary self-organization and repository alignment.
import KUOS.WORLD.KuuOSSelfOrganizingImprovementLoopV0_78
import KUOS.WORLD.KuuOSBoundedSelfOrganizationSupervisorV0_78
import KUOS.WORLD.KuuOSRepositoryStructureAlignmentV0_79
import KUOS.WORLD.KuuOSRepositoryAlignmentNormalFormV0_80
import KUOS.WORLD.KuuOSRepositoryIncrementalPreservationV0_81
import KUOS.WORLD.KuuOSRepositoryCertificateChainV0_82
import KUOS.WORLD.KuuOSRepositoryGitRevisionAdapterV0_83
import KUOS.WORLD.KuuOSRepositoryMergeCertificateV0_84
import KUOS.WORLD.KuuOSRepositoryRevisionDagV0_85
import KUOS.WORLD.KuuOSRepositoryFrontierCertificateV0_86
import KUOS.WORLD.KuuOSRepositorySelfEvolutionPortfolioV0_87
import KUOS.WORLD.KuuOSRepositorySelfEvolutionShadowV0_88
import KUOS.WORLD.KuuOSRepositoryEvolutionAdmissionV0_89
import KUOS.WORLD.KuuOSRepositoryExternalApprovalV0_90
import KUOS.WORLD.KuuOSRepositoryApplicationAuthorizationV0_91
import KUOS.WORLD.KuuOSRepositoryAtomicApplicationV0_92
import KUOS.WORLD.KuuOSRepositoryCommitCandidateV0_93
import KUOS.WORLD.KuuOSRepositoryObjectMaterializationAuthorizationV0_94
import KUOS.WORLD.KuuOSRepositoryObjectMaterializationReceiptV0_95
import KUOS.WORLD.KuuOSRepositoryReferenceUpdateV0_96
import KUOS.WORLD.KuuOSRepositoryAtomicReferenceUpdateV0_97
import KUOS.WORLD.KuuOSRepositoryReferenceUpdateReceiptV0_98
import KUOS.WORLD.KuuOSRepositoryReferenceStabilityReachabilityV0_99
import KUOS.WORLD.KuuOSRepositoryLocalFrontierFinalityV1_00
import KUOS.WORLD.KuuOSRepositoryLocalFrontierCheckpointAuthorizationV1_01
import KUOS.WORLD.KuuOSRepositoryAtomicCheckpointCreationV1_02
import KUOS.WORLD.KuuOSRepositoryCheckpointCreationReceiptV1_03
import KUOS.WORLD.KuuOSRepositoryCheckpointEvolutionWorkspaceV1_04
import KUOS.WORLD.KuuOSRepositoryCheckpointStabilityV1_05
import KUOS.WORLD.KuuOSRepositoryCheckpointDiscrepancyReviewV1_06
import KUOS.WORLD.KuuOSRepositoryCheckpointRepairRoutingV1_07
import KUOS.WORLD.KuuOSRepositoryCheckpointNamespaceGateV1_08
import KUOS.WORLD.KuuOSRepositoryCheckpointCandidateV1_09
import KUOS.WORLD.KuuOSRepositoryCheckpointCasContractV1_10
import KUOS.WORLD.KuuOSCheckpointCandidateValidationV1_11
import KUOS.WORLD.KuuOSRepositoryCheckpointValidatedCasIntakeV1_12
import KUOS.WORLD.KuuOSRepositoryCheckpointCasCoherenceV1_13
import KUOS.WORLD.KuuOSRepositoryCheckpointCasAuthorizationRequestV1_14
import KUOS.WORLD.KuuOSRepositoryCheckpointCasAuthorizationDecisionV1_15
import KUOS.WORLD.KuuOSRepositoryCheckpointAtomicCasTransitionV1_16
import KUOS.WORLD.KuuOSRepositoryCheckpointLiveGitPreflightV1_17
import KUOS.WORLD.KuuOSRepositoryCheckpointLiveRefCasV1_18
import KUOS.WORLD.KuuOSRepositoryBoundedBlobV1_19
import KUOS.WORLD.KuuOSRepositoryTreeCommitV1_20
import KUOS.WORLD.KuuOSRepositoryConstructedCommitPublicationV1_21
import KUOS.WORLD.KuuOSRepositoryDedicatedIndexV1_22
import KUOS.WORLD.KuuOSRepositorySandboxReflectionV1_23
import KUOS.WORLD.KuuOSRepositoryCheckpointReflogV1_24

-- Independent non-mutation recovery-governance line.
import KUOS.WORLD.KuuOSCheckpointRecoveryProposalV0_1

-- Independent read-only lifecycle-governance line.
import KUOS.WORLD.KuuOSApoptosisObservationV0_1
import KUOS.WORLD.KuuOSApoptosisCandidateV0_2
import KUOS.WORLD.KuuOSApoptosisDependencyReviewV0_3
import KUOS.WORLD.KuuOSApoptosisAuthorityReviewV0_4
