/-
# KuuOS aggregate formal root

This is the strict aggregate build surface for the formal artifacts integrated on
`main` through KuuOS Repository Object Materialization Receipt v0.95.

The root preserves the distinction between a Lean-derived theorem, a structure
supplied by hypotheses, an external analytic or institutional receipt, and an
empirical claim.

Version-specific roots remain available for local validation.  This aggregate
root exists to detect missing imports and cross-version regressions.
-/

import KUOS

-- Vacuum-expectation OS receipt and execution chain.
import KUOS.WORLD.BimoduleSectorFusionCategoryBridgeV0_40
import KUOS.VerifyOS.VacuumExpectationCommitVerificationReceiptV0_3
import KUOS.LearnOS.VacuumExpectationVerificationFutureOnlyDeltaV0_3
import KUOS.PlanOS.VacuumExpectationLearningReplanIntakeV0_18
import KUOS.PlanOS.VacuumExpectationHistoryQiCandidateGenerationV0_19
import KUOS.PlanOS.VacuumExpectationHysteresisConstraintDecisionHandoffV0_20
import KUOS.PlanOS.VacuumExpectationSelectedCandidateNextCycleSynthesisV0_21
import KUOS.PlanOS.VacuumExpectationCompilerMaterializationV0_22
import KUOS.PlanOS.«VacuumExpectationActivationAdmissionActOSHandoffV0_23»
import KUOS.ActOS.«VacuumExpectationActivationAuthorizationIntakeV0_3»
import KUOS.ActOS.VacuumExpectationBoundedAdapterInvocationV0_4
import KUOS.WORLD.VacuumExpectationHostEffectAtomicCommitIntakeV0_52
import KUOS.ObserveOS.WorldHostEffectObservationReceiptV0_4
import KUOS.WORLD.VacuumExpectationObserveOSCommitVerifyHandoffBridgeV0_53

-- WORLD operator-algebraic and four-great continuation.
import KUOS.WORLD.KuuVacuumCentralReferenceStateBridgeV0_54
import KUOS.WORLD.KuuVacuumInformationGeometryBridgeV0_55
import KUOS.WORLD.KuuVacuumArakiHessianOSTransportV0_56
import KUOS.WORLD.TomitaClosedGraphIsometryV0_57
import KUOS.WORLD.TomitaConjugateAdjointClosedV0_58
import KUOS.WORLD.FourGreatPhaseDynamicsCoreBridgeV0_59

-- Gauge-field self-organization and legacy approval boundary.
import KUOS.WORLD.KuuOSGaugeFieldSelfOrganizationV0_60
import KUOS.WORLD.KuuOSOSAssociatedGaugeFieldsV0_61
import KUOS.WORLD.KuuOSConnectionCandidateCoreV0_62
import KUOS.WORLD.KuuOSConnectionCandidateGaugeInvarianceV0_62
import KUOS.WORLD.KuuOSConnectionReviewCoreV0_63
import KUOS.WORLD.KuuOSConnectionEvaluationCoreV0_64
import KUOS.WORLD.KuuOSConnectionStagingV0_65
import KUOS.WORLD.KuuOSConnectionShadowV0_66
import KUOS.WORLD.KuuOSFiniteGaugeValidationV0_67
import KUOS.WORLD.KuuOSConnectionEvidenceV0_68
import KUOS.WORLD.KuuOSConnectionEvidenceReviewV0_69

-- Module-bundle, noncommutative connection, and MemoryOS production chain.
import KUOS.WORLD.KuuOSModuleBundleSelfOrganizationV0_70
import KUOS.WORLD.KuuOSNoncommutativeLeibnizConnectionV0_71
import KUOS.WORLD.KuuOSNonMarkovMemoryConnectionV0_72
import KUOS.WORLD.KuuOSFiniteMemoryEvaluationV0_73
import KUOS.WORLD.KuuOSMemorySelectionReviewV0_74
import KUOS.WORLD.KuuOSAuthorizedMemoryApplicationV0_75
import KUOS.WORLD.KuuOSMemoryRollbackV0_76

-- Primary self-organization and repository alignment.
import KUOS.WORLD.KuuOSSelfOrganizingImprovementLoopV0_78
import KUOS.WORLD.KuuOSBoundedSelfOrganizationSupervisorV0_78
import KUOS.WORLD.KuuOSRepositoryStructureAlignmentV0_79
import KUOS.WORLD.KuuOSRepositoryAlignmentNormalFormV0_80
import KUOS.WORLD.KuuOSRepositoryIncrementalPreservationV0_81
import KUOS.WORLD.KuuOSRepositoryCertificateChainV0_82
import KUOS.WORLD.KuuOSRepositoryGitRevisionAdapterV0_83
import KUOS.WORLD.KuuOSRepositoryMergeCertificateV0_84
import KUOS.WORLD.KuuOSRepositoryRevisionDagV0_85
import KUOS.WORLD.KuuOSRepositoryFrontierCertificateV0_86
import KUOS.WORLD.KuuOSRepositorySelfEvolutionPortfolioV0_87
import KUOS.WORLD.KuuOSRepositorySelfEvolutionShadowV0_88
import KUOS.WORLD.KuuOSRepositoryEvolutionAdmissionV0_89
import KUOS.WORLD.KuuOSRepositoryExternalApprovalV0_90
import KUOS.WORLD.KuuOSRepositoryApplicationAuthorizationV0_91
import KUOS.WORLD.KuuOSRepositoryAtomicApplicationV0_92
import KUOS.WORLD.KuuOSRepositoryCommitCandidateV0_93
import KUOS.WORLD.KuuOSRepositoryObjectMaterializationAuthorizationV0_94
import KUOS.WORLD.KuuOSRepositoryObjectMaterializationReceiptV0_95
