from __future__ import annotations
from copy import deepcopy
from runtime.kuuos_learnos_dukkha_preserving_future_only_learning_maintenance_disposition_intake_v0_1 import *
from scripts.check_verifyos_dukkha_preserving_realized_dukkha_verification_disposition_intake_v0_1 import _build as build_verifyos_v010

def source():
    result=build_verifyos_v010(); assert result.status==STATUS_READY,result.blockers; assert result.receipt is not None; return deepcopy(result.receipt)

def evidence(src):
    packet=src["realized_dukkha_verification_evidence_packet"]
    value={
        "source_realized_dukkha_verification_receipt_digest":src[SOURCE_RECEIPT_DIGEST_FIELD],"source_realized_dukkha_verification_evidence_packet_digest":src[SOURCE_EVIDENCE_DIGEST_FIELD],"source_realized_dukkha_verification_review_certificate_digest":src[SOURCE_REVIEW_DIGEST_FIELD],"source_realized_dukkha_verification_record_digest":src["realized_dukkha_verification_record_digest"],"source_realized_dukkha_verification_debt_consumption_record_digest":src["realized_dukkha_verification_debt_consumption_record_digest"],"source_bounded_realized_dukkha_confirmation_binding_digest":src["bounded_realized_dukkha_confirmation_binding_digest"],"source_future_learning_handoff_envelope_digest":src["future_learning_handoff_envelope_digest"],
        "world_candidate_fact_digest":src["world_candidate_fact_digest"],"world_candidate_relation_digest":src["world_candidate_relation_digest"],"resulting_world_state_digest":src["source_world_model_state_digest"],"resulting_world_revision":src["source_world_model_revision"],"realized_dukkha_observation_digest":packet["realized_dukkha_observation_digest"],"realized_dukkha_effect_estimate_digest":packet["realized_dukkha_effect_estimate_digest"],
        "learning_target_digest":"learnos-bounded-realized-dukkha-target-v04-001","future_only_learning_delta_digest":"learnos-future-only-delta-v04-001","maintenance_policy_candidate_digest":"learnos-maintenance-policy-candidate-v04-001","maintenance_window_digest":"learnos-maintenance-window-v04-001","durability_monitoring_specification_digest":"learnos-durability-monitor-v04-001","adverse_effect_monitoring_specification_digest":"learnos-adverse-monitor-v04-001","distributional_monitoring_specification_digest":"learnos-distributional-monitor-v04-001","reobservation_trigger_digest":"learnos-reobservation-trigger-v04-001","retention_window_digest":"learnos-retention-window-v04-001","uncertainty_digest":"learnos-future-only-uncertainty-v04-001","calibration_digest":"learnos-future-only-calibration-v04-001","provenance_chain_digests":sorted({src[SOURCE_RECEIPT_DIGEST_FIELD],src["bounded_realized_dukkha_confirmation_binding_digest"],src["future_learning_handoff_envelope_digest"],"learnos-future-only-provenance-v04-001"}),"tamper_evidence_digest":"learnos-future-only-tamper-v04-001","protected_group_learning_impact_digest":"learnos-protected-learning-impact-v04-001","future_subject_learning_impact_digest":"learnos-future-learning-impact-v04-001",
        "evidence_collector_id":"learnos-future-only-evidence-collector-v04","evidence_source_id":"independent-future-only-learning-source-v04","collection_started_epoch":145,"collection_completed_epoch":146,"maximum_collection_duration":4,"independent_future_only_learning_evidence":True,"exactly_one_future_only_learning_evidence_collection":True,"current_world_mutation_performed":False,"current_plan_revised":False,"current_policy_activated":False,"generalized_benefit_claimed":False,"authority_escalation_claimed":False,
    }
    value[EVIDENCE_DIGEST_FIELD]=compute_future_only_learning_evidence_packet_digest(value); return value

def review(src, ev):
    value={"source_realized_dukkha_verification_receipt_digest":src[SOURCE_RECEIPT_DIGEST_FIELD],EVIDENCE_DIGEST_FIELD:ev[EVIDENCE_DIGEST_FIELD],"source_bounded_realized_dukkha_confirmation_binding_digest":src["bounded_realized_dukkha_confirmation_binding_digest"],"source_future_learning_handoff_envelope_digest":src["future_learning_handoff_envelope_digest"],"world_candidate_fact_digest":ev["world_candidate_fact_digest"],"world_candidate_relation_digest":ev["world_candidate_relation_digest"],"resulting_world_state_digest":ev["resulting_world_state_digest"],"resulting_world_revision":ev["resulting_world_revision"],"learning_target_digest":ev["learning_target_digest"],"future_only_learning_delta_digest":ev["future_only_learning_delta_digest"],"maintenance_policy_candidate_digest":ev["maintenance_policy_candidate_digest"],"reviewer_id":"learnos-future-only-learning-reviewer-v04","verification_method_digest":"learnos-future-only-method-v04-001","verification_evidence_digest":"learnos-future-only-review-evidence-v04-001","review_started_epoch":146,"review_completed_epoch":147,"maximum_review_duration":4,"source_receipt_correspondence_confirmed":True,"source_bounded_world_fact_correspondence_confirmed":True,"source_causal_attribution_correspondence_confirmed":True,"source_realized_dukkha_correspondence_confirmed":True,"maintenance_window_adequate":True,"durability_monitoring_adequate":True,"adverse_effect_monitoring_adequate":True,"distributional_monitoring_adequate":True,"uncertainty_adequate":True,"calibration_adequate":True,"provenance_continuity_preserved":True,"protected_group_nonexternalization_supported":True,"future_nonexternalization_supported":True,"no_current_state_mutation":True,"no_authority_escalation":True}
    value[REVIEW_DIGEST_FIELD]=compute_future_only_learning_review_certificate_digest(value); return value

def context(src, ev, rv):
    source_epoch=src["realized_dukkha_verification_record"]["realized_dukkha_verification_intake_epoch"]
    value={"source_realized_dukkha_verification_receipt_digest":src[SOURCE_RECEIPT_DIGEST_FIELD],EVIDENCE_DIGEST_FIELD:ev[EVIDENCE_DIGEST_FIELD],REVIEW_DIGEST_FIELD:rv[REVIEW_DIGEST_FIELD],"current_world_binding_digest":src["source_world_binding_digest"],"current_world_model_state_digest":src["source_world_model_state_digest"],"current_world_model_revision":src["source_world_model_revision"],"current_persistent_world_storage_target_digest":src["source_persistent_world_storage_target_digest"],"source_realized_dukkha_verification_epoch":source_epoch,"future_only_learning_intake_epoch":source_epoch+3,"maximum_future_only_learning_intake_delay":8,"future_only_learning_intake_session_id":"learnos-future-only-intake-v04-001","future_only_learning_intake_nonce_digest":"learnos-future-only-nonce-v04-001","prior_future_only_learning_intake_session_ids":[],"prior_future_only_learning_evidence_packet_digests":[],"prior_future_only_learning_review_certificate_digests":[],"prior_future_only_learning_intake_nonce_digests":[],"prior_future_only_learning_source_receipt_digests":[],"requested_future_only_learning_operation_digest":compute_requested_future_only_learning_operation_digest(src,ev,rv),"exact_future_only_learning_cycle_digest":""}
    value["exact_future_only_learning_cycle_digest"]=compute_exact_future_only_learning_cycle_digest(src,ev,rv,value); value[CONTEXT_DIGEST_FIELD]=compute_future_only_learning_intake_context_digest(value); return value

def redigest_evidence(value):
    value=deepcopy(value); value.pop(EVIDENCE_DIGEST_FIELD,None); value[EVIDENCE_DIGEST_FIELD]=compute_future_only_learning_evidence_packet_digest(value); return value

def redigest_review(value, ev):
    value=deepcopy(value); value[EVIDENCE_DIGEST_FIELD]=ev[EVIDENCE_DIGEST_FIELD]; value.pop(REVIEW_DIGEST_FIELD,None); value[REVIEW_DIGEST_FIELD]=compute_future_only_learning_review_certificate_digest(value); return value

def redigest_context(src,ev,rv,value):
    value=deepcopy(value); value[EVIDENCE_DIGEST_FIELD]=ev[EVIDENCE_DIGEST_FIELD]; value[REVIEW_DIGEST_FIELD]=rv[REVIEW_DIGEST_FIELD]; value["requested_future_only_learning_operation_digest"]=compute_requested_future_only_learning_operation_digest(src,ev,rv); value["exact_future_only_learning_cycle_digest"]=compute_exact_future_only_learning_cycle_digest(src,ev,rv,value); value.pop(CONTEXT_DIGEST_FIELD,None); value[CONTEXT_DIGEST_FIELD]=compute_future_only_learning_intake_context_digest(value); return value

def build(**overrides):
    src=deepcopy(overrides.pop("source_realized_dukkha_verification_receipt",None) or source()); ev=deepcopy(overrides.pop("future_only_learning_evidence_packet",None) or evidence(src)); rv=deepcopy(overrides.pop("future_only_learning_review_certificate",None) or review(src,ev)); cx=deepcopy(overrides.pop("future_only_learning_intake_context",None) or context(src,ev,rv))
    sd=src.get(SOURCE_RECEIPT_DIGEST_FIELD,"source-missing"); ed=ev.get(EVIDENCE_DIGEST_FIELD,"evidence-missing"); rd=rv.get(REVIEW_DIGEST_FIELD,"review-missing"); cd=cx.get(CONTEXT_DIGEST_FIELD,"context-missing")
    expected_source=overrides.pop("expected_source_realized_dukkha_verification_receipt_digest",sd); expected_evidence=overrides.pop("expected_future_only_learning_evidence_packet_digest",ed); expected_review=overrides.pop("expected_future_only_learning_review_certificate_digest",rd); expected_context=overrides.pop("expected_future_only_learning_intake_context_digest",cd); policy=overrides.pop("future_only_learning_policy_digest","learnos-future-only-policy-v04"); responsibility=overrides.pop("future_only_learning_responsibility_digest","learnos-future-only-responsibility-v04"); request=overrides.pop("future_only_learning_request_id","learnos-future-only-v04-001")
    bundle=overrides.pop("future_only_learning_bundle_digest",compute_future_only_learning_bundle_digest(source_realized_dukkha_verification_receipt_digest=sd,expected_source_realized_dukkha_verification_receipt_digest=expected_source,future_only_learning_evidence_packet_digest=ed,expected_future_only_learning_evidence_packet_digest=expected_evidence,future_only_learning_review_certificate_digest=rd,expected_future_only_learning_review_certificate_digest=expected_review,future_only_learning_intake_context_digest=cd,expected_future_only_learning_intake_context_digest=expected_context,requested_future_only_learning_operation_digest=cx.get("requested_future_only_learning_operation_digest"),exact_future_only_learning_cycle_digest=cx.get("exact_future_only_learning_cycle_digest"),future_only_learning_policy_digest=policy,future_only_learning_responsibility_digest=responsibility,future_only_learning_request_id=request))
    args=dict(source_realized_dukkha_verification_receipt=src,expected_source_realized_dukkha_verification_receipt_digest=expected_source,future_only_learning_evidence_packet=ev,expected_future_only_learning_evidence_packet_digest=expected_evidence,future_only_learning_review_certificate=rv,expected_future_only_learning_review_certificate_digest=expected_review,future_only_learning_intake_context=cx,expected_future_only_learning_intake_context_digest=expected_context,future_only_learning_policy_digest=policy,future_only_learning_responsibility_digest=responsibility,future_only_learning_request_id=request,future_only_learning_bundle_digest=bundle); args.update(overrides); return build_learnos_dukkha_preserving_future_only_learning_maintenance_disposition_intake(**args)
