from __future__ import annotations

from typing import Any, Mapping


def project_fixture(fixture: Mapping[str, Any]) -> dict[str, Any]:
    pack = fixture["gate_pack"]
    receipt = fixture["receipt"]
    return {
        "schema_version": pack["schema_version"],
        "profile_version": pack["profile_version"],
        "repository_full_name": pack["repository_full_name"],
        "source_commit_sha": pack["source_commit_sha"],
        "selected_specialist_id": pack["selected_specialist_id"],
        "selected_specialist_kind": pack["selected_specialist_kind"],
        "selected_subtask_kind": pack["selected_subtask_kind"],
        "predecessor_gate_manifest_digest": pack["predecessor_gate_manifest_digest"],
        "predecessor_gate_pack_digest": pack["predecessor_gate_pack_digest"],
        "predecessor_gate_receipt_digest": pack["predecessor_gate_receipt_digest"],
        "environment_capsule_digest": pack["environment_capsule_digest"],
        "progress_trace_digest": pack["progress_trace_digest"],
        "continuation_round": pack["continuation_round"],
        "action_count": pack["action_count"],
        "action_kind": pack["action_kind"],
        "predecessor_steps": pack["predecessor_steps"],
        "predecessor_tool_calls": pack["predecessor_tool_calls"],
        "predecessor_model_calls": pack["predecessor_model_calls"],
        "predecessor_token_units": pack["predecessor_token_units"],
        "predecessor_wall_clock_ms": pack["predecessor_wall_clock_ms"],
        "predecessor_failed_actions": pack["predecessor_failed_actions"],
        "requested_steps": pack["requested_steps"],
        "requested_tool_calls": pack["requested_tool_calls"],
        "requested_model_calls": pack["requested_model_calls"],
        "requested_token_units": pack["requested_token_units"],
        "requested_wall_clock_ms": pack["requested_wall_clock_ms"],
        "requested_failed_actions": pack["requested_failed_actions"],
        "residual_steps_before": pack["residual_steps_before"],
        "residual_tool_calls_before": pack["residual_tool_calls_before"],
        "residual_model_calls_before": pack["residual_model_calls_before"],
        "residual_token_units_before": pack["residual_token_units_before"],
        "residual_wall_clock_ms_before": pack["residual_wall_clock_ms_before"],
        "residual_failed_actions_before": pack["residual_failed_actions_before"],
        "residual_steps_if_executed": pack["residual_steps_if_executed"],
        "residual_tool_calls_if_executed": pack["residual_tool_calls_if_executed"],
        "residual_model_calls_if_executed": pack["residual_model_calls_if_executed"],
        "residual_token_units_if_executed": pack["residual_token_units_if_executed"],
        "residual_wall_clock_ms_if_executed": pack["residual_wall_clock_ms_if_executed"],
        "residual_failed_actions_if_executed": pack["residual_failed_actions_if_executed"],
        "predecessor_gate_verified": pack["predecessor_gate_verified"],
        "proposal_bounded": pack["proposal_bounded"],
        "proposal_grounded": pack["proposal_grounded"],
        "read_only_action": pack["read_only_action"],
        "observable_return_required": pack["observable_return_required"],
        "new_checkpoint_required": pack["new_checkpoint_required"],
        "predecessor_gate_reentry_required": pack["predecessor_gate_reentry_required"],
        "gate_decision": pack["gate_decision"],
        "hold_reasons": pack["hold_reasons"],
        "proposal_hint_only": pack["proposal_hint_only"],
        "hypothetical_residual_only": pack["hypothetical_residual_only"],
        "budget_reserved": pack["budget_reserved"],
        "budget_consumed": pack["budget_consumed"],
        "action_executed": pack["action_executed"],
        "specialist_dispatched": pack["specialist_dispatched"],
        "candidate_selected": pack["candidate_selected"],
        "continuation_authority_granted": pack["continuation_authority_granted"],
        "execution_authority_granted": pack["execution_authority_granted"],
        "repository_mutation_performed": pack["repository_mutation_performed"],
        "git_authority_granted": pack["git_authority_granted"],
        "correctness_claimed": pack["correctness_claimed"],
        "request_digest": pack["request_digest"],
        "policy_digest": pack["policy_digest"],
        "proposal_digest": pack["proposal_digest"],
        "gate_pack_digest": pack["codeai_reobservation_bounded_continuation_proposal_gate_pack_digest"],
        "receipt_digest": receipt["codeai_reobservation_bounded_continuation_proposal_gate_receipt_digest"],
    }


__all__ = ["project_fixture"]
